Repository pingcap/tiflash, pull requests merged in 2022-11, with the labels that each got.

#6219 remove useless arrayJoin
  dbms/src/Columns/IColumn.h
  dbms/src/Functions/FunctionsMiscellaneous.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Parsers/ASTSelectQuery.cpp
  dbms/src/Parsers/ASTSelectQuery.h
  dbms/src/Parsers/ASTTablesInSelectQuery.cpp
  dbms/src/Parsers/ASTTablesInSelectQuery.h
  dbms/src/Parsers/ParserTablesInSelectQuery.cpp
  dbms/src/Parsers/ParserTablesInSelectQuery.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6224 tool: Show the entries from wal log files
  dbms/src/Storages/Page/Config.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/tools/PageCtl/CMakeLists.txt
  dbms/src/Storages/Page/tools/PageCtl/Main.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6223 cmake: Exclude some targets
  CMakeLists.txt
  contrib/CMakeLists.txt
  dbms/src/CMakeLists.txt
  dbms/src/TestUtils/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6226 cmake: Use gnu objcopy by default
  cmake/tiflash_linux_post_install.cmake
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6202 Exchange receiver decode optimization to do squashing work at the same time
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/DataStreams/NativeBlockInputStream.h
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.h
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.h
  dbms/src/Flash/Coprocessor/CoprocessorReader.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DecodeDetail.h
  dbms/src/Flash/Coprocessor/IChunkDecodeAndSquash.cpp
  dbms/src/Flash/Coprocessor/IChunkDecodeAndSquash.h
  dbms/src/Flash/Coprocessor/tests/gtest_chunk_decode_and_squash.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Planner/plans/PhysicalExchangeReceiver.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6232 metrics: remove batch item in metrics
  dbms/src/Common/TiFlashMetrics.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6239 KVStore: Support new lock type 'l'
  dbms/src/Storages/Transaction/RegionCFDataBase.cpp
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
  dbms/src/Storages/Transaction/tests/gtest_tikv_keyvalue.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6236 fix potential failure when allocating space from BlobFile
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6234 tsan: disable sanitizer for func `StringHashTable::dispatch`
  dbms/src/Common/HashTable/StringHashTable.h
  dbms/src/Common/HashTable/TwoLevelStringHashTable.h
Labels: type/enhancement, status/can-merge, status/LGT2, size/XS, release-note-none

#6243 *: remove a virtual class `IChunkDecodeAndSquash`
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/ChunkDecodeAndSquash.cpp
  dbms/src/Flash/Coprocessor/ChunkDecodeAndSquash.h
  dbms/src/Flash/Coprocessor/CoprocessorReader.h
  dbms/src/Flash/Coprocessor/tests/gtest_chunk_decode_and_squash.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6230 tsan: remove useless limit check for `Interpreters::Join` to fix the data race
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/StorageJoin.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6246 asan: Fix compile error
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6247 Confirm repo git info before compilation
  dbms/cmake/version.cmake
Labels: type/enhancement, status/can-merge, status/LGT2, size/XS, release-note-none

#6249 metrics: refine some metrics name
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/FlashService.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6255 degrade to armv8.0
  cmake/cpu_features.cmake
  tests/fullstack-test2/ddl/alter_pk.test
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6251 Fix cmake scripts error caused by #6200
  cmake/find_ccache.cmake
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6258 Fix exception type and error code.
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.1

#6082 Refactor regexp and regexp_like function
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRegexp.cpp
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/FunctionsStringReplace.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Functions/FunctionsStringSearch.h
  dbms/src/Functions/IFunction.cpp
  dbms/src/Functions/IFunction.h
  dbms/src/Functions/re2Util.cpp
  dbms/src/Functions/re2Util.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_regexp.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6259 Remove gcc legacy scripts
  CMakeLists.txt
  README.md
  cmake/test_compiler.cmake
  cmake/tools.cmake
Labels: type/enhancement, status/can-merge, status/LGT2, release-note-none, size/L

#6260 fix unstable ut.
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6263 PageStorage: remove useless interface
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_gc.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Page/workload/PSRunnable.cpp
Labels: status/can-merge, status/LGT2, type/code-quality-improvement, size/XL, release-note-none

#6277 fix the bug that Planner Interpreter lost the metric `Executor OPS`
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlan.h
Labels: status/can-merge, status/LGT2, release-note, size/M

#6186 .*: refine streaming writer and exchange writer
  dbms/src/Flash/Coprocessor/DAGBlockOutputStream.cpp
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/newMPPExchangeWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6175 Add more metrics about PageStorage
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/Page/FileUsage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6281 Optimize `inline_memcpy` by `avx2`
  CMakeLists.txt
  cmake/print_flags.cmake
  cmake/utils.cmake
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashBuildInfo.cpp
  dbms/src/Functions/CMakeLists.txt
  dbms/src/Functions/CollationStringOptimized.cpp
  libs/libcommon/CMakeLists.txt
  libs/libcommon/include/common/avx2_mem_utils.h
  libs/libcommon/include/common/avx2_memcpy.h
  libs/libcommon/include/common/mem_utils_opt.h
  libs/libcommon/include/common/memcpy.h
  libs/libcommon/src/avx2_mem_utils_impl.cpp
  libs/libcommon/src/tests/CMakeLists.txt
  libs/libcommon/src/tests/bench_memcpy.cpp
  libs/libcommon/src/tests/gtest_mem_utils_opt.cpp
  libs/libmemcpy/CMakeLists.txt
  libs/libmemcpy/memcpy.cpp
  release-centos7-llvm/scripts/build-tiflash-release.sh
  release-darwin/build/build-release.sh
Labels: type/enhancement, status/can-merge, status/LGT2, size/XXL, release-note-none

#6273 Add metrics about grpc async client and server connections
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6178 testing: pageworkload `HeavySkewWriteRead` support deleting data
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/workload/HeavyMemoryCostInGC.h
  dbms/src/Storages/Page/workload/HeavyRead.h
  dbms/src/Storages/Page/workload/HeavySkewWriteRead.h
  dbms/src/Storages/Page/workload/HeavyWrite.h
  dbms/src/Storages/Page/workload/HighValidBigFileGC.h
  dbms/src/Storages/Page/workload/HoldSnapshotsLongTime.h
  dbms/src/Storages/Page/workload/MainEntry.cpp
  dbms/src/Storages/Page/workload/Normal.h
  dbms/src/Storages/Page/workload/PSBackground.cpp
  dbms/src/Storages/Page/workload/PSBackground.h
  dbms/src/Storages/Page/workload/PSRunnable.cpp
  dbms/src/Storages/Page/workload/PSRunnable.h
  dbms/src/Storages/Page/workload/PSStressEnv.cpp
  dbms/src/Storages/Page/workload/PSStressEnv.h
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Page/workload/PSWorkload.h
  dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
  dbms/src/Storages/Page/workload/ThousandsOfOffset.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.3

#6271 .*: remove delta mode of execution summary
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/ExecutionSummaryCollector.cpp
  dbms/src/Flash/Coprocessor/ExecutionSummaryCollector.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.h
  dbms/src/Flash/Planner/plans/PhysicalExchangeSender.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6282 Use another lock to protect PageDirectory::apply
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6288 Remove unreachable google docs
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/tools/auto-fio.sh
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6292 remove SpaceMapRBTree
  dbms/src/Storages/Page/V3/spacemap/RBTree.cpp
  dbms/src/Storages/Page/V3/spacemap/RBTree.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.h
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Page/workload/PSRunnable.cpp
Labels: status/can-merge, status/LGT2, type/code-quality-improvement, size/XXL, release-note-none

#6205 Support extract duration
  dbms/src/Common/MyDuration.cpp
  dbms/src/Common/MyDuration.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/tests/gtest_log_search.cpp
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/FunctionsDuration.cpp
  dbms/src/Functions/FunctionsDuration.h
  dbms/src/Functions/tests/gtest_datetime_extract.cpp
  dbms/src/Functions/tests/gtest_duration_extract.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  tests/fullstack-test/expr/extract_duration.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6291 Introduce dependabot as a mid-state mitigation for too much TiFlash Proxy PRs
  .github/dependabot.yml
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6191 do not cast not null column to nullable implicitly
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6285 Add metrics about write bytes for EstablishConnection call
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6179 *.: Use String as the common type for Decimal in join when an Exception occurs
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_format_decimal.cpp
  tests/fullstack-test/mpp/issue_4519.test
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/XXL, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#6313 Use right-valued reference passing for `TrackedMppDataPacketPtr`
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6279 Support using FineGrainedShuffle Info for Join&Agg
  dbms/src/DataStreams/MockExchangeReceiverInputStream.cpp
  dbms/src/DataStreams/MockExchangeReceiverInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/plans/PhysicalAggregation.h
  dbms/src/Flash/Planner/plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalExchangeReceiver.h
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.h
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.h
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Storages/StorageJoin.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6317 Move most of `WindowBlockInputStream`'s code to `WindowTransformAction`
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/WindowFunctions/IWindowFunction.cpp
  dbms/src/WindowFunctions/IWindowFunction.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6320 fix: error data input for date(CAST(value AS DATETIME)) causing high TiFlash sys CPU
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/tests/gtest_mytime.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/return_warning.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, cherry-pick-approved

#6323 fix: error data input for date(CAST(value AS DATETIME)) causing high …
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/tests/gtest_mytime.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/return_warning.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, cherry-pick-approved

#6321 fix: error data input for date(CAST(value AS DATETIME)) causing high …
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/tests/gtest_mytime.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/return_warning.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, cherry-pick-approved

#6330 fix ut
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
Labels: status/LGT1, size/XL, release-note-none, do-not-merge/cherry-pick-not-approved

#6331 Remove Useless Code
  dbms/src/Storages/DeltaMerge/SkipHeadBlockInputStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6328 Fix some unstable unit-tests.
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6297 Use alarm to retry client's connection
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/tests/bench_exchange.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6340 *: fix coredump when stopping tiflash
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6348 Fix test utils.
  dbms/src/TestUtils/InputStreamTestUtils.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6357 Remove `DAGResponseWriter::finishWrite`
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGBlockOutputStream.cpp
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6363 avoid always compacting level0 under heavy write pressure
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note, cherry-pick-approved

#6362 avoid always compacting level0 under heavy write pressure
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note, needs-cherry-pick-release-6.1

#6342 Let mpp task send remote read request after it is scheduled.
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/CoprocessorReader.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6367 revert #6340
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6344 Use `num_streams` as parallelism when read thread is enabled.
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6371 test: Introduce ASSERT_PROFILE_EVENT
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6369 test: merge blocks when prepare
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6372 metrics: Fix duplicated id in Grafana panels
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6272 Support regexp_instr function
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Common/UTF8Helpers.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRegexp.cpp
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/tests/gtest_regexp.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6374 fix unstable test
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6375 storage: Add more checks for ingestFiles
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6382 Raise error for streamAgg when plan contains group by key
  dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6353 PageStorage: Fix unexpected high file open ops
  dbms/src/Common/LRUCache.h
  dbms/src/Common/tests/CMakeLists.txt
  dbms/src/Common/tests/gtest_lru_cache.cpp
  dbms/src/Common/tests/lru_cache.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/MarkCache.h
  dbms/src/Storages/Page/Config.h
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/V3/Blob/BlobConfig.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#6385 storage: Accepts a snapshot for segment replaceData API
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none
