Repository pingcap/tiflash, pull requests merged in 2022-09, with the labels that each got.

#5734 Add UT for list struct based executors
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/TestUtils/executorSerializer.cpp
  dbms/src/TestUtils/executorSerializer.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5414 docs : add rfc for fast scan
  docs/design/2022-07-19-tiflash-support-fast-mode.md
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5759 chore: remove redundant suffix `BlockInputStream` of debug string
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5745 TestUtils: read all blocks and sort them by handle before comparison.
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/TestUtils/InputStreamTestUtils.cpp
  dbms/src/TestUtils/InputStreamTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4743 doc: planner refactor
  docs/design/2022-04-24-planner-refactor.md
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5743 Test: RandomGenColumns
  dbms/src/Core/ColumnWithTypeAndName.h
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
  dbms/src/TestUtils/tests/gtest_column_generator.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5746 Add rfc for feature 'placement rules in SQL works with tables with TiFlash replica'
  docs/design/2022-08-31-placement-rules-in-SQL-works-with-tables-with-TiFlash-replica.md
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5671 Support window Function lead/lag
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Planner/plans/PhysicalWindow.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/Interpreters/WindowDescription.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/Interpreters/convertFieldToType.cpp
  dbms/src/Interpreters/convertFieldToType.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/WindowFunctions/IWindowFunction.cpp
  dbms/src/WindowFunctions/IWindowFunction.h
  dbms/src/WindowFunctions/WindowFunctionFactory.cpp
  dbms/src/WindowFunctions/WindowFunctionFactory.h
  dbms/src/WindowFunctions/tests/CMakeLists.txt
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
  tests/fullstack-test/expr/lead_lag.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#5770 fix memory leaks in *.ListBase
  dbms/src/TestUtils/mockExecutor.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5773 *: fix lead_lag test build fail.
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5740 storage: correct the write amplification
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5695 storage: count more as write stalls
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5777 misc: protect from calling RUNTIME_CHECK with string literals
  dbms/src/Common/Exception.h
  dbms/src/DataStreams/WindowBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5779 Bugfix of memtracker released early
  dbms/src/Common/MemoryTracker.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Interpreters/ProcessList.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5765 MemoryTracker*: Use std::shared_ptr to manage MemoryTracker.
  dbms/src/Common/MemoryTracker.h
  dbms/src/Common/tests/gtest_dynamic_thread_pool.cpp
  dbms/src/Common/tests/gtest_memtracker.cpp
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/Page/workload/PSBackground.cpp
  dbms/src/Storages/Page/workload/PSRunnable.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5780 doc: update window function design doc
  docs/design/2022-05-12-window-function.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5699 PageStorage: Fine grained lock on external callbacks
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  tests/delta-merge-test/ddl/alter.test
  tests/delta-merge-test/raft/schema/partition_table_restart.test
  tests/delta-merge-test/raft/schema/rename_on_read.test
  tests/delta-merge-test/raft/schema/rename_on_write.test
  tests/delta-merge-test/raft/schema/rename_tables.test
  tests/delta-merge-test/raft/txn_mock/partition_table.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5784 Remove useless test
  dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/bank/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/bank/DeltaMergeStoreProxy.cpp
  dbms/src/Storages/DeltaMerge/tests/bank/DeltaMergeStoreProxy.h
  dbms/src/Storages/DeltaMerge/tests/bank/IDGenerator.h
  dbms/src/Storages/DeltaMerge/tests/bank/SimpleDB.h
  dbms/src/Storages/DeltaMerge/tests/bank/SimpleLockManager.h
  dbms/src/Storages/DeltaMerge/tests/bank/main.cpp
  dbms/src/Storages/DeltaMerge/tests/stress/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/stress/DMStressProxy.cpp
  dbms/src/Storages/DeltaMerge/tests/stress/DMStressProxy.h
  dbms/src/Storages/DeltaMerge/tests/stress/main.cpp
  libs/libcommon/src/tests/bench_logger.cpp
  libs/libcommon/src/tests/gtest_logger.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5763 check the accuracy of the memory track in test mode
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5791 fix unstable tests
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5762 PageStorage: Fix unstable rename test
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/TestUtils/TiFlashTestBasic.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  tests/delta-merge-test/raft/schema/partition_table_restart.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5788 Enable read thread.
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5728 storage: unify segment_id in log
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/Region.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5796 Bugfix of memtracker accuracy test
  dbms/src/Common/MemoryTracker.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5806 Change an unserious log from error to warning
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5797 *: supress grpc "tcp set inq" loggings
  contrib/grpc-cmake/0001-disable-tcp-set-inq-debug-message.patch
  contrib/grpc-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note, size/M

#5804 use shared_ptr of memtracker in MPPTunnel
  dbms/src/Common/MemoryTracker.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5810 Add pb code for regexp functions
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5795 storage: prefer physical split when the segment's delta is large
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5805 Fix issue 3595 that invalid string/decimal/float cast to non-null datetime/date
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_date_add.cpp
  dbms/src/Functions/tests/gtest_date_sub.cpp
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/cast_as_time.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5811 *: Fix verbose logging in the DeltaTree engine
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  tests/delta-merge-test/query/misc/timestamp_rough_set_filter.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5732 Test: Test CancelMPPTask in UT
  dbms/CMakeLists.txt
  dbms/src/DataStreams/MockTableScanBlockInputStream.cpp
  dbms/src/DataStreams/MockTableScanBlockInputStream.h
  dbms/src/Debug/MockComputeServerManager.cpp
  dbms/src/Debug/MockComputeServerManager.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5818 Fix incorrect window function cancellation handling
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
Labels: status/can-merge, status/LGT2, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5824 Refine error propagation in local tunnel
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5832 Storage: (Refactor) Separate ingest impl out
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5833 Storage: (Refactor) Separate segment impl out
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5808 metric: Add graph for thread CPUs
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5838 refine random_tunnel_wait_timeout_failpoint
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5840 add memory_tracker_holder in TrackedMppDataPacket
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5854 eliminate tsan warnings of accuracy_diff_for_test
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5835 Storage: (Refactor) Avoid referencing DeltaMergeStore.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Management/ManualCompact.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5848 storage: Allow merging multiple segments in the segment API
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5655 Support sm4 encryption algorithm
  .gitmodules
  cmake/find_ssl.cmake
  dbms/src/Common/TiFlashBuildInfo.cpp
  dbms/src/Common/config_build.cpp.in
  dbms/src/Encryption/AESCTRCipherStream.cpp
  dbms/src/Encryption/AESCTRCipherStream.h
  dbms/src/Encryption/KeyManager.h
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/install_openssl.sh
  release-centos7-llvm/dockerfiles/tiflash-llvm-base-aarch64
  release-centos7-llvm/dockerfiles/tiflash-llvm-base-amd64
  release-centos7-llvm/env/loader
  release-centos7-llvm/env/prepare-sysroot.sh
  release-centos7-llvm/scripts/build-tiflash-release.sh
  release-darwin/build/build-release.sh
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5858 Storage: (Refactor) Separate bg tasks out
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5657 Planner: remove useless project action in `PhysicalProjection`
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.h
  dbms/src/Flash/Planner/plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5239 Implement Space function push down #5113
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_space.cpp
  tests/fullstack-test/expr/space.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5839 fix: the results of tikv and tiflash are different
  dbms/src/Functions/FunctionsLogical.h
  dbms/src/Functions/tests/gtest_logical.cpp
  tests/fullstack-test/expr/logical_op.test
Labels: status/can-merge, needs-cherry-pick-release-4.0, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5865 Replace Poco::Logger by DB::Logger in MPPTaskManager and MinTSOScheduler
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5860 clean up segments with large space amplification ratio generated by logical split
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5862 *: Make test runner compatible with py2 and py3; show time elapsed
  tests/run-test.py
  tests/run-test.sh
  tests/wait-table.py
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5883 *: Fix lint for files under src/Columns
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnConst.cpp
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnTuple.cpp
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/FilterDescription.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5867 storage: Use different names for block bg pool
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5889 Test: refine Executor Unit Test
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5894 storage: require lock for segment operations
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5886 .*: Separate `TemporaryFileStream` from `AggregatingBlockInputStream/ParallelAggregatingBlockInputStream`
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/AggregatingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/TemporaryFileStream.cpp
  dbms/src/DataStreams/TemporaryFileStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5863 storage: Merge multiple segments in gc thread
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/tests/MultiSegmentTestUtil.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5895 Test: Refine astToExecutor
  dbms/CMakeLists.txt
  dbms/src/Debug/MockExecutor/astToExecutor.cpp
  dbms/src/Debug/MockExecutor/astToExecutor.h
  dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp
  dbms/src/Debug/MockExecutor/astToExecutorUtils.h
  dbms/src/Debug/MockExecutor/funcSigs.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5896 Fix crash when do gc on table with empty stable
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5890 storage: Allow specifying split point and split method in the segment API
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/MultiSegmentTestUtil.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5882 fix unittests tsan warnings.
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.h
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5799 fix that the result of expression cast(Real/Decimal)AsTime is inconsistent with TiDB
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/tests/gtest_mytime.cpp
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/cast_as_time.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5899 tests: Fix RegionBlockReaderTest helper functions
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
  dbms/src/TestUtils/TiFlashTestBasic.cpp
  dbms/src/TestUtils/TiFlashTestBasic.h
Labels: status/can-merge, needs-cherry-pick-release-4.0, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5904 storage: Introduce replaceData in the segment API
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5902 Fix data race when exceptions happen in SegmentReader.
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5906 storage: Support transform SST to multiple DTFile
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PartitionStreams.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5852 Fix `alloc_bytes` of ReadLimiter
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/TestUtils/MockReadLimiter.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1

#5879 Fix decode error when "NULL" value in the column with "primary key" flag
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/PartitionStreams.h
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.h
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/RowCodec.h
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
  tests/fullstack-test2/ddl/alter_pk.test
Labels: status/can-merge, needs-cherry-pick-release-4.0, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/XXL, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5927 storage: Ingest snapshot by split
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/ExternalDTFileInfo.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#5920 *: Fix build astToExecutorUtils
  dbms/src/Debug/MockExecutor/astToExecutorUtils.cpp
  dbms/src/Debug/MockExecutor/astToExecutorUtils.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5928 Revert "Use safe_ts to determine whether the peer's data synchronizat…
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5945 storage: Always split the pre-ingested DTFile
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5941 storage: Fix GC for logical split not working
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5856 cmake: Build rust deps using debug profile when build-type is not release
  contrib/tiflash-proxy-cmake/CMakeLists.txt
  libs/libsymbolization/CMakeLists.txt
  libs/libsymbolization/Cargo.toml
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5948 Fix data race of DeltaIndex::toString
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.1

#5828 PageStorage: Refactor some file structure
  dbms/CMakeLists.txt
  dbms/src/Storages/Page/V3/Blob/BlobConfig.h
  dbms/src/Storages/Page/V3/Blob/BlobFile.cpp
  dbms/src/Storages/Page/V3/Blob/BlobFile.h
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/WALConfig.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/entries_helper.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5951 Minor refactoring of `ExchangeReceiver`
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5942 Add boost macro BOOST_NO_CXX98_FUNCTION_BASE.
  contrib/boost-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5959 add mpp query count metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5957 Test: Support coprocessor test
  dbms/src/Debug/MockComputeServerManager.cpp
  dbms/src/Debug/MockComputeServerManager.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5952 cmake: Let README just work™ in more environments
  CMakeLists.txt
  README.md
  cmake/find_rust.cmake
  tests/_env.sh
  tests/run-test.sh
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5969 Add lld to Arch dependencies of README.
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5964 fix: make ReadLimiterTest more stable
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5970 Fix gtest_dm_minmax_index.cpp clang tidy.
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5955 Fix compile warnings when using clang-15
  .clang-tidy
  contrib/boost-cmake/CMakeLists.txt
  contrib/boost-cmake/fiber.cmake
  dbms/src/Common/CPUAffinityManager.cpp
  dbms/src/Common/CPUAffinityManager.h
  dbms/src/Common/DynamicThreadPool.h
  dbms/src/Common/ExternalTable.h
  dbms/src/Common/UnifiedLogPatternFormatter.cpp
  dbms/src/DataStreams/FormatFactory.cpp
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Flash/LogSearch.cpp
  dbms/src/Functions/FunctionsGeo.cpp
  dbms/src/Functions/GeoUtils.h
  dbms/src/Functions/tests/bench_function_cast.cpp
  dbms/src/IO/Endian.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/Page/PageUtil.h
  dbms/src/Storages/Page/V1/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.cpp
  dbms/src/Storages/Page/tools/PageCtl/MainEntry.cpp
  libs/libcommon/include/boost_wrapper/cpp_int.h
  libs/libcommon/include/boost_wrapper/endian_conversion.h
  libs/libcommon/include/boost_wrapper/geometry.h
  libs/libcommon/include/boost_wrapper/lockfree_queue.h
  libs/libcommon/include/boost_wrapper/program_options.h
  libs/libcommon/include/boost_wrapper/string.h
  libs/libcommon/include/boost_wrapper/string_split.h
  libs/libcommon/include/common/types.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5963 *: Remove function higherOrder & ExternalModels & FindCluster
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
  dbms/src/Functions/FunctionsExternalModels.cpp
  dbms/src/Functions/FunctionsExternalModels.h
  dbms/src/Functions/FunctionsFindCluster.cpp
  dbms/src/Functions/FunctionsFindCluster.h
  dbms/src/Functions/FunctionsHigherOrder.cpp
  dbms/src/Functions/FunctionsHigherOrder.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Interpreters/ExternalModels.cpp
  dbms/src/Interpreters/ExternalModels.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5971 Fix DeltaMergeHelpers.cpp clang tidy.
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5977 .*: Minor improvement for executor ut
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5958 Always use readable pathname in DMFileReader
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.3

#5978 *: Remove external models
  dbms/src/Dictionaries/CatBoostModel.cpp
  dbms/src/Dictionaries/CatBoostModel.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/ExternalModels.cpp
  dbms/src/Interpreters/ExternalModels.h
  dbms/src/Interpreters/IRuntimeComponentsFactory.h
  dbms/src/Interpreters/RuntimeComponentsFactory.h
  dbms/src/Storages/System/StorageSystemModels.cpp
  dbms/src/Storages/System/StorageSystemModels.h
  dbms/src/Storages/System/attachSystemTables.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5915 Test: refine astToExecutor to ExecutorBinders
  dbms/src/Debug/MockExecutor/AggregationBinder.cpp
  dbms/src/Debug/MockExecutor/AggregationBinder.h
  dbms/src/Debug/MockExecutor/AstToPB.cpp
  dbms/src/Debug/MockExecutor/AstToPB.h
  dbms/src/Debug/MockExecutor/AstToPBUtils.cpp
  dbms/src/Debug/MockExecutor/AstToPBUtils.h
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.h
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.h
  dbms/src/Debug/MockExecutor/ExecutorBinder.h
  dbms/src/Debug/MockExecutor/FuncSigMap.cpp
  dbms/src/Debug/MockExecutor/FuncSigMap.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Debug/MockExecutor/LimitBinder.cpp
  dbms/src/Debug/MockExecutor/LimitBinder.h
  dbms/src/Debug/MockExecutor/ProjectBinder.cpp
  dbms/src/Debug/MockExecutor/ProjectBinder.h
  dbms/src/Debug/MockExecutor/SelectionBinder.cpp
  dbms/src/Debug/MockExecutor/SelectionBinder.h
  dbms/src/Debug/MockExecutor/SortBinder.cpp
  dbms/src/Debug/MockExecutor/SortBinder.h
  dbms/src/Debug/MockExecutor/TableScanBinder.cpp
  dbms/src/Debug/MockExecutor/TableScanBinder.h
  dbms/src/Debug/MockExecutor/TopNBinder.cpp
  dbms/src/Debug/MockExecutor/TopNBinder.h
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.h
  dbms/src/Debug/MockExecutor/astToExecutor.cpp
  dbms/src/Debug/MockExecutor/astToExecutor.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5992 .*: `TiRemoteBlockInputStream` use loop instead of recursion
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5996 Disable folly memcpy as default memcpy
  libs/libmemcpy/CMakeLists.txt
Labels: type/enhancement, status/can-merge, type/bug-fix, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.3

#5976 Pre-support for C++20
  contrib/boost-cmake/CMakeLists.txt
  contrib/re2-cmake/CMakeLists.txt
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Common/Exception.h
  dbms/src/Common/FmtUtils.h
  dbms/src/Common/MyDuration.cpp
  dbms/src/Debug/dbgFuncSchemaName.cpp
  dbms/src/Storages/DeltaMerge/SchemaUpdate.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  libs/libcommon/include/boost_wrapper/lockfree_queue.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5966 Do not use extra threads when cancel mpp query
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/MPMCQueue.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/tests/gtest_grpc_send_queue.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#5982 storage: Introduce test framework similar to Segment Test for DMStore
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  libs/libsymbolization/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6011 storage: GC segments contained by the pack (#6010)
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  libs/libsymbolization/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, cherry-pick-approved, type/cherry-pick-for-release-6.3

#6010 storage: GC segments contained by the pack
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.3

#5961 Performance optimization of SegmentReadTaskScheduler
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.3

#6009 build: Suppress unknown warning
  CMakeLists.txt
  cmake/add_warning.cmake
  contrib/CMakeLists.txt
  contrib/boost-cmake/CMakeLists.txt
  contrib/boost-cmake/fiber.cmake
  contrib/re2-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6003 add locally run tidy check instructions
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5962 Use safe_ts to determine whether the peer's data synchronization progress is far behind the leader.
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6012 Performance optimization of SegmentReadTaskScheduler
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, cherry-pick-approved

#6000 Use BoringSSL in release build
  release-centos7-llvm/scripts/build-tiflash-release.sh
  release-darwin/build/build-release.sh
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, cherry-pick-approved

#5528 Server: reduce too many pings
  dbms/src/Server/FlashGrpcServerHolder.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5908 Optimize block sort
  dbms/src/Interpreters/sortBlock.cpp
  dbms/src/Interpreters/tests/gtest_block_sort.cpp
  libs/libcommon/include/common/avx2_strstr.h
  libs/libcommon/include/common/sse2_memcpy.h
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XXL, release-note-none

#5997 dttool: Support dump the column values from a dtfile
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6015 Upgrade rust toolchain for `libs/libsymbolization`
  libs/libsymbolization/rust-toolchain
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XS, release-note-none

#5897 .*: Refine storage interpreter
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Interpreters/ExpressionActions.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5988 fix: add some error log when get config before load
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6021 .*: fix build fail in linux amd64
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6026 Fix SyncStatusTest UT detected memory leaks.
  dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6018 clear encryption info for temporary dmfile
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#5623 test(KVStore): Support Proxy's apply pattern on normal write and compact log
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionMeta.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6028 Unified log tracing id of storage read request.
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6024 Remove useless gcov utils scripts for GCC
  CMakeLists.txt
  cmake/Modules/CodeCoverage.cmake
  dbms/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6020 Refine the lifecycle of memory_tracker for MPP query
  dbms/src/Common/MemoryTracker.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Planner/PlanQuerySource.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Interpreters/executeQuery.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6036 remove IfNull duplicated implementation
  dbms/src/Functions/FunctionsNull.cpp
  dbms/src/Functions/FunctionsNull.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6040 doc: Add "Improve Snapshot Ingestion" RFC.
  docs/design/2022-09-27-improve-snapshot-ingestion.md
  docs/design/images/2022-09-27-improve-snapshot-ingestion-1.png
  docs/design/images/2022-09-27-improve-snapshot-ingestion-2.png
  docs/design/images/2022-09-27-improve-snapshot-ingestion-3.png
  docs/design/images/2022-09-27-improve-snapshot-ingestion-4.png
  docs/design/images/2022-09-27-improve-snapshot-ingestion-5.svg
  docs/design/images/2022-09-27-improve-snapshot-ingestion-6.svg
  docs/design/images/2022-09-27-improve-snapshot-ingestion-7.svg
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6050 Refine checkIsConfigLoaded in TiFlashTestEnv.
  dbms/src/Interpreters/Context.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6053 Revert "*: supress grpc "tcp set inq" loggings (#5797)"
  contrib/grpc-cmake/0001-disable-tcp-set-inq-debug-message.patch
  contrib/grpc-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note-none, size/M, cherry-pick-approved

#6044 Some scheduler related refinements
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/Transaction/TMTContext.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6043 .*: refine `executeQuery`
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Flash/executeQuery.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6066 Ignore jemalloc stderr message in test script
  tests/run-test.py
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.3

#6074 tests: Remove embed test funcs from PageEntriesEdit
  contrib/grpc-cmake/CMakeLists.txt
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none
