Repository pingcap/tiflash, pull requests merged in 2022-10, with the labels that each got.

#6070 PageStorage: Make deserialize out of WALReader
  dbms/src/Storages/Page/ExternalPageCallbacks.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6067 storage: add sleep to split retry
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.3

#6055 storage: include segment and table info in more logs
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6038 storage: add more store statistics
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.3

#5877 *: Fix set cancel test tsan.
  tests/sanitize/tsan.suppression
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6052 storage: always flush the delete range when region range changes
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/GCOptions.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/GCManager.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note, needs-cherry-pick-release-6.3

#6083 fix unstable tests
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6094 suppress cmake warning
  CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6098 Fix I/O limiter auto-tuner.
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.1

#6096 Fix "dirty" status cause by grpc patch
  .gitmodules
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6105 Fix unstable ut.
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6103 fix apple clang compiler warning
  CMakeLists.txt
  cmake/test_compiler.cmake
  dbms/src/Storages/Page/workload/CMakeLists.txt
  libs/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6106 *: remove VisitParam functions
  dbms/src/Functions/FunctionsVisitParam.cpp
  dbms/src/Functions/FunctionsVisitParam.h
  dbms/src/Functions/registerFunctions.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6108 Fix that empty namespace won't be clean
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.3

#6117 reduce sync-status log
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6120 Fix unit test under clang-15
  contrib/abseil-cpp-cmake/CMakeLists.txt
  contrib/grpc-cmake/CMakeLists.txt
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
  dbms/src/Functions/tests/gtest_strings_simd_consistency.cpp
  dbms/src/IO/tests/gtest_dm_checksum_buffer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6124 avoid init store when process query for tiflash system tables
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6058 Make fast scan code mode clean
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6125 cmake: Bring back the option to specify external TiFlash proxy
  cmake/find_tiflash_proxy.cmake
  contrib/CMakeLists.txt
  dbms/src/Server/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6097 Optimization of SegmentReadTaskPool::getTask
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6136 storage: Fix some tests not working
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6133 fix inconsistent result before deleting some rows
  dbms/src/Functions/FunctionsLogical.h
  dbms/src/Functions/tests/gtest_logical.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#6134 Fix memory statistics of `MemoryTracker` when input stream released.
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.3

#6085 Test: Support running raw query in Executor UT.
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6165 Fix write stall after set replica 0 and then restart.
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.3

#6041 KVStore: Support multi file snapshot
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Debug/MockSSTReader.cpp
  dbms/src/Debug/MockSSTReader.h
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/SSTReader.cpp
  dbms/src/Storages/Transaction/SSTReader.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
  tests/tidb-ci/new_collation_fullstack/clustered_index.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5878 feat: Enable minmax index on the pack with nullable value
  dbms/src/Debug/MockExecutor/FuncSigMap.cpp
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6171 Fix initialization of `Context` in DTTool
  dbms/src/Server/DTTool/DTTool.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6156 add track info for mem tracker fault inject
  dbms/src/Common/BackgroundTask.cpp
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Storages/BackgroundProcessingPool.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6169 [doc] Add new rfc for 'Enhance null value support for minmax index'
  docs/design/2022-10-20-enhance-null-value-support-for-minmax-index.md
  docs/design/images/2022-10-20-enhance-null-value-support-for-minmax-index-1.png
  docs/design/images/2022-10-20-enhance-null-value-support-for-minmax-index-2.png
  docs/design/images/2022-10-20-enhance-null-value-support-for-minmax-index-3.png
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6160 Test: port some of delta-merge test into ut, part 1
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Flash/tests/gtest_query_executor.cpp
  dbms/src/Flash/tests/gtest_query_expr.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  tests/delta-merge-test/query/executor/aggregation.test
  tests/delta-merge-test/query/executor/filter.test
  tests/delta-merge-test/query/executor/limit.test
  tests/delta-merge-test/query/executor/project.test
  tests/delta-merge-test/query/executor/topn.test
  tests/delta-merge-test/query/expr/bit_op.test
  tests/delta-merge-test/query/expr/if.test
  tests/delta-merge-test/query/expr/in.test
  tests/delta-merge-test/query/expr/logical_op.test
  tests/delta-merge-test/query/expr/round_with_frac.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6180 .*: minor improvement
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/executorSerializer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6088 Test: Refine dbgFuncCoprocessor
  dbms/src/Columns/ColumnUtils.cpp
  dbms/src/Columns/ColumnUtils.h
  dbms/src/Core/BlockUtils.cpp
  dbms/src/Core/BlockUtils.h
  dbms/src/DataStreams/UniqRawResReformatBlockOutputStream.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Debug/dbgFuncCoprocessorUtils.cpp
  dbms/src/Debug/dbgFuncCoprocessorUtils.h
  dbms/src/Debug/dbgQueryCompiler.cpp
  dbms/src/Debug/dbgQueryCompiler.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Debug/dbgQueryExecutor.h
  dbms/src/Debug/dbgTools.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6168 PageStorage: Fix peak memory usage when running GC on PageDirectory
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note, needs-cherry-pick-release-6.3

#6183 .*: Remove useless settings `join_concurrent_build`
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/DataStreams/PartialSortingBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6192 Fix minor compaction after restart
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#6122 make `establishMPPConnectionAsync` non block
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/dbgFuncFailPoint.cpp
  dbms/src/Debug/dbgFuncFailPoint.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Server/tests/gtest_grpc_alarm.cpp
  tests/fullstack-test/mpp/async_server_alarm.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6128 Set linker name when using AppleClang
  CMakeLists.txt
  cmake/arch.cmake
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6004 storage: multi-threads protection for PathPool
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/tests/gtest_path_pool.cpp
  dbms/src/TestUtils/MockDiskDelegator.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.3

#6146 storage: include memtable in for_update snapshots
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6193 KVStore: Force persist when meet Prepare(Finish)Flashback
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6207 storage: Introduce isDefinitelyEmpty API
  .clangd
  .github/licenserc.yml
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/ProfileEvents.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6135 Optimize Aggregator/Join/Set keys
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Common/ColumnsHashing.h
  dbms/src/Common/HashTable/StringHashTable.h
  dbms/src/Common/HashTable/TwoLevelStringHashTable.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Set.cpp
  dbms/src/Interpreters/Set.h
  dbms/src/Interpreters/SetVariants.cpp
  dbms/src/Interpreters/SetVariants.h
  dbms/src/Interpreters/sortBlock.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XXL, release-note-none

#6203 fix metrics for establish connection
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#6199 Fix minor compaction after restart
  dbms/src/Storages/DeltaMerge/Delta/DeltaPack_V3.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, cherry-pick-approved, needs-cherry-pick-release-5.3

#6173 Fine grained partition writer optimization
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.cpp
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.cpp
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNothing.h
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.cpp
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_scatterTo.cpp
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashParitionWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6217 use default ar,ranlib,objcopy when using AppleClang
  cmake/tools.cmake
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6042 Fix two DDL bugs on hotfix branch
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Core/Block.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/dbgFuncMockRaftCommand.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgFuncRegion.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/PartitionStreams.h
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.h
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/RowCodec.h
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/Storages/Transaction/tests/bench_region_block_reader.cpp
  dbms/src/Storages/Transaction/tests/gtest_decoding_storage_schema_snapshot.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
  dbms/src/Storages/Transaction/tests/region.cpp
  dbms/src/Storages/Transaction/tests/region_helper.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TestUtils/TiFlashTestBasic.cpp
  dbms/src/TestUtils/TiFlashTestBasic.h
  tests/fullstack-test-dt/clustered_index/ddl.test
  tests/fullstack-test2/ddl/alter_pk.test
Labels: status/LGT2, size/XXL, release-note-none, cherry-pick-approved
