Repository pingcap/tiflash, pull requests merged in 2022-04, with the labels that each got.

#4551 Celebrate open-source
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note

#4555 doc: add apt.llvm.org in README
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4540 PageStorage: Fix bug for reporting BlobFile disk usage
  dbms/src/Storages/Page/V3/BlobFile.cpp
  dbms/src/Storages/Page/V3/BlobFile.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4548 PageStorage: Fix data race in BlobStore
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4561 Fix typo in README/build
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4566 Unify the url of submodule to https url
  .gitmodules
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4475 Remove invalid blob file after BlobStore restored.
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4486 Remove redundant use of marco __PRETTY_FUNCTION__
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/SchemaUpdate.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/SchemaBuilder.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4572 Remove useless TODO in `dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp`
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
Labels: status/can-merge, status/LGT2, size/XS

#4582 Agg: replace the usage of `ThreadPool` by `ThreadPoolManager`.
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4563 Tiflash crash when scanning partition table with `time` column
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  tests/delta-merge-test/query/mpp/partition_table.test
  tests/fullstack-test/mpp/partition_table_with_time.test
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.0

#4576 doc: add instructions for runing unit tests
  README.md
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4537 Add a stale snapshots check, also add some logs
  dbms/src/Common/Stopwatch.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4288 Tracing: Add read_tso as tracing id to PageStorage snapshot
  dbms/src/Common/Logger.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/RowKeyRangeUtils.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRangeUtils.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/DTWorkload.cpp
  dbms/src/Storages/SelectQueryInfo.cpp
  dbms/src/Storages/SelectQueryInfo.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDeltaMergeHelpers.h
  dbms/src/Storages/System/StorageSystemDTTables.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4613 Inhibit warning messages in tiflash-proxy
  contrib/tiflash-proxy-cmake/CMakeLists.txt
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XS, release-note-none

#3695 Do background compaction when the ratio of stable data covered by delete range is too large
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/GCManager.cpp
  dbms/src/Storages/GCManager.h
  dbms/src/Storages/MergeTree/BackgroundProcessingPool.cpp
  dbms/src/Storages/MergeTree/BackgroundProcessingPool.h
  dbms/src/Storages/Transaction/RegionTable.cpp
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XXL, release-note, cherry-pick-approved

#4610 Split AstToExecutor from dbgFuncCoprocessor.
  dbms/src/Debug/DAGProperties.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4608 Fix can not find right path when blobstore restore
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4638 *:Fix MppInfo saving reference to temporary object.
  dbms/src/Debug/astToExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4637 Fix logger initialization of DTWorkload.
  dbms/src/Storages/DeltaMerge/tools/workload/MainEntry.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4626 move `output_field_types` and `output_offsets` to `DAGContext`
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlock.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4648 Fix potential data race in DynamicThreadPool
  dbms/src/Common/DynamicThreadPool.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4630 Fix create table error
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4320 Add a pagestorage v3 controller.
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/CMakeLists.txt
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Page/V3/tests/page_storage_ctl.cpp
  dbms/src/Storages/Page/stress/PSStressEnv.cpp
  dbms/src/Storages/Page/stress/PSStressEnv.h
  dbms/src/Storages/Page/stress/PSWorkload.cpp
  dbms/src/Storages/Page/stress/workload/Normal.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4657 cherry pick #4285 to 5.4 hotfix branch
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/UnionBlockInputStream.h
Labels: release-note-none, size/M, do-not-merge/cherry-pick-not-approved

#4658 Fix a bug that MPP tasks may leak threads forever (#4241)
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: size/XS, release-note-none, do-not-merge/cherry-pick-not-approved

#4659 MPP: update the state of building a hash table when createOnce throw …
  dbms/src/Common/FailPoint.cpp
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/tests/exchange_perftest.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/LGT1, release-note-none, size/L, do-not-merge/cherry-pick-not-approved

#4656 Fix crash when prehandle snapshot (#4140)
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RowCodec.cpp
Labels: CHERRY-PICK, release-note-none, size/M, do-not-merge/cherry-pick-not-approved

#4664 fix a bug that ExchangeReceiver can't be canceled (#4441)
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/CoprocessorReader.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: status/LGT1, release-note-none, size/M, do-not-merge/cherry-pick-not-approved

#4667 Fix the bug that canceled MPP query may cause tasks hang forever when local tunnel is enabled.
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: status/LGT1, size/XS, release-note-none, do-not-merge/cherry-pick-not-approved

#4669 format of release-5.4-20200312
  dbms/src/Flash/Coprocessor/InterpreterDAG.h
Labels: status/LGT1, size/XS, release-note-none, do-not-merge/cherry-pick-not-approved

#4670 fix code style of release-5.4-20220312
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
Labels: status/LGT1, size/XS, release-note-none, do-not-merge/cherry-pick-not-approved

#4671 fix typo
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V1/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4620 Add a fail point that can hold PS snapshot for five minute.
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4675 Fix data race of DeltaIndexManager.
  dbms/src/Storages/DeltaMerge/DeltaIndexManager.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, cherry-pick-approved

#4632 Interpreter: Hand write tipb::Executor.
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/InterpreterTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4682 code stlye&format of mpptunnel
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/LGT1, size/XS, release-note-none, do-not-merge/cherry-pick-not-approved

#4683 fix clang tidy error
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
Labels: status/LGT1, release-note-none, size/M, do-not-merge/cherry-pick-not-approved

#4623 refine `SubqueryForSet`
  dbms/src/DataStreams/CreatingSetsBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.h
  dbms/src/Interpreters/ExpressionAnalyzer.h
  dbms/src/Interpreters/SubqueryForSet.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4553 Add gtests for MPPTunnel
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4686 Fix background_pool_size not take effect and BackgroundProcessingPool::getThreadIds may misses some thread_ids.
  dbms/CMakeLists.txt
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  libs/libcommon/include/common/logger_useful.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4700 fix: fix build issue `‘maybe_unused’ attribute ignored` on centos server
  dbms/src/Common/CPUAffinityManager.h
  libs/libcommon/include/common/defines.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4699 *: fix tableScan incorrect trace.
  dbms/src/Flash/Statistics/TableScanImpl.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4570 Make performance of TPCH q15 stable
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4633 cherry pick PR#3283 about sending schemas in exchangeSender
  dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
  tests/tidb-ci/fullstack-test-dt/union_push_down.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L, cherry-pick-approved

#4668 clear old range before apply snapshot
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
Labels: status/can-merge, needs-cherry-pick-release-4.0, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/S, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4711 reuse old index file format for empty dmfile and just ignore it's size in statistical data
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4698 Add some debug friendly utilities for dag request based test framework
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgNaturalDag.cpp
  dbms/src/Debug/dbgNaturalDag.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4593 Add a background metrics for both v2 and v3
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Storages/Page/PageUtil.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.h
  dbms/src/Storages/Page/V2/gc/DataCompactor.cpp
  dbms/src/Storages/Page/V2/gc/LegacyCompactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_util.cpp
  dbms/src/Storages/Page/V3/BlobFile.cpp
  dbms/src/Storages/Page/V3/BlobFile.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4706 Interpreter: Mock exchange executors.
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/InterpreterTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4691 Fix pagestorage v3 ddl problem.
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/WriteBatch.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4029 Fix calling virtual function in ctor (#4022)
  dbms/src/DataStreams/AggregatingBlockInputStream.h
  dbms/src/DataStreams/ConcatBlockInputStream.h
  dbms/src/DataStreams/ExpressionBlockInputStream.cpp
  dbms/src/DataStreams/ExpressionBlockInputStream.h
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/FilterBlockInputStream.h
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/DataStreams/LimitBlockInputStream.cpp
  dbms/src/DataStreams/LimitBlockInputStream.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/PartialSortingBlockInputStream.h
  dbms/src/DataStreams/SharedQueryBlockInputStream.h
  dbms/src/DataStreams/SquashingBlockInputStream.cpp
  dbms/src/DataStreams/SquashingBlockInputStream.h
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/DataStreams/UnionBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
Labels: status/can-merge, type/bug-fix, status/LGT2, release-note-none, size/L, cherry-pick-approved, type/cherry-pick-for-release-5.4

#4735 fix tiflash crash when setting join_concurrent_build = 0
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Interpreters/Join.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4741 Fxied some compile errors on mac in PS V3
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
Labels: status/can-merge, status/LGT2, size/XS

#4721 Refine handle agg and exchange sender
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/ExchangeSenderInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/ExchangeSenderInterpreterHelper.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4746 ignore delmark when add minmax for pk column
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/tests/dm_basic_include.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4753 disable cache small column
  dbms/src/Storages/DeltaMerge/Delta/FlushDelta.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: status/LGT2, release-note-none, size/L, do-not-merge/cherry-pick-not-approved

#4742 Interpreter: Serialize executors
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/Statistics/ExchangeSenderImpl.cpp
  dbms/src/TestUtils/CMakeLists.txt
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/InterpreterTestUtils.h
  dbms/src/TestUtils/executorSerializer.cpp
  dbms/src/TestUtils/executorSerializer.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4754 fix: frame total size include header for indices
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4522 fix empty segment cannot merge after gc
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaPackFile.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  tests/delta-merge-test/query/misc/timestamp_rough_set_filter.test
  tests/fullstack-test-dt/expr/timestamp_filter.test
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XL, release-note, cherry-pick-approved, type/cherry-pick-for-release-5.4

#4769 Add more debug info for gtest failure
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4785 Fix ingest dmfile won't rollback
  dbms/src/Storages/DeltaMerge/WriteBatches.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4777 fix: ut and more idx error
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
Labels: status/can-merge, status/LGT2, release-note, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4786 refactor: Remove some non-const member methods in Context.
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4750 doc: add sanitizer test related docs
  README.md
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4213 metrics: support multi-k8s in grafana dashboards (#4099)
  metrics/grafana/tiflash_proxy_details.json
  metrics/grafana/tiflash_proxy_summary.json
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note, cherry-pick-approved

#4796 fix: Suppress the warning from boost to fix build failure.
  dbms/src/Functions/GeoUtils.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4502 Export PageStorage V3 config into global config
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/ConfigSettings.cpp
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/gc/DataCompactor.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L
