Repository pingcap/tiflash, pull requests merged in 2022-07, with the labels that each got.

#5273 Fix README type error
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5281 fix(cmake): make sure libc++ is utilized by tiflash-proxy
  contrib/tiflash-proxy-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5242 fix the wrong order of execution summary for list based executors
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.cpp
Labels: status/can-merge, status/LGT2, release-note, size/M

#5245 Schema: allow loading empty schema diff when the version grows up.
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Storages/Transaction/ReadIndexWorker.cpp
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4883 Optimize apply speed under heavy write pressure
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RegionTable.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5288 Delete range can not remove expected data
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: CHERRY-PICK, release-note-none, size/M, do-not-merge/cherry-pick-not-approved

#5289 flush cache before segment merge
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  tests/_env.sh
  tests/run-gtest.sh
Labels: CHERRY-PICK, release-note-none, size/L, cherry-pick-approved

#5284 Flush segment cache when doing the compaction
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.1

#5061 metrics: Fix incorrect metrics for delta_merge tasks
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1

#5303 suppresion false positive report from tsan
  .github/licenserc.yml
  tests/sanitize/tsan.suppression
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5261 Refine test framework code and tests
  dbms/src/Flash/tests/gtest_executor.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/WindowFunctions/tests/gtest_window_functions.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5124 feat: add logical cpu cores and memory into grafana
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Server/Server.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5235 Implement TimeToSec function push down
  dbms/src/Common/MyDuration.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsDuration.cpp
  dbms/src/Functions/FunctionsDuration.h
  dbms/src/Functions/tests/gtest_duration_pushdown.cpp
  tests/fullstack-test/expr/duration_pushdown.test
Labels: status/can-merge, status/LGT2, size/L, release-note

#5156 feat: implement shiftRight function push down
  dbms/src/DataTypes/NumberTraits.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/bitShiftRight.cpp
  dbms/src/Functions/tests/gtest_bitshiftright.cpp
  tests/fullstack-test/expr/bitshift_operator.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5267 schema : make update to partition tables when 'set tiflash replica'
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/Debug/dbgFuncSchemaName.cpp
  dbms/src/Debug/dbgFuncSchemaName.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/alter_table_tiflash_replica.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5307 Replace initializer_list with vector for planner test framework
  dbms/src/Flash/tests/bench_window.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5304 refine error message in mpptask
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/Utils.cpp
  dbms/src/Flash/Mpp/Utils.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  tests/fullstack-test/mpp/issue_2471.test
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5233 Implement ReverseUTF8/Reverse function push down
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/tests/gtest_strings_reverse.cpp
  tests/fullstack-test/expr/reverse.test
Labels: status/can-merge, status/LGT2, size/L, release-note

#5299 Optimize comparision for collation `UTF8_BIN` and `UTF8MB4_BIN`
  dbms/src/Columns/ColumnConst.h
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Functions/FunctionsComparison.h
  dbms/src/Storages/Transaction/Collator.cpp
  tests/tidb-ci/new_collation_fullstack/expr.test
Labels: type/enhancement, status/can-merge, status/LGT2, size/XL, release-note-none

#5311 Add non-blocking functions for MPMCQueue
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_mpmc_queue.cpp
  dbms/src/Common/tests/mpmc_queue_perftest.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5300 add random segment test for CI weekly
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5312 *: tidy FunctionString.cpp
  dbms/src/Functions/FunctionsString.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5318 ci: fix check-license github action
  .github/workflows/license-checker.yml
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5274 Change one `additional_input_at_end` to many streams in `ParallelInputsProcessor`
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/ParallelInputsProcessor.h
  dbms/src/DataStreams/UnionBlockInputStream.h
  dbms/src/DataStreams/tests/union_stream2.cpp
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/tests/bench_exchange.cpp
  dbms/src/Flash/tests/bench_window.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/Interpreters/InterpreterSelectWithUnionQuery.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5269 feat: pushdown get_format into TiFlash
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsConversion.cpp
  dbms/src/Functions/FunctionsConversion.h
  dbms/src/Functions/tests/gtest_get_format.cpp
  tests/fullstack-test/expr/get_format.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5272 fix: format throw data truncated error
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_format.cpp
  tests/fullstack-test/expr/format.test
Labels: status/can-merge, status/LGT2, release-note, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5243 Print content of columns for gtest
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TestUtils/tests/gtest_print_columns.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5338 *: also enable O3 for aarch64
  CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5344 Add debug image build target for CentOS7
  release-centos7-llvm/Makefile
  release-centos7-llvm/scripts/build-debug.sh
  release-centos7-llvm/scripts/build-tiflash-release.sh
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5326 *: mini refactor
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5190 Refactor initialize of background pool
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5328 delete copy/move ctor of MPMCQueue explicitly
  dbms/src/Common/MPMCQueue.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5354 Optimize comparision for collation `UTF8_BIN` and `UTF8MB4_BIN` (#5299)
  dbms/src/Columns/ColumnConst.h
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Functions/FunctionsComparison.h
  dbms/src/Storages/Transaction/Collator.cpp
  tests/tidb-ci/new_collation_fullstack/expr.test
Labels: status/LGT2, size/XL, release-note-none, cherry-pick-approved

#5360 decrease the frequency of background gc log
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/GCManager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5277 Fix shell escaped character comparison bug in test scripts
  tests/delta-merge-test/raft/schema/default_value.test
  tests/fullstack-test/expr/reverse.test
  tests/run-test.py
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5286 Refact MPPTunnel class to encapsulate different tunnel mode
  dbms/src/Common/MPMCQueue.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/PacketWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5361 Refine cancelMPPQuery
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5357 keep delete entry when dump snapshot
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1

#5276 expr: pushdown `repeat` to tiflash
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_repeat.cpp
  tests/tidb-ci/fullstack-test-dt/repeat_push_down.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5160 Add options to support `Profile Guided Optimization`
  CMakeLists.txt
  dbms/src/Common/TiFlashBuildInfo.cpp
  format-diff.py
  libs/libcommon/include/common/config_common.h.in
  release-centos7-llvm/env/prepare-sysroot.sh
  release-centos7-llvm/scripts/perf-autofdo-llvm.py
Labels: type/enhancement, status/can-merge, status/LGT2, size/XL, release-note-none

#5379 Fix write after unconnect finish bug
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5369 *: Test DagRequest to MPPTasks
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5254 Add UT for MinMax Index
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5383 Fix background thread count in dtworkload.
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5371 feat: support clean read base on fast mode
  dbms/src/Storages/DeltaMerge/DMDecoratorStreams.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_mode.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5384 fix pagestorage v2 restore
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5380 *: suppress tsan in BlockStreamProfileInfo
  tests/sanitize/tsan.suppression
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5373 clear obsolete v2 data for tables that totally transform to ps v3
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5305 Enhance executor join tests
  dbms/src/Flash/tests/gtest_executor.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5398 change some default config of ps v3
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/PageStorage.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5404 refine log in creating set for join build
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5407 Fix async sender nullptr bug
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5364 Test aggregation functions
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5417 DAGContext: remove useless explicitly call to tunnel_set's default ctor
  dbms/src/Flash/Coprocessor/DAGContext.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5420 Fix extract fullstack test
  tests/fullstack-test/expr/extract_datetime.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, affects-6.2, needs-cherry-pick-release-6.2

#5410 Yield CPU for concurrent flush and concurrent mergeDelta
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5411 fix the incorrect execution time of join in explain analyze
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.cpp
  dbms/src/Flash/Statistics/ExecutorStatistics.h
  dbms/src/Flash/Statistics/JoinImpl.cpp
  dbms/src/Flash/Statistics/JoinImpl.h
Labels: status/can-merge, status/LGT2, release-note, size/M

#5413 fix read from ColumnFileBigReader
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5427 Revert "Fix extract fullstack test (#5420)"
  tests/fullstack-test/expr/extract_datetime.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5431 *: fix incorrect results when handling `like` with `escape`
  dbms/src/Storages/Transaction/Collator.cpp
  tests/fullstack-test/expr/like.test
Labels: status/can-merge, type/bug-fix, status/LGT2, release-note, size/M

#5419 Fix test framework's groupby expression support
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/TestUtils/mockExecutor.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5377 Read ThreadPool and Data Sharing of DeltaTree
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.h
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_circular_scan_list.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_column_sharing_cache.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_mode.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/SelectQueryInfo.cpp
  dbms/src/Storages/SelectQueryInfo.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5433 fix a panic issue in parallel agg when exception is thrown
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/XS, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5436 Fix proxy build on non-llvm env
  contrib/tiflash-proxy-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5394 change cpu feature behavior for M1
  contrib/CMakeLists.txt
  libs/libcommon/CMakeLists.txt
  libs/libcommon/include/common/detect_features.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5375 Optimize string sort for default collation `UTF8MB4_BIN`
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Interpreters/AggregationCommon.h
  dbms/src/Interpreters/SetVariants.h
  dbms/src/Storages/Transaction/Collator.cpp
  dbms/src/Storages/Transaction/CollatorUtils.h
  dbms/src/Storages/Transaction/tests/gtest_tidb_collator.cpp
Labels: type/enhancement, status/can-merge, type/bug-fix, status/LGT2, type/performance, size/XL, release-note-none

#5447 build: Fix build under intel mac machine
  contrib/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5280 feat: implement hexInt/hexStr function push down
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_hexint.cpp
  dbms/src/Functions/tests/gtest_strings_hexstr.cpp
  tests/fullstack-test/expr/hex_int.test
  tests/fullstack-test/expr/hex_str.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5451 *: try not to use lld as default linker in macos
  CMakeLists.txt
Labels: type/enhancement, status/can-merge, status/LGT2, size/XS, release-note-none

#5358 fix: incorrect uptime in grafana panel
  dbms/src/Common/Stopwatch.h
  dbms/src/Common/ThreadMetricUtil.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/tests/stress/DMStressProxy.cpp
  dbms/src/Storages/DeltaMerge/tests/stress/DMStressProxy.h
  dbms/src/Storages/DeltaMerge/workload/TimestampGenerator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5459 fix sched_setaffinity failed.
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.2

#5246 feat: support 'bin' function push down
  dbms/src/Common/hex.cpp
  dbms/src/Common/hex.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_bin.cpp
  tests/fullstack-test/expr/bin.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5320 Planner: support Join
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlan.h
  dbms/src/Flash/Planner/PlanType.cpp
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Planner.cpp
  dbms/src/Flash/Planner/plans/PhysicalBinary.h
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.h
  dbms/src/Flash/Planner/plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/plans/PhysicalSource.cpp
  dbms/src/Flash/Planner/plans/PhysicalSource.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5449 Support colllation for planner refactory test framework
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5466 refine `InterpreterDAG`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5460 fix hexInt `sprintf` format pattern
  dbms/src/Functions/FunctionsString.cpp
Labels: status/can-merge, status/LGT2, size/S, release-note

#5472 Fix typo of Metrics
  dbms/src/Common/TiFlashMetrics.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.2

#5471 refine FlashService
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5434 *: improve RUNTIME_CHECK and RUNTIME_ASSERT
  dbms/src/Common/Exception.cpp
  dbms/src/Common/Exception.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/Common/Logger.h
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/UserConfigParser.cpp
  dbms/src/Server/UserConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5464 refine Window Executor Test
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/WindowFunctions/tests/gtest_window_functions.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5476 Add metrics of Read Thread and Cache to Grafana
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.2

#5483 bugfix for core of GRPCCompQueue when tiflash shutdown
  dbms/src/Flash/Mpp/GRPCCompletionQueuePool.cpp
  dbms/src/Flash/Mpp/GRPCCompletionQueuePool.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.2

#5478 Design doc: DeltaTree Read Thread Pool and Data Sharing
  docs/design/2022-07-25-read-thread-pool-and-data-sharing.md
  docs/design/images/2022-07-25-read-thread-pool-and-data-sharing.png
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.2

#5453 *: Simplify join executor translation
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5435 test: Simplify comparing the stream read result
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Core/ColumnWithTypeAndName.cpp
  dbms/src/Core/ColumnWithTypeAndName.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_column_filter.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_data_streams.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_index_manager.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_mode.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TestUtils/InputStreamTestUtils.cpp
  dbms/src/TestUtils/InputStreamTestUtils.h
  dbms/src/TestUtils/tests/gtest_function_test_utils.cpp
  dbms/src/TestUtils/tests/gtest_inputstream_test_utils.cpp
  dbms/src/TestUtils/tests/gtest_print_columns.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5506 fix the schema version error in sync schema when latest schema diff is empty
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.2

#5494 *: Refine the ExchangeReceiverResult
  dbms/src/Common/ThreadManager.cpp
  dbms/src/Common/ThreadManager.h
  dbms/src/DataStreams/IBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5491 Add benchmark for collation
  dbms/src/Functions/tests/bench_collation.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L
