Repository pingcap/tiflash, pull requests merged in 2022-06, with the labels that each got.

#5011 support mix_mode in dt_workload
  dbms/src/Storages/DeltaMerge/tools/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/MainEntry.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/Options.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/Options.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5029 enable new function test framework by default
  dbms/src/Functions/tests/gtest_arithmetic_functions.cpp
  dbms/src/Functions/tests/gtest_bitand.cpp
  dbms/src/Functions/tests/gtest_bitnot.cpp
  dbms/src/Functions/tests/gtest_bitor.cpp
  dbms/src/Functions/tests/gtest_bitxor.cpp
  dbms/src/Functions/tests/gtest_date_add.cpp
  dbms/src/Functions/tests/gtest_date_or_datetime_to_something.cpp
  dbms/src/Functions/tests/gtest_date_sub.cpp
  dbms/src/Functions/tests/gtest_datetime_daymonthyear.cpp
  dbms/src/Functions/tests/gtest_duration_pushdown.cpp
  dbms/src/Functions/tests/gtest_functions_round_with_frac.cpp
  dbms/src/Functions/tests/gtest_ifnull.cpp
  dbms/src/Functions/tests/gtest_inet_aton_ntoa.cpp
  dbms/src/Functions/tests/gtest_is_true_false.cpp
  dbms/src/Functions/tests/gtest_least_greatest.cpp
  dbms/src/Functions/tests/gtest_logical.cpp
  dbms/src/Functions/tests/gtest_regexp.cpp
  dbms/src/Functions/tests/gtest_string_left.cpp
  dbms/src/Functions/tests/gtest_string_lrtrim.cpp
  dbms/src/Functions/tests/gtest_strings_cmp.cpp
  dbms/src/Functions/tests/gtest_strings_format.cpp
  dbms/src/Functions/tests/gtest_strings_right.cpp
  dbms/src/Functions/tests/gtest_strings_search.cpp
  dbms/src/Functions/tests/gtest_strings_tidb_concat.cpp
  dbms/src/Functions/tests/gtest_strings_trim.cpp
  dbms/src/Functions/tests/gtest_substring.cpp
  dbms/src/Functions/tests/gtest_substring_index.cpp
  dbms/src/Functions/tests/gtest_unix_timestamp.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5046 Fix potential data inconsistency under heavy ddl operation
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/SchemaBuilder.cpp
  dbms/src/Storages/Transaction/TiDBSchemaSyncer.h
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  tests/fullstack-test2/ddl/alter_column_when_pk_is_handle.test
Labels: CHERRY-PICK, status/can-merge, type/bug-fix, status/LGT2, size/L, release-note, cherry-pick-approved

#5044 Fix potential data inconsistency under heavy ddl operation
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  tests/fullstack-test2/ddl/alter_column_when_pk_is_handle.test
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#4523 fix empty segment cannot merge after gc
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaPackFile.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  tests/delta-merge-test/query/misc/timestamp_rough_set_filter.test
  tests/fullstack-test-dt/expr/timestamp_filter.test
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XL, release-note, cherry-pick-approved, type/cherry-pick-for-release-5.3

#5053 *: fix invalid fmt format string in CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#3703 Do background compaction when the ratio of stable data covered by delete range is too large
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/GCManager.cpp
  dbms/src/Storages/GCManager.h
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/BackgroundService.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XL, release-note, cherry-pick-approved

#5056 increase bg gc check interval
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/XS, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5069 PageStorage: Fix pages are not deleted under some cases
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/V2/PageEntries.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1

#5070 PageStorage: Fix pages are not deleted under some cases (#5069)
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/V2/PageEntries.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, cherry-pick-approved

#5059 Fix unstable drop table unit test
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.1

#5083 use pagestorage V2 by default
  dbms/src/Storages/FormatVersion.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, cherry-pick-approved

#5047 Add `Precompiled header` for modules & Refine by PImpl to accelerate release build
  CMakeLists.txt
  cmake/find_ccache.cmake
  dbms/CMakeLists.txt
  dbms/pch-common.h
  dbms/pch-dbms.h
  dbms/pch-kvpb.h
  dbms/pch-stl.h
  dbms/src/Common/FmtUtils.h
  dbms/src/Common/TiFlashException.cpp
  dbms/src/Common/TiFlashException.h
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/CoprocessorReader.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.h
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.h
  dbms/src/Flash/Management/tests/gtest_manual_compact.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
  dbms/src/Interpreters/Context.h
  dbms/src/Server/CLIService.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ReadIndexWorker.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  release-centos7-llvm/scripts/build-tiflash-release.sh
Labels: type/enhancement, status/can-merge, status/LGT2, size/XL, release-note-none

#5041 Test: Mock Input columns for operator tests
  dbms/src/DataStreams/MockExchangeReceiverInputStream.cpp
  dbms/src/DataStreams/MockExchangeReceiverInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/tests/gtest_executor.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4988 Improve the performance of partition table in extreme case
  dbms/src/DataStreams/MultiplexInputStream.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5086 Fix some fail cases when enable TASN
  dbms/src/Flash/Management/tests/gtest_manual_compact.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/tests/MultiSegmentTestUtil.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5094 PageStorage: Fix entry.tag after full gc && add more debug message
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/Page/PageUtil.h
  dbms/src/Storages/Page/V2/tests/gtest_page_util.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1

#5090 feat: add hardware information of server as an attribute
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/Server.cpp
  dbms/src/Server/Server.h
  dbms/src/Server/ServerInfo.cpp
  dbms/src/Server/ServerInfo.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5123 move `tunnel_map` to MPPTunnelSet
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5126 add some notes about `getMemoryAmount()` and `getNumberOfPhysicalCPUCores()`
  dbms/src/Common/getNumberOfPhysicalCPUCores.h
  dbms/src/Storages/DeltaMerge/workload/Handle.h
  libs/libcommon/include/common/getMemoryAmount.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5098 *: remove TableFunctionFile
  dbms/src/Storages/StorageFile.cpp
  dbms/src/Storages/StorageFile.h
  dbms/src/Storages/registerStorages.cpp
  dbms/src/TableFunctions/TableFunctionFile.cpp
  dbms/src/TableFunctions/TableFunctionFile.h
  dbms/src/TableFunctions/registerTableFunctions.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5133 README.md: update URL of TiDB Cloud free trial
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5021 Test: Mock window function, refactor window function tests
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Interpreters/WindowDescription.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TestUtils/executorSerializer.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
  dbms/src/WindowFunctions/tests/gtest_window_functions.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4820 Introduce physical plan and add switch
  .github/workflows/license-checker.yml
  dbms/src/Common/TiFlashException.h
  dbms/src/Flash/CMakeLists.txt
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlan.h
  dbms/src/Flash/Planner/PhysicalPlanBuilder.cpp
  dbms/src/Flash/Planner/PhysicalPlanBuilder.h
  dbms/src/Flash/Planner/PhysicalPlanHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.h
  dbms/src/Flash/Planner/PlanType.cpp
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Planner.cpp
  dbms/src/Flash/Planner/Planner.h
  dbms/src/Flash/Planner/optimize.cpp
  dbms/src/Flash/Planner/optimize.h
  dbms/src/Flash/Planner/plans/PhysicalLeaf.h
  dbms/src/Flash/Planner/plans/PhysicalSource.h
  dbms/src/Flash/Planner/plans/PhysicalUnary.h
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_qb_interpreter.cpp
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5141 Remove the log with high frequency and not useful enough
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/TiDB/Schema/SchemaBuilder-internal.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5079 modify cached_gc_safe_point to atomic to prevent more request to PD
  dbms/src/Storages/Transaction/PDTiKVClient.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5136 Removed a unused proxy status api named test-show
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5139 enhencement: supplement the comment for SchemaActionType
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4723 Revise default background threads size
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, release-note-none, size/M

#5137 add microbenchmark for exchange and window function
  dbms/CMakeLists.txt
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/tests/CMakeLists.txt
  dbms/src/Flash/tests/WindowTestUtil.h
  dbms/src/Flash/tests/bench_exchange.cpp
  dbms/src/Flash/tests/bench_exchange.h
  dbms/src/Flash/tests/bench_window.cpp
  dbms/src/Flash/tests/exchange_perftest.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  libs/libcommon/include/common/types.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5157 Fix the rename_table_across_databases.test to make it can run successfully multiple times.
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5158 *: Add some comments about decoding
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.h
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/region_helper.h
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5153 MinMax Index Supports Nullable DataType
  dbms/src/DataTypes/IDataType.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5165 fix pageworklaod
  dbms/src/Storages/Page/workload/CMakeLists.txt
  dbms/src/Storages/Page/workload/HeavyMemoryCostInGC.h
  dbms/src/Storages/Page/workload/HeavyRead.h
  dbms/src/Storages/Page/workload/HeavySkewWriteRead.h
  dbms/src/Storages/Page/workload/HeavyWrite.h
  dbms/src/Storages/Page/workload/HighValidBigFileGC.h
  dbms/src/Storages/Page/workload/HoldSnapshotsLongTime.h
  dbms/src/Storages/Page/workload/MainEntry.cpp
  dbms/src/Storages/Page/workload/Normal.h
  dbms/src/Storages/Page/workload/PSWorkload.h
  dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
  dbms/src/Storages/Page/workload/ThousandsOfOffset.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5182 Enhancement: Add how to run integration tests and microbenchmark tests in README
  README.md
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5130 Enhancement: add a integrated test on DDL module
  dbms/src/Common/FailPoint.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  tests/fullstack-test2/ddl/multi_alter_with_write.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5176 Revert "Revise default background threads size"
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5186 chore: remove extra dyn cast
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5175 Add MPPReceiverSet, which includes ExchangeReceiver and CoprocessorReader
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5166 DDL: Use Column Name Instead of Offset to Find the common handle cluster index
  dbms/src/Core/Block.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/dbgFuncMockRaftCommand.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgFuncRegion.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/Storages/Transaction/tests/bench_region_block_reader.cpp
  dbms/src/Storages/Transaction/tests/gtest_decoding_storage_schema_snapshot.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
  tests/fullstack-test-dt/clustered_index/ddl.test
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XXL, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#4876 Add random failpoint in critical paths
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/Common/wrapInvocable.h
  dbms/src/DataStreams/SharedQueryBlockInputStream.h
  dbms/src/DataStreams/SizeLimits.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5163 optimize ps v3 restore
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5196 Fix build failed
  dbms/src/Common/FailPoint.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5199 feat: delta tree dispatching
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/DeltaTree.ipp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5181 feat: introduce specialized API to write fixed length data rapidly
  dbms/src/Flash/Coprocessor/TiDBColumn.cpp
  dbms/src/IO/WriteBuffer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5188 Add gtest for Limit, TopN, Projection (#5187)
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Flash/tests/gtest_executor.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5202 add `MPPTask::handleError()`
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/UnionBlockInputStream.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/TaskStatus.cpp
  dbms/src/Flash/Mpp/TaskStatus.h
  tests/fullstack-test/mpp/issue_2471.test
  tests/fullstack-test/mpp/mpp_fail.test
  tests/run-test.py
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5257 Check result of starting grpc server
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note

#5259 fix: aarch64-quick-fix
  contrib/arm-optimized-routines-cmake/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none
