Repository pingcap/tiflash, pull requests merged in 2022-12, with the labels that each got.

#6300 Support Extract DateTimeFromString
  dbms/src/Common/MyDuration.h
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/StringUtils/StringUtils.h
  dbms/src/Common/tests/gtest_mytime.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsDateTime.cpp
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/FunctionsDuration.h
  dbms/src/Functions/tests/gtest_datetime_extract.cpp
  tests/fullstack-test/expr/extract_datetime_from_string.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6316 Support regexp_substr function
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRegexp.cpp
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/tests/gtest_regexp.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6396 Add RFC for 'Enrich the information of Explain Analyze for TableScan'
  docs/design/2022-12-01-enrich-the-information-of-explain-analyze-for-tablescan.md
  docs/design/images/2022-12-01-enrich-the-information-of-explain-analyze-for-tablescan-1.png
  docs/design/images/2022-12-01-enrich-the-information-of-explain-analyze-for-tablescan-2.png
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6378 storage: handle IngestSST using segment split
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#6406 refine/add some logs
  dbms/src/DataStreams/SquashingTransform.cpp
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6405 Optimize search write position in BlobFile
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.5

#6377 Json unquote extract pushdown
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Common/UTF8Helpers.cpp
  dbms/src/Common/UTF8Helpers.h
  dbms/src/Common/tests/gtest_UTF8Helpers.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/TiDBTime.h
  dbms/src/Functions/FunctionsJson.cpp
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_cast_json_as_string.cpp
  dbms/src/Functions/tests/gtest_json_extract.cpp
  dbms/src/Functions/tests/gtest_json_unquote.cpp
  dbms/src/IO/Endian.h
  dbms/src/Storages/Transaction/DatumCodec.cpp
  dbms/src/Storages/Transaction/DatumCodec.h
  dbms/src/Storages/Transaction/JSONCodec.cpp
  dbms/src/Storages/Transaction/JsonBinary.cpp
  dbms/src/Storages/Transaction/JsonBinary.h
  dbms/src/Storages/Transaction/JsonPathExpr.cpp
  dbms/src/Storages/Transaction/JsonPathExpr.h
  dbms/src/Storages/Transaction/JsonPathExprRef.cpp
  dbms/src/Storages/Transaction/JsonPathExprRef.h
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/tests/gtest_json_binary.cpp
  dbms/src/Storages/Transaction/tests/gtest_json_path_expr.cpp
  tests/fullstack-test/expr/cast_json_as_string.test
  tests/fullstack-test/expr/json_extract.test
  tests/fullstack-test/expr/json_unquote_extract.test
  tests/run-test.py
Labels: status/can-merge, status/LGT2, size/XXL

#6408 Revert "Use `num_streams` as parallelism when read thread is enabled."
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6356 make join as top level operator
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.h
Labels: status/can-merge, status/LGT2, size/L, release-note

#6421 Use `BlockIO.in->cancel` directly to avoid possible blocking of ProcessList::mutex
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
Labels: status/can-merge, status/LGT2, release-note, size/M, cherry-pick-approved

#6427 Combine all data in one UniversalPageStorage instance
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/UniversalPage.h
  dbms/src/Storages/Page/UniversalWriteBatch.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_paths.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdTrait.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.h
  dbms/src/Storages/Page/universal/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/workload/PSRunnable.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: size/XXL, release-note-none, needs-rebase

#6268 *: Refine LimitInputStream
  dbms/src/DataStreams/LimitBlockInputStream.cpp
  dbms/src/DataStreams/LimitBlockInputStream.h
  dbms/src/DataStreams/LimitTransformAction.cpp
  dbms/src/DataStreams/LimitTransformAction.h
  dbms/src/DataStreams/tests/CMakeLists.txt
  dbms/src/DataStreams/tests/expression_stream.cpp
  dbms/src/DataStreams/tests/filter_stream.cpp
  dbms/src/DataStreams/tests/filter_stream_hitlog.cpp
  dbms/src/DataStreams/tests/sorting_stream.cpp
  dbms/src/DataStreams/tests/union_stream2.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/plans/PhysicalLimit.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/tests/CMakeLists.txt
  dbms/src/Interpreters/tests/expression.cpp
  dbms/src/Storages/System/StorageSystemNumbers.cpp
  dbms/src/Storages/tests/CMakeLists.txt
  dbms/src/Storages/tests/storage_log.cpp
  dbms/src/Storages/tests/system_numbers.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6433 reduce column files num under heavy write pressure
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XL, release-note, cherry-pick-approved

#6392 Throw when meet empty PK
  dbms/src/Common/RedactHelpers.cpp
  dbms/src/Common/RedactHelpers.h
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/Transaction/RegionData.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6430 Get correct cpu cores in k8s pod
  dbms/src/Common/getNumberOfLogicalCPUCores.cpp
  dbms/src/Common/getNumberOfLogicalCPUCores.h
  dbms/src/Common/getNumberOfPhysicalCPUCores.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/ServerInfo.h
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6446 PageStorage: background version compact for v2
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageEntries.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h
  dbms/src/Storages/Page/V2/gc/LegacyCompactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_data_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_legacy_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_paths.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Page/workload/PSWorkload.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  metrics/grafana/tiflash_proxy_details.json
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/XXL, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6447 PageStorage: background version compact for v2 (#6446)
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageEntries.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h
  dbms/src/Storages/Page/V2/gc/LegacyCompactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_data_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_legacy_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_paths.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Page/workload/PSWorkload.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  metrics/grafana/tiflash_proxy_details.json
Labels: CHERRY-PICK, status/can-merge, status/LGT2, size/XXL, release-note, cherry-pick-approved

#6472 Refine the storage->read in DAGStorageInterpreter
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/RegionQueryInfo.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/LearnerRead.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6461 Optimize delta compact strategy to reduce iops and write amplification
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6483 Add metrics about the status of exchange sender/receiver queue
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6481 Set max_threads according to the number of physical cpu cores
  dbms/src/Common/getNumberOfCPUCores.cpp
  dbms/src/Common/getNumberOfCPUCores.h
  dbms/src/Common/getNumberOfLogicalCPUCores.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.5

#6487 Fix compilation error on macOS m1 due to sprintf
  dbms/src/Storages/Page/tools/PageCtl/MainEntry.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6280 split hash join return block if its rows is more than max_block_size
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.cpp
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.cpp
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.cpp
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/MockExchangeReceiverInputStream.h
  dbms/src/DataStreams/MockTableScanBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#6484 Minor refine of `TableLock` and `MPPTask::cancel`
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.h
  dbms/src/Flash/Executor/QueryExecutor.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6492 Support reading from remote delta
  dbms/CMakeLists.txt
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileRemote.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileRemote.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetStorageReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/RemoteProto/RemoteProtos.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.h
  dbms/src/Storages/DeltaMerge/Remote/Manager.cpp
  dbms/src/Storages/DeltaMerge/Remote/Manager.h
  dbms/src/Storages/DeltaMerge/Remote/ObjectId.h
  dbms/src/Storages/DeltaMerge/RemoteSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/universal/Readers.h
  dbms/src/Storages/Page/universal/UniversalPageStorage.h
  dbms/src/Storages/Page/workload/PSRunnable.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: do-not-merge/release-note-label-needed, size/XXL

#6493 [Cloud] fast add peer: support basic ffi
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
Labels: release-note-none

#6494 [Cloud] fast add peer: main body
  dbms/src/Storages/Transaction/ProxyFFI.cpp
Labels: release-note-none, size/M

#6497 move NonJoinedBlockInputStream out of Join.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6499 fix typo in config-template.toml
  etc/config-template.toml
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6501 *: remove redundant log
  dbms/src/Common/TiFlashSecurity.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6502 *: .clang-format ignores protobuf files
  .clang-format
  dbms/src/Flash/FlashService.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/CertificateReloader.cpp
  dbms/src/Server/CertificateReloader.h
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/MetricsPrometheus.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6505 Avoid the occurrence of 0 physical cpu cores
  dbms/src/Common/getNumberOfCPUCores.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6503 .*: Refine `FilterBlockInputStream` and `FilterTransformAction`
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/DataStreams/FilterTransformAction.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6510 optimize write latency and add metric for UniversalPageStorage
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.cpp
Labels: release-note-none, size/L

#6274 refine SegmentRead streams
  dbms/src/DataStreams/SegmentReadTransformAction.cpp
  dbms/src/DataStreams/SegmentReadTransformAction.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6420 Optimize deltamerge store restore speed
  dbms/src/DataTypes/DataTypeFactory.cpp
  dbms/src/DataTypes/DataTypeFactory.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/ColumnStat.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6512 MPP: Fix bug when building disaggregated regions info of mpp dispatch task
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
  dbms/src/Debug/dbgFuncCoprocessorUtils.cpp
  dbms/src/Debug/dbgFuncCoprocessorUtils.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlock.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/DAGQuerySource.h
  dbms/src/Flash/Coprocessor/DAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/FineGrainedShuffle.h
  dbms/src/Flash/Coprocessor/InterpreterDAG.h
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.h
  dbms/src/Flash/Coprocessor/RequestUtils.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_req_encode.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Planner/PlanQuerySource.cpp
  dbms/src/Flash/Planner/PlanQuerySource.h
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Statistics/ExchangeSenderImpl.cpp
  dbms/src/Flash/Statistics/ExecutorStatistics.h
  dbms/src/Flash/tests/gtest_storage_disaggregated.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/TestUtils/ColumnsToTiPBExpr.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6519 Disable ingest range check
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
Labels: status/can-merge, status/LGT2, release-note, size/M, needs-cherry-pick-release-6.5

#6511 Test: fix mpp test bug
  dbms/src/Debug/MockComputeServerManager.cpp
  dbms/src/Debug/MockComputeServerManager.h
  dbms/src/Debug/MockExecutor/AggregationBinder.cpp
  dbms/src/Debug/MockExecutor/AggregationBinder.h
  dbms/src/Debug/MockExecutor/AstToPB.cpp
  dbms/src/Debug/MockExecutor/AstToPB.h
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.h
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.h
  dbms/src/Debug/MockExecutor/ExecutorBinder.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Debug/MockExecutor/LimitBinder.cpp
  dbms/src/Debug/MockExecutor/ProjectBinder.cpp
  dbms/src/Debug/MockExecutor/SelectionBinder.cpp
  dbms/src/Debug/MockExecutor/SelectionBinder.h
  dbms/src/Debug/MockExecutor/SortBinder.cpp
  dbms/src/Debug/MockExecutor/TableScanBinder.cpp
  dbms/src/Debug/MockExecutor/TopNBinder.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Debug/dbgFuncCoprocessorUtils.cpp
  dbms/src/Debug/dbgFuncCoprocessorUtils.h
  dbms/src/Debug/dbgNaturalDag.h
  dbms/src/Debug/dbgQueryCompiler.cpp
  dbms/src/Debug/dbgQueryCompiler.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Debug/dbgQueryExecutor.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6517 [Cloud] fast add peer: Peer selecting
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/Keys.cpp
  dbms/src/Storages/Transaction/Keys.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XXL, release-note-none

#6526 Fix stale read in testing scenario
  dbms/src/Storages/Transaction/LearnerRead.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6530 *: Remove useless DataType widen property
  dbms/src/DataTypes/DataTypeNullable.cpp
  dbms/src/DataTypes/DataTypeNullable.h
  dbms/src/DataTypes/DataTypeNumberBase.cpp
  dbms/src/DataTypes/DataTypeNumberBase.h
  dbms/src/DataTypes/DataTypesNumber.h
  dbms/src/DataTypes/IDataType.h
  dbms/src/Storages/MutableSupport.h
  dbms/src/Storages/Transaction/Datum.cpp
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
  dbms/src/Storages/Transaction/TypeMapping.cpp
  dbms/src/Storages/Transaction/tests/gtest_type_mapping.cpp
Labels: status/can-merge, status/LGT2, type/code-quality-improvement, size/XL, release-note-none

#6531 move MergingAndConvertingBlockInputStream out of Aggregate.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/MergingAndConvertingBlockInputStream.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6527 doc: add doc for auto-reload-cert
  docs/design/2022-12-21-auto-reload-tls-certificate.md
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6539 *: remove limitByStream
  dbms/src/DataStreams/LimitByBlockInputStream.cpp
  dbms/src/DataStreams/LimitByBlockInputStream.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6445 Add unit tests for fine-grained join & agg
  dbms/src/Debug/MockExecutor/AggregationBinder.cpp
  dbms/src/Debug/MockExecutor/AggregationBinder.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6543 Serialize ColumnFileTiny schema to remote snapshot
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: release-note-none, size/L

#6544 Adapt with ser/deser
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/RemoteProto/RemoteProtos.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/Remote/DisaggregatedSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: do-not-merge/release-note-label-needed, size/XXL

#6551 Support disaggregated read all data from remote data source
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: release-note-none, size/L

#6553 Fix bug for reading persisted cfs under disaggregated read
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Flash/Disaggregated/GRPCPageReceiverContext.cpp
  dbms/src/Flash/Disaggregated/GRPCPageReceiverContext.h
  dbms/src/Flash/Disaggregated/PageReceiver.cpp
  dbms/src/Flash/Disaggregated/PageReceiver.h
  dbms/src/Flash/Disaggregated/PageTunnel.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_remote_read_task.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/Page/PageUtil.cpp
  dbms/src/Storages/Page/PageUtil.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: size/XL, release-note-none

#6529 merge output blocks if need in hash join
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/SquashingHashJoinBlockTransform.cpp
  dbms/src/DataStreams/SquashingHashJoinBlockTransform.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_squashing_hash_join_transform.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note

#6549 refine agg/topn and add more unit tests
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/DataStreams/MergeSortingBlocksBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlocksBlockInputStream.h
  dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6370 Support regexp_replace function
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRegexp.cpp
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/tests/gtest_regexp.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6557 Test: Refine fine-grained shuffle ut
  dbms/src/Debug/MockExecutor/AggregationBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeSenderBinder.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6556 Fix big endian issue for StringHashTable
  dbms/src/Common/HashTable/StringHashTable.h
  dbms/src/Common/HashTable/TwoLevelStringHashTable.h
  dbms/src/IO/Endian.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6560 chore: fix build on mac m1
  dbms/src/Common/OptimizedRegularExpression.inl.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5686 feat: support function unhex pushdown
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_unhex.cpp
  tests/fullstack-test/expr/unhex.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6567 metrics: refine metrics of `Request Duration` and `Request Handle Duration`
  dbms/src/Common/TiFlashMetrics.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/M
