Repository pingcap/tiflash, pull requests merged in 2022-05, with the labels that each got.

#4791 Support weekofyear pushdown to tiflash
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsDateTime.cpp
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/tests/gtest_weekofyear.cpp
  tests/fullstack-test/expr/week_of_year.test
Labels: status/can-merge, status/LGT2, size/L, release-note

#4818 Revert "Dump suspicious val (#4812)"
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
Labels: status/LGT1, release-note-none, size/L, do-not-merge/cherry-pick-not-approved

#4819 fix bug that Decimal256's hash value is not stable (#1574) (#1597)
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Common/SipHash.h
  dbms/src/Common/tests/gtest_siphash.cpp
  dbms/src/Core/Types.h
  dbms/src/DataTypes/DataTypeDecimal.h
  dbms/src/DataTypes/IDataType.h
  dbms/src/Flash/Coprocessor/DefaultChunkCodec.cpp
  dbms/src/Storages/Transaction/DatumCodec.cpp
  dbms/src/Storages/Transaction/DatumCodec.h
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/tests/gtest_row_v2.cpp
  tests/fullstack-test/expr/decimal_hash.test
Labels: status/LGT1, size/XL, release-note-none, do-not-merge/cherry-pick-not-approved

#4811 Fix gtest mpp tunnel local write unstable issue
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4736 PageStorage APIs support throw_on_not_exist.
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V1/PageStorage.cpp
  dbms/src/Storages/Page/V1/PageStorage.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/entries_helper.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4797 refactor: Remove unused FunctionIPv6NumToString from ClickHouse.
  dbms/src/Functions/FunctionsCoding.cpp
  dbms/src/Functions/FunctionsCoding.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4815 Not moving local object in return statement
  dbms/src/Common/DynamicThreadPool.h
  dbms/src/Common/packTask.h
  dbms/src/Common/wrapInvocable.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4783 Migrate table scan related code to `DAGStorageInterpreter`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Coprocessor/PushDownFilter.cpp
  dbms/src/Flash/Coprocessor/PushDownFilter.h
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.h
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4828 *: remove useless BatchCommandsHandler.
  dbms/src/Flash/BatchCommandsHandler.cpp
  dbms/src/Flash/BatchCommandsHandler.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4177 Fix a encryption problem in pagestorage v3.
  dbms/src/Storages/Page/V3/BlobFile.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4094 Add some tests to test PageStorageV3 IO limiter
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/TestUtils/MockReadLimiter.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4242 BlobStore:Add a block_alignment_bytes to make sure write have been align
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/ConfigSettings.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4784 Refine some comments about learner read
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Functions/GeoUtils.h
  dbms/src/Storages/Transaction/LearnerRead.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4838 Fix getMaxId won't get the right max id before GC
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4817 Enable PageStorage V3 by default in dtworkload tool
  dbms/src/Storages/DeltaMerge/tools/workload/MainEntry.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/Options.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/Options.h
  dbms/src/Storages/DeltaMerge/tools/workload/TableGenerator.cpp
  dbms/src/Storages/DeltaMerge/tools/workload/TableGenerator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4839 avoid use MAX_NAMESPACE_ID as kvstore's ns_id
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Transaction/RegionPersister.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4840 Fix dump snapshot encryption info not right after rename.
  dbms/src/Storages/Page/V3/LogFile/LogReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4845 Revert "Fix getMaxId won't get the right max id before GC"
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4619 Add a metric to statistics expansion or reused.
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMapRBTree.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4792 MinMax Index Supports Nullable DataType
  dbms/src/DataTypes/IDataType.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4788 Interpreter: Run interpreter test without exchange executors
  dbms/src/DataStreams/MockTableScanBlockInputStream.cpp
  dbms/src/DataStreams/MockTableScanBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/InterpreterTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
  dbms/src/WindowFunctions/tests/gtest_window_functions.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4673 clear storage data before drop its metadata
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Debug/dbgFuncMisc.h
  dbms/src/Interpreters/InterpreterDropQuery.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/IStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  tests/delta-merge-test/raft/schema/partition_table_restart.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4850 Fix wal may dump write diff type in same page_id
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  tests/delta-merge-test/ddl/alter.test
  tests/delta-merge-test/raft/txn_mock/partition_table.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4854 Fix bug for deseri type error that cause data error
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4589 Interpreter: Remove Optimize query.
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterOptimizeQuery.cpp
  dbms/src/Interpreters/InterpreterOptimizeQuery.h
  dbms/src/Parsers/ASTOptimizeQuery.h
  dbms/src/Parsers/ParserOptimizeQuery.cpp
  dbms/src/Parsers/ParserOptimizeQuery.h
  dbms/src/Parsers/ParserQuery.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4564 Interpreter: Remove kill Query
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterKillQueryQuery.cpp
  dbms/src/Interpreters/InterpreterKillQueryQuery.h
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Parsers/ASTKillQueryQuery.cpp
  dbms/src/Parsers/ASTKillQueryQuery.h
  dbms/src/Parsers/ParserKillQueryQuery.cpp
  dbms/src/Parsers/ParserKillQueryQuery.h
  dbms/src/Parsers/ParserQueryWithOutput.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4568 Interpreter: Remove CheckQuery.
  dbms/src/Interpreters/InterpreterCheckQuery.cpp
  dbms/src/Interpreters/InterpreterCheckQuery.h
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Parsers/ASTCheckQuery.h
  dbms/src/Parsers/ParserCheckQuery.cpp
  dbms/src/Parsers/ParserCheckQuery.h
  dbms/src/Parsers/ParserQueryWithOutput.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4587 Interpreter: Remove Truncate query
  dbms/src/Functions/FunctionBinaryArithmetic.h
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterTruncateQuery.cpp
  dbms/src/Interpreters/InterpreterTruncateQuery.h
  dbms/src/Parsers/ASTTruncateQuery.h
  dbms/src/Parsers/ParserQuery.cpp
  dbms/src/Parsers/ParserTruncateQuery.cpp
  dbms/src/Parsers/ParserTruncateQuery.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4864 fix tispark query err: `for PushDownFilter, conditions and executor_id should both be empty or neither should be empty`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/PushDownFilter.cpp
  dbms/src/Flash/Coprocessor/PushDownFilter.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4726 PageStorage: Add mix mode
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/WriteBatches.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/Snapshot.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Page/WriteBatch.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4833 Add fail point pause_after_copr_streams_acquired_once
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4586 Interpreter: Remove Table properties query
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterShowCreateQuery.cpp
  dbms/src/Interpreters/InterpreterShowCreateQuery.h
  dbms/src/Parsers/ParserQueryWithOutput.cpp
  dbms/src/Parsers/ParserTablePropertiesQuery.cpp
  dbms/src/Parsers/ParserTablePropertiesQuery.h
  dbms/src/Parsers/TablePropertiesQueriesASTs.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4594 Interpreter: Remove delete query
  dbms/src/Interpreters/InterpreterDeleteQuery.cpp
  dbms/src/Interpreters/InterpreterDeleteQuery.h
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Parsers/ASTDeleteQuery.cpp
  dbms/src/Parsers/ASTDeleteQuery.h
  dbms/src/Parsers/ParserDeleteQuery.cpp
  dbms/src/Parsers/ParserDeleteQuery.h
  dbms/src/Parsers/ParserQuery.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4878 restore global storage pool in test cases
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4590 Interpreter: Remove system query
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterSystemQuery.cpp
  dbms/src/Interpreters/InterpreterSystemQuery.h
  dbms/src/Parsers/ASTSystemQuery.cpp
  dbms/src/Parsers/ASTSystemQuery.h
  dbms/src/Parsers/ParserQuery.cpp
  dbms/src/Parsers/ParserSystemQuery.cpp
  dbms/src/Parsers/ParserSystemQuery.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4863 misc: Add comments
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4795 add DB config max_threads by grpc context
  dbms/src/Flash/FlashService.cpp
Labels: status/can-merge, status/LGT2, size/S, release-note

#4873 Add a force transfrom meta from v2 to v3
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/PageEntry.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4866 Add to_seconds support for tiflash
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/MyTime.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsDateTime.cpp
  dbms/src/Functions/FunctionsDateTime.h
  dbms/src/Functions/tests/gtest_toseconds.cpp
  tests/fullstack-test/expr/to_seconds.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4882 Support big page PUT into blobstore.
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapBig.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4875 Add a force transfrom kvstore from v2 to v3
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4881 add metrics for storage pool run mode
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4898 Fix nullptr when mix mode change to only v3.
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4895 Revert "MinMax Index Supports Nullable DataType"
  dbms/src/DataTypes/IDataType.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4869 Delete config 'disable_bg_flush '
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/BackgroundService.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4890 Add option to support clang LTO(Link Time Optimization) and time-traces
  CMakeLists.txt
Labels: type/enhancement, status/can-merge, status/LGT2, release-note-none, size/S

#4889 Fix the bug for restoring data with duplicated page id
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/Page/V3/tests/page_storage_ctl.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  tests/delta-merge-test/ddl/alter.test
  tests/delta-merge-test/raft/schema/partition_table_restart.test
  tests/delta-merge-test/raft/txn_mock/partition_table.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4804 doc: add pagestorage v3 design doc
  docs/design/2022-04-28-architecture-of-storage-engine-pagestorage.md
  docs/design/images/tiflash-dt-architecture.png
  docs/design/images/tiflash-ps-v3-architecture.png
  docs/design/images/tiflash-ps-v3-freemap.png
  docs/design/images/tiflash-ps-v3-wal-store.png
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4919 Fix some bugs in grafana panels
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4927 fix bug of weekofyear
  dbms/src/Common/MyTime.cpp
  dbms/src/Functions/tests/gtest_weekofyear.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4925 Fix pageutils will truncate the file if write failed
  dbms/src/Storages/Page/PageUtil.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_util.cpp
  dbms/src/Storages/Page/V3/BlobFile.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#4930 docs: git clone concurrently
  README.md
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4933 Fix ref a del id failed in mix mode.
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesView.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1

#4762 expression: check Overflow int128
  libs/libcommon/include/common/arithmeticOverflow.h
  libs/libcommon/src/tests/CMakeLists.txt
  libs/libcommon/src/tests/gtest_arithmetic_overflow.cpp
  tests/tidb-ci/fullstack-test-dt/expr_push_down.test
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4920 Add a fail point named force_change_all_blobs_to_read_only
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#4950 Fix StorageDeltaMerge constructor not match in gtest_manual_compact
  dbms/src/Flash/Management/tests/gtest_manual_compact.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4951 Add note about how to handle build oom or hang
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#4955 flush cache before segment merge
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: status/can-merge, needs-cherry-pick-release-4.0, type/bug-fix, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/L, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#4948 Add a global max_id to fix reuse page_id problem
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1

#4958 Schedule: track the waiting tasks with task ID, and deleted the scheduled task with exceeded state from the waiting tasks queue
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#4963 ignore delmark when add minmax for pk column (#4746)
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/tests/dm_basic_include.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  tests/docker/run.sh
  tests/docker/util.sh
Labels: status/LGT2, release-note, size/M, do-not-merge/cherry-pick-not-approved

#4938 Revert the retry applyRecord when loadEdit
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, type/bug-fix, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1

#4978 Remove useless template instantiations
  dbms/src/Functions/FunctionsTiDBConversion.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, release-note-none, size/L

#4961 fix clang tidy err for `ExpressionAnalyzer`, `Join`, `StorageJoin`, `DAGQueryBlockInterpreter`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Storages/StorageJoin.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4722 refine `handleJoin`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/tests/exchange_perftest.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Storages/StorageJoin.cpp
  tests/fullstack-test/mpp/misc_join.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#4984 Change BlobFileId to uint64.
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/V3/LogFile/LogFormat.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.1

#3790 *: Rename the function with “withCollation” postfix
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/IColumn.h
  dbms/src/Core/SortCursor.h
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/Interpreters/sortBlock.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4987 PageStorage: Fix the WAL snapshot dumped into file may contains invalid "being_ref_count"
  dbms/src/Encryption/FileProvider.cpp
  dbms/src/Encryption/FileProvider.h
  dbms/src/Encryption/MockKeyManager.cpp
  dbms/src/Encryption/MockKeyManager.h
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/entries_helper.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/Page/WALRecoveryMode.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1

#4884 Enable PageStorage V3 in UT
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4911 Interpreter: Print BlockInputStream
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/DataStreams/IBlockInputStream.cpp
  dbms/src/DataStreams/IBlockInputStream.h
  dbms/src/DataStreams/LimitBlockInputStream.cpp
  dbms/src/DataStreams/LimitBlockInputStream.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/PartialSortingBlockInputStream.cpp
  dbms/src/DataStreams/PartialSortingBlockInputStream.h
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/executeQuery.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5001 Fix v3 can not find entry in mix mode.
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1

#4861 Refine function test framework
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TestUtils/ColumnsToTiPBExpr.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5015 Optimize blobstore gc when current stat total size is 0
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.1

#4916 Fix an invalid default value cause bootstrap failed
  dbms/src/Storages/Transaction/TiDB.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#4999 PageStorage: Report the file usage of BlobStore
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/AsynchronousMetrics.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/FileUsage.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/Snapshot.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.1

#5024 Fix unstable ut in the master branch
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5014 refine get type from decimal literal
  dbms/src/Common/Decimal.h
  dbms/src/Core/Field.h
  dbms/src/DataTypes/DataTypeDecimal.h
  dbms/src/DataTypes/FieldToDataType.h
  dbms/src/DataTypes/tests/gtest_decimal_literal_datatype.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4932 Refactor: add new module schema
  dbms/CMakeLists.txt
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Debug/MockSchemaNameMapper.h
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncMockTiDBTable.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchemaName.cpp
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/IDAsPathUpgrader.cpp
  dbms/src/Interpreters/IDAsPathUpgrader.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
  dbms/src/Storages/System/StorageSystemDatabases.cpp
  dbms/src/Storages/System/StorageSystemTables.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/tests/gtest_rename_resolver.cpp
  dbms/src/Storages/Transaction/tests/gtest_table_info.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/TiDB/Schema/SchemaBuilder-internal.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/SchemaNameMapper.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/SchemaSyncer.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#4929 docs: Add rfc for compact table via sql
  docs/design/2022-05-19-compact-table-via-sql.md
  docs/design/images/2022-05-19-compact-table-via-sql-1.png
  docs/design/images/2022-05-19-compact-table-via-sql-2.png
  docs/design/images/2022-05-19-compact-table-via-sql-3.png
  docs/design/images/2022-05-19-compact-table-via-sql-4.png
  docs/design/images/2022-05-19-compact-table-via-sql-5.png
  docs/design/images/2022-05-19-compact-table-via-sql-6.png
  docs/design/images/2022-05-19-compact-table-via-sql-7.png
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#4903 Fix broken unit test for `--gtest_filter='*StorageDeltaMergeTest*:*RegionKVStoreTest*'`
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  tests/docker/config/tics_dt.toml
  tests/docker/config/tiflash_dt_async_grpc.toml
  tests/docker/config/tiflash_dt_disable_local_tunnel.toml
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5004 Remove useless code
  dbms/src/Debug/dbgFuncRegion.cpp
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/ProxyFFI.h
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.h
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/StorageEngineType.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  etc/config-template.toml
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5012 Add mix mode UT
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none
