Repository pingcap/tiflash, pull requests merged in 2022-08, with the labels that each got.

#5512 *: Combine LOG_XXX and LOG_FMT_XXX
  libs/libcommon/include/common/MacroUtils.h
  libs/libcommon/include/common/logger_useful.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5516 *: decouple FlashGrpcServerHolder from Server.cpp
  dbms/src/Flash/DiagnosticsService.cpp
  dbms/src/Flash/DiagnosticsService.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/Server.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5489 Optimize expression `LIKE() ESCAPE()` for bin collator
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Functions/CollationStringSearchOptimized.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Storages/Transaction/Collator.cpp
  dbms/src/Storages/Transaction/tests/gtest_tidb_collator.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XXL, release-note-none

#5520 fix wrong path for BlobStat under multi-disks env
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/TestUtils/MockDiskDelegator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5450 Test: Mock TiFlash compute service and dispatch MPPTask to single service.
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/CoprocessorHandler.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/IServer.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/Server/Server.cpp
  dbms/src/TestUtils/CMakeLists.txt
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5523 gtests: fix tiflash-sanitizer-daily (ASan)
  dbms/src/Storages/Transaction/tests/gtest_tidb_collator.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5495 feat: implement shiftLeft function push down
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/bitShiftLeft.cpp
  dbms/src/Functions/tests/gtest_bitshiftleft.cpp
  tests/fullstack-test/expr/bitshift_operator.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5536 fix potential dead lock when remove blob file
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5415 feat: calculate the io throughput in background in ReadLimiter
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/TestUtils/MockReadLimiter.h
Labels: status/can-merge, status/LGT2, size/XL, release-note

#5537 fix potential dead lock when remove blob file
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: CHERRY-PICK, status/can-merge, status/LGT2, release-note-none, size/S, cherry-pick-approved

#5526 Add more information when read index fail
  dbms/src/Storages/Transaction/LearnerRead.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5496 feat: Support elt pushdown
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionHelpers.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_strings_elt.cpp
  tests/fullstack-test/expr/elt.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#5543 Enhance join test framework with conditional expressions
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5557 fix bug in `MinTSOScheduler` that `estimated_thread_usage`/`waiting_tasks_count`/`active_tasks_count` are not 0 even if there is no queries running
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5550 fix dead lock when do truncate gc on blob file
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5564 Add desc of read thread and data sharing cache in grafana.
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5575 fix the problem that some config in profiles.default may not take effect
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5553 Fix mpp tunnel crash issue for async writer nullptr
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.2

#5593 fix: use arguments[arg0] as argument column offset
  dbms/src/Functions/FunctionsString.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5580 fix the problem that some config in profiles.default may not take effect
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/ConfigSettings.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: CHERRY-PICK, status/can-merge, status/LGT2, release-note-none, size/L, cherry-pick-approved

#5591 Fix compile error under MacOS
  dbms/src/Flash/Planner/PhysicalPlanVisitor.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5597 refine: shuffle column order before execute function ut
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5601 fix asan UT fail
  dbms/src/Flash/Planner/ExecutorIdGenerator.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5586 rename and remove some ps v3 config
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/ConfigSettings.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5594 time unit not match in ThreadMetricUtil.cpp
  dbms/src/Common/ThreadMetricUtil.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.2

#5607 fix: time unit not match in ThreadMetricUtil.cpp
  dbms/src/Common/ThreadMetricUtil.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5603 Fix panic when region is not found on TiFlash's side in `tryFlushData`
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.2

#5606 Fix panic when region is not found on TiFlash's side in tryFlushData to release-6.2
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: CHERRY-PICK, status/can-merge, status/LGT2, release-note-none, size/S, cherry-pick-approved

#5545 Wrap & Optimize rest bin collator
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Functions/CollationStringSearchOptimized.h
  dbms/src/Functions/FunctionsComparison.h
  dbms/src/Storages/Transaction/Collator.cpp
  dbms/src/Storages/Transaction/Collator.h
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XL, release-note-none

#5533 Enable read thread in dtworkload
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/DeltaMerge/workload/Options.cpp
  dbms/src/Storages/DeltaMerge/workload/Options.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5620 *: remove useless BlockInputStreams
  dbms/src/DataStreams/BlockExtraInfoInputStream.h
  dbms/src/DataStreams/DeletingDeletedBlockInputStream.cpp
  dbms/src/DataStreams/DeletingDeletedBlockInputStream.h
  dbms/src/DataStreams/ExtraHeadTailBlockInputStream.h
  dbms/src/DataStreams/FilterColumnsBlockInputStream.cpp
  dbms/src/DataStreams/FilterColumnsBlockInputStream.h
  dbms/src/DataStreams/InBlockDedupBlockInputStream.h
  dbms/src/DataStreams/PlaygroundBlockInputStream.h
  dbms/src/DataStreams/RemoveColumnsBlockInputStream.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5548 support CastTimeAsDuration in TiFlash
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  tests/fullstack-test/expr/cast_as_duration.test
Labels: status/can-merge, status/LGT2, size/L, release-note

#5569 Optimize equality comparison for small str with fixed size
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Storages/Transaction/CollatorUtils.h
  libs/libcommon/include/common/defines.h
  libs/libcommon/include/common/fixed_mem_eq.h
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XL, release-note-none

#5627 *: Remove embeddedDictionary and ExternalDictionary
  dbms/src/Databases/DatabaseDictionary.cpp
  dbms/src/Databases/DatabaseDictionary.h
  dbms/src/Databases/DatabaseFactory.cpp
  dbms/src/Dictionaries/Embedded/GeoDictionariesLoader.cpp
  dbms/src/Dictionaries/Embedded/GeoDictionariesLoader.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/Entries.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/HierarchiesProvider.cpp
  dbms/src/Dictionaries/Embedded/GeodataProviders/HierarchiesProvider.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/HierarchyFormatReader.cpp
  dbms/src/Dictionaries/Embedded/GeodataProviders/HierarchyFormatReader.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/IHierarchiesProvider.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/INamesProvider.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/NamesFormatReader.cpp
  dbms/src/Dictionaries/Embedded/GeodataProviders/NamesFormatReader.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/NamesProvider.cpp
  dbms/src/Dictionaries/Embedded/GeodataProviders/NamesProvider.h
  dbms/src/Dictionaries/Embedded/GeodataProviders/Types.h
  dbms/src/Dictionaries/Embedded/IGeoDictionariesLoader.h
  dbms/src/Dictionaries/Embedded/RegionsHierarchies.cpp
  dbms/src/Dictionaries/Embedded/RegionsHierarchies.h
  dbms/src/Dictionaries/Embedded/RegionsHierarchy.cpp
  dbms/src/Dictionaries/Embedded/RegionsHierarchy.h
  dbms/src/Dictionaries/Embedded/RegionsNames.cpp
  dbms/src/Dictionaries/Embedded/RegionsNames.h
  dbms/src/Dictionaries/Embedded/TechDataHierarchy.h
  dbms/src/Functions/FunctionsEmbeddedDictionaries.cpp
  dbms/src/Functions/FunctionsEmbeddedDictionaries.h
  dbms/src/Functions/FunctionsExternalDictionaries.cpp
  dbms/src/Functions/FunctionsExternalDictionaries.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/EmbeddedDictionaries.cpp
  dbms/src/Interpreters/EmbeddedDictionaries.h
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/ExternalDictionaries.cpp
  dbms/src/Interpreters/ExternalDictionaries.h
  dbms/src/Interpreters/IRuntimeComponentsFactory.h
  dbms/src/Interpreters/RuntimeComponentsFactory.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/StorageDictionary.cpp
  dbms/src/Storages/StorageDictionary.h
  dbms/src/Storages/System/StorageSystemDictionaries.cpp
  dbms/src/Storages/System/StorageSystemDictionaries.h
  dbms/src/Storages/System/attachSystemTables.cpp
  dbms/src/Storages/registerStorages.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5614 Test: support qualified column reference in writing tests
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5624 fix incorrect execution summary of table scan
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.h
  dbms/src/Flash/Planner/plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5637 Fix bug that mpp_task is not move to cancel thread due to llvm SOO
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.2

#5642 refine MPPTaskCancelFunctor
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.2

#5647 Remove `MPPTaskManager::findTaskWithTimeout`
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5629 Avoid duplicate column names for multiple windows.
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Planner/PhysicalPlanHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.h
  dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalWindow.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  tests/fullstack-test/mpp/window.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5615 *: Improve RUNTIME_CHECK (again)
  dbms/src/Common/Exception.h
  dbms/src/Common/tests/gtest_exception.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Planner/ExecutorIdGenerator.h
  dbms/src/Flash/Planner/FinalizeHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.cpp
  dbms/src/TestUtils/InputStreamTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5650 Fix data race in tunnel_set/receiver_set and establish call data
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.2

#5663 Set jemalloc's narenas to 40 for debug image to work properly in compute resource pool of k8s pods
  CMakeLists.txt
  contrib/jemalloc-cmake/CMakeLists.txt
  release-centos7-llvm/scripts/build-tiflash-release.sh
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.2

#5612 Fix fail to create three hops of ref pages
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/tests/TiFlashStorageTestBasic.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5660 fix the problem that there may be some obsolete data left in storage which cannot be deleted
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5573 Test: Mock multiple compute service to run MPPTasks.
  dbms/src/Debug/MockComputeServerManager.cpp
  dbms/src/Debug/MockComputeServerManager.h
  dbms/src/Debug/MockServerInfo.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Debug/astToExecutor.cpp
  dbms/src/Debug/astToExecutor.h
  dbms/src/Debug/dbgFuncCoprocessor.cpp
  dbms/src/Debug/dbgFuncCoprocessor.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/bench_window.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  libs/libdaemon/src/tests/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5679 Refactor KVStore/RegionPersister test
  dbms/src/Debug/MockSSTReader.h
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionMeta.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5544 remove big blob file type in ps v3
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapBig.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/TestUtils/MockDiskDelegator.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#5547 fix: align output type of second or third stage sum function with tidb
  dbms/src/AggregateFunctions/AggregateFunctionSum.cpp
  dbms/src/AggregateFunctions/AggregateFunctionSum.h
  dbms/src/AggregateFunctions/Helpers.h
  dbms/src/AggregateFunctions/tests/gtest_agg_func_return_type.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/TestUtils/AggregationTestUtils.cpp
  dbms/src/TestUtils/AggregationTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5572 Schedule SegmentReadTaskPool until no other component refer to it.
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_circular_scan_list.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.2

#5696 Avoid too many log in `ExchangeReceiver`/`MPPTunnel`
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5693 fix wrong alloc size when do heavy gc for blob file
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5649 metric: count foreground split / merge independently
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5683 More segment tests
  dbms/src/Common/CPUAffinityManager.h
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#5709 fix unstable mpp fail tests
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Mpp/MPPReceiverSet.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5705 avoid init useless DeltaMergeStore
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5656 do not merge delta foreground if replica not exist
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: status/can-merge, status/LGT2, size/S, release-note

#5713 MPMCQueue: push/pop return status; add cancelWith
  dbms/src/Common/Exception.h
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_mpmc_queue.cpp
  dbms/src/DataStreams/ParallelInputsProcessor.h
  dbms/src/DataStreams/SharedQueryBlockInputStream.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5729 remove old test for fast mode to make ci work
  tests/fullstack-test2/ddl/alter_table_tiflash_replica.test
  tests/fullstack-test2/ddl/alter_table_tiflash_replica_and_mode.test
  tests/fullstack-test2/ddl/alter_tiflash_mode.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#5724 Fix initialization of read thread pool.
  dbms/src/Server/Server.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5715 Use read tso instead of threrad ID in 'DBGInvoke search_log_for_key'
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5658 Optimize mem utils functions
  dbms/CMakeLists.txt
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Functions/CMakeLists.txt
  dbms/src/Functions/CollationOperatorOptimized.h
  dbms/src/Functions/CollationStringComparision.h
  dbms/src/Functions/CollationStringOptimized.cpp
  dbms/src/Functions/CollationStringSearch.h
  dbms/src/Functions/CollationStringSearchOptimized.h
  dbms/src/Functions/FunctionsComparison.cpp
  dbms/src/Functions/FunctionsComparison.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Functions/tests/gtest_strings_cmp.cpp
  dbms/src/Storages/Transaction/CollatorUtils.h
  dbms/src/Storages/Transaction/tests/gtest_tidb_collator.cpp
  libs/libcommon/CMakeLists.txt
  libs/libcommon/include/common/StringRef.h
  libs/libcommon/include/common/avx2_mem_utils.h
  libs/libcommon/include/common/avx2_strstr.h
  libs/libcommon/include/common/mem_utils.h
  libs/libcommon/include/common/mem_utils_opt.h
  libs/libcommon/src/avx2_mem_utils_impl.cpp
  libs/libcommon/src/tests/CMakeLists.txt
  libs/libcommon/src/tests/bench_mem_utils.cpp
  libs/libcommon/src/tests/gtest_mem_utils_opt.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, size/XXL, release-note-none

#5730 Remove useless experimental configurations of read thread pool.
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#5733 Fix exception of search_log_for_key.
  dbms/src/Debug/dbgFuncMisc.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#5752 fix ci
  tests/fullstack-test/expr/from_unixtime.test
  tests/fullstack-test/expr/str_to_date.test
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5739 PageStorage: Log down the gc time for external pages
  dbms/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5742 *: fix asan false positive case
  libs/libcommon/include/common/avx2_strstr.h
  libs/libcommon/include/common/mem_utils_opt.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#5731 PageStorage: avoid reallocate wal write buffer size
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
Labels: status/can-merge, type/bug-fix, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#5610 Improve memtrack
  dbms/src/Common/BackgroundTask.cpp
  dbms/src/Common/BackgroundTask.h
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Common/tests/gtest_memtracker.cpp
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/MPPReceiverSet.cpp
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/tests/bench_exchange.h
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none
