Repository pingcap/tiflash, pull requests merged in 2023-10, with the labels that each got.

#8063 use logical cores as max_threads
  dbms/src/Interpreters/SettingsCommon.h
Labels: size/XS, release-note-none, approved, lgtm

#8158 Adjust the soft limit of mintso scheduler to 2 * logical cores
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8164 Fix possible stuck due to cop response writing occur error
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_context.cpp
Labels: release-note-none, size/M, approved, lgtm

#8166 Fix possible stuck due to cop response writing occur error
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_context.cpp
  dbms/src/Flash/Mpp/MPPTaskId.h
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#8161 refine resource group metric name
  dbms/src/Flash/Mpp/MPPTaskId.h
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/S, approved, lgtm

#8172 fix In/NotIn columnRef in RoughSetFilter (cherry-pick-8171)
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  tests/fullstack-test/expr/in_expression.test
Labels: release-note-none, size/S, cherry-pick-approved, approved, lgtm

#8174 Reset current_memory_tracker when WNEstablishDisaggTaskHandler finished.
  dbms/src/Flash/FlashService.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8179 Disable cop stream for remote read by default
  dbms/src/Interpreters/Settings.h
Labels: size/XS, release-note-none, approved, lgtm

#8183 Add some debug info when meet duplicate key in parallel prehandling
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/Region.cpp
Labels: release-note-none, size/L, approved, lgtm

#8168 add some failpoints for remote read
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/Limiter.h
  dbms/src/Common/tests/gtest_limiter.cpp
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  tests/fullstack-test/mpp/remote_cop_fail.test
Labels: size/XL, release-note-none, approved, lgtm

#8176 refine LAC in disaggregated mode
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/ResourceControl/TokenBucket.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  dbms/src/TiDB/Etcd/Client.h
Labels: release-note-none, size/L, approved, lgtm

#8191 Add asan/tsan docker build script
  release-centos7-llvm/Makefile
  release-centos7-llvm/scripts/build-asan.sh
  release-centos7-llvm/scripts/build-tiflash-release.sh
  release-centos7-llvm/scripts/build-tsan.sh
Labels: release-note-none, size/M, approved, lgtm

#8188 *: Refine error message when deadline exceeded
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/tests/mpmc_queue_perftest.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/tests/bench_exchange.cpp
  dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  libs/libcommon/src/tests/gtest_crc64.cpp
  libs/libcommon/src/tests/gtest_mem_utils.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8193 Fix potential hang when duplicated task registered.
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#8200 fix the unexpected error `Block schema mismatch in FineGrainedShuffleWriter-V1`
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  tests/fullstack-test/issues/issue_8111.test
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8205 tests: Fix unstable integration tests
  tests/docker/run.sh
  tests/docker/util.sh
  tests/fullstack-test2/ddl/alter_partition_by.test
Labels: release-note-none, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8198 KVStore: Refine learner read process
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/RegionInfo.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/Storages/KVStore/Decode/DecodedTiKVKeyValue.h
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
  dbms/src/Storages/KVStore/Read/LearnerRead.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_learner_read.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/kvstore_helper.h
  dbms/src/Storages/RegionQueryInfo.h
  dbms/src/Storages/RegionQueryInfo_fwd.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: size/XXL, release-note-none, approved, lgtm

#8214 Add some logs about concurrency
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.h
  dbms/src/Flash/Statistics/ExecutorStatistics.h
  dbms/src/Flash/Statistics/JoinImpl.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
Labels: release-note-none, size/M, approved, lgtm

#8209 Fix check fail when cancel parallel prehandling
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8184 Rate limiter for parallel prehandling
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Debug/MockSSTReader.cpp
  dbms/src/Debug/MockSSTReader.h
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#8212 Remove useless RSOperator & refactor function parseTiCompareExpr
  dbms/src/Storages/DeltaMerge/Filter/NotIn.h
  dbms/src/Storages/DeltaMerge/Filter/NotLike.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8221 disagg: Fix error when there are empty partitions
  dbms/src/Common/MPMCQueue.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
Labels: release-note, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8210 Fix the compatibility issue in func `FunctionIPv4NumToString`
  dbms/src/Functions/FunctionsCoding.h
  dbms/src/Functions/tests/gtest_inet_aton_ntoa.cpp
Labels: size/L, release-note, approved, lgtm

#8223 Refine filter parser
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
Labels: release-note-none, size/L, approved, lgtm

#8225 Enhance some debug utils
  dbms/CMakeLists.txt
  dbms/src/Debug/MockKVStore/MockFFIImpls.cpp
  dbms/src/Debug/MockKVStore/MockFFIImpls.h
  dbms/src/Debug/MockKVStore/MockProxyRegion.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
  dbms/src/Debug/MockKVStore/MockReadIndex.cpp
  dbms/src/Debug/MockKVStore/MockSSTGenerator.cpp
  dbms/src/Debug/MockKVStore/MockSSTGenerator.h
  dbms/src/Debug/MockKVStore/MockSSTReader.cpp
  dbms/src/Debug/MockKVStore/MockSSTReader.h
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
  dbms/src/Storages/KVStore/MultiRaft/RegionsRangeIndex.h
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
  dbms/src/Storages/KVStore/Read/RegionException.h
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_proactive_flush.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  dbms/src/Storages/KVStore/tests/gtest_read_index_worker.cpp
  dbms/src/Storages/KVStore/tests/kvstore_helper.h
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: size/XXL, release-note-none, approved, lgtm

#8216 Refine SegmentReadTask for disaggregated-mode and op-mode.
  dbms/src/Storages/DeltaMerge/Remote/RNDataProvider.h
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8232 Fix RSOperator parse nested ColumnRef in In expression
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  tests/fullstack-test/expr/in_expression.test
Labels: release-note-none, size/S, approved, lgtm

#8236 *: Fix build on mac
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
Labels: size/XS, release-note-none, approved, lgtm

#8229 ddl: Fix corner case when multiple region creates one table simultaneously
  dbms/src/Databases/DatabaseMemory.cpp
  dbms/src/Databases/DatabaseMemory.h
  dbms/src/Databases/DatabaseOrdinary.cpp
  dbms/src/Databases/DatabaseOrdinary.h
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabaseTiFlash.h
  dbms/src/Databases/IDatabase.h
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  tests/fullstack-test2/ddl/alter_create_table_from_multi_regions.test
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8234 *: Refine pageworkload output
  dbms/src/Storages/Page/workload/HeavyMemoryCostInGC.h
  dbms/src/Storages/Page/workload/HighValidBigFileGC.h
  dbms/src/Storages/Page/workload/MainEntry.cpp
  dbms/src/Storages/Page/workload/Normal.h
  dbms/src/Storages/Page/workload/PSBackground.cpp
  dbms/src/Storages/Page/workload/PSBackground.h
  dbms/src/Storages/Page/workload/PSRunnable.cpp
  dbms/src/Storages/Page/workload/PSRunnable.h
  dbms/src/Storages/Page/workload/PSStressEnv.cpp
  dbms/src/Storages/Page/workload/PSStressEnv.h
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Page/workload/PSWorkload.h
  dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
  dbms/src/Storages/Page/workload/ThousandsOfOffset.h
Labels: size/XL, release-note-none, approved, lgtm

#8242 Remove legacy collator related code
  CMakeLists.txt
  cmake/find_icu4c.cmake
  dbms/CMakeLists.txt
  dbms/src/Columns/Collator.cpp
  dbms/src/Columns/Collator.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/IColumn.h
  dbms/src/Common/config.h.in
  dbms/src/Common/config_build.cpp.in
  dbms/src/Core/SortDescription.cpp
  dbms/src/Core/SortDescription.h
  dbms/src/Functions/CMakeLists.txt
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Parsers/ASTOrderByElement.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TiDB/Collation/Collator.cpp
  dbms/src/TiDB/Collation/Collator.h
Labels: size/XL, release-note-none, approved, lgtm

#8235 fix potential data race when report resource group metric
  dbms/src/Common/TiFlashMetrics.h
Labels: release-note-none, size/S, approved, lgtm, needs-cherry-pick-release-7.5

#8244 keep toCase function the same as golang implementation
  dbms/src/Functions/CharUtil.h
  tests/fullstack-test/expr/issue_7695.test
Labels: release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8245 Fix integration test of parallel prehandling
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: release-note-none, size/L, approved, lgtm

#8258 Add some logs about join build
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/S, approved, lgtm

#8248 ddl: Fix frequent schema GC under multi tenant
  dbms/src/Databases/IDatabase.h
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/Read/ReadIndexWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorker.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/XL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8259 Fix a potential null pointer issue
  dbms/src/Storages/KVStore/Read/LearnerRead.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
  dbms/src/Storages/KVStore/tests/gtest_learner_read.cpp
Labels: release-note-none, size/M, approved, lgtm

#8237 Storages: Refine SegmentReadTaskPool and SegmentReadTaskScheduler
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8273 runtime filter: fix timezone error in runtime filter
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  tests/fullstack-test/mpp/runtime_filter.test
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8271 fix lock contension of consumeResource in storage layer
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Executor/toRU.cpp
  dbms/src/Flash/Executor/toRU.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8279 Remove disaggregated mode without s3
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Statistics/TableScanImpl.cpp
  dbms/src/Flash/tests/gtest_storage_disaggregated.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
Labels: size/XXL, release-note-none, approved, lgtm
