Repository pingcap/tiflash, pull requests merged in 2023-08, with the labels that each got.

#7854 fix issue #7810
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.h
Labels: release-note-none, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7875 refine the use of `pause_when_reading_from_dt_stream`
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
Labels: release-note-none, size/M, approved, lgtm

#7820 Support `In`/`NotIn` in RSOperator
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Filter/And.h
  dbms/src/Storages/DeltaMerge/Filter/Equal.h
  dbms/src/Storages/DeltaMerge/Filter/FilterHelper.h
  dbms/src/Storages/DeltaMerge/Filter/Greater.h
  dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/Less.h
  dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Like.h
  dbms/src/Storages/DeltaMerge/Filter/Not.h
  dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
  dbms/src/Storages/DeltaMerge/Filter/NotIn.h
  dbms/src/Storages/DeltaMerge/Filter/NotLike.h
  dbms/src/Storages/DeltaMerge/Filter/Or.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/Index/RSResult.h
  dbms/src/Storages/DeltaMerge/Index/RoughCheck.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  libs/libcommon/include/common/likely.h
Labels: size/XXL, release-note, approved, lgtm

#7888 fix daily fail for releaes-7.3 branch
  dbms/src/Debug/dbgFuncSchemaName.cpp
  dbms/src/Debug/dbgTools.cpp
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#7882 fix daily fail
  dbms/src/Debug/dbgFuncSchemaName.cpp
  dbms/src/Debug/dbgTools.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7893 Fix exception `Illegal type MyDuration(0) of first argument of function` when remote read occur
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Coprocessor/StorageDisaggregatedInterpreter.h
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.h
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
Labels: size/XL, release-note-none, approved, lgtm

#7897 Add RFC for 'Reduce the number of files used by TiFlash'
  docs/design/2023-08-04-reduce-the-number-of-files-used-by-TiFlash
Labels: release-note-none, size/S, approved, lgtm

#7898 Upgrade DMFile::V3 as the default version
  dbms/src/Storages/FormatVersion.h
Labels: size/XS, release-note, approved, lgtm

#7680 Add some security notation for tcp_port in sample config file
  etc/config-template.toml
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#7903 refine TaskQueue::take semantics to drain all tasks when finished
  dbms/CMakeLists.txt
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/bench_task_queue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_io_priority.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_mlfq.cpp
Labels: release-note-none, size/L, approved, lgtm

#7894 Refine pagestorage cache wait time.
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
Labels: release-note-none, size/S, approved, lgtm

#7907 Fix bug in join spill
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/M, approved, needs-1-more-lgtm, lgtm

#7901 fix row key not in standard format
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
Labels: release-note, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7863 Some code refactor on the Raft layer
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/dbgNaturalDag.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Debug/dbgTools.h
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: size/XL, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#7906 Update the log in SchemaBuilder
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaNameMapper.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
Labels: release-note-none, size/M, approved, lgtm

#7920 ensure every record in wal is only applied once when restart
  dbms/src/Storages/Page/V3/LogFile/LogFilename.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_gc.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: size/L, release-note, approved, lgtm

#7923 Revert gc speed related optimization
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_gc.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, cherry-pick-approved, approved, lgtm

#7926 Enable unit test `JoinExecutorTestRunner.ScanHashMapAfterProbeData` for pipeline model
  dbms/src/Flash/tests/gtest_join_executor.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7895 *: add ColumnLimit for clang-format
  .clang-format
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/BatchCoprocessorHandler.h
  dbms/src/Flash/CaresPTRResolver.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/CoprocessorHandler.h
  dbms/src/Flash/DiagnosticsService.cpp
  dbms/src/Flash/DiagnosticsService.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/LogSearch.cpp
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/GRPCCompletionQueuePool.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPReceiverSet.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskId.cpp
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
  dbms/src/Flash/Mpp/ReceivedMessage.cpp
  dbms/src/Flash/Mpp/ReceivedMessage.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/Utils.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
  dbms/src/Flash/ServiceUtils.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
Labels: size/XXL, release-note-none, approved, lgtm

#7929 Turn off clang-format for settings
  dbms/src/Interpreters/Settings.h
Labels: size/XXL, release-note-none, approved, lgtm

#7900 support Sort operator auto spill when query memory usage exceed threshold
  dbms/src/Core/AutoSpillTrigger.h
  dbms/src/Core/OperatorSpillContext.h
  dbms/src/Core/QueryOperatorSpillContexts.h
  dbms/src/Core/TaskOperatorSpillContexts.h
  dbms/src/DataStreams/IProfilingBlockInputStream.cpp
  dbms/src/DataStreams/IProfilingBlockInputStream.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/AggSpillContext.cpp
  dbms/src/Interpreters/AggSpillContext.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/HashJoinSpillContext.cpp
  dbms/src/Interpreters/HashJoinSpillContext.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SortSpillContext.cpp
  dbms/src/Interpreters/SortSpillContext.h
  dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
  dbms/src/Interpreters/tests/gtest_query_operator_spill_contexts.cpp
  dbms/src/Interpreters/tests/gtest_task_operator_spill_contexts.cpp
  dbms/src/Operators/MergeSortTransformOp.cpp
  dbms/src/Operators/MergeSortTransformOp.h
  dbms/src/Operators/Operator.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7934 remove redundant error message
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: size/XS, release-note-none, approved, lgtm

#7938 Fix race condition in PreHandlingTrace
  dbms/src/Storages/Transaction/KVStore.h
Labels: release-note-none, size/M, approved, lgtm

#7940 Remove excess backslashes
  release-centos7-llvm/dockerfiles/misc/prepare_basic.sh
Labels: size/XS, release-note-none, skip-issue-check, approved, lgtm

#7947 Revert "Use `num_streams` as parallelism when read thread is enabled.…
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: release-note-none, size/M, cherry-pick-approved, type/cherry-pick-for-release-6.5, approved, lgtm

#7939 Make window function return null when frame is valid
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/DataTypes/DataTypeNullable.h
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/WindowFunctions/IWindowFunction.cpp
  dbms/src/WindowFunctions/IWindowFunction.h
  dbms/src/WindowFunctions/WindowUtils.h
  dbms/src/WindowFunctions/tests/gtest_first_value.cpp
  dbms/src/WindowFunctions/tests/gtest_last_value.cpp
Labels: size/XXL, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#7954 Format code under dbms/src/Server
  dbms/src/Server/BgStorageInit.cpp
  dbms/src/Server/BgStorageInit.h
  dbms/src/Server/Bootstrap.cpp
  dbms/src/Server/Bootstrap.h
  dbms/src/Server/CLIService.h
  dbms/src/Server/Client.cpp
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/InterruptListener.h
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/MetricsTransmitter.cpp
  dbms/src/Server/MetricsTransmitter.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/Server.h
  dbms/src/Server/ServerInfo.cpp
  dbms/src/Server/StatusFile.cpp
  dbms/src/Server/StatusFile.h
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Server/TCPHandler.h
  dbms/src/Server/TCPHandlerFactory.h
  dbms/src/Server/clickhouse-client.cpp
  dbms/src/Server/clickhouse-server.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Server/tests/gtest_grpc_alarm.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Server/tests/gtest_storage_config.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7953 fix ResourceControlQueue::updateStatistics declaration
  dbms/src/Common/ThreadedWorker.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h
Labels: release-note-none, size/S, skip-issue-check, approved, lgtm

#7963 Fix memory leak in `ReceivedMessageQueue`
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
Labels: release-note-none, size/S, approved, lgtm

#7964 Add tidb executor id in Join's log
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: release-note-none, size/L, approved, lgtm

#7977 Update licenserc.yml (release-7.1)
  .github/licenserc.yml
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#7966 fix data race on `MockLocalAdmissionController`
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.h
Labels: release-note-none, size/M, approved, lgtm

#7997 Fix license (release-7.2)
  .devcontainer/Makefile
Labels: size/XS, release-note-none, cherry-pick-approved, skip-issue-check, approved, lgtm

#7999 Fix license (release-7.0)
  .devcontainer/Makefile
Labels: size/XS, release-note-none, cherry-pick-approved, skip-issue-check, approved, lgtm

#7996 Fix license (release-7.3)
  .devcontainer/Makefile
Labels: size/XS, release-note-none, cherry-pick-approved, skip-issue-check, approved, lgtm

#7998 Fix license (release-7.1)
  .devcontainer/Makefile
Labels: size/XS, release-note-none, cherry-pick-approved, skip-issue-check, approved, lgtm

#7995 Fix license
  .devcontainer/Makefile
Labels: size/XS, release-note-none, skip-issue-check, approved, lgtm

#7629 Support range frame type
  dbms/src/Core/Field.h
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/DataTypes/getMostSubtype.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Functions/FunctionBinaryArithmetic.h
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Interpreters/WindowDescription.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/TestUtils/WindowTestUtils.h
  dbms/src/WindowFunctions/tests/gtest_first_value.cpp
  dbms/src/WindowFunctions/tests/gtest_last_value.cpp
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
  tests/fullstack-test/mpp/window_range_frame.test
Labels: size/XXL, release-note-none, approved, lgtm

#7969 Not call abortMPPGather when mpp task met error
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7945 Skip first state change of EXCHANGE Partition.
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/_env.sh
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: release-note-none, size/S, approved, lgtm

#8006 fix the potential problem that some ref id may be lost after restart
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: release-note-none, size/M, approved, lgtm

#7937 Fix crash when meet unknown column type from TiDB
  dbms/CMakeLists.txt
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Debug/dbgTools.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/TypeMapping.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_table_info.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7959 Implement utf8mb4_0900_ai_ci collation
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Functions/FunctionsStringSearch.h
  dbms/src/Functions/tests/bench_collation.cpp
  dbms/src/Functions/tests/gtest_strings_search.cpp
  dbms/src/Storages/Transaction/CollationLUT.cpp
  dbms/src/Storages/Transaction/Collator.cpp
  dbms/src/Storages/Transaction/Collator.h
  dbms/src/Storages/Transaction/tests/gtest_tidb_collator.cpp
Labels: size/XXL, release-note, approved, lgtm

#8021 Export tikv status port in CI
  .gitignore
  tests/docker/cluster.yaml
  tests/docker/cluster_disable_new_collation.yaml
  tests/docker/cluster_new_collation.yaml
  tests/docker/cluster_tidb_fail_point.yaml
  tests/docker/run.sh
Labels: release-note-none, size/S, approved, lgtm

#8013 fix data race on `Join::getTotalRowCount()`
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: size/XS, release-note-none, approved, lgtm

#8017 PageStorage: Fix exception caused by empty page
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8020 Fix potential receiver blocked in deconstruction
  dbms/src/Flash/Mpp/MPPReceiverSet.h
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7948 Limit memory usage of RNDeltaIndexCache
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7942 Support Join auto spill
  dbms/src/Core/OperatorSpillContext.cpp
  dbms/src/Core/OperatorSpillContext.h
  dbms/src/Core/QueryOperatorSpillContexts.cpp
  dbms/src/Core/QueryOperatorSpillContexts.h
  dbms/src/Core/TaskOperatorSpillContexts.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/AggSpillContext.cpp
  dbms/src/Interpreters/AggSpillContext.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/HashJoinSpillContext.cpp
  dbms/src/Interpreters/HashJoinSpillContext.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SortSpillContext.cpp
  dbms/src/Interpreters/SortSpillContext.h
  dbms/src/Interpreters/tests/gtest_task_operator_spill_contexts.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8035 Fix MinTSOScheduler incorrectly erased waiting_set issue
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: release-note-none, size/M, approved, lgtm

#8033 Auto spill enhance
  dbms/src/Common/Arena.h
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/Exception.h
  dbms/src/Common/HashTable/FixedHashTable.h
  dbms/src/Common/HashTable/HashTable.h
  dbms/src/Common/HashTable/SmallTable.h
  dbms/src/Common/HashTable/StringHashTable.h
  dbms/src/Core/AutoSpillTrigger.h
  dbms/src/Core/QueryOperatorSpillContexts.cpp
  dbms/src/Core/QueryOperatorSpillContexts.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/HashJoinSpillContext.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/tests/gtest_query_operator_spill_contexts.cpp
Labels: release-note-none, size/L, approved, lgtm

#8040 spill agg blocks using BlockInputStream
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/AggHashTableToBlocksBlockInputStream.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: release-note-none, size/L, approved, lgtm

#8037 support auto spill set by tidb
  dbms/src/Core/AutoSpillTrigger.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
Labels: release-note-none, size/M, approved, lgtm

#8043 Fix exception when apply snapshot is canceled
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/Transaction/tests/gtest_tikv_keyvalue.cpp
  dbms/src/Storages/Transaction/tests/region_helper.h
Labels: release-note-none, size/M, approved, lgtm

#8038 Agg auto spill refine
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Interpreters/AggSpillContext.cpp
  dbms/src/Interpreters/AggSpillContext.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
  dbms/src/Operators/LocalAggregateTransform.cpp
Labels: release-note-none, size/M, approved, lgtm

#8012 Add MemoryTracker and limit concurrency of EstablishDisaggTask
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/IO/IOThreadPools.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
Labels: release-note-none, size/M, approved, lgtm
