Repository pingcap/tiflash, pull requests merged in 2023-06, with the labels that each got.

#7579 Print corresponding region and index when meet PK error
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/dbgFuncMockTiDBTable.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionData.cpp
  dbms/src/Storages/Transaction/RegionData.h
  dbms/src/Storages/Transaction/RegionManager.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7567 fix false positive error in spiller
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Operators/MergeSortTransformOp.cpp
  dbms/src/Operators/MergeSortTransformOp.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7489 Print MPPTask info when it's alive for a long time
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7514 Support offset frame type
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Debug/MockExecutor/WindowBinder.h
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/WindowFunctions/tests/gtest_first_value.cpp
  dbms/src/WindowFunctions/tests/gtest_last_value.cpp
  tests/fullstack-test/mpp/window.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7554 Refine ExchangeReceiver's receiver queue for fine grained shuffle
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceivedMessage.cpp
  dbms/src/Flash/Mpp/ReceivedMessage.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/ReceiverChannelBase.cpp
  dbms/src/Flash/Mpp/ReceiverChannelBase.h
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/Mpp/tests/gtest_received_message_queue.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7571 Report add tiflash replica RU.
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: release-note-none, size/L, approved, lgtm

#7561 Pipeline: more performance optimization for `WaitReactor`
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.h
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Operators/AggregateRestoreSourceOp.h
  dbms/src/Operators/CoprocessorReaderSourceOp.h
  dbms/src/Operators/ExchangeReceiverSourceOp.h
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/HashJoinProbeTransformOp.h
  dbms/src/Operators/SharedQueue.h
  dbms/src/Operators/SourceOp_fwd.h
  dbms/src/Operators/UnorderedSourceOp.h
Labels: status/LGT1, size/XL, release-note-none, approved, lgtm

#7596 Add metrics of RU to grafana.
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7589 Fix "lost cancel" for mpp query
  dbms/src/Flash/Mpp/MPPTaskId.cpp
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: size/XL, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7584 Pipeline: add grafana panel
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.h
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#7606 Add some logging for locating bug
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-7.1, approved, lgtm

#7609 fix build fail in mac introduce by https://github.com/pingcap/tiflash/pull/7584
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
Labels: size/XS, release-note-none, approved, lgtm

#7597 Initialize the pipeline task scheduler by default
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/S, approved, lgtm

#7613 Fix unstable tests and add more ut
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Debug/dbgQueryExecutor.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/tests/gtest_aborted_mpp_gather_cache.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/MockComputeClient.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: size/XL, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7614 *: call PODArray::resize_fill(size_t n) instead of resize_fill(size_t n, 0)
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/DataTypes/DataTypeNumberBase.cpp
  dbms/src/Functions/FunctionsGrouping.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
Labels: release-note-none, size/M, approved, lgtm

#7627 Tsan: fix data race on `ComputeServerRunner`
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
  dbms/src/DataStreams/IProfilingBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/QueryExecutor.cpp
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  tests/fullstack-test/mpp/mpp_fail.test
  tests/sanitize/tsan.suppression
Labels: release-note-none, size/L, approved, lgtm

#7622 Use memory bounded buffer in executors
  dbms/src/Common/CapacityLimits.h
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_loose_bounded_mpmc_queue.cpp
  dbms/src/Common/tests/gtest_mpmc_queue.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/SharedQueryBlockInputStream.h
  dbms/src/DataStreams/UnionBlockInputStream.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/tests/gtest_grpc_send_queue.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindow.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectWithUnionQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SharedQueries.h
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Operators/tests/gtest_shared_queue.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: size/XL, release-note-none, approved, lgtm

#7616 avoid unnecessary fsync in ps
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/LogFile/LogReader.h
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#7633 Make integration test time balanced
  tests/docker/config/tiflash_dt_sync_grpc.toml
  tests/docker/tiflash-dt-sync-grpc.yaml
  tests/fullstack-test/mpp/window.test
  tests/fullstack-test/run.sh
  tests/fullstack-test/tiflash-dt-sync-grpc.yaml
  tests/fullstack-test2/run.sh
  tests/fullstack-test2/tiflash-dt-disable-local-tunnel.yaml
  tests/fullstack-test2/tiflash-dt-disable-planner.yaml
  tests/fullstack-test2/variables/set_variable_fastscan.test
  tests/tidb-ci/async_grpc
  tests/tidb-ci/disable_local_tunnel
  tests/tidb-ci/disable_planner
  tests/tidb-ci/run.sh
  tests/tidb-ci/tiflash-dt-async-grpc.yaml
Labels: release-note-none, size/L, approved, lgtm

#7612 Add design doc for pipeline model
  docs/design/2023-06-07-tiflash-pipeline-model.md
  docs/design/images/2023-06-07-pipeline-dag.png
  docs/design/images/2023-06-07-tiflash-pipeline-model.png
Labels: release-note-none, size/L, approved, lgtm

#7639 Enable LZ4_FAST_DEC_LOOP for Arm to optimize decompression loop
  contrib/lz4-cmake/CMakeLists.txt
Labels: size/XS, release-note, approved, lgtm

#7615 Remove local DMFiles and Checkpoints on failure
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/MockS3Client.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
Labels: size/XL, release-note-none, approved, lgtm

#7655 add more log when learner read meet error
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/Transaction/TiKVKeyValue.cpp
  dbms/src/Storages/Transaction/TiKVKeyValue.h
Labels: release-note-none, size/M, approved, lgtm

#7663 Fix unstable unittest `ThreadedWorker.ErrorInWorkerWithNonEmptyQueue`
  dbms/src/Common/tests/gtest_threaded_worker.cpp
Labels: release-note-none, size/S, approved, lgtm

#7581 Add log when handling a snapshot with invalid data
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/Transaction/SSTReader.cpp
  dbms/src/Storages/Transaction/SSTReader.h
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
Labels: status/LGT2, release-note-none, size/M, approved, lgtm

#7644 Introduce mpp query level processListEntry
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.h
Labels: release-note-none, size/L, approved, lgtm

#7642 Not create segment for empty table.
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: size/XL, release-note-none, approved, lgtm

#7665 Change escape character from '$' to '\' for `regexp_replace`
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Functions/tests/gtest_regexp_replace.cpp
  tests/fullstack-test/expr/regexp.test
Labels: release-note-none, size/L, approved, lgtm

#7666 create partition table when tiflash restart
  dbms/src/Interpreters/Settings.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
Labels: release-note-none, size/S, approved, lgtm

#7669 v6.1 Bugfix of async grpc
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#7673 Cut down the wait time for sync schema in restart(release-6.5)
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#7679 Support TiFlash Metrics with keyspace info and adjust schema metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  metrics/alertmanager/tiflash.rules.yml
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7688 Revert "Introduce mpp query level processListEntry (#7644)"
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.h
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#7696 Remove keyspace info in metrics and some useless metrics info in schema
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7684 Support different gc_safepoint for different keyspace
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.h
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/TiDB.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
Labels: release-note-none, size/L, approved, lgtm

#7694 Fix bug introduced by #7644
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  tests/fullstack-test/mpp/apply.test
  tests/fullstack-test/mpp/async_server_alarm.test
  tests/fullstack-test/mpp/mpp_fail.test
Labels: size/XL, release-note-none, approved, lgtm

#7712 cherry-pick #7693
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: release-note-none, size/S, approved, lgtm

#7706 Reduce UniPS snapshot stat overhead
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
Labels: release-note-none, size/L, approved, lgtm

#7369 Use try lock first for `insertBlockIntoMapsTypeCase`
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
Labels: release-note-none, size/L, approved, lgtm

#7686 Do parallel among sync all schemas to speed up tiflash restart
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: release-note, size/M, approved, lgtm

#7699 Optimize DDLGuard to remove useless two-level mapping
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/InterpreterDropQuery.cpp
  dbms/src/Interpreters/InterpreterRenameQuery.cpp
Labels: release-note-none, size/M, approved, lgtm

#7718 function: fix grouping function result name
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
Labels: size/XS, release-note, approved, lgtm

#7667 Tracking memory usage of `PagePacket` and `RemotePage` in RN fetching pages
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7668 improve ps gc speed by dumping snapshot from memory directly
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_gc.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm
