Repository pingcap/tiflash, pull requests merged in 2023-09, with the labels that each got.

#8047 Remove useless codes
  dbms/src/Client/Connection.h
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/Management/ManualCompact.h
  dbms/src/Functions/IFunction.cpp
  dbms/src/Interpreters/Settings_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/Page/CMakeLists.txt
  dbms/src/Storages/Page/V1/Page.h
  dbms/src/Storages/Page/V1/PageEntries.h
  dbms/src/Storages/Page/V1/PageFile.cpp
  dbms/src/Storages/Page/V1/PageFile.h
  dbms/src/Storages/Page/V1/PageStorage.cpp
  dbms/src/Storages/Page/V1/PageStorage.h
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesBuilder.cpp
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesBuilder.h
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesEdit.h
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesVersionSet.cpp
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesVersionSet.h
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesVersionSetWithDelta.h
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesView.cpp
  dbms/src/Storages/Page/V1/VersionSet/PageEntriesView.h
  dbms/src/Storages/Page/V1/WriteBatch.h
  dbms/src/Storages/Page/V1/mvcc/VersionSet.h
  dbms/src/Storages/Page/V1/mvcc/VersionSetWithDelta.h
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/System/StorageSystemBuildOptions.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/CHTableHandle.h
  dbms/src/Storages/Transaction/HashCheckHelper.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/TiKVHandle.h
  dbms/src/Storages/Transaction/tests/gtest_tikv_keyvalue.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8048 Add keyspace_id to RNDeltaIndexCache.
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
Labels: release-note-none, size/S, approved, lgtm

#8045 Refine auto spill for fine grained executor
  dbms/src/Core/FineGrainedOperatorSpillContext.cpp
  dbms/src/Core/FineGrainedOperatorSpillContext.h
  dbms/src/Core/OperatorSpillContext.cpp
  dbms/src/Core/OperatorSpillContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindowSort.cpp
  dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
  dbms/src/Operators/LocalAggregateTransform.cpp
  dbms/src/Operators/LocalAggregateTransform.h
  dbms/src/Operators/MergeSortTransformOp.h
Labels: size/XL, release-note-none, approved, lgtm

#8055 Fix crash for cancel apply snapshot
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/PathPool.cpp
Labels: release-note-none, size/M, approved, lgtm

#8041 Remove delta index from cache if a related exception raised
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/Remote/RNReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#8044 Add doc for reducing wait index at random write
  docs/design/2023-08-31-reduce-wait-index-in-random-write.md
Labels: release-note-none, size/M, approved, lgtm

#8056 Refine API in IAggregateFunction/Aggregator to support aggregate on part of the input `block` formally
  dbms/src/AggregateFunctions/AggregateFunctionCount.h
  dbms/src/AggregateFunctions/AggregateFunctionIf.h
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
  dbms/src/AggregateFunctions/AggregateFunctionSum.h
  dbms/src/AggregateFunctions/IAggregateFunction.h
  dbms/src/Columns/ColumnsCommon.cpp
  dbms/src/Columns/ColumnsCommon.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
Labels: size/XL, release-note-none, approved, lgtm

#8058 Update the weight function for Mark Cache and Min Max Index Cache
  dbms/src/Common/LRUCache.h
  dbms/src/Common/tests/gtest_lru_cache.cpp
  dbms/src/IO/UncompressedCache.h
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
  dbms/src/Storages/MarkCache.h
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#7858 Disagg: Eager remove applied RaftLog to fix OOM when down-peers exist
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/Stopwatch.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/BackgroundService.h
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RaftLogManager.cpp
  dbms/src/Storages/Transaction/RaftLogManager.h
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionMeta.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_proactive_flush.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8049 Add some metrics about KVStore
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/Region.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8070 Disagg: Fix hang when canceling non-owner
  dbms/src/Storages/Transaction/RaftLogManager.cpp
  dbms/src/Storages/Transaction/RaftLogManager.h
  dbms/src/Storages/Transaction/tests/gtest_raft_log_manager.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  dbms/src/TiDB/Etcd/Client.h
  dbms/src/TiDB/OwnerManager.cpp
  dbms/src/TiDB/OwnerManager.h
  dbms/src/TiDB/tests/gtest_owner_manager.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#7822 Added support for new DDL actions for remove and add table partitioning
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  tests/fullstack-test2/ddl/alter_partition_by.test
  tests/fullstack-test2/ddl/remove_partitioning.test
  tests/run-test.sh
Labels: size/XL, release-note-none, approved, lgtm

#8064 Fully support aggregate on part of a input block
  dbms/src/Common/FailPoint.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Operators/AggregateBuildSinkOp.cpp
  dbms/src/Operators/AggregateBuildSinkOp.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/LocalAggregateTransform.cpp
Labels: release-note-none, size/L, approved, lgtm

#8075 Disagg: show the num of tables on Grafana
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/M, approved, lgtm

#8080 Fix error message.
  dbms/src/Server/Server.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8071 add metrics for resource group
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#8079 rename `tidb_enable_tiflash_pipeline_model` to `tiflash_enable_pipeline_model`
  dbms/src/Flash/FlashService.cpp
  tests/fullstack-test/issues/issue_2471.test
Labels: size/XS, release-note-none, approved, lgtm

#8091 Disagg: Fix exception when query table with generated column(s)
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
Labels: release-note-none, size/M, approved, lgtm

#8078 support agg resize callback
  dbms/src/Common/HashTable/TwoLevelHashTable.h
  dbms/src/Common/HashTable/TwoLevelStringHashTable.h
  dbms/src/Core/CachedSpillHandler.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/JoinPartition.cpp
Labels: release-note-none, size/L, approved, lgtm

#8101 Fix MPPTask hang introduced by #8064
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  tests/fullstack-test2/ddl/alter_partition_by.test
Labels: release-note-none, size/M, approved, lgtm

#8102 *: Fix max snapshot lifetime is now shown on Grafana
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#8095 Add metrics to monitor size of ongoing raft snapshots
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/KVStore/Decode/RegionDataRead.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8105 Sort raft snapshot related utils into different modules
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/Region.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8110 Extract common parts of ApplySnapshot
  dbms/src/Storages/DeltaMerge/BoundedSSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.h
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.h
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8096 Add auto spill ut
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/tests/gtest_auto_spill_aggregation.cpp
  dbms/src/Flash/tests/gtest_auto_spill_join.cpp
  dbms/src/Flash/tests/gtest_auto_spill_sort.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Flash/tests/gtest_spill_join.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Interpreters/AggSpillContext.cpp
  dbms/src/Interpreters/AggSpillContext.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/HashJoinSpillContext.cpp
  dbms/src/Interpreters/HashJoinSpillContext.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/SortSpillContext.cpp
  dbms/src/Interpreters/SortSpillContext.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
Labels: size/XXL, release-note-none, approved, lgtm

#8112 Make delta_index_epoch monotonic increase.
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test

#8072 add min tso scheduler for each resource group
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
  dbms/src/Flash/ResourceControl/TokenBucket.cpp
  dbms/src/Flash/ResourceControl/TokenBucket.h
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#8116 Delete tidb sys variable `tiflash_enable_pipeline`
  dbms/src/Flash/FlashService.cpp
  dbms/src/Interpreters/Settings.h
  tests/docker/config/tics_dt.toml
  tests/fullstack-test/issues/issue_2471.test
Labels: release-note-none, size/S, approved, lgtm, needs-ok-to-test

#8114 Fix func log error
  dbms/src/Functions/FunctionsMath.h
  dbms/src/Functions/tests/gtest_functions_log.cpp
  tests/fullstack-test/expr/issue_3373.test
  tests/fullstack-test/expr/issue_8113.test
Labels: release-note-none, size/L, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#8115 Spill in pipeline model not driven by input block
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/AggregateBuildSinkOp.cpp
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/HashJoinBuildSink.cpp
  dbms/src/Operators/HashJoinBuildSink.h
  dbms/src/Operators/LocalAggregateTransform.cpp
  dbms/src/Operators/MergeSortTransformOp.cpp
Labels: release-note-none, size/M, approved, lgtm

#8097 integrate read_ru into tiflash resource control
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/tests/gtest_to_ru.cpp
  dbms/src/Flash/Executor/toRU.cpp
  dbms/src/Flash/Executor/toRU.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.cpp
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  tests/docker/config/tics_dt.toml
Labels: release-note-none, size/L, approved, lgtm

#8127 Fix empty rethrow in apply snapshot
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/FFI/ProxyFFI.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
Labels: release-note-none, size/M, approved, lgtm

#8118 Clear column cache as soon as possible.
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/File/ColumnCache.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/M, approved, lgtm, needs-ok-to-test

#8125 tiflash resource control design doc
  docs/design/2023-09-21-tiflash-resource-control.md
Labels: release-note-none, size/M, approved, lgtm

#8130 Window function should handle default range frame in different way
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  tests/fullstack-test/mpp/window_range_frame.test
Labels: size/XL, release-note-none, approved, lgtm

#8132 add design doc for query level spill
  docs/design/2023-09-22-tiflash-query-level-auto-spill.md
Labels: release-note-none, size/M, approved, lgtm

#8131 No tracing memory usage of shared column data in MPPTask's memory tracker
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Common/PODArray.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-ok-to-test

#8137 Only add shared column data size to root_of_query_mem_trackers.
  dbms/src/Common/MemoryTracker.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8134 fix network error handling of LocalAdmissionController
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
Labels: release-note-none, size/L, approved, lgtm

#8142 fix RCQ::cancel miss calling notify_all
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8145 fix data race in join auto spill
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/Interpreters/HashJoinSpillContext.cpp
  dbms/src/Interpreters/HashJoinSpillContext.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/HashProbeTransformExec.cpp
Labels: release-note-none, size/M, approved, lgtm

#8149 disagg: Increase default establish disagg task timeout
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8155 Fix potential hang if tidb cancel is lost
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/L, approved, lgtm

#8156 Adjust the soft limit of mintso scheduler to logical cores
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: size/XS, release-note-none, approved, lgtm
