Repository pingcap/tiflash, pull requests merged in 2023-11, with the labels that each got.

#8281 remove useless config `enforce_enable_resource_control`
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: release-note-none, size/M, approved, lgtm

#8284 disagg: Fix lifecycle set on AWS S3 and add more http hooks
  .gitmodules
  contrib/aws-cmake/0001-More-reliable-way-to-check-if-there-is-anything-in-r.patch
  contrib/aws-cmake/0002-Reduce-verbose-error-logging-and-404-for-HEAD-reques.patch
  contrib/aws-cmake/CMakeLists.txt
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
Labels: size/XL, release-note-none, approved, lgtm

#8277 refine LAC computation of avg_speed
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/ResourceControl/TokenBucket.cpp
  dbms/src/Flash/ResourceControl/TokenBucket.h
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8297 Reduce redundant calculation in join probe, optimize `mergeNullAndFilterResult`
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Interpreters/ProbeProcessInfo.h
Labels: release-note-none, size/L, approved, lgtm

#8302 minmax: fix copy index data in a wrong way
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
Labels: release-note-none, size/M, cherry-pick-approved, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#8263 Add semi and cross semi join kind
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Coprocessor/tests/gtest_join_get_kind_and_build_index.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Interpreters/CrossJoinProbeHelper.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Parsers/ASTTablesInSelectQuery.h
Labels: size/XL, release-note-none, approved, lgtm

#8291 *: Fix compile error under clang-17
  .devcontainer/README.md
  .gitignore
  check_grafana.py
  contrib/CMakeLists.txt
  dbms/src/Common/GRPCKickTag.h
  dbms/src/Common/RecycledAllocator.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggTaskId.h
  dbms/src/Storages/DeltaMerge/Remote/ObjectId.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/Page/PageDefinesBase.h
  dbms/src/Storages/Page/V3/Blob/GCInfo.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPDumpStat.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  inode_usage.py
  libs/libprocess_metrics/src/lib.rs
  release-centos7-llvm/env/.gitignore
  release-centos7-llvm/env/Makefile
  release-centos7-llvm/env/README.md
Labels: size/XL, release-note-none, approved, lgtm

#8309 Let late materialization work when read thread is not enable
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
Labels: release-note-none, size/M, approved, lgtm

#8272 Storages: disaggregated mode supports storage read thread.
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreMock.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreMock.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8313 Update README.md of devcontainer
  .devcontainer/README.md
Labels: release-note-none, size/S, approved, lgtm

#8299 some refine for pipeline
  dbms/src/Common/CPUAffinityManager.h
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.cpp
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/L, approved, lgtm

#8317 Storage: Add stacktrace in log when ThreadedWorker meets an exception.
  dbms/src/Common/ThreadedWorker.h
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8325 fix: update git version for submodules
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/install_ccache.sh
  release-centos7-llvm/dockerfiles/misc/install_git.sh
Labels: release-note-none, size/M, approved, lgtm

#8328 fix unstable unit test `CPUAffinityManagerTest.CPUAffinityManager`
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8330 Support Clang Thread Safety Analysis
  CMakeLists.txt
  dbms/src/Debug/MockKVStore/MockProxyRegion.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
  dbms/src/Debug/MockKVStore/MockReadIndex.cpp
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Flash/Disaggregated/S3LockService.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
  dbms/src/Storages/KVStore/Read/ReadIndexWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorker.h
  dbms/src/Storages/KVStore/tests/gtest_read_index_worker.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
Labels: release-note-none, size/L, approved, lgtm

#8329 Support `json array`
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsJson.cpp
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_json_array.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
  dbms/src/TiDB/Decode/JsonBinary.h
  tests/fullstack-test/expr/json_array.test
Labels: size/XL, release-note-none, approved, lgtm

#8338 *: Fix time step backward for `Stopwatch::elapsedFromLastTime`
  dbms/src/Common/Stopwatch.h
Labels: release-note-none, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8344 Try to fix unstable unittests.
  dbms/src/TestUtils/FunctionTestUtils.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8315 Some refine for RSOperator
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Filter/And.h
  dbms/src/Storages/DeltaMerge/Filter/Equal.h
  dbms/src/Storages/DeltaMerge/Filter/FilterHelper.h
  dbms/src/Storages/DeltaMerge/Filter/Greater.h
  dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/Less.h
  dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Like.h
  dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Or.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/Index/ValueComparison.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8350 ddl: Fix potential data lost of `alter_partition_by` (release-7.5)
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  tests/fullstack-test2/ddl/alter_partition_by.test
  tests/fullstack-test2/ddl/remove_partitioning.test
  tests/fullstack-test2/ddl/reorganize_partition.test
Labels: size/XL, release-note-none, cherry-pick-approved, approved, lgtm

#8337 ddl: Fix potential data lost of `alter_partition_by`
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  tests/fullstack-test2/ddl/alter_partition_by.test
  tests/fullstack-test2/ddl/remove_partitioning.test
  tests/fullstack-test2/ddl/reorganize_partition.test
Labels: size/XL, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8293 FAP: Introduce some metrics and enhancement
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/KVStore/Decode/RegionDataRead.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8353 Remove useless CascadeWriteBuffer
  dbms/src/Common/Allocator.h
  dbms/src/Encryption/AESCTRCipherStream.h
  dbms/src/Encryption/CompressedReadBufferFromFileProvider.h
  dbms/src/Encryption/DataKeyManager.h
  dbms/src/IO/AsynchronousWriteBuffer.h
  dbms/src/IO/BufferWithOwnMemory.h
  dbms/src/IO/CachedCompressedReadBuffer.h
  dbms/src/IO/CascadeWriteBuffer.cpp
  dbms/src/IO/CascadeWriteBuffer.h
  dbms/src/IO/ReadBufferFromFileBase.h
  dbms/src/IO/tests/gtest_cascade_and_memory_write_buffer.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8359 add read bytes ru in disagg mode for resource control
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8361 ddl: Fix zero safepoint make schema gc run repeatly
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8374 ddl: Fix failure on executing exchange partition(release-6.5)
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#8375 ddl: Fix failure on executing exchange partition(release-7.1)
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#8376 ddl: Fix failure on executing exchange partition(release-6.1)
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Storages/Transaction/SchemaBuilder.cpp
  dbms/src/Storages/Transaction/SchemaBuilder.h
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#8364 Set log level to FATAL on FFI boundary on exception
  dbms/src/Common/Exception.cpp
  dbms/src/Common/Exception.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
Labels: release-note-none, size/L, approved, lgtm

#8381 set tunnel timeout to 60s by default in ut
  dbms/src/Debug/DAGProperties.h
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8369 Check RU in read thread of Storage.
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8386 Check RU in read thread of Storage.
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#8368 Print changed config during starting to better check whether configs take affect
  dbms/src/Interpreters/Settings.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/M, approved, lgtm

#8393 Fix unstable ut.
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8403 ddl: Fix broken TableIDMapping lead to data loss or crashes (release-7.5)
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  dbms/src/TiDB/Schema/tests/gtest_table_id_map.cpp
  tests/fullstack-test2/ddl/alter_exchange_partition.test
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#8401 Rename some names of DB::DM::Remote::Serializer.
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: release-note-none, size/M, approved, lgtm

#8402 ddl: Fix broken TableIDMapping lead to data loss or crashes
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  dbms/src/TiDB/Schema/tests/gtest_table_id_map.cpp
  tests/fullstack-test2/ddl/alter_exchange_partition.test
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: size/XXL, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8320 Cache probe column when key has many entries
  dbms/src/Columns/IColumn.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinHashMap.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/ProbeProcessInfo.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8409 *: Fix invalid memory access when shutting down
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Common/tests/gtest_memtracker.cpp
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Storages/BackgroundProcessingPool.cpp
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8400 Don't log too many useless information in log
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MPPTaskId.cpp
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
Labels: release-note-none, size/L, approved, lgtm

#8414 Fixed the issue that `updateStatistics` was not called for `mlfq` in `resource group queue`
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.h
Labels: size/S, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8418 refine log
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: release-note-none, size/M, approved, lgtm

#8388 RCQ wakup actively when resource group is in trickle mode
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.h
  dbms/src/Flash/ResourceControl/TokenBucket.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8425 PageStorage: fix some tidy
  dbms/src/Encryption/KeyManager.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesBuilder.h
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h
  dbms/src/Storages/Page/V2/gc/DataCompactor.h
  dbms/src/Storages/Page/V2/gc/LegacyCompactor.cpp
  dbms/src/Storages/Page/V2/gc/LegacyCompactor.h
  dbms/src/Storages/Page/V2/gc/restoreFromCheckpoints.h
  dbms/src/Storages/Page/V2/tests/gtest_legacy_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_file.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/workload/PSStressEnv.h
Labels: release-note-none, size/L, approved, lgtm

#8426 fix asan fail for `cast_decimal_as_json` and `cast_time_as_json`
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_cast_as_json.cpp
Labels: release-note-none, size/M, approved, lgtm

#8407 Support Json unquote function
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.h
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_cast_as_json.cpp
  dbms/src/Functions/tests/gtest_cast_json_as_string.cpp
  dbms/src/Functions/tests/gtest_json_array.cpp
  dbms/src/Functions/tests/gtest_json_unquote.cpp
  dbms/src/TestUtils/ColumnsToTiPBExpr.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  dbms/src/TiDB/Decode/JsonScanner.cpp
  dbms/src/TiDB/Decode/JsonScanner.h
  tests/fullstack-test/expr/cast_json_as_string.test
  tests/fullstack-test/expr/json_extract.test
  tests/fullstack-test/expr/json_unquote.test
  tests/fullstack-test/expr/json_unquote_extract.test
Labels: size/XXL, release-note-none, approved, lgtm

#8421 ddl: Refactor for fixing unstable drop table
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/DatabaseInfoCache.h
  dbms/src/TiDB/Schema/SchemaBuilder-internal.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/SchemaNameMapper.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/SchemaSyncer.h
  dbms/src/TiDB/Schema/TableIDMap.cpp
  dbms/src/TiDB/Schema/TableIDMap.h
  dbms/src/TiDB/Schema/TiDBSchemaManager.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  dbms/src/TiDB/Schema/tests/gtest_name_mapper.cpp
  dbms/src/TiDB/tests/gtest_rename_resolver.cpp
Labels: size/XXL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8437 Disagg: Fix the problem of missing remote page id in MemTableSet.
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8422 ddl: Fix unstable `DROP TABLE`/`FLASHBACK TABLE`/`RECOVER TABLE`
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/SchemaSyncer.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  dbms/src/TiDB/tests/gtest_table_info.cpp
  tests/fullstack-test2/ddl/alter_create_database_crash.test
  tests/fullstack-test2/ddl/alter_drop_database.test
  tests/fullstack-test2/ddl/alter_drop_table.test
  tests/fullstack-test2/ddl/alter_drop_table_crash.test
  tests/fullstack-test2/ddl/flashback/flashback_table.test
  tests/fullstack-test2/ddl/flashback/recover_table.test
  tests/fullstack-test2/ddl/partitions/alter_exchange_partition.test
  tests/fullstack-test2/ddl/partitions/alter_partition_by.test
  tests/fullstack-test2/ddl/partitions/partition_basic.test
  tests/fullstack-test2/ddl/partitions/remove_partitioning.test
  tests/fullstack-test2/ddl/partitions/reorganize_partition.test
  tests/fullstack-test2/ddl/rename_table_crash.test
  tests/run-test.py
Labels: size/XXL, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, approved, lgtm, needs-cherry-pick-release-7.5

#8435 Support `json_depth`
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsJson.cpp
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_cast_as_json.cpp
  dbms/src/Functions/tests/gtest_json_depth.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
  dbms/src/TiDB/Decode/JsonBinary.h
  tests/fullstack-test/expr/json_depth.test
Labels: release-note-none, size/L, approved, lgtm

#8432 make tiflash scale-in faster
  dbms/src/Common/Config/ConfigReloader.cpp
  dbms/src/Common/Config/ConfigReloader.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/L, approved, lgtm
