Repository pingcap/tiflash, pull requests merged in 2023-01, with the labels that each got.

#6562 Support fast add peer at tiflash side
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/PageReceiver.cpp
  dbms/src/Flash/Disaggregated/PageReceiver.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.h
  dbms/src/Storages/Page/V3/Remote/Proto/common.proto
  dbms/src/Storages/Page/V3/Remote/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/universal/Readers.h
  dbms/src/Storages/Page/universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.h
  dbms/src/Storages/Page/universal/tests/gtest_page_storage.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XXL, release-note-none

#6565 check structure when merging blocks
  dbms/src/Core/Block.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6561 Test: Bind delta merge storage with executor ut
  dbms/src/Debug/MockComputeServerManager.cpp
  dbms/src/Debug/MockComputeServerManager.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.h
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_executors_with_dm.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/Flash/tests/gtest_mock_storage.cpp
  dbms/src/Flash/tests/gtest_projection_executor.cpp
  dbms/src/Flash/tests/gtest_squashing_hash_join_transform.cpp
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/FlashGrpcServerHolder.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6570 fix tsan fail in unit test `ConfigReloaderTest.WithConfigObject`
  dbms/src/Common/Config/ConfigReloader.h
  dbms/src/Common/tests/gtest_config_reloader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6563 schema: support flashback with ddl hisotry
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6577 [Cloud] Fast add peer: Fix peer
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionMeta.h
Labels: release-note-none, size/M

#6573 Test: support push down filter in ut
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_query_expr.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6592 Load DMFile metadata in parallel
  contrib/boost-cmake/CMakeLists.txt
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/ThreadFactory.h
  dbms/src/Common/ThreadManager.cpp
  dbms/src/Common/ThreadPool.cpp
  dbms/src/Common/ThreadPool.h
  dbms/src/Common/tests/gtest_concurrent_hashmap.cpp
  dbms/src/Common/tests/gtest_rw_lock.cpp
  dbms/src/Common/tests/parallel_aggregation.cpp
  dbms/src/Common/tests/parallel_aggregation2.cpp
  dbms/src/Common/tests/thread_creation_latency.cpp
  dbms/src/Common/tests/thread_pool.cpp
  dbms/src/DataStreams/AsynchronousBlockInputStream.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.h
  dbms/src/Databases/DatabaseOrdinary.cpp
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabasesCommon.cpp
  dbms/src/Databases/IDatabase.h
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Management/ManualCompact.cpp
  dbms/src/Flash/Management/ManualCompact.h
  dbms/src/Flash/Mpp/MPPTaskId.cpp
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/IO/AsynchronousWriteBuffer.h
  dbms/src/IO/IOThreadPool.cpp
  dbms/src/IO/IOThreadPool.h
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggregatedSnapshotManager.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggregatedTaskId.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp
  libs/libcommon/CMakeLists.txt
  libs/libcommon/include/boost_wrapper/priority_queue.h
  libs/libcommon/include/common/ThreadPool.h
  libs/libcommon/src/ThreadPool.cpp
  libs/libcommon/src/tests/multi_version.cpp
Labels: do-not-merge/release-note-label-needed, size/XXL

#6593 Fix dump snapshot
  dbms/src/Storages/Page/V3/PageDirectory.cpp
Labels: release-note-none, size/M

#6591 support scan concurrency hint for mock table
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
  dbms/src/Flash/Coprocessor/MockSourceStream.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/tests/gtest_scan_concurrency_hint.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6568 add spiller
  dbms/src/Common/Spiller.cpp
  dbms/src/Common/Spiller.h
  dbms/src/Common/tests/gtest_spiller.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.h
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6595 Removed redundant query id from tracingJson
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.5

#6599 Read from InputStream in parallel
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: do-not-merge/release-note-label-needed, size/M

#6597 [Cloud] Fast add peer: Add cache for local PS
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/LocalPageStorageCache.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XL, release-note-none

#6602 Cherry-pick regexp_replace function
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRegexp.cpp
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/tests/gtest_regexp.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, cherry-pick-approved

#6558 PageStorage: Fix unexpected dmfile removed after shutdown
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note, needs-cherry-pick-release-6.5

#6514 *: minor refine for storage stream
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/RowKeyFilter.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_utils.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6610 Speed up read checkpoint
  dbms/src/Common/tests/gtest_concurrent_hashmap.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.h
  dbms/src/Storages/Page/V3/Remote/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Transaction/FastAddPeer.cpp
Labels: release-note-none, size/L

#6576 move non joined block stream into HashJoinProbeBlockInputStream
  dbms/src/Common/tests/gtest_spiller.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/MockExchangeReceiverInputStream.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGPipeline.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.h
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockExchangeReceiver.h
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6463 Refine local tunnel
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/tests/bench_exchange.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6614 [Cloud] Fast add peer: Fix thread pool
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/FastAddPeerContext.cpp
Labels: release-note-none, size/S

#6607 feat(config): support config `max_memory_usage_for_all_queries` to either UInt64 or double(means ratio of total memory).
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/ProcessList.cpp
  dbms/src/Interpreters/ProcessList.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SettingsCommon.cpp
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  libs/libdaemon/src/tests/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XL, release-note

#6624 [Cloud] Fast add peer: Fix dangling future
  dbms/src/Common/ThreadPool.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/FastAddPeerContext.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: release-note-none, size/M

#6625 Optimize `getPartitionEndRow` for window function
  dbms/src/DataStreams/WindowBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, cherry-pick-approved

#6628 Support push down filter to disaggregated read
  dbms/src/Common/tests/gtest_concurrent_hashmap.cpp
  dbms/src/Flash/Disaggregated/GRPCPageReceiverContext.cpp
  dbms/src/Flash/Disaggregated/PageDownloader.cpp
  dbms/src/Flash/Disaggregated/PageDownloader.h
  dbms/src/Flash/Disaggregated/PageReceiver.cpp
  dbms/src/Flash/Disaggregated/PageReceiver.h
  dbms/src/IO/ReadBuffer.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriterRemote.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriterRemote.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_remote_read_task.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.h
  dbms/src/Storages/Page/V3/Remote/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/universal/tests/gtest_page_storage.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
Labels: size/XXL, release-note-none

#6629 Fix build fail
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6630 fix pthread_setname_np
  libs/libglibc-compatibility/glibc-compatibility.c
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6496 Storage: Avoid wasting CPU with inefficient scheduling in SegmentReadTaskScheduler
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.5

#6633 remove over_flow_row in aggregation
  dbms/src/Core/BlockInfo.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.h
  dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/SizeLimits.h
  dbms/src/DataStreams/TotalsHavingBlockInputStream.cpp
  dbms/src/DataStreams/TotalsHavingBlockInputStream.h
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/Interpreters/SettingsCommon.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6637 Read node support build delta index in background threads
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/PageDownloader.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RemoteSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_remote_read_task.cpp
Labels: release-note-none, size/M

#6639 fix(build): fix gtests_dbms build on mac m1
  dbms/src/Flash/tests/gtest_join_executor.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6590 split aggregation out block smaller than max block size
  dbms/src/Core/Block.h
  dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note

#6642 6.5 poc: support data compression in FineGrainedShuffle
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriterV1.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriterV1.h
  dbms/src/Flash/Mpp/HashPartitionWriterV1.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6644 Move the logic of encoding mpp packet from exchange writer to mpp tunnel set
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6636 change the time unit of measurement in ScanContext
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6643 Aggregator use spiller
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Core/SpillConfig.cpp
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/AggregatingBlockInputStream.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.h
  dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/DataStreams/SpilledFilesInputStream.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.h
  dbms/src/DataStreams/TemporaryFileStream.cpp
  dbms/src/DataStreams/TemporaryFileStream.h
  dbms/src/Debug/MockExecutor/TableScanBinder.cpp
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6647 Add log when Poco Exception
  dbms/src/TiDB/Schema/SchemaGetter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6645 Use ${thread_name}_${thread_id} as RWLock query_id
  dbms/src/Common/RWLock.cpp
  dbms/src/Common/setThreadName.cpp
  dbms/src/Common/setThreadName.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6652 fix compile on mac os
  dbms/src/Common/setThreadName.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6658 Cherry-pick: fix metrics for establish connection
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, cherry-pick-approved

#6664 Cover the whole SchemaDiff::deserialize in a try block and print out the error data
  dbms/src/TiDB/Schema/SchemaGetter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6619 Fix tiflash crash caused by local tunnel
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6663 `max_block_size` take effect on `NonJoinedBlockInputStream`
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6670 Remove some useless class and remove settings in `ExpressionActions`
  dbms/src/Core/iostream_debug_helpers.cpp
  dbms/src/Core/iostream_debug_helpers.h
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.h
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/Debug/dbgQueryCompiler.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Planner/PhysicalPlanHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.h
  dbms/src/Flash/Planner/plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/plans/PhysicalFilter.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.h
  dbms/src/Flash/Planner/plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/plans/PhysicalTableScan.h
  dbms/src/Flash/Planner/plans/PhysicalTopN.cpp
  dbms/src/Functions/IFunction.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Parsers/iostream_debug_helpers.cpp
  dbms/src/Parsers/iostream_debug_helpers.h
  libs/libcommon/src/tests/CMakeLists.txt
  libs/libcommon/src/tests/dump_variable.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6672 Skip read `regenerate_schema_map` is not present
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6673 Remove useless code in join
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/StorageJoin.cpp
  dbms/src/Storages/StorageJoin.h
  dbms/src/Storages/registerStorages.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6677 Remove some useless settings and related codes
  dbms/src/DataStreams/FormatFactory.cpp
  dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  dbms/src/Interpreters/InterpreterFactory.cpp
  dbms/src/Interpreters/InterpreterInsertQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Interpreters/executeQuery.h
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Storages/StorageBuffer.cpp
  dbms/src/Storages/StorageBuffer.h
  dbms/src/Storages/registerStorages.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6684 CI: delete useless ci files
  .github/workflows/bug-closed.yml
  .github/workflows/license-checker.yml
  Jenkinsfile
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6679 *: rename `PushDownFilter` to `FilterConditions`
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/FilterConditions.cpp
  dbms/src/Flash/Coprocessor/FilterConditions.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.h
  dbms/src/Flash/Coprocessor/StorageDisaggregatedInterpreter.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.h
  dbms/src/Flash/tests/gtest_storage_disaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6680 Some code refine in join
  dbms/src/DataStreams/LimitTransformAction.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6538 Add back ingest file range check
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.5

#6689 refine interpreter unit test
  .github/licenserc.yml
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_pipeline_interpreter.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Flash/tests/gtest_scan_concurrency_hint.cpp
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/InterpreterTestUtils.h
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6588 remove tiflash-proxy for tiflash_compute mode
  dbms/src/Flash/DiagnosticsService.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6572 Enable glibc-compatibility on arm
  CMakeLists.txt
  libs/libglibc-compatibility/CMakeLists.txt
  libs/libglibc-compatibility/glibc-compatibility.c
  libs/libglibc-compatibility/musl/aarch64/longjmp.s
  libs/libglibc-compatibility/musl/aarch64/syscall.s
  libs/libglibc-compatibility/musl/x86_64/longjmp.s
  libs/libglibc-compatibility/musl/x86_64/syscall.s
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6690 Fix potential hang in right join
  dbms/src/Common/FailPoint.cpp
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Debug/dbgFuncMisc.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6693 Optimize `getPartitionEndRow` for window function
  dbms/src/DataStreams/WindowBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6700 add use_autoscaler config for AutoSaler prod rollback
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/Flash/DiagnosticsService.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
  etc/config-template.toml
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6458 Storage: row ID generation for MVCC bitmap filter
  dbms/CMakeLists.txt
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/RowKeyFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic_bitmap.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none
