Repository pingcap/tiflash, pull requests merged in 2023-05, with the labels that each got.

#7412 add info log to log tunnel time for local tunnel
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7411 Tsan: fix data race on `Event::insertEvent`
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7380 Refine metrics of uploading DMFile.
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/S3/S3Common.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7418 Donot reserve memory for non-fixed type columns in decodeAndSquash
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
Labels: status/can-merge, status/LGT2, size/S, release-note, needs-cherry-pick-release-7.1

#7422 add allocated bytes to runtime statistics
  dbms/src/DataStreams/BlockStreamProfileInfo.cpp
  dbms/src/DataStreams/BlockStreamProfileInfo.h
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.cpp
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.h
  dbms/src/Flash/Statistics/ExecutorStatistics.h
  dbms/src/Flash/Statistics/JoinImpl.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7415 Fix dead lock in`ComputeServerRunner.*`
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7419 use `Block::estimateByteSizeForSpill` to estimate block memory in spill
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/IColumn.h
  dbms/src/Core/tests/gtest_block.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Operators/LocalSortTransformOp.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-7.1

#7429 make mpp_fail test stable
  tests/fullstack-test/mpp/having.test
  tests/fullstack-test/mpp/late_materialization_generate_column.test
  tests/fullstack-test/mpp/left_semi_family_joins.test
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7434 Tsan: fix data race on `ComputeServerRunner.cancelJoinTasks`
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7143 Fix failing to read from blob store when upload checkpoint
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7444 Cross join use probe info
  dbms/src/Interpreters/CrossJoinProbeHelper.cpp
  dbms/src/Interpreters/CrossJoinProbeHelper.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7441 Fix mpp task hang in spill random fail point
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/tests/bench_exchange.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7271 Support capture group in regexp_replace
  dbms/src/Common/OptimizedRegularExpression.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Functions/FunctionsRegexpCommon.h
  dbms/src/Functions/FunctionsRegexpReplace.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Functions/tests/gtest_regexp_replace.cpp
  tests/fullstack-test/expr/regexp.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7449 remove an unstable test
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7452 RUNTIME_ASSERT fail without `Terminate called without an active exception` in `BaseDaemon.cpp`
  dbms/src/Common/Exception.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7438 Rmove all `noexcept` in pipeline model
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/CMakeLists.txt
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/Spinner.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/Spinner.h
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.h
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitingTaskList.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitingTaskList.h
  dbms/src/Flash/Pipeline/Schedule/Reactor/tests/gtest_wait_task_list.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FIFOTaskQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FIFOTaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_fifo.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_mlfq.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskHelper.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.h
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7445 Restore checkpoint location after restart
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-7.1

#7227 chore: migrate to new prow reviewing
  .github/licenserc.yml
  OWNERS
Labels: status/can-merge, status/LGT2, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, skip-issue-check

#7462 Fix a crash issue when connection to PD is not stable
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  dbms/src/TiDB/Etcd/Client.h
  dbms/src/TiDB/OwnerManager.cpp
  dbms/src/TiDB/tests/gtest_owner_manager.cpp
Labels: status/can-merge, status/LGT2, release-note, size/M, needs-cherry-pick-release-7.1

#7460 Fix read duration type column failed in disaggregated mode
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/Transaction/TypeMapping.cpp
  dbms/src/Storages/Transaction/TypeMapping.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-7.1

#7471 Fix MPP Task hang in spill random fail point
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/GRPCReceiveQueue.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7473 Check CPU cores in CPUAffinityManagerTest
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#7458 Pipeline: support `collectRequestUnit`
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7427 Support `first_value` window function
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Debug/MockExecutor/FuncSigMap.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/WindowFunctions/IWindowFunction.cpp
  dbms/src/WindowFunctions/tests/gtest_first_value.cpp
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
  tests/fullstack-test/mpp/window.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7469 Fix query fail when there are timestamp or time columns after generated column
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  tests/fullstack-test/expr/duration_filter_late_materialization.test
  tests/fullstack-test/mpp/late_materialization_generate_column.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#7433 Support `last_value` window function
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Debug/MockExecutor/FuncSigMap.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/WindowFunctions/IWindowFunction.cpp
  dbms/src/WindowFunctions/tests/gtest_last_value.cpp
  tests/fullstack-test/mpp/window.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7487 Throw exception when disable read thread pool and enable late materialization
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7474 Pipeline: support partition table scan without optimize
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7461 Pipeline: Reduce CPU usage of `WaitReactor`
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/Spinner.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/Spinner.h
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskHelper.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Operators/AggregateRestoreSourceOp.h
  dbms/src/Operators/CoprocessorReaderSourceOp.h
  dbms/src/Operators/ExchangeReceiverSourceOp.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.h
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/HashJoinProbeTransformOp.h
  dbms/src/Operators/Operator.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/UnorderedSourceOp.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7479 optimize cross join probe
  dbms/src/Debug/MockExecutor/AstToPBUtils.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/CrossJoinProbeHelper.cpp
  dbms/src/Interpreters/CrossJoinProbeHelper.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Interpreters/ProbeProcessInfo.h
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7493 storage: Add AddExtraTableIDColumn action and stream
  dbms/src/DataStreams/AddExtraTableIDColumnInputStream.cpp
  dbms/src/DataStreams/AddExtraTableIDColumnInputStream.h
  dbms/src/DataStreams/AddExtraTableIDColumnTransformAction.cpp
  dbms/src/DataStreams/AddExtraTableIDColumnTransformAction.h
  dbms/src/DataStreams/SegmentReadTransformAction.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.h
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7490 add option setting: disable promethues metrics tls
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/MetricsPrometheus.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7499 Add info for ExchangeReceiver logs
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7497 fix query fail when there is extra table id column and late materialization
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  tests/fullstack-test/mpp/late_materialization_extra_table_id_column.test
  tests/fullstack-test/mpp/late_materialization_generate_column.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-7.1

#7501 Add `reserveWithTotalMemoryHint` to IColumn
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/IColumn.h
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Core/tests/gtest_block.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7506 Fix crash when `Pipeline::executePrefix` fail and support random point for pipeline in unit test
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TestUtils/ConfigTestUtils.h
  dbms/src/TestUtils/FailPointUtils.cpp
  dbms/src/TestUtils/FailPointUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7508 Set reactor as default config for ExchangeReceiver
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7509 *: refine appendExtraCastsAfterTS
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7504 storage: Code refactor
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_circular_scan_list.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7521 Pipeline: fix crash on `ResultHandler` throwing exception
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7522 storage: add an info log of query
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7529 fix keep order in table scan is lost when remote read of PartitionTableScan
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  tests/fullstack-test/issues/issue_7519.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#7492 Pipeline: support non fine grained window
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.h
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindow.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindow.h
  dbms/src/Flash/Planner/Plans/PhysicalWindowSort.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Operators/MergeSortTransformOp.cpp
  dbms/src/Operators/MergeSortTransformOp.h
  dbms/src/Operators/PartialSortTransformOp.cpp
  dbms/src/Operators/PartialSortTransformOp.h
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Operators/tests/gtest_shared_queue.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/IStorage.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  tests/docker/config/tiflash_dt_enable_pipeline.toml
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7533 Reduce unnecessary S3 read flow after restart
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7510 *: use `if (container.contains(value))` instead of `if (container.count(value))`
  dbms/src/Functions/FunctionHelpers.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7537 Improve KVStore tests
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Debug/dbgFuncMockRaftCommand.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/ReadIndexWorker.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionCFDataBase.cpp
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionMeta.h
  dbms/src/Storages/Transaction/TiKVRecordFormat.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_read_index_worker.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
  dbms/src/Storages/Transaction/tests/region_helper.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7541 Delete `only_have_pure_window` variable in WindowTransformAction
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7546 If `result_handler` throws an error, `PipelineExecutorStatus` should notify the query to terminate, and wait for the end of the query.
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_status.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7532 Support memory bounded for `LooseBoundedMPMCQueue`
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_loose_bounded_mpmc_queue.cpp
  dbms/src/Common/tests/gtest_mpmc_queue.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7399 Add a config to force enable lm and add more tests for lm
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/Flash/Coprocessor/DAGQueryInfo.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  tests/docker/config/tiflash_dt_force_enable_lm.toml
  tests/docker/tiflash-dt-force-enable-lm.yaml
  tests/tidb-ci/force_enable_lm
  tests/tidb-ci/run.sh
  tests/tidb-ci/tiflash-dt-force-enable-lm.yaml
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7553 Fix the total_local_region_num in ScanContext
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7218 Runtime Filter: Support Local Mode and In Type
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Debug/MockExecutor/TableScanBinder.cpp
  dbms/src/Debug/MockExecutor/TableScanBinder.h
  dbms/src/Debug/MockRuntimeFilter.cpp
  dbms/src/Debug/MockRuntimeFilter.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryInfo.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Coprocessor/RuntimeFilterMgr.cpp
  dbms/src/Flash/Coprocessor/RuntimeFilterMgr.h
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Flash/tests/gtest_execution_summary.cpp
  dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Set.cpp
  dbms/src/Interpreters/Set.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7549 Add tests for learner read
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockRaftStoreProxy.h
  dbms/src/Debug/MockSSTReader.h
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionCFDataBase.h
  dbms/src/Storages/Transaction/RegionRangeKeys.h
  dbms/src/Storages/Transaction/RegionState.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionsRangeIndex.cpp
  dbms/src/Storages/Transaction/RegionsRangeIndex.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7566 fix possible issues for `PipelineExecGroupBuilder`
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7570 DTWorkload: initialize global storage pool every time before creating DeltaMergeStore.
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7569 Filter lock flag 'F'
  dbms/src/Storages/Transaction/TiKVRecordFormat.cpp
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7572 Fix Region cache update when duplicated Region id exist
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  dbms/src/Storages/CMakeLists.txt
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedHelpers.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/Transaction/tests/CMakeLists.txt
  dbms/src/Storages/tests/CMakeLists.txt
  dbms/src/Storages/tests/gtest_disagg_remote.cpp
  dbms/src/Storages/tests/hit_log.cpp
  dbms/src/Storages/tests/remove_symlink_directory.cpp
  dbms/src/Storages/tests/seek_speed_test.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note, needs-cherry-pick-release-7.1
