Repository pingcap/tiflash, pull requests merged in 2023-03, with the labels that each got.

#6915 fix potential deadlock in spiller
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6818 Support skip rows both in delta and stable
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ReadUtil.cpp
  dbms/src/Storages/DeltaMerge/ReadUtil.h
  dbms/src/Storages/DeltaMerge/RowKeyOrderedBlockInputStream.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6925 Fix delta index cache
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/Remote/DeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
Labels: do-not-merge/release-note-label-needed, size/M

#6910 Fix the tasks in bkg pool may be called more frequently than expected
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  dbms/src/Storages/tests/gtest_bkg_pool.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6923 Pipeline: add random fail points
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FiFOTaskQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FiFOTaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_fifo.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.h
  dbms/src/Flash/Pipeline/Schedule/WaitingTaskList.cpp
  dbms/src/Flash/Pipeline/Schedule/WaitingTaskList.h
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
  dbms/src/Operators/Operator.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6921 Pipeline: refine log
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.h
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/QueryExecutor.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Pipeline/PipelineBuilder.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/PipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FiFOTaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_fifo.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Operators/BlockInputStreamSourceOp.cpp
  dbms/src/Operators/BlockInputStreamSourceOp.h
  dbms/src/Operators/ExchangeReceiverSourceOp.h
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/ExpressionTransformOp.h
  dbms/src/Operators/FilterTransformOp.h
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/LimitTransformOp.h
  dbms/src/Operators/Operator.h
  dbms/src/Operators/TopNTransformOp.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6898 Support C++20
  CMakeLists.txt
  README.md
  dbms/CMakeLists.txt
  dbms/src/Columns/ColumnsCommon.cpp
  dbms/src/Common/Exception.h
  dbms/src/Common/HyperLogLogCounter.h
  dbms/src/Common/MyDuration.cpp
  dbms/src/Common/StringSearcher.h
  dbms/src/Common/TiFlashException.h
  dbms/src/DataStreams/DistinctBlockInputStream.cpp
  dbms/src/DataStreams/DistinctSortedBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
  dbms/src/Functions/tests/gtest_strings_simd_consistency.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  libs/libcommon/include/common/avx2_byte_count.h
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/env/prepare-sysroot.sh
Labels: status/can-merge, status/LGT2, size/L, release-note

#6931 chore: Add ccache tip in readme.md
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6913 Storage: DMFile supports read/write from S3.
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Encryption/FileProvider.cpp
  dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/MockS3Client.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3Filename.cpp
  dbms/src/Storages/S3/S3Filename.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/Storages/S3/S3WritableFile.cpp
  dbms/src/Storages/S3/S3WritableFile.h
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/S3/tests/gtest_s3filename.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6933 Support read S3 authentication information from configuration.
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/tests/gtest_storage_config.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6855 Pipeline: Support pipeline agg
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregationConvergent.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationConvergent.h
  dbms/src/Flash/Planner/Plans/PipelineBreakerHelper.h
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/AggregateConvergentSourceOp.cpp
  dbms/src/Operators/AggregateConvergentSourceOp.h
  dbms/src/Operators/AggregateSinkOp.cpp
  dbms/src/Operators/AggregateSinkOp.h
  dbms/src/Operators/NullSourceOp.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6940 Revert "make tiflash compatible with old version client (#6702)"
  dbms/src/Core/BlockInfo.cpp
  dbms/src/Core/BlockInfo.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6928 Add dumpIncrementalCheckpoint utility
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6937 Rename env variables of S3 authentication.
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6939 Remove `with totals` support
  dbms/src/Client/Connection.cpp
  dbms/src/Client/MultiplexedConnections.cpp
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/DataStreams/AdditionalColumnsBlockOutputStream.h
  dbms/src/DataStreams/BlockOutputStreamFromRowOutputStream.cpp
  dbms/src/DataStreams/BlockOutputStreamFromRowOutputStream.h
  dbms/src/DataStreams/CSVRowOutputStream.cpp
  dbms/src/DataStreams/CSVRowOutputStream.h
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/CreatingSetsBlockInputStream.h
  dbms/src/DataStreams/ExpressionBlockInputStream.cpp
  dbms/src/DataStreams/ExpressionBlockInputStream.h
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/FilterBlockInputStream.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/IBlockOutputStream.h
  dbms/src/DataStreams/IProfilingBlockInputStream.cpp
  dbms/src/DataStreams/IProfilingBlockInputStream.h
  dbms/src/DataStreams/IRowOutputStream.h
  dbms/src/DataStreams/JSONCompactRowOutputStream.cpp
  dbms/src/DataStreams/JSONCompactRowOutputStream.h
  dbms/src/DataStreams/JSONRowOutputStream.cpp
  dbms/src/DataStreams/JSONRowOutputStream.h
  dbms/src/DataStreams/MaterializingBlockOutputStream.h
  dbms/src/DataStreams/MockExchangeSenderInputStream.cpp
  dbms/src/DataStreams/MockExchangeSenderInputStream.h
  dbms/src/DataStreams/PrettyBlockOutputStream.cpp
  dbms/src/DataStreams/PrettyBlockOutputStream.h
  dbms/src/DataStreams/PrettySpaceBlockOutputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowOutputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowOutputStream.h
  dbms/src/DataStreams/TotalsHavingBlockInputStream.cpp
  dbms/src/DataStreams/TotalsHavingBlockInputStream.h
  dbms/src/DataStreams/VerticalRowOutputStream.cpp
  dbms/src/DataStreams/VerticalRowOutputStream.h
  dbms/src/DataStreams/XMLRowOutputStream.cpp
  dbms/src/DataStreams/XMLRowOutputStream.h
  dbms/src/DataStreams/copyData.cpp
  dbms/src/Functions/FunctionsMiscellaneous.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/Interpreters/InterpreterSelectWithUnionQuery.cpp
  dbms/src/Interpreters/InterpreterSelectWithUnionQuery.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Parsers/ASTSelectQuery.cpp
  dbms/src/Parsers/ASTSelectQuery.h
  dbms/src/Parsers/ParserSelectQuery.cpp
  dbms/src/Server/Client.cpp
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Server/TCPHandler.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6938 README: add instructions for installing llvm clang in macOS
  README.md
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6942 Add DataStoreS3 and IOThreadPool
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/ThreadPool.cpp
  dbms/src/Common/ThreadPool.h
  dbms/src/IO/IOThreadPool.cpp
  dbms/src/IO/IOThreadPool.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
  libs/libcommon/include/boost_wrapper/priority_queue.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6899 GC data on S3
  dbms/src/Flash/Disaggregated/S3LockClient.h
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesBuilder.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/S3/CheckpointManifestS3Set.cpp
  dbms/src/Storages/S3/CheckpointManifestS3Set.h
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3Filename.cpp
  dbms/src/Storages/S3/S3Filename.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/TiDB/OwnerManager.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6944 Specifies the namespace of the bit_cast.
  libs/libcommon/include/ext/bit_cast.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6880 Optimize data size of `Broadcast` / `Passthrough` exchange operator
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.h
  dbms/src/Flash/Coprocessor/tests/gtest_block_chunk_codec.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/IO/CompressedWriteBuffer.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/Transaction/ReadIndexWorker.cpp
  dbms/src/Storages/Transaction/ReadIndexWorker.h
  dbms/src/Storages/Transaction/RegionManager.h
  dbms/src/Storages/Transaction/Utils.h
  libs/libcommon/include/common/avx2_byte_count.h
Labels: type/enhancement, status/can-merge, status/LGT2, size/XXL, release-note-none

#6957 *: fix crash issue
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
Labels: status/can-merge, type/bug-fix, status/LGT2, release-note-none, size/M

#6947 Ignored "-Wdeprecated-builtins" in boost priority_queue.
  libs/libcommon/include/boost_wrapper/priority_queue.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6945 *: fix tsan in Pipeline Agg
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/AggregateSinkOp.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6960 Rename filename to UniThreadPool to fix build on mac
  dbms/src/Common/ThreadFactory.h
  dbms/src/Common/ThreadManager.cpp
  dbms/src/Common/UniThreadPool.cpp
  dbms/src/Common/UniThreadPool.h
  dbms/src/Common/tests/CMakeLists.txt
  dbms/src/Common/tests/gtest_rw_lock.cpp
  dbms/src/Common/tests/parallel_aggregation.cpp
  dbms/src/Common/tests/parallel_aggregation2.cpp
  dbms/src/Common/tests/thread_creation_latency.cpp
  dbms/src/Common/tests/thread_pool.cpp
  dbms/src/IO/IOThreadPool.h
  dbms/src/Interpreters/Join.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6930 Support remote read on uni ps
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesBuilder.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/Page/WriteBatchImpl.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/MockS3Client.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6965 Tsan: fix data race in `MPPTunnel::updateConnProfileInfo`
  dbms/src/Flash/Mpp/MPPTunnel.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6972 Remove ByteBuffer
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageDefinesBase.h
  dbms/src/Storages/Page/V1/Page.h
  dbms/src/Storages/Page/V1/PageFile.cpp
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_file.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6967 Add remote storage cache config.
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6961 Add local page cache
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.h
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_local_page_cache.cpp
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_local_page_cache_lru.cpp
  dbms/src/Storages/DeltaMerge/tests/MultiSegmentTestUtil.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_store_background.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageConstants.h
  dbms/src/Storages/Page/PageDefinesBase.h
  dbms/src/Storages/Page/V3/Blob/BlobFile.h
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage_storage_pool.cpp
  dbms/src/Storages/tests/TiFlashStorageTestBasic.h
  dbms/src/TestUtils/TiFlashTestEnv.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6831 Pipeline: Support pipeline table scan in UT
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/tests/gtest_executors_with_dm.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6974 Protect language boundary between C++ and Rust codes
  dbms/src/Storages/Transaction/ProxyFFI.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6883 Add cloud-native-architecture.md
  docs/design/2023-02-23-cloud-native-architecture.md
  docs/design/images/2023-02-23-cloud-native-architecture-1.png
  docs/design/images/2023-02-23-cloud-native-architecture-2.png
  docs/design/images/2023-02-23-cloud-native-architecture-3.png
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6978 Allow specifying data provider for ColumnFiles
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDataProvider.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDataProvider.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDataProvider_fwd.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6988 Make DMContext adapt to remote data provider
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6990 Initialize Local Page Cache
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.h
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/PathCapacityMetrics.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6992 release block earlier in SpillHandler
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/Interpreters/Aggregator.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6991 Encode delta index epoch
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6984 Upload checkpoint, dtfile to S3
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/FailPoint.cpp
  dbms/src/Encryption/FileProvider.h
  dbms/src/Encryption/PosixRandomAccessFile.cpp
  dbms/src/Encryption/PosixRandomAccessFile.h
  dbms/src/Flash/Disaggregated/MockS3LockClient.h
  dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileReader.h
  dbms/src/Storages/Page/V3/CheckpointFile/CheckpointFiles.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.cpp
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.h
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/WriteBatchWrapperImpl.h
  dbms/src/Storages/S3/CheckpointManifestS3Set.cpp
  dbms/src/Storages/S3/CheckpointManifestS3Set.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Filename.cpp
  dbms/src/Storages/S3/S3Filename.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6999 mock exchange receiver with fine grained enable support different max_streams
  dbms/src/DataStreams/MockExchangeReceiverInputStream.cpp
  dbms/src/DataStreams/MockExchangeReceiverInputStream.h
  dbms/src/Flash/Coprocessor/MockSourceStream.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6971 Reduce DMFile::restore in DeltaMergeStore::DeltaMergeStore
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
Labels: type/enhancement, status/can-merge, status/LGT2, release-note, size/M

#7004 support store remote location info in external page
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7002 Fix incorrect result of max aggregation fun with collation ci
  dbms/src/Core/SortCursor.h
  tests/fullstack-test/issues/issue_1962.test
  tests/fullstack-test/issues/issue_2471.test
  tests/fullstack-test/issues/issue_4519.test
  tests/fullstack-test/issues/issue_6807.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-6.4

#6861 Change mark_cache size calculation to cut down memory usage
  dbms/src/Common/PODArray.h
  dbms/src/Storages/MarkCache.h
Labels: status/can-merge, status/LGT2, size/S, release-note

#7009 Fix colDataSize of null map.
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7026 fix decimal cast bug
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-6.4

#7025 Fix witness by providing a default behaviour on TiFlash's side
  dbms/src/Storages/Transaction/KVStore.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7003 Add file cache of DTFile
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Encryption/PosixRandomAccessFile.cpp
  dbms/src/Encryption/PosixRandomAccessFile.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7044 Disable some useless services on disagg read node
  dbms/src/Client/ConnectionPoolWithFailover.cpp
  dbms/src/Client/MultiplexedConnections.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Transaction/BackgroundService.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7045 Check FileCache's initialization state.
  dbms/src/Storages/S3/FileCache.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7049 Rename tiflash_storage to tiflash_write
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7048 Fix thread pool blocks when program exit
  dbms/src/Common/ThreadManager.cpp
  dbms/src/Common/UniThreadPool.cpp
  dbms/src/Common/UniThreadPool.h
  dbms/src/Common/tests/gtest_concurrent_hashmap.cpp
  dbms/src/DataStreams/AsynchronousBlockInputStream.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.h
  dbms/src/Databases/DatabaseMemory.cpp
  dbms/src/Databases/DatabaseMemory.h
  dbms/src/Databases/DatabaseOrdinary.cpp
  dbms/src/Databases/DatabaseOrdinary.h
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabaseTiFlash.h
  dbms/src/Databases/DatabasesCommon.cpp
  dbms/src/Databases/DatabasesCommon.h
  dbms/src/Databases/IDatabase.h
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Management/ManualCompact.cpp
  dbms/src/Flash/Management/ManualCompact.h
  dbms/src/IO/AsynchronousWriteBuffer.h
  dbms/src/IO/IOThreadPool.h
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_paths.cpp
  dbms/src/Storages/Page/V2/tests/test_page_storage_write_disk_full.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  libs/libcommon/include/common/ThreadPool.h
  libs/libcommon/src/ThreadPool.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7037 Add more deserializers for disaggregation protocol
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/DataStreams/SelectionByColumnIdTransformAction.cpp
  dbms/src/DataStreams/SelectionByColumnIdTransformAction.h
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Interpreters/SharedContexts/Disagg.cpp
  dbms/src/Interpreters/SharedContexts/Disagg.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaIndexManager.h
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6650 support spill to disk in join
  dbms/CMakeLists.txt
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/HashTable/HashTable.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Statistics/JoinImpl.cpp
  dbms/src/Flash/Statistics/JoinImpl.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/Settings.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7047 Remove DMFile after upload S3
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.h
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/DeltaMerge/workload/Options.cpp
  dbms/src/Storages/DeltaMerge/workload/Options.h
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/PathCapacityMetrics.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/tests/gtest_path_pool.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7050 S3GC with lifecycle config
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/MockS3Client.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7053 Fix several issues related with disaggregate remote read
  dbms/src/Flash/Disaggregated/RNPagePreparer.cpp
  dbms/src/Flash/Disaggregated/RNPagePreparer.h
  dbms/src/Flash/Disaggregated/RNPageReceiverContext.cpp
  dbms/src/Flash/Disaggregated/RNPageReceiverContext.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/RNDataProvider.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNDataProvider.h
  dbms/src/Storages/DeltaMerge/Remote/RNDataProvider_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/data_file.proto
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/manifest_file.proto
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/Transaction/TiKVKeyValue.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7005 Cut down mark_cache default size and add the corresponding metrics in grafana
  dbms/src/Core/Defines.h
  etc/config-template.toml
  metrics/grafana/tiflash_summary.json
  tests/docker/config/tics_dt.toml
  tests/docker/config/tiflash_dt.toml
  tests/docker/config/tiflash_dt_async_grpc.toml
  tests/docker/config/tiflash_dt_disable_local_tunnel.toml
  tests/docker/config/tiflash_dt_disable_planner.toml
Labels: status/can-merge, status/LGT2, size/L, release-note

#7059 Test: support mock not null column
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/MockSourceStream.h
  dbms/src/Flash/tests/gtest_limit_executor.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7057 Add capacity metrics for FileCache
  dbms/src/Server/Server.cpp
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7061 fix get remote DTFile path
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7064 disable join from tiflash client
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7065 Add design doc for spill to disk
  docs/design/2023-03-13-tiflash-supports-spill-to-disk.md
  docs/design/images/2023-03-13-tiflash-supports-spill-to-disk-agg_with_spill.png
  docs/design/images/2023-03-13-tiflash-supports-spill-to-disk-hash_join_with_spill.png
  docs/design/images/2023-03-13-tiflash-supports-spill-to-disk-sort_with_spill.png
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7063 Fix agg spilt bug
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-6.6

#7060 Fix several issues under disagg mode
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Flash/Disaggregated/S3LockService.h
  dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/BgStorageInit.cpp
  dbms/src/Server/BgStorageInit.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.h
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7069 Storage: File size of DMFile's subfiles can be zero.
  dbms/src/Storages/S3/FileCache.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7073 Add more spill tests and fix bug
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/IColumn.h
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/TestUtils/mockExecutor.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6950 Fix ilike function
  dbms/src/Common/StringUtils/StringUtils.h
  dbms/src/Functions/FunctionsStringSearch.h
  dbms/src/Functions/tests/gtest_strings_search.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7068 Simplify the config for disagg deployment
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/Interpreters/SharedContexts/Disagg.h
  dbms/src/Server/Server.cpp
  etc/config-template.toml
  tests/docker/config/tiflash_dt.toml
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7075 Support disagg read after data ingest by FAP
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  dbms/src/TiDB/OwnerManager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7078 Disable prepare stage
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  tests/tidb-ci/new_collation_fullstack/function_collator.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7076 Support sharing the same S3 bucket for multiple clusters
  dbms/src/Flash/Disaggregated/MockS3LockClient.h
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Flash/Disaggregated/S3LockService.h
  dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/common.proto
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/S3/CheckpointManifestS3Set.cpp
  dbms/src/Storages/S3/CheckpointManifestS3Set.h
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/MockS3Client.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/Storages/S3/S3WritableFile.cpp
  dbms/src/Storages/S3/S3WritableFile.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
  dbms/src/Storages/S3/tests/gtest_s3client.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT1, status/LGT2, size/XXL, release-note-none

#7077 Fix checksums of metav2.
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7072 Fix sync schema after schema version key be removed
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/SchemaSyncer.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7085 TiDB use session variable to set the memory threshold for TiFlash spill
  dbms/src/Flash/FlashService.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7086 Fix evicting files of file cache.
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7091 suppress deprecated builtins for boost string
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7092 add more collator tests for null-aware semi join
  tests/fullstack-test2/mpp/null_aware_semi_join.test
  tests/tidb-ci/new_collation_fullstack/function_collator.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7087 Default enable Delta Index cache for disaggregated read
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7051 Compaction for CheckpointDataFile
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore_fwd.h
  dbms/src/Storages/Page/Config.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/GCDefines.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_versioned_entries.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7080 Refactor cache policy for FAP
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/CheckpointInfo.h
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
  dbms/src/Storages/Transaction/FastAddPeerAsyncTasksImpl.h
  dbms/src/Storages/Transaction/FastAddPeerCache.cpp
  dbms/src/Storages/Transaction/FastAddPeerCache.h
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7081 Optimize null rows for null-aware semi join
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7094 Add disaggregated read duration breakdown metrics
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7095 share data_file_id when deserialize put entry
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_gc.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7096 Introduce DevContainers
  .devcontainer/.local_persist/gh/.gitignore
  .devcontainer/Dockerfile
  .devcontainer/Makefile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.vscode.yml
  .devcontainer/docker-compose.yml
  .env
  .github/licenserc.yml
  dbms/src/Server/CMakeLists.txt
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7098 Merge small files into one or more larger one before upload to S3
  dbms/src/IO/ReadHelpers.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/MergedFile.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/MemoryRandomAccessFile.h
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7099 Fix read when enable FAP
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/MockS3LockClient.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.h
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.h
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/Page/WriteBatchWrapperImpl.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeerCache.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7103 Fix deprecated warnings of clang-15
  dbms/src/Storages/S3/MockS3Client.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7104 rename JoinOtherConditions to JoinNonEqualConditions and move all non-equal contitions to JoinNonEqualConditions
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7105 Fix race condition for DisaggSnapshot
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7108 Remove from FileCache if local file not exists.
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7111 Retry when upload files failed.
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7116 Add a config flash.use_autoscaler_without_s3
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7118 Fix some issues on S3
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7125 *: fix unstable summary tests
  dbms/src/Flash/tests/gtest_execution_summary.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7129 Fix bug for dmfile is remove unexpectly
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-7.0

#7130 Fix bug for dmfile is remove unexpectly (release-7.0)
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, cherry-pick-approved

#7124 .*: Refine the checking of dag request
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/DAGRequest.cpp
  dbms/src/Flash/Coprocessor/DAGRequest.h
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Planner/ExecutorIdGenerator.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Statistics/ExecutionSummaryHelper.cpp
  dbms/src/Flash/Statistics/ExecutorStatistics.h
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.cpp
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7142 fix tsan in `StorageDeltaMerge::parsePushDownFilter`
  dbms/src/Debug/MockStorage.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7127 Move JoinPartition to a seperated file
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7153 add unified restore log for spill
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7151 Skip remote read and local rewrite when possible
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7149 Split checkpoint data files.
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7150 Avoid frequent S3 data rewrite
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7154 Decrease ps write latency
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7161 Storage: should seek before read
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, cherry-pick-approved

#7162 Show CallerIdentity when connect to S3 client
  contrib/aws-cmake/CMakeLists.txt
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7170 Split edits record of checkpoint manifest into multi-parts.
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7168 Fix S3GC is broken on AWS
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  dbms/src/Storages/Transaction/TMTContext.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-7.0

#7173 Add S3 metrics to Grafana.
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7093 Add more message for exception in RegionBlockReader::read
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-7.0

#7185 Fix exception thrown when reading from multiple partitions under S3 disagg
  dbms/src/Common/FailPoint.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask_fwd.h
  dbms/src/Storages/DeltaMerge/Remote/tests/gtest_rn_remote_read_task.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3WritableFile.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/TiDB/Etcd/Client.cpp
  dbms/src/TiDB/OwnerManager.cpp
  dbms/src/TiDB/tests/gtest_owner_manager.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-7.0

#7159 Storage: should seek before read
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockOutputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-7.0

#7182 Fix performance regression caused by local tunnel v2
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7178 Support ScanContext for Disaggregated Read
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7197 [release-6.1] Bump toolchain to nightly-2022-02-14
  libs/libsymbolization/rust-toolchain
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, cherry-pick-approved

#7200 Use the same rust-toolchain for all Rust sub-projects
  contrib/tiflash-proxy-cmake/CMakeLists.txt
  libs/libsymbolization/CMakeLists.txt
  libs/libsymbolization/rust-toolchain
  rust-toolchain
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7201 Change the default config for local tunnel
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none
