Repository pingcap/tiflash, pull requests merged in 2023-02, with the labels that each got.

#6712 fix: mitigate old docker for full stack test
  tests/docker/cluster.yaml
  tests/docker/cluster_disable_new_collation.yaml
  tests/docker/cluster_new_collation.yaml
  tests/docker/cluster_tidb_fail_point.yaml
  tests/docker/tiflash-dt.yaml
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6457 Doc: Support MVCC Bitmap Filter
  docs/design/2022-12-08-support-MVCC-bitmap-filter.md
  docs/design/images/2022-12-08-mvcc-bitmap-filter.png
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6709 Fix incorrect use of static.
  dbms/src/Storages/DeltaMerge/Segment.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6711 Move `exec_status` from `PipelineExec` to `Operator`
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.h
  dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalProjection.cpp
  dbms/src/Operators/BlockInputStreamSourceOp.cpp
  dbms/src/Operators/BlockInputStreamSourceOp.h
  dbms/src/Operators/ExpressionTransformOp.h
  dbms/src/Operators/FilterTransformOp.h
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/LimitTransformOp.h
  dbms/src/Operators/Operator.cpp
  dbms/src/Operators/Operator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6710 Fix a doomed assert in WaitCheckRegionReady
  dbms/src/Storages/Transaction/KVStore.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6714 Remove usage about `SquashingHashJoinBlockTransform` in `HashJoinProbeBlockInputStream`
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
Labels: type/enhancement, status/can-merge, status/LGT2, type/performance, release-note-none, size/M

#6707 Optimize cross join impl
  dbms/src/Interpreters/Join.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6722 fix the fail of the compilation of bench
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/mockExecutor.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6725 Fix hashJoinProb thread leak issue
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6687 POC: Reuse Delta Index
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetStorageReader.h
  dbms/src/Storages/DeltaMerge/File/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/Remote/DeltaIndexCache.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggregatedSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/Manager.cpp
  dbms/src/Storages/DeltaMerge/Remote/Manager.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
Labels: do-not-merge/release-note-label-needed, size/L

#6724 Fix incorrect string value when doing int_handle.toNext
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6729 Fix an exception thrown while reading from ColumnFileTiny after add column
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/WriteBatches.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/PageEntry.h
Labels: status/can-merge, status/LGT2, size/L, release-note, needs-cherry-pick-release-6.5

#6737 Fix gtest false negative case
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6704 Remove related code about single file mode in DMFile
  dbms/src/Common/FailPoint.cpp
  dbms/src/DataStreams/MarkInCompressedFile.h
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/DMChecksumConfig.cpp
  dbms/src/Storages/DeltaMerge/DMChecksumConfig.h
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockOutputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/StorageEngineType.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6589 Optimization schema memory utilization of ColumnFile in instance level
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V2.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6746 Use size of filtered column to reserve memory for filter when result_size_hint < 0
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnsCommon.cpp
  dbms/src/Columns/IColumn.h
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, release-note, size/M, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6745 fix the problem that offset in limit query for tiflash system tables doesn't take effect
  dbms/src/DataStreams/LimitBlockInputStream.cpp
  dbms/src/DataStreams/LimitBlockInputStream.h
  dbms/src/DataStreams/LimitTransformAction.cpp
  dbms/src/DataStreams/LimitTransformAction.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Storages/System/StorageSystemNumbers.cpp
Labels: status/can-merge, status/LGT2, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, needs-cherry-pick-release-5.2, size/L, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6744 Fix tsan fail in unit test `EventTestRunner.base`
  dbms/src/Common/Exception.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  tests/sanitize/tsan.suppression
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6748 fix unstable mpp_fail tests
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  tests/fullstack-test/mpp/mpp_fail.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6769 fix timezone test
  dbms/src/Functions/tests/gtest_from_unixtime.cpp
  dbms/src/Functions/tests/gtest_unix_timestamp.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6683 Add switch for disabling refined local tunnel
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6774 Fix new segment check in gcTrySegmentMergeDelta/gcTrySegmentMerge
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6662 least/greatest function for string
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsComparison.h
  dbms/src/Functions/FunctionsConversion.h
  dbms/src/Functions/LeastGreatest.h
  dbms/src/Functions/greatest.cpp
  dbms/src/Functions/least.cpp
  dbms/src/Functions/tests/gtest_least_greatest.cpp
  tests/fullstack-test/expr/least_greatest.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6736 fix tls ipv6 metric
  dbms/src/Server/MetricsPrometheus.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6780 Refine spiller
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6781 remove legacy code in RegionPersister
  dbms/src/Common/FailPoint.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6768 fix RegionKVStoreTest
  dbms/src/Debug/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/tests/gtest_mock_storage.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6785 Add LRU to LocalPageCache
  contrib/aws-cmake/CMakeLists.txt
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreNFS.cpp
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/LocalPageCache.h
  dbms/src/Storages/DeltaMerge/Remote/ObjectId.h
  dbms/src/Storages/DeltaMerge/Remote/RemoteReadTask.cpp
  dbms/src/Storages/Page/PageDefines.h
  dbms/src/Storages/Page/universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.h
Labels: do-not-merge/release-note-label-needed, size/XL

#6770 fix tsan fail in unit test `JoinExecutorTestRunner.MultiJoin`
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6788 Init aws SDK and enable aws internal http client
  contrib/aws-cmake/CMakeLists.txt
  dbms/CMakeLists.txt
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
Labels: size/XL, release-note-none

#6784 Refine the hostname backlist in `MetricsPrometheus`
  dbms/src/Server/MetricsPrometheus.cpp
  etc/config-template.toml
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6787 Add more information to the error message in MPPTunnel
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6471 fix the issue that decimal divide not round.
  dbms/src/Functions/divide.cpp
  dbms/src/Functions/tests/gtest_arithmetic_functions.cpp
  tests/fullstack-test/expr/decimal_divide.test
  tests/tidb-ci/fullstack-test-dt/issue_1425.test
Labels: status/can-merge, status/LGT2, size/XL, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6708 Refine the spill threshold for aggregation/sort, refine the memory usage calculation for aggregation
  dbms/src/Common/ThresholdUtils.h
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.h
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6799 fix(README) : Prepare Prerequisites on Arch Linux
  README.md
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6803 Add hstackBlocks for Block to join blocks by columns
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/SquashingHashJoinBlockTransform.cpp
  dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic_bitmap.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6796 add GeneratedColumnPlaceholderInputStream
  dbms/src/DataStreams/GeneratedColumnPlaceholderBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Storages/Transaction/TiDB.h
  tests/fullstack-test/expr/generated_index.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6814 Destroy dynamic thread pool in Server
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6793 Refine merge agg stream
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedBlockInputStream.cpp
  dbms/src/DataStreams/MergingAggregatedBlockInputStream.h
  dbms/src/DataStreams/MergingAndConvertingBlockInputStream.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6717 support storing all data in UniversalPageStorage
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/WriteBatches.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/PageIdTrait.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormat.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatch.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage_storage_pool.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/Storages/Page/WriteBatch.h
  dbms/src/Storages/Page/WriteBatchWrapper.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6773 feat(expr):support is_ipv4 and is_ipv6 expr to tiflash
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsIsIPAddr.cpp
  dbms/src/Functions/FunctionsIsIPAddr.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_is_ip_addr.cpp
  tests/fullstack-test/expr/is_ip_addr.test
Labels: status/can-merge, status/LGT2, size/XL, release-note

#6805 Pipeline: support topn
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.h
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Flash/tests/gtest_topn_executor.cpp
  dbms/src/Operators/TopNTransformOp.cpp
  dbms/src/Operators/TopNTransformOp.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6821 refine spill log
  dbms/src/Core/Spiller.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6802 fix the issue that the RU returned by the DataStreamExecutor was too large
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6790 Add insertManyFrom/insertDisjunctFrom/insertManyDefaults interface for IColumn
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_insertFrom.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6820 add support for auxiliary memory bound in mpmc_queue
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_mpmc_queue.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6810 Support `read(filter, true)` in `FilterBlockInputStream`
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/FilterBlockInputStream.h
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/DataStreams/FilterTransformAction.h
  dbms/src/DataStreams/tests/CMakeLists.txt
  dbms/src/DataStreams/tests/block_row_transforms.cpp
  dbms/src/DataStreams/tests/native_streams.cpp
  dbms/src/DataStreams/tests/tab_separated_streams.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Operators/FilterTransformOp.cpp
  dbms/src/Operators/FilterTransformOp.h
  tests/fullstack-test/mpp/bool_column_filter.test
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6840 Fix asan test failed
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage_storage_pool.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6842 bump openssl version to 1.1.1t in build image
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6830 Refine `GetResultSink` and use `QueryExecutor` for cop/batchCop
  dbms/src/Flash/Coprocessor/DAGBlockOutputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/DataStreamExecutor.h
  dbms/src/Flash/Executor/ExecutionResult.h
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/QueryExecutor.cpp
  dbms/src/Flash/Executor/QueryExecutor.h
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_status.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.h
  dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/tests/gtest_pipeline.cpp
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.cpp
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.h
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.cpp
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.h
  dbms/src/Flash/Statistics/ExecutorStatisticsBase.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Flash/executeQuery.h
  dbms/src/Flash/tests/bench_exchange.h
  dbms/src/Flash/tests/gtest_pipeline_interpreter.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Operators/BlockInputStreamSourceOp.h
  dbms/src/Operators/ExpressionTransformOp.h
  dbms/src/Operators/FilterTransformOp.h
  dbms/src/Operators/GetResultSinkOp.cpp
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/LimitTransformOp.h
  dbms/src/Operators/TopNTransformOp.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6838 fix proxy log search
  dbms/src/Flash/LogSearch.cpp
  dbms/src/Flash/tests/gtest_log_search.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#6428 Added support for ALTER TABLE t REORGANIZE PARTITION p INTO (..)
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/fullstack-test2/ddl/reorganize_partition.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6835 Introduce `ConcurrentIOQueue` for async exchange sender
  dbms/src/Common/ConcurrentIOQueue.h
  dbms/src/Common/MPMCQueue.h
  dbms/src/Common/tests/gtest_concurrent_io_queue.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6844 *: Refine some logging level
  dbms/src/Common/TiFlashException.h
  dbms/src/Common/tests/gtest_logger.cpp
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Flash/LogSearch.h
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/DeltaTree.ipp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/GCManager.cpp
  dbms/src/Storages/GCManager.h
  dbms/src/Storages/Page/V3/Blob/GCInfo.cpp
  dbms/src/Storages/Page/V3/Blob/GCInfo.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/GCDefines.h
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/PathCapacityMetrics.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/Transaction/BackgroundService.cpp
  dbms/src/Storages/Transaction/BackgroundService.h
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/SSTReader.h
  dbms/src/Storages/Transaction/TMTContext.cpp
  dbms/src/Storages/Transaction/TMTContext.h
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_table_info.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  libs/libcommon/include/common/logger_useful.h
  libs/libcommon/src/tests/gtest_logger.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none, needs-cherry-pick-release-6.5

#6870 Unify the url of submodule to https url
  .gitmodules
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6872 PageStorage: Fix unexpected dmfile removed after shutdown (cherry-pick #6558)
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.cpp
  dbms/src/Storages/Page/V3/PageDirectory/ExternalIdsByNamespace.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: status/can-merge, type/bug-fix, status/LGT2, size/XL, release-note, cherry-pick-approved

#6862 Refine `Spiller` to support append write
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/IColumn.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Core/SpillConfig.cpp
  dbms/src/Core/SpillConfig.h
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_block.cpp
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/copyData.cpp
  dbms/src/DataStreams/copyData.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/Settings.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6826 Merge small metadata files of DMFile
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Storages/DeltaMerge/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/FormatVersion.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6545 plan, executor: implement Expand operator for grouping sets
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/DataStreams/ExpressionBlockInputStream.cpp
  dbms/src/Debug/MockExecutor/ExpandBinder.cpp
  dbms/src/Debug/MockExecutor/ExpandBinder.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlock.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/collectOutputFieldTypes.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Plans/PhysicalExpand.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand.h
  dbms/src/Flash/Statistics/CommonExecutorImpl.h
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.cpp
  dbms/src/Flash/Statistics/traverseExecutors.cpp
  dbms/src/Flash/tests/gtest_expand_executor.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_pipeline_interpreter.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Interpreters/Expand.cpp
  dbms/src/Interpreters/Expand.h
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/tests/gtest_block_expand.cpp
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/executorSerializer.cpp
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/TestUtils/tests/gtest_mock_executors.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note

#6875 build: refactor cmake
  .gitignore
  cmake/print_include_directories.cmake
  dbms/CMakeLists.txt
  dbms/src/AggregateFunctions/CMakeLists.txt
  dbms/src/Client/CMakeLists.txt
  dbms/src/Common/CMakeLists.txt
  dbms/src/Common/Config/CMakeLists.txt
  dbms/src/Common/StringUtils/CMakeLists.txt
  dbms/src/Common/tests/CMakeLists.txt
  dbms/src/Core/tests/CMakeLists.txt
  dbms/src/DataStreams/tests/CMakeLists.txt
  dbms/src/Functions/CMakeLists.txt
  dbms/src/IO/tests/CMakeLists.txt
  dbms/src/Parsers/CMakeLists.txt
  dbms/src/Parsers/tests/CMakeLists.txt
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/config_tools.h.in
  dbms/src/Server/main.cpp
  dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/workload/CMakeLists.txt
  dbms/src/Storages/Page/V3/CMakeLists.txt
  dbms/src/Storages/Page/tools/PageCtl/CMakeLists.txt
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/workload/CMakeLists.txt
  dbms/src/Storages/Page/workload/PageStorageInMemoryCapacity.h
  dbms/src/Storages/System/CMakeLists.txt
  dbms/src/Storages/Transaction/tests/CMakeLists.txt
  dbms/src/Storages/Transaction/tests/bench_region_block_reader.cpp
  dbms/src/TableFunctions/CMakeLists.txt
  dbms/src/TestUtils/CMakeLists.txt
  libs/libdaemon/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6833 Cloud POC: support remote read
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/Page/UniversalWriteBatch.h
  dbms/src/Storages/Page/V2/PageFile.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesBuilder.cpp
  dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.cpp
  dbms/src/Storages/Page/V3/Remote/CheckpointPageManager.h
  dbms/src/Storages/Page/V3/Remote/Proto/manifest_file.proto
  dbms/src/Storages/Page/V3/Remote/RemoteDataInfo.h
  dbms/src/Storages/Page/V3/Remote/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/WAL/serialize.cpp
  dbms/src/Storages/Page/WriteBatch.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/universal/RemotePageReader.cpp
  dbms/src/Storages/Page/universal/RemotePageReader.h
  dbms/src/Storages/Page/universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/universal/UniversalPageStorage.h
  dbms/src/Storages/Page/universal/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/FastAddPeer.h
Labels: size/XXL, release-note-none

#6867 doc: Add stale read design doc
  docs/design/2023-02-21-tiflash-supports-stale-read.md
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6878 Add S3 key utils
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3Filename.cpp
  dbms/src/Storages/S3/S3Filename.h
  dbms/src/Storages/S3/tests/gtest_s3filename.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/Types.h
  libs/libcommon/include/common/StringRef.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6886 Fix broken build process with cmake option `NO_SSE42_OR_HIGHER`
  README.md
  cmake/cpu_features.cmake
  dbms/src/Columns/ColumnsCommon.cpp
  dbms/src/Storages/DeltaMerge/DeltaTree.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6718 Storage: minor refine of bitmap and add more tests
  dbms/src/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/RowKeyFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6891 avoid spill empty block in agg
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6885 Refine storage read thread count.
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.h
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#6889 fix unstable ut.
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#6892 Add S3 config and utils.
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#6881 Change the implementation of shared_block_schemas with LRUCache
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSchema.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XL, release-note-none, needs-cherry-pick-release-6.5

#6896 build: refactor cmake
  contrib/abseil-cpp-cmake/CMakeLists.txt
  dbms/CMakeLists.txt
  dbms/src/AggregateFunctions/CMakeLists.txt
  dbms/src/Core/CMakeLists.txt
  dbms/src/Core/tests/CMakeLists.txt
  dbms/src/Core/tests/exception.cpp
  dbms/src/Core/tests/field.cpp
  dbms/src/Core/tests/move_field.cpp
  dbms/src/Core/tests/rvo_test.cpp
  dbms/src/Core/tests/string_pool.cpp
  dbms/src/Core/tests/string_ref_hash.cpp
  dbms/src/DataStreams/CMakeLists.txt
  dbms/src/DataStreams/tests/CMakeLists.txt
  dbms/src/DataTypes/CMakeLists.txt
  dbms/src/DataTypes/tests/CMakeLists.txt
  dbms/src/DataTypes/tests/data_type_string.cpp
  dbms/src/DataTypes/tests/data_types_number_fixed.cpp
  dbms/src/Encryption/CMakeLists.txt
  dbms/src/Encryption/tests/CMakeLists.txt
  dbms/src/Flash/CMakeLists.txt
  dbms/src/Flash/Coprocessor/tests/CMakeLists.txt
  dbms/src/Flash/Executor/tests/CMakeLists.txt
  dbms/src/Flash/Pipeline/Exec/tests/CMakeLists.txt
  dbms/src/Flash/Pipeline/Schedule/Events/tests/CMakeLists.txt
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/CMakeLists.txt
  dbms/src/Flash/Pipeline/Schedule/tests/CMakeLists.txt
  dbms/src/Flash/Planner/tests/CMakeLists.txt
  dbms/src/Flash/tests/CMakeLists.txt
  dbms/src/Functions/CMakeLists.txt
  dbms/src/Functions/tests/CMakeLists.txt
  dbms/src/Functions/tests/number_traits.cpp
  dbms/src/Interpreters/CMakeLists.txt
  dbms/src/Server/CMakeLists.txt
  dbms/src/Storages/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/workload/CMakeLists.txt
  dbms/src/Storages/Page/CMakeLists.txt
  dbms/src/Storages/Page/tools/PageCtl/CMakeLists.txt
  dbms/src/TestUtils/CMakeLists.txt
  dbms/src/WindowFunctions/tests/CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6912 use RepeatedPtrField<tipb::Expr> instead of vector<tipb::Expr *>
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryInfo.h
  dbms/src/Flash/Coprocessor/FilterConditions.cpp
  dbms/src/Flash/Coprocessor/FilterConditions.h
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6911 build: remove boost::{fiber,context} depends
  contrib/boost-cmake/CMakeLists.txt
  contrib/boost-cmake/context.cmake
  contrib/boost-cmake/fiber.cmake
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6900 Add checkpoint utilities
  dbms/CMakeLists.txt
  dbms/src/Storages/Page/CMakeLists.txt
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileReader.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileReader.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.h
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/CMakeLists.txt
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/common.proto
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/data_file.proto
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/manifest_file.proto
  dbms/src/Storages/Page/V3/CheckpointFile/ProtoHelper.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/ProtoHelper.h
  dbms/src/Storages/Page/V3/CheckpointFile/fwd.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_proto_helper.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.cpp
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/WriteBatchImpl.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6854 Pipeline: support async exchange sender/receiver
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.cpp
  dbms/src/Debug/MockExecutor/ExchangeReceiverBinder.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.h
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.h
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/Operator.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/OperatorHelper.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  dbms/src/TestUtils/mockExecutor.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#6918 Retry establish when regions epoch does not match
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/DisaggreatedTaskHandler.cpp
  dbms/src/Flash/DisaggreatedTaskHandler.h
  dbms/src/Flash/Disaggregated/EstablishDisaggregatedTask.cpp
  dbms/src/Flash/Disaggregated/EstablishDisaggregatedTask.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Storages/StorageDisaggregated.cpp
  dbms/src/Storages/StorageDisaggregated.h
Labels: status/LGT1, do-not-merge/release-note-label-needed, size/XL
