Repository pingcap/tiflash, pull requests merged in 2023-07, with the labels that each got.

#7722 Pipeline: support io priority queue
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/FIFOTaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/MultiLevelFeedbackQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/TaskQueueType.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_fifo.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_io_priority.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_mlfq.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/IOEventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/LoadBucketTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolImpl.h
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
  dbms/src/Operators/AggregateBuildSinkOp.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.cpp
  dbms/src/Operators/LocalAggregateTransform.cpp
  dbms/src/Operators/MergeSortTransformOp.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/OperatorHelper.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentSourceOp.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7683 Make packet size of fetching page small to reduce memory comsumption
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Encryption/PosixWritableFile.cpp
  dbms/src/Encryption/PosixWriteReadableFile.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/IO/ChecksumBuffer.h
  dbms/src/IO/IOThreadPools.h
  dbms/src/IO/WriteBufferAIO.cpp
  dbms/src/IO/WriteBufferFromFileDescriptor.cpp
  dbms/src/IO/WriteBufferFromWritableFile.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#7731 Donot reserve string column size and remove uncertain size reservation
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/S, approved, lgtm

#7730 Neglect orphan key error if we are from a restart
  dbms/src/Storages/Transaction/RegionData.cpp
Labels: release-note-none, size/S, approved, lgtm

#7732 ReportStatus to coordinator only when report info is needed
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7698 Support local rf for pipeline
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/RuntimeFilterMgr.h
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_status.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_executors_with_dm.cpp
  dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  tests/fullstack-test/mpp/runtime_filter.test
Labels: size/XL, release-note-none, approved, lgtm

#7723 Pipeline: optimize part scan
  dbms/src/DataStreams/MultiplexInputStream.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Operators/ConcatSourceOp.h
  dbms/src/Operators/tests/gtest_concat_source.cpp
Labels: size/XL, release-note-none, approved, lgtm

#7742 .*: Pre refine for supporting join spill in pipeline
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Core/SpillConfig.cpp
  dbms/src/Core/SpillConfig.h
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/ConstantsBlockInputStream.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/NullBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/IOPriorityQueue.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_mlfq.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/IOEventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/MergeSortTransformOp.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7769 fix tidy in dbms/src/IO/BufferWithOwnMemory.h
  dbms/src/IO/BufferWithOwnMemory.h
Labels: size/XS, release-note-none, approved, lgtm

#7770 fix tidy in dbms/src/IO/CompressedReadBuffer.cpp
  dbms/src/IO/CompressedReadBuffer.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7775 Make concurrency of RNWorkers configurable
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/M, approved, lgtm

#7753 add config to disable upload page data when do checkpoint
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
Labels: release-note-none, size/M, approved, lgtm

#7767 Add flag for ingest range check
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
Labels: release-note-none, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7785 Check CPU cores in CPUAffinityManagerTest (#7473) (#7476)
  dbms/src/Common/tests/gtest_cpu_affinity_manager.cpp
Labels: release-note-none, size/S, approved, lgtm, type/cherry-pick-for-release-6.5-20230710-v6.5.2

#7783 Decrease write latency in PageStorage
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/LogFile/LogReader.h
  dbms/src/Storages/Page/V3/LogFile/LogWriter.cpp
  dbms/src/Storages/Page/V3/LogFile/LogWriter.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageEntriesEdit.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm, type/cherry-pick-for-release-6.5-20230710-v6.5.2

#7789 Fix a typo in ingest range check
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#7637 Improve error message for tidb TableScan schema check
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp
  tests/fullstack-test/mpp/issue_6808.test
Labels: release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7794 [Bug] Fix the empty values when runtime filter is LOCAL mode
  dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
  dbms/src/Storages/DeltaMerge/Filter/In.h
Labels: release-note-none, size/M, approved, lgtm

#7802 enable parallel apply tests
  tests/fullstack-test/mpp/apply.test
Labels: release-note-none, size/S, approved, lgtm

#7778 .*: spilt profile info from `Interpreters::Join` and implement `PipelineExecutor::getRuntimeStatistics`
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Statistics/JoinImpl.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: release-note-none, size/M, approved, lgtm

#7801 Fix wrong checkpoint info after restart
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageEntriesEdit.cpp
  dbms/src/Storages/Page/V3/PageEntryCheckpointInfo.h
Labels: release-note-none, size/M, approved, lgtm

#7779 PageStorage: remove wal files according to its max sequence when dump snapshot
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: size/XL, release-note-none, approved, lgtm

#7808 Add back reservation in join probe
  dbms/src/Interpreters/Join.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7724 Refactor async grpc part of ExchangeReceiver
  dbms/src/Common/GRPCKickTag.h
  dbms/src/Common/GRPCQueue.h
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Common/tests/gtest_grpc_queue.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCCompletionQueuePool.cpp
  dbms/src/Flash/Mpp/GRPCCompletionQueuePool.h
  dbms/src/Flash/Mpp/GRPCReceiveQueue.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceivedMessage.cpp
  dbms/src/Flash/Mpp/ReceivedMessage.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/ReceiverChannelBase.cpp
  dbms/src/Flash/Mpp/ReceiverChannelBase.h
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/TrackedMppDataPacket.h
  dbms/src/Flash/Mpp/tests/gtest_grpc_send_queue.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/Mpp/tests/gtest_received_message_queue.cpp
  dbms/src/Flash/tests/bench_exchange.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7811 Some refines
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: release-note-none, size/M, approved, lgtm

#7719 store raft data in dedicated blob file
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/Page/Config.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/V3/Blob/BlobConfig.h
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/CheckpointFile/tests/gtest_file_read_write.cpp
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageType.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Transaction/ProxyFFI.cpp
  dbms/src/Storages/Transaction/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#7815 TiFlash accept lossless data type change for mydatetime
  dbms/src/DataTypes/DataTypeMyDateTime.cpp
  dbms/src/DataTypes/isSupportedDataTypeCast.cpp
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_convert_column.cpp
  tests/fullstack-test2/ddl/alter_column_datetime.test
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#7813 TiFlash accept lossless data type change for mydatetime(release-6.5)
  dbms/src/DataTypes/DataTypeMyDateTime.cpp
  dbms/src/DataTypes/isSupportedDataTypeCast.cpp
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_convert_column.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/fullstack-test2/ddl/alter_column_datetime.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#7816 Fix deadlock in DAGStorageInterpreter::getAndLockStorages
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
Labels: release-note-none, size/S, approved, lgtm

#7806 Limiting max block bytes
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: release-note-none, size/L, approved, lgtm

#7551 support fetch raft log num of each region for page-ctl
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: release-note-none, size/L, approved, lgtm

#7825 Some code refine on storage layer and Grafana panels
  dbms/src/Core/Defines.h
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/Transaction/PDTiKVClient.h
  dbms/src/Storages/Transaction/TiDB.cpp
  dbms/src/Storages/Transaction/tests/gtest_table_info.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#7824 fix potential deadlock in the process of shutdown
  dbms/src/Storages/BackgroundProcessingPool.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7828 Remove useless files
  dbms/src/DataStreams/DebugPrintBlockInputStream.h
  dbms/src/DataStreams/StringStreamBlockInputStream.h
  dbms/src/DataStreams/VersionFilterBlockInputStream.cpp
  dbms/src/DataStreams/VersionFilterBlockInputStream.h
  dbms/src/DataStreams/dedupUtils.h
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Storages/MutableSupport.h
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
Labels: size/XXL, release-note-none, approved, lgtm

#7827 Fix clipBlockRows when stable is null.
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: release-note-none, size/M, approved, lgtm

#7819 More refine for join spill
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/DataStreams/HashJoinProbeExec.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/HashJoinBuildSink .cpp
  dbms/src/Operators/HashJoinBuildSink.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
  dbms/src/Operators/HashJoinProbeTransformOp.h
Labels: size/XXL, release-note-none, approved, lgtm

#7771 Merge small files in dmfiles
  dbms/src/Encryption/CompressedReadBufferFromFileProvider.cpp
  dbms/src/Encryption/CompressedReadBufferFromFileProvider.h
  dbms/src/Encryption/createReadBufferFromFileBaseByFileProvider.cpp
  dbms/src/Encryption/createReadBufferFromFileBaseByFileProvider.h
  dbms/src/Encryption/createWriteBufferFromFileBaseByFileProvider.cpp
  dbms/src/Encryption/createWriteBufferFromFileBaseByFileProvider.h
  dbms/src/IO/WriteBufferFromWritableFile.h
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/CLIService.h
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: size/XXL, release-note, approved, lgtm

#7814 TiFlash accept lossless data type change for mydatetime(release-7.1)
  dbms/src/DataTypes/DataTypeMyDateTime.cpp
  dbms/src/DataTypes/isSupportedDataTypeCast.cpp
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_convert_column.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/fullstack-test2/ddl/alter_column_datetime.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#7842 Handle orphan default keys
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
Labels: release-note-none, size/S, approved, lgtm

#7829 rollup: fix tpcds rollup query errors as field type mis-match
  .github/licenserc.yml
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand2.cpp
  tests/fullstack-test/mpp/rollup_tpcds.test
  tests/fullstack-test/tpcds_util/tpcds.sql
  tests/fullstack-test/tpcds_util/tpcds_clean.sql
  tests/fullstack-test/tpcds_util/tpcds_q18.sql
  tests/fullstack-test/tpcds_util/tpcds_q27.sql
  tests/fullstack-test/tpcds_util/tpcds_q5.sql
  tests/fullstack-test/tpcds_util/tpcds_q67.sql
  tests/fullstack-test/tpcds_util/tpcds_q80.sql
Labels: size/XXL, release-note, approved, lgtm

#7843 Align logging for region_id
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/DecodingStorageSchemaSnapshot.h
  dbms/src/Storages/Transaction/FastAddPeer.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/LockException.h
  dbms/src/Storages/Transaction/PartitionStreams.cpp
  dbms/src/Storages/Transaction/ProxyFFIStatusService.cpp
  dbms/src/Storages/Transaction/ReadIndexWorker.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/RegionBlockReader.cpp
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionState.cpp
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/RegionsRangeIndex.cpp
  dbms/src/Storages/Transaction/tests/RowCodecTestUtils.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_sync_status.cpp
  tests/delta-merge-test/raft/region_merge.test
  tests/delta-merge-test/raft/region_merge_common_handle.test
  tests/delta-merge-test/raft/snapshot.test
  tests/delta-merge-test/raft/txn_mock/merge_rollback.test
  tests/delta-merge-test/raft/txn_mock/snapshot_no_overlap.test
  tests/delta-merge-test/raft/txn_mock/split.test
  tests/delta-merge-test/raft/txn_mock/split_merge_split.test
Labels: size/XL, release-note-none, approved, lgtm

#7850 Add more message for ingest range check
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#7847 Fix the logical when multi threads in create table
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7845 Fix a invalid failpoint `random_receiver_async_msg_push_failure_failpoint`
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
Labels: size/XS, release-note-none, approved, lgtm

#7856 Remove more dead codes
  dbms/src/Debug/dbgFuncRegion.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Transaction/tests/kvstore_helper.h
Labels: release-note-none, size/L, approved, lgtm

#7861 Fix tiflash crash in `ThreadedWorker`
  dbms/src/Common/ThreadedWorker.h
  dbms/src/Common/tests/gtest_threaded_worker.cpp
Labels: release-note-none, size/M, approved, lgtm

#7859 Fix `DynamicThreadPool` may never be destructed, causing tiflash node to fail to exit normally
  dbms/src/Common/DynamicThreadPool.cpp
  dbms/src/Common/DynamicThreadPool.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/tests/gtest_dynamic_thread_pool.cpp
  dbms/src/Core/tests/gtest_spiller.cpp
Labels: release-note-none, size/M, approved, lgtm

#7866 Avoid meanless runtime filter wait when filter failed
  dbms/src/DataStreams/RuntimeFilter.cpp
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm
