Repository pingcap/tiflash, pull requests merged in 2023-04, with the labels that each got.

#7211 Split `FunctionsRegexp.h`
  dbms/src/Functions/FunctionsRegexp.h
  dbms/src/Functions/FunctionsRegexpCommon.cpp
  dbms/src/Functions/FunctionsRegexpCommon.h
  dbms/src/Functions/FunctionsRegexpInstr.cpp
  dbms/src/Functions/FunctionsRegexpInstr.h
  dbms/src/Functions/FunctionsRegexpLike.cpp
  dbms/src/Functions/FunctionsRegexpLike.h
  dbms/src/Functions/FunctionsRegexpReplace.cpp
  dbms/src/Functions/FunctionsRegexpReplace.h
  dbms/src/Functions/FunctionsRegexpSubstr.cpp
  dbms/src/Functions/FunctionsRegexpSubstr.h
  dbms/src/Functions/FunctionsRegexpUndef.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_regexp_instr.cpp
  dbms/src/Functions/tests/gtest_regexp_like.cpp
  dbms/src/Functions/tests/gtest_regexp_replace.cpp
  dbms/src/Functions/tests/gtest_regexp_substr.cpp
  dbms/src/Functions/tests/regexp_test_util.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7215 change metrics of schema of column files
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7214 Compatible new field in write/lock cf with TiKV
  dbms/src/Storages/Transaction/RegionCFDataBase.cpp
  dbms/src/Storages/Transaction/TiKVRecordFormat.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.5

#7175 Pipeline: refine result handler for batch cop
  dbms/src/Common/PtrHolder.h
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.h
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/QueryExecutor.h
  dbms/src/Flash/Executor/ResultQueue.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.cpp
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.h
  dbms/src/Operators/GetResultSinkOp.cpp
  dbms/src/Operators/GetResultSinkOp.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#6979 Use thread pool to optimize loadMetadata and initStores in tiflash starts
  dbms/src/Common/UniThreadPool.h
  dbms/src/Databases/DatabaseMemory.cpp
  dbms/src/Databases/DatabaseMemory.h
  dbms/src/Databases/DatabaseOrdinary.cpp
  dbms/src/Databases/DatabaseOrdinary.h
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabaseTiFlash.h
  dbms/src/Databases/DatabasesCommon.cpp
  dbms/src/Databases/DatabasesCommon.h
  dbms/src/Databases/IDatabase.h
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/IO/IOThreadPools.h
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/BgStorageInit.cpp
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note

#7195 Pipeline: support io task thread pool
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPoolImpl.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/tests/gtest_task_scheduler.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Operators/Operator.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/OperatorHelper.cpp
  dbms/src/Server/Server.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7223 fix potential deadlock in `CreatingSetBlockInputStream`
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-6.4, needs-cherry-pick-release-7.0

#7244 .*: fix bug introduced by https://github.com/pingcap/tiflash/pull/7175
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7247 Fix S3 file's seek operation and retry when connection reset by peer
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
  dbms/src/Storages/S3/PocoHTTPClient.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7228 Fix data race in join when `Join::cancel()` is called
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7246 Improve metrics for BR import
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7248 Metrics of S3
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/S3/S3Common.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7249 Fix metrics of FileCache used size.
  dbms/src/Storages/S3/FileCache.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7180 Support thread pool for restore multi segments for one table in tiflash restart
  dbms/src/Server/BgStorageInit.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: status/can-merge, status/LGT2, size/L, release-note

#7152 Move maps to join partition
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/DataStreams/NonJoinedBlockInputStream.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinHashTable.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7253 Region retry for partitioned table in disaggrgated read
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7257 Minor refine of join
  dbms/src/Columns/ColumnUtils.cpp
  dbms/src/Columns/ColumnUtils.h
  dbms/src/DataStreams/NonJoinedBlockInputStream.cpp
  dbms/src/Interpreters/Expand.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinHashMap.cpp
  dbms/src/Interpreters/JoinHashMap.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7174 Add status metrics, grafana panels about S3 GC
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/Page/PageConstants.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPDataFileStat.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPDumpStat.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPDumpStat.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/S3/PocoHTTPClient.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3GCManager.cpp
  dbms/src/Storages/S3/S3GCManager.h
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7156 Refine join probe
  dbms/src/Common/PtrHolder.h
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/DataStreams/HashJoinProbeExec.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7260 add process metrics(cpu/mem) for disagg-compute mode
  dbms/CMakeLists.txt
  dbms/src/Common/ProcessCollector.cpp
  dbms/src/Common/ProcessCollector.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Server/MetricsPrometheus.cpp
  libs/CMakeLists.txt
  libs/libprocess_metrics/CMakeLists.txt
  libs/libprocess_metrics/Cargo.lock
  libs/libprocess_metrics/Cargo.toml
  libs/libprocess_metrics/include/ProcessMetrics/ProcessMetrics.h
  libs/libprocess_metrics/src/lib.rs
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7274 build process_metrics/symbolization/tiflash-proxy sequentially
  CMakeLists.txt
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7255 test: add read system table test
  tests/fullstack-test/system-table/read_system_table.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7263 Support duplicated key in KVStore when ingesting
  dbms/src/Storages/DeltaMerge/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionCFDataBase.cpp
  dbms/src/Storages/Transaction/RegionCFDataBase.h
  dbms/src/Storages/Transaction/RegionData.cpp
  dbms/src/Storages/Transaction/RegionData.h
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7283 fix `columns_to_read` contains `_tidb_rowid`
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7216 Pipeline: support spill for local sort
  dbms/src/Core/CachedSpillHandler.cpp
  dbms/src/Core/CachedSpillHandler.h
  dbms/src/Core/SpillConfig.h
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Operators/LocalSortTransformOp.cpp
  dbms/src/Operators/LocalSortTransformOp.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7281 *: fix exception when no tcp and http server created
  dbms/src/Server/Server.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7278 fix mac build for process_metrics
  libs/libprocess_metrics/src/lib.rs
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7117 Pipeline: add metrics for scheduler and task
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPoolImpl.h
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPoolMetrics.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPoolMetrics.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7230 Support page ctl tool for unips
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/tools/PageCtl/MainEntry.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7269 Make devcontainer work in multi-user env
  .devcontainer/.local_persist/gh/.gitignore
  .devcontainer/Dockerfile
  .devcontainer/Makefile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.vscode.yml
  .devcontainer/docker-compose.yml
  .env
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7285 Refine log level for compute layer
  dbms/src/Core/SpillHandler.cpp
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/executeQuery.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7268 merge join result block if needed
  dbms/src/DataStreams/SquashingHashJoinBlockTransform.cpp
  dbms/src/DataStreams/SquashingHashJoinBlockTransform.h
  dbms/src/DataStreams/tests/gtest_squashing_hash_join_transform.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7291 refine code to avoid redundant calculation when join probe split happens
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7288 Add metric to count the number of cases where memory exceeds quota
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Common/tests/gtest_memtracker.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7298 Refine establish log
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/FlashService.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7293 Pipeline: support insert event
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Operators/AggregateConvergentSourceOp.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.cpp
  dbms/src/Operators/LocalSortTransformOp.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7267 Support RightSemi/RightAnti Join
  dbms/src/Core/Block.cpp
  dbms/src/Core/NamesAndTypes.h
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.h
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Coprocessor/tests/gtest_join_get_kind_and_build_index.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinHashMap.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Parsers/ASTTablesInSelectQuery.h
  dbms/src/TestUtils/mockExecutor.cpp
  dbms/src/TestUtils/mockExecutor.h
  tests/fullstack-test/mpp/right_semi_family_join.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7305 *: fix read system table without key when tls is enable
  dbms/src/Flash/FlashService.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7315 Support using podman to replace docker in some build scripts
  release-centos7-llvm/Makefile
  release-centos7-llvm/env/Makefile
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7319 Rename left to leftouter, right to rightouter for join kind enum
  dbms/src/DataStreams/HashJoinBuildBlockInputStream.cpp
  dbms/src/Debug/MockExecutor/JoinBinder.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Coprocessor/tests/gtest_join_get_kind_and_build_index.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinUtils.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
  dbms/src/Parsers/ASTTablesInSelectQuery.cpp
  dbms/src/Parsers/ASTTablesInSelectQuery.h
  dbms/src/Parsers/ParserTablesInSelectQuery.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7313 Storage: refine some code in lm
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Coprocessor/DAGQueryInfo.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7208 Support monitor store size on S3
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/MetricsPrometheus.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/PathCapacityMetrics.h
  dbms/src/Storages/PathPool.cpp
  dbms/src/Storages/PathPool.h
  metrics/grafana/tiflash_summary.json
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7323 Refine remote cache capacity.
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/PathCapacityMetrics.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7317 Clean remaining non_joined code and tests
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.h
  dbms/src/DataStreams/HashJoinProbeExec.cpp
  dbms/src/DataStreams/HashJoinProbeExec.h
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7220 Pipeline: support spill for fine grained aggregation
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationConvergent.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/BucketInput.cpp
  dbms/src/Operators/BucketInput.h
  dbms/src/Operators/LocalAggregateRestorer.cpp
  dbms/src/Operators/LocalAggregateRestorer.h
  dbms/src/Operators/LocalAggregateTransform.cpp
  dbms/src/Operators/LocalAggregateTransform.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7321 Add more cross join tests, refine `CrossJoinAdder`
  dbms/src/Debug/MockExecutor/JoinBinder.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7330 fix build fail
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  tests/tidb-ci/fullstack-test-dt/issue_1425.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7326 Check read content length of S3 file.
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-7.1

#7339 Fix build under release mode
  dbms/src/Functions/FunctionsGrouping.h
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7333 Pipeline: support join without spill
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.h
  dbms/src/Flash/Planner/Plans/PhysicalJoinProbe.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinProbe.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Flash/tests/gtest_join.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.out
  dbms/src/Flash/tests/gtest_spill_join.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/HashJoinBuildSink .cpp
  dbms/src/Operators/HashJoinBuildSink.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
  dbms/src/Operators/HashJoinProbeTransformOp.h
  dbms/src/TestUtils/ExecutorTestUtils.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7343 Refine assert in Pipeline Model
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExecBuilder.cpp
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/PipelineBuilder.h
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/FineGrainedPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Planner/FinalizeHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlanHelper.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/PhysicalPlanVisitor.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationConvergent.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindow.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindowSort.cpp
  dbms/src/Flash/Planner/optimize.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7335 Fix large write cause tiflash crash
  dbms/src/Common/FailPoint.cpp
  dbms/src/IO/MemoryReadWriteBuffer.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#7350 truncate should always be treated as warning in cast decimal as decimal
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#7322 Refact getJoinKindAndBuildSideIndex function
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_join_get_kind_and_build_index.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7356 storage: Fix UAFs in PageStorage
  dbms/src/Storages/Page/V3/PageDirectory.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-7.1

#7345 Fix large write cause tiflash crash (release-6.5)
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/FailPoint.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/IO/MemoryReadWriteBuffer.cpp
  dbms/src/Storages/Page/V3/Blob/BlobStat.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
Labels: status/can-merge, status/LGT2, size/XXL, release-note, cherry-pick-approved

#7353 *: fix asan in `StorageDeltaMerge::parsePushDownFilter` and `FilterParserTest`
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7347 Pipeline: Fix crash for `random_pipeline_model_task_construct_failpoint`
  dbms/src/Flash/Executor/DataStreamExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorStatus.cpp
  dbms/src/Flash/Executor/PipelineExecutorStatus.h
  dbms/src/Flash/Executor/ResultHandler.h
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_status.cpp
  dbms/src/Flash/Pipeline/Exec/tests/gtest_simple_operator.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/Events/FineGrainedPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/FineGrainedPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/PlainPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
Labels: status/can-merge, status/LGT2, size/XL, release-note-none

#7368 tsan: fix data race in `MemoryTracker::setDescription` and `MemoryTracker::logPeakMemoryUsage`
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
Labels: status/can-merge, status/LGT2, release-note-none, size/S

#7349 test: add decimal test back
  tests/tidb-ci/fullstack-test-dt/issue_1425.test
Labels: status/can-merge, status/LGT2, size/XS, release-note-none, needs-cherry-pick-release-7.1

#7360 storage: Fix counter race in disaggregated mode
  dbms/src/Flash/Disaggregated/RNPageReceiver.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-7.1

#7363 Retry when 'Resource temporarily unavailable'
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M, needs-cherry-pick-release-7.1

#7374 Add ft for `ilike` function
  tests/fullstack-test/expr/ilike_pushdown.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7387 [cherry-pick 7386] fix lm query fail when there are generated columns
  dbms/src/Storages/StorageDeltaMerge.cpp
  tests/fullstack-test/mpp/late_materialization_generate_column.test
Labels: status/can-merge, status/LGT2, release-note-none, size/M, cherry-pick-approved

#7344 Support right outer join with other conditions
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/JoinUtils.h
  tests/fullstack-test/mpp/right_join.test
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7389 Fix unit test `ComputeServerRunner.*` tsan fail
  dbms/src/Common/BackgroundTask.cpp
  dbms/src/Common/BackgroundTask.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  tests/run-gtest.sh
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7392 fix unstable test `WriteLimiterTest.Rate`
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
Labels: status/can-merge, status/LGT2, size/XS, release-note-none

#7386 fix lm query fail when there are generated columns
  dbms/src/Storages/StorageDeltaMerge.cpp
  tests/fullstack-test/mpp/late_materialization_generate_column.test
Labels: status/can-merge, status/LGT2, release-note-none, size/L, needs-cherry-pick-release-7.1

#7398 fix crash on `SharedAggregateRestorer::tryLoadBucketData`
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/SpilledBucketInput.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#7401 refine spill failpoint and `SharedSpilledBucketDataLoader`
  dbms/src/Core/Spiller.cpp
  dbms/src/DataStreams/SpilledFilesInputStream.cpp
  dbms/src/Operators/AggregateRestoreSourceOp.cpp
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/SharedAggregateRestorer.h
Labels: status/can-merge, status/LGT2, release-note-none, size/M

#6811 Remove reactor threads in ExchangeReceiver
  dbms/src/Common/ConcurrentIOQueue.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/dbgQueryExecutor.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/AsyncRequestHandler.h
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/GRPCReceiveQueue.h
  dbms/src/Flash/Mpp/GRPCReceiverContext.cpp
  dbms/src/Flash/Mpp/GRPCReceiverContext.h
  dbms/src/Flash/Mpp/GRPCSendQueue.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceiverChannelBase.cpp
  dbms/src/Flash/Mpp/ReceiverChannelBase.h
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelTryWriter.h
  dbms/src/Flash/Mpp/ReceiverChannelWriter.cpp
  dbms/src/Flash/Mpp/ReceiverChannelWriter.h
  dbms/src/Flash/Mpp/tests/gtest_grpc_send_queue.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/StorageDisaggregated.cpp
Labels: status/can-merge, status/LGT2, size/XXL, release-note-none

#7406 refine some codes for pipeline
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Event.h
  dbms/src/Flash/Pipeline/Schedule/TaskScheduler.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/AggregateFinalSpillTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/WaitReactor.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L

#7402 Integrate some functions in KVStore and rename them to what they actually do
  dbms/src/Debug/dbgFuncRegion.cpp
  dbms/src/Storages/Transaction/ApplySnapshot.cpp
  dbms/src/Storages/Transaction/KVStore.cpp
  dbms/src/Storages/Transaction/KVStore.h
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  dbms/src/Storages/Transaction/tests/gtest_new_kvstore.cpp
Labels: status/can-merge, status/LGT2, release-note-none, size/L
