Repository pingcap/tiflash, pull requests merged in 2023-12, with the labels that each got.

#8445 Avoid out of bound InsertRangeFrom exception in MergingSortedBlockInputStream
  dbms/src/DataStreams/MergingSortedBlockInputStream.cpp
Labels: release-note-none, size/S, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8465 Add try/catch protection for ~LocalAdmissionController
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
Labels: release-note-none, size/S, approved, lgtm

#8446 Raft: Add identifier to logger when wait index happens
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8473 Raft: Add identifier to logger when wait index happens(release-7.1)
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/Transaction/LearnerRead.cpp
  dbms/src/Storages/Transaction/Region.cpp
  dbms/src/Storages/Transaction/Region.h
  dbms/src/Storages/Transaction/RegionMeta.cpp
  dbms/src/Storages/Transaction/RegionMeta.h
  dbms/src/Storages/Transaction/tests/gtest_kvstore.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#8424 ddl: Support `FLASHBACK DATABASE`
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabaseTiFlash.h
  dbms/src/Databases/IDatabase.h
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  tests/fullstack-test2/ddl/alter_drop_database.test
  tests/fullstack-test2/ddl/flashback/flashback_database.test
  tests/fullstack-test2/ddl/partitions/reorganize_partition.test
Labels: size/XL, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8449 ddl: Support `FLASHBACK DATABASE` (release-7.1)
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/Databases/DatabaseTiFlash.h
  dbms/src/Databases/IDatabase.h
  dbms/src/Databases/test/gtest_database.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/flashback_database.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8487 ddl: Fix unstable FLASHBACK DATABASE test (release-6.5)
  tests/fullstack-test2/ddl/flashback_database.test
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#8489 Support only null type for json_extract
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_json_extract.cpp
  tests/fullstack-test/expr/json_extract.test
Labels: release-note-none, size/M, approved, lgtm

#8483 Fix the issue that functions that rely on `tipb::FieldType` may produce incorrect results
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  tests/fullstack-test/expr/issue_8482.test
Labels: release-note-none, size/M, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8485 *: let version follows TiDB convention
  dbms/cmake/version.cmake
  dbms/src/Client/Connection.cpp
  dbms/src/Client/Connection.h
  dbms/src/Client/ConnectionPoolWithFailover.cpp
  dbms/src/Common/ClickHouseRevision.cpp
  dbms/src/Common/ClickHouseRevision.h
  dbms/src/Common/ErrorCodes.cpp
  dbms/src/Common/TiFlashBuildInfo.cpp
  dbms/src/Common/TiFlashBuildInfo.h
  dbms/src/Common/config_version.h.in
  dbms/src/Core/Defines.h
  dbms/src/DataStreams/MarkInCompressedFile.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.h
  dbms/src/DataStreams/NativeBlockInputStream.h
  dbms/src/DataStreams/NativeBlockOutputStream.cpp
  dbms/src/Functions/FunctionsMiscellaneous.cpp
  dbms/src/IO/Progress.cpp
  dbms/src/IO/Progress.h
  dbms/src/Interpreters/ClientInfo.cpp
  dbms/src/Interpreters/ClientInfo.h
  dbms/src/Interpreters/QueryLog.cpp
  dbms/src/Interpreters/TablesStatus.cpp
  dbms/src/Interpreters/TablesStatus.h
  dbms/src/Server/Client.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/StatusFile.cpp
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Server/TCPHandler.h
  dbms/src/Server/main.cpp
  dbms/src/Storages/System/StorageSystemProcesses.cpp
  libs/libdaemon/include/daemon/BaseDaemon.h
  libs/libdaemon/src/BaseDaemon.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8430 Disagg: Fetch MemTableSet by streaming
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8509 Fix compile error on mac
  dbms/src/Functions/FunctionsMiscellaneous.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8499 Add protobuf::internal::AssignDescriptors into tsan.suppression to ignore false positive warning
  tests/sanitize/tsan.suppression
Labels: size/XS, release-note-none, approved, lgtm

#8511 Refine cancel for read thread stream
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
Labels: release-note-none, size/S, approved, lgtm

#8481 *: add util functions to generate random data
  dbms/src/Common/RandomData.cpp
  dbms/src/Common/RandomData.h
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Storages/DeltaMerge/workload/DataGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
Labels: size/XL, release-note-none, approved, lgtm

#8512 Storages: small refine of MergedTask.
  dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
Labels: release-note-none, size/L, approved, lgtm

#8498 FAP: Persist Segment with meta info rather than segment_id
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/KVStore/CMakeLists.txt
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/CMakeLists.txt
  dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.h
  dbms/src/Storages/KVStore/MultiRaft/Disagg/fast_add_peer.proto
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.h
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/Proto/manifest_file.proto
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: size/XL, release-note-none, approved, lgtm

#8523 Storages: fix segmentfault when `fetchPages` failed.
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8480 Add test for tidb/issues/49241
  tests/fullstack-test/mpp/apply_with_late_materialization.test
Labels: release-note-none, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8530 Update tsan suppressions to ignore protobuf DebugString and ShortDebugString
  tests/sanitize/tsan.suppression
Labels: size/XS, release-note-none, approved, lgtm

#8536 ddl: Fix corner case of `FLASHBACK DATABASE`
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/MockSchemaGetter.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/tests/gtest_table_info.cpp
  tests/fullstack-test2/ddl/flashback/flashback_database.test
Labels: size/XL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8541 Revert "Refine cancel for read thread stream (#8511)"
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
Labels: release-note-none, size/S, approved, lgtm

#8533 Support enum with index 0
  dbms/src/DataTypes/DataTypeEnum.h
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
  tests/fullstack-test2/ddl/alter_column_enum.test
Labels: release-note-none, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8491 support `json_valid` and `json_keys`
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsJson.cpp
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_json_keys.cpp
  dbms/src/Functions/tests/gtest_json_valid.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
  dbms/src/TiDB/Decode/JsonBinary.h
  tests/fullstack-test/expr/json_keys.test
  tests/fullstack-test/expr/json_valid.test
Labels: size/XXL, release-note-none, approved, lgtm

#8552 Storages: fix MemoryTracker may release before MemoryTrackerSetter destructed
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
Labels: release-note-none, size/S, approved, lgtm

#8553 Add mutex to protect concurrent prepareMPPTasks
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: release-note-none, size/S, approved, lgtm

#8513 Encryption: seprate the cipher method from AESCTRCipherStream to support encrypt/decrypt simple data
  dbms/src/Encryption/AESCTRCipher.cpp
  dbms/src/Encryption/AESCTRCipher.h
  dbms/src/Encryption/AESCTRCipherStream.cpp
  dbms/src/Encryption/AESCTRCipherStream.h
  dbms/src/Encryption/BlockAccessCipherStream.h
  dbms/src/Encryption/KeyManager.h
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8554 tests: remove raftstore-v2 integration test
  tests/docker/config/tikv_v2.toml
  tests/fullstack-test/run.sh
  tests/fullstack-test2/cluster-v2.yaml
  tests/fullstack-test2/run.sh
Labels: release-note-none, size/L, approved, lgtm

#8472 Enhance metrics for KVStore write
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/MemoryTracker.cpp
  dbms/src/Common/MemoryTracker.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/Decode/DecodedTiKVKeyValue.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8559 fix darwin compile
  dbms/src/Encryption/AESCTRCipher.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8502 Support `json_contains_path`
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsJson.cpp
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_json_contains_path.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
  dbms/src/TiDB/Decode/JsonBinary.h
  tests/fullstack-test/expr/json_contains_path.test
Labels: size/XXL, release-note-none, approved, lgtm

#8565 Fix gtest data race detected by tsan check
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.cpp
  dbms/src/TestUtils/MPPTaskTestUtils.h
Labels: release-note-none, size/S, approved, lgtm

#8524 Encryption: do not expose key
  dbms/src/Encryption/AESCTRCipher.h
  dbms/src/Encryption/AESCTRCipherStream.cpp
  dbms/src/Encryption/AESCTRCipherStream.h
  dbms/src/Encryption/DataKeyManager.cpp
  dbms/src/Encryption/FileProvider.cpp
  dbms/src/Encryption/KeyManager.h
  dbms/src/Encryption/MockKeyManager.cpp
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
  dbms/src/Storages/KVStore/CMakeLists.txt
  dbms/src/Storages/KVStore/FFI/FileEncryption.cpp
  dbms/src/Storages/KVStore/FFI/FileEncryption.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8560 ddl: Fix snap after dropping database
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
  tests/fullstack-test2/ddl/flashback/flashback_database.test
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8567 Storages: limit memory usage of data sharing
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
  dbms/src/Storages/DeltaMerge/tests/gtest_column_sharing_cache.cpp
Labels: release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8540 Storage: add keyspaceID to DMFile
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/PathPool.h
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: release-note-none, size/L, approved, lgtm

#8384 Use HashSet for semi join with no other condition
  dbms/src/Common/ColumnsHashingImpl.h
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/JoinHashMap.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/JoinPartition.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/SemiJoinHelper.cpp
  dbms/src/Interpreters/SetVariants.h
Labels: release-note-none, size/L, approved, lgtm

#8570 Storages: fix memory track of fetchPages.
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8586 *: Reduce logging from `UnorderedInputStream`
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
Labels: release-note-none, size/S, cherry-pick-approved, approved, lgtm

#8587 Handle ColumnNothing column in recordFilteredRows of Join
  dbms/src/Interpreters/JoinUtils.cpp
  tests/fullstack-test/issues/issue_8562.test
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8584 KVStore: Reduce lock contention in `RegionPersister::doPersist`
  dbms/src/Common/FailPoint.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.h
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
  dbms/src/Storages/KVStore/tests/kvstore_helper.h
Labels: size/L, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8593 KVStore: Reduce lock contention in `RegionPersister::doPersist` (release-6.5)
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/Transaction/RegionPersister.cpp
  dbms/src/Storages/Transaction/RegionPersister.h
  dbms/src/Storages/Transaction/tests/gtest_region_persister.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8581 Support cancel in AsyncTasks
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_proactive_flush.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp
  dbms/src/Storages/KVStore/tests/kvstore_helper.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/TiDB/tests/gtest_json_binary.cpp
  dbms/src/TiDB/tests/gtest_json_path_expr.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8569 Log Improvement Back Port
  dbms/src/DataStreams/CreatingSetsBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/executeQuery.cpp
  libs/libdaemon/src/BaseDaemon.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8579 refine log
  dbms/src/Core/OperatorSpillContext.cpp
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Interpreters/Aggregator.cpp
Labels: release-note, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8605 *: Add mvcc input bytes and num columns read to logging
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
Labels: release-note-none, size/S, cherry-pick-approved, approved, lgtm

#8606 Set remote requst's DagRequest flags field
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  tests/fullstack-test/issues/issue_8607.test
Labels: release-note-none, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8608 PageStorage: avoid redundantly print stale snapshot log
  dbms/src/Storages/Page/V3/PageDirectory.cpp
Labels: release-note-none, size/S, approved, lgtm

#8618 tests: Fix some issue found by ASAN
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/S3/MockS3Client.cpp
Labels: release-note-none, size/M, approved, lgtm

#8613 fix invalid memory access bug in `tidbGreatestString`
  dbms/src/Functions/LeastGreatest.h
  tests/fullstack-test/mpp/issue_8604.test
Labels: release-note-none, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8366 Support finalize for join
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Planner/PhysicalPlanNode.cpp
  dbms/src/Flash/Planner/PhysicalPlanNode.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.h
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeReceiver.h
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.h
  dbms/src/Flash/Planner/Plans/PhysicalExpand.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand.h
  dbms/src/Flash/Planner/Plans/PhysicalExpand2.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExpand2.h
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.h
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoin.h
  dbms/src/Flash/Planner/Plans/PhysicalLimit.cpp
  dbms/src/Flash/Planner/Plans/PhysicalLimit.h
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeReceiver.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeReceiver.h
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeSender.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockExchangeSender.h
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Flash/Planner/Plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/Plans/PhysicalProjection.h
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTableScan.h
  dbms/src/Flash/Planner/Plans/PhysicalTopN.cpp
  dbms/src/Flash/Planner/Plans/PhysicalTopN.h
  dbms/src/Flash/Planner/Plans/PhysicalWindow.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindow.h
  dbms/src/Flash/Planner/Plans/PhysicalWindowSort.cpp
  dbms/src/Flash/Planner/Plans/PhysicalWindowSort.h
  dbms/src/Flash/Planner/Plans/PipelineBreakerHelper.h
  dbms/src/Flash/Planner/optimize.cpp
  dbms/src/Flash/tests/gtest_join.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Flash/tests/gtest_spill_join.cpp
  dbms/src/Interpreters/CrossJoinProbeHelper.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Interpreters/ProbeProcessInfo.h
  dbms/src/Interpreters/SemiJoinHelper.cpp
  dbms/src/Interpreters/SemiJoinHelper.h
Labels: size/XXL, release-note-none, approved, lgtm

#8623 ddl: Fix sync empty schema diff
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  tests/README.md
  tests/_env.sh
  tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test
  tests/docker/config/tics_dt.toml
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8627 Encryption: add MasterKey and EncryptionKey util
  dbms/src/Encryption/EncryptionKey.h
  dbms/src/Encryption/MasterKey.h
  dbms/src/Encryption/tests/gtest_encryption_test.cpp
  dbms/src/Storages/KVStore/FFI/FileEncryption.h
Labels: size/XL, release-note-none, approved, lgtm

#8566 Encryption: support encrypt/decrypt pages belongs to different keyspaces but in the same Blob file using different key
  dbms/src/Encryption/FileProvider.cpp
  dbms/src/Encryption/FileProvider.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V2.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/KVStore/FFI/FileEncryption.cpp
  dbms/src/Storages/KVStore/FFI/FileEncryption.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/V3/Blob/BlobFile.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
  dbms/src/TestUtils/TiFlashStorageTestBasic.h
Labels: release-note-none, size/L, approved, lgtm

#8616 *: Add table scan details logging; change default logging level to "info"
  dbms/src/DataStreams/TiRemoteBlockInputStream.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/ExecutionSummary.cpp
  dbms/src/Flash/Coprocessor/ExecutionSummary.h
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Statistics/ExecutionSummaryHelper.cpp
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.cpp
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.h
  dbms/src/Flash/Statistics/TableScanImpl.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ReadMode.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.h
  dbms/src/Storages/DeltaMerge/RowKeyOrderedBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/ScanContext_fwd.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/Storages/StorageDeltaMerge.h
  libs/libdaemon/src/BaseDaemon.cpp
Labels: size/XL, release-note, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5
