Repository pingcap/tiflash, pull requests merged in 2024-05, with the labels that each got.

#9019 tests: remove a fake test
  tests/fullstack-test2/variables/set_sql_mode_ansi.test
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#9021 tests: remove a fake test
  tests/fullstack-test2/variables/set_sql_mode_ansi.test
Labels: release-note-none, size/M, approved, lgtm

#8987 Pipeline: refactor the extra time calculation in explain analyze
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/QueryExecutor.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.h
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTaskBase.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/SimplePipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Operators/ConcatSourceOp.h
  dbms/src/Operators/Operator.cpp
  dbms/src/Operators/Operator.h
Labels: release-note-none, size/L, approved, lgtm

#9023 Add agg final spill event if have spill data
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/AggregateFinalConvertEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/AggregateFinalConvertEvent.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/AggSpillContext.cpp
Labels: release-note-none, size/L, approved, lgtm

#9026 Storages: Avoid SegmentReadTaskScheduler blocking the adding threads and ignore empty SegmentReadTaskPool
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_circular_scan_list.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#9027 Storages: Refine SegmentReadTaskScheduler::add to reduce lock contention
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#9003 KVStore: Expand the usage of thread-wise alloc/dealloc trace
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/kvstore_helper.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9031 Storages: Fix max_dup_tuple_id in DeltaTree::swap
  dbms/src/Storages/DeltaMerge/DeltaTree.h
Labels: release-note-none, size/S, approved, lgtm

#9035 Compression: refine unit tests
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
Labels: release-note-none, size/M, approved, lgtm

#9037 *: Fix allocateptr call from Proxy
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/S, approved, lgtm

#9044 *: Fix too long thread name make TSAN failed to run
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9041 Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-8.1

#9045 Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5 (release-8.1)
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9053 Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5 (#9041)
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: size/L, release-note

#9048 Storage: Fix page_id being mis-reuse when upgrade from cluster < 6.5 (#9041) (release-7.1)
  dbms/src/Storages/DeltaMerge/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9059 *: Use static to avoid thread-wise memtrace lifetime problem
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: release-note-none, size/M, approved, lgtm

#9054 Storage: let stable meta using protobuf format
  dbms/src/Storages/DeltaMerge/File/dtpb/dmfile.proto
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/FormatVersion.h
Labels: release-note-none, size/L, approved, lgtm

#8875 Pipeline: use `notify` instead of `polling` for `SharedQueue`
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Operators/tests/gtest_shared_queue.cpp
  tests/fullstack-test/mpp/window.test
Labels: size/XL, release-note-none, approved, lgtm

#9042 Storage: Separate DMFile
  dbms/src/Flash/Disaggregated/MockS3LockClient.h
  dbms/src/Flash/Disaggregated/S3LockService.cpp
  dbms/src/Flash/Disaggregated/tests/gtest_s3_lock_service.cpp
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/DMChecksumConfig.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileMeta.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileMeta.h
  dbms/src/Storages/DeltaMerge/File/DMFileMetaV2.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileMetaV2.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileUtil.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileUtil.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStore.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreMock.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreMock.h
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_column_sharing_cache.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_lock_local_mgr.cpp
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9001 ddl: Fix exchange partition across databases (release-7.1)
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaNameMapper.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
  tests/fullstack-test2/ddl/alter_exchange_partition.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9064 Storages: Trace memory allocation by thread
  dbms/src/Common/MemoryAllocTrace.cpp
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Storages/BackgroundProcessingPool.cpp
  dbms/src/Storages/BackgroundProcessingPool.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
  dbms/src/Storages/Page/V2/tests/gtest_data_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_legacy_compactor.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_paths.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_storage_multi_writers.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV2.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/tests/gtest_bkg_pool.cpp
  dbms/src/TestUtils/TiFlashTestEnv.h
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#9068 security: Do not let grpc reload ssh cert if not changed
  .github/licenserc.yml
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Common/tests/gtest_tiflash_security.cpp
  dbms/src/Common/tests/tls/ca.crt
  dbms/src/Common/tests/tls/cert.crt
  dbms/src/Common/tests/tls/key.pem
  dbms/src/Server/FlashGrpcServerHolder.cpp
Labels: release-note-none, size/L, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9075 GitHub: Add marker in PR template to be recognized by bot to put into commit message
  .github/pull_request_template.md
Labels: size/XS, release-note-none, approved, lgtm

#9076 chore: Test commit message
  README.md
Labels: size/XS, release-note-none, approved, lgtm

#9077 chore: Revert "chore: Test commit message (#9076)"
  README.md
Labels: size/XS, release-note-none, approved, lgtm

#9080 security: Do not let grpc reload ssh cert if not changed (#9068) (#9069)
  .github/licenserc.yml
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Common/tests/gtest_tiflash_security.cpp
  dbms/src/Common/tests/tls/ca.crt
  dbms/src/Common/tests/tls/cert.crt
  dbms/src/Common/tests/tls/key.pem
  dbms/src/Server/FlashGrpcServerHolder.cpp
Labels: release-note-none, size/L, approved, lgtm

#9083 *: Fix USE_JEMALLOC macro
  dbms/src/Common/MemoryAllocTrace.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9078 KVStore: Distinguish different versions of Proxy
  cmake/find_tiflash_proxy.cmake
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
Labels: release-note-none, size/M, approved, lgtm

#9086 *: fix tipb::ColumnInfo to TiDB::ColumnInfo
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
Labels: size/XS, release-note, approved, lgtm

#9058 Remove the redundant copy of join key column
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/JoinInterpreterHelper.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Flash/tests/gtest_split_tasks.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Interpreters/ProbeProcessInfo.h
Labels: size/XXL, release-note-none, approved, lgtm

#9093 tests: Disable some tests when jemalloc is not enabled
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: release-note-none, size/M, approved, lgtm

#9094 *: fix Exception
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9096 tests: Fix MPPTask-Moniter may live longer than TiFlashMetrics
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Storages/KVStore/TMTContext.cpp
  tests/sanitize/tsan.suppression
Labels: release-note-none, size/M, approved, lgtm

#8967 chore: strengthen configuration change approval
  OWNERS_ALIASES
  dbms/src/Interpreters/OWNERS
Labels: release-note-none, size/S, approved, lgtm

#8985 Optimize unnecessary column copy for HashAgg
  dbms/CMakeLists.txt
  dbms/src/DataStreams/AggHashTableToBlocksBlockInputStream.h
  dbms/src/Debug/MockExecutor/TableScanBinder.cpp
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregation.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/bench_aggregation_hash_map.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Interpreters/AggregateDescription.h
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  dbms/src/TiDB/Schema/TiDB.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9099 *: fix bench_dbms build
  dbms/src/IO/Compression/tests/bench_codec_delta_for.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9100 Pipeline: refine directory for pipeline
  dbms/src/Flash/CMakeLists.txt
  dbms/src/Flash/Pipeline/Pipeline.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/AggregateFinalConvertEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/AggregateFinalConvertEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/AggregateFinalSpillEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/AggregateFinalSpillEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/FineGrainedPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/FineGrainedPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/LoadBucketEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/LoadBucketEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/PlainPipelineEvent.cpp
  dbms/src/Flash/Pipeline/Schedule/Events/Impls/PlainPipelineEvent.h
  dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/AggregateFinalConvertTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/AggregateFinalConvertTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/AggregateFinalSpillTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/AggregateFinalSpillTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/EventTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/EventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/IOEventTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/LoadBucketTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/LoadBucketTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/PipelineTaskBase.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/RFWaitTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/SimplePipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/StreamRestoreTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/StreamRestoreTask.h
  dbms/src/Flash/Planner/Plans/PhysicalAggregationBuild.cpp
  dbms/src/Operators/HashProbeTransformExec.cpp
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/UnorderedSourceOp.cpp
Labels: release-note-none, size/M, approved, lgtm

#9095 FAP: Add some logs
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Page/V3/Blob/GCInfo.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/GCDefines.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
Labels: size/XL, release-note-none, approved, lgtm
