Repository pingcap/tiflash, pull requests merged in 2024-07, with the labels that each got.

#9174 KVStore: Get addressed engine-addr from proxy
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: release-note-none, size/M, approved, lgtm

#9176 Storages: Fix returned column types may not match in late-materialization
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  tests/fullstack-test/expr/duration_filter_late_materialization2.test
Labels: size/L, release-note, approved, lgtm

#9178 build: fix docker image misc script
  release-centos7-llvm/dockerfiles/misc/prepare_basic.sh
Labels: size/XS, release-note-none, approved, lgtm

#9192 KVStore: Refine parallel prehandle snapshot (part-1)
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
Labels: release-note-none, size/L, approved, lgtm

#9194 Change sleep time for sanitizer build type of gtest_compute_server
  dbms/src/Flash/tests/gtest_compute_server.cpp
Labels: release-note-none, size/S, approved, lgtm

#8903 Support Adaptive Lightweight Compression Algorithm
  dbms/CMakeLists.txt
  dbms/src/IO/Compression/CompressionCodecDeflateQpl.h
  dbms/src/IO/Compression/CompressionCodecDeltaFOR.cpp
  dbms/src/IO/Compression/CompressionCodecDeltaFOR.h
  dbms/src/IO/Compression/CompressionCodecFOR.cpp
  dbms/src/IO/Compression/CompressionCodecFOR.h
  dbms/src/IO/Compression/CompressionCodecLZ4.cpp
  dbms/src/IO/Compression/CompressionCodecLZ4.h
  dbms/src/IO/Compression/CompressionCodecLightweight.cpp
  dbms/src/IO/Compression/CompressionCodecLightweight.h
  dbms/src/IO/Compression/CompressionCodecLightweight_Integer.cpp
  dbms/src/IO/Compression/CompressionCodecLightweight_NonInteger.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.h
  dbms/src/IO/Compression/CompressionCodecNone.h
  dbms/src/IO/Compression/CompressionCodecRLE.cpp
  dbms/src/IO/Compression/CompressionCodecRunLength.cpp
  dbms/src/IO/Compression/CompressionCodecRunLength.h
  dbms/src/IO/Compression/CompressionCodecZSTD.h
  dbms/src/IO/Compression/CompressionFactory.h
  dbms/src/IO/Compression/CompressionInfo.h
  dbms/src/IO/Compression/CompressionMethod.h
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/IO/Compression/EncodingUtil.cpp
  dbms/src/IO/Compression/EncodingUtil.h
  dbms/src/IO/Compression/ICompressionCodec.cpp
  dbms/src/IO/Compression/ICompressionCodec.h
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
  dbms/src/Storages/KVStore/FFI/SSTReader.h
Labels: size/XXL, release-note-none, approved, lgtm

#9199 fix fmt error
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9200 Adjust sanitizer sleep time for cancelMPPGather
  dbms/src/Flash/tests/gtest_compute_server.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9189 Storages: Fix obtaining incorrect column information when there are virtual columns in the query
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/RFWaitTask.h
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Storages/DeltaMerge/ColumnDefine_fwd.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/TiDB.h
  tests/fullstack-test/expr/generated_columns.test
  tests/fullstack-test/expr/generated_columns2.test
  tests/fullstack-test/expr/runtime_filter.test
Labels: size/XL, release-note, approved, lgtm

#9210 *: fix bench_dbms build
  dbms/src/IO/Compression/tests/bench_codec_delta_for.cpp
Labels: release-note-none, size/S, approved, lgtm

#9205 *: Add binaryDir to CMakePresets.json
  CMakePresets.json
Labels: release-note-none, size/S, approved, lgtm

#9209 *: reduce virtual function call in ColumnNullable::size()
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Functions/tests/gtest_cast_json_as_string.cpp
  dbms/src/Functions/tests/gtest_json_extract.cpp
Labels: release-note-none, size/S, approved, lgtm

#9213 tests: Add ut for parsing lock value
  dbms/src/Storages/Transaction/tests/gtest_tikv_keyvalue.cpp
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#9214 tests: Add ut for parsing lock value
  dbms/src/Storages/KVStore/tests/gtest_tikv_keyvalue.cpp
Labels: release-note-none, size/M, approved, lgtm

#9133 ddl: Fix rename partitioned table is not atomic
  dbms/src/Common/FailPoint.cpp
  dbms/src/Databases/DatabasesCommon.h
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/SchemaNameMapper.h
  dbms/src/TiDB/Schema/TableIDMap.cpp
  dbms/src/TiDB/Schema/TableIDMap.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/tests/gtest_name_mapper.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_id_map.cpp
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: size/XXL, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9211 tests: Refine the README of running test cases
  tests/README.md
  tests/_env.sh
  tests/docker/config/tiflash_dt.toml
  tests/docker/config/tiflash_dt_disable_local_tunnel.toml
  tests/docker/config/tiflash_dt_force_enable_lm.toml
  tests/docker/config/tiflash_dt_sync_grpc.toml
Labels: release-note-none, size/M, approved, lgtm

#9115 *: Introduce MutexProtected and SharedMutexProtected
  dbms/src/Common/MutexProtected.h
  dbms/src/Common/SharedMutexProtected.h
  dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.cpp
  dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.h
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
Labels: size/XL, release-note-none, approved, lgtm

#9234 security: Allow empty security config for disabling tls
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Common/tests/gtest_tiflash_security.cpp
  dbms/src/Server/Server.cpp
Labels: size/L, release-note, approved, lgtm

#9195 support selective block for MPPExchangeWriter
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.cpp
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.cpp
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.cpp
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Core/BlockInfo.h
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/TestUtils/ColumnGenerator.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9240 Accumulated updates for heap profiling
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/Page/PageStorageMemorySummary.h
  dbms/src/Storages/Page/V3/Universal/UniversalWriteBatchImpl.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/Page/V3/tests/gtest_wal_log.cpp
  libs/libcommon/cmake/find_jemalloc.cmake
Labels: release-note-none, size/M, approved, lgtm

#9246 ddl: Atomic rename `DeltaMergeStore::db_name` in memory
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/TableNameMeta.h
Labels: release-note-none, size/L, approved, lgtm

#9254 Storages: Fix statistical data of DMFilePackFilter
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
Labels: release-note-none, size/M, approved, lgtm

#9253 KVStore: Fallback elegantly when getting table error in FAP
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.h
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: release-note-none, size/L, approved, lgtm

#9259 tests: Limit the segments to be merged under tsan to suppress deadlock
  README.md
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  tests/sanitize/tsan.suppression
Labels: release-note-none, size/S, approved, lgtm

#9260 Storages: Add Block pop-up latency metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#9265 Storages: Fix obtaining incorrect column information when there are virtual columns in the query (release-8.1)
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.h
  dbms/src/Storages/DeltaMerge/ColumnDefine_fwd.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/TiDB.h
  tests/fullstack-test/expr/generated_columns.test
  tests/fullstack-test/expr/generated_columns2.test
  tests/fullstack-test/expr/runtime_filter.test
Labels: size/XL, release-note, cherry-pick-approved, approved, lgtm

#9262 compute: Add Vector data type and functions
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/IColumn.h
  dbms/src/DataTypes/DataTypeArray.h
  dbms/src/Debug/MockExecutor/AstToPB.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
  dbms/src/Flash/Coprocessor/DAGCodec.cpp
  dbms/src/Flash/Coprocessor/DAGCodec.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/Coprocessor/TiDBColumn.h
  dbms/src/Functions/FunctionHelpers.h
  dbms/src/Functions/FunctionsVector.cpp
  dbms/src/Functions/FunctionsVector.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_vector.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/TiDB/Decode/DatumCodec.cpp
  dbms/src/TiDB/Decode/DatumCodec.h
  dbms/src/TiDB/Decode/RowCodec.cpp
  dbms/src/TiDB/Decode/TypeMapping.cpp
  dbms/src/TiDB/Decode/Vector.cpp
  dbms/src/TiDB/Decode/Vector.h
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
Labels: size/XXL, release-note-none, approved, lgtm
