Repository pingcap/tiflash, pull requests merged in 2024-01, with the labels that each got.

#8634 fix In ScalarFunc in RoughSetFilter
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  tests/fullstack-test/expr/in_expression.test
Labels: size/S, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8638 Fix hash join crash
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/M, approved, lgtm

#8640 *: Add compiler info to the `tiflash version`
  contrib/aws-cmake/CMakeLists.txt
  dbms/src/Common/TiFlashBuildInfo.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  libs/libcommon/include/common/config_common.h.in
  release-centos7-llvm/Makefile
  release-centos7-llvm/README.md
  release-centos7-llvm/env/README.md
Labels: release-note-none, size/L, approved, lgtm

#8637 fix crash when stopping because of lac reset
  dbms/src/Server/Server.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8557 Storages: refine `SegmentReadTaskScheduler`
  dbms/src/Flash/Pipeline/Schedule/Tasks/RFWaitTask.h
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CircularScanList.h
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_circular_scan_list.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8614 KVStore: introduce flexible region format
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/MultiRaft/PreHandlingTrace.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/Utils/SerializationHelper.h
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
  dbms/src/Storages/KVStore/tests/gtests_async_tasks.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8636 Storages: Add metrics in RateLimiter
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Encryption/RateLimiter.h
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8643 KVStore: pick flexible region format to release-7.5
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/Utils/SerializationHelper.h
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
Labels: size/XXL, release-note-none, cherry-pick-approved, approved, lgtm

#8651 PageStorage: Optimize the critical region when removing a BlobFile from disk
  dbms/src/Storages/Page/V3/BlobStore.cpp
Labels: size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8653 Storages: Refine metrics of read threads and data sharing
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8657 testing: Add the p99 quantile of write latency to `pageworkload`
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/Page/workload/CMakeLists.txt
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  dbms/src/Storages/Page/workload/TiFlashMetricsHelper.cpp
  dbms/src/Storages/Page/workload/TiFlashMetricsHelper.h
Labels: release-note-none, size/L, approved, lgtm

#8622 lowerUTF8/upperUTF8 allow lower/uppercase characters occupy different number of bytes
  dbms/src/Common/UTF8Helpers.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/FunctionsString.h
  dbms/src/Functions/tests/gtest_strings_lower.cpp
  dbms/src/Functions/tests/gtest_strings_upper.cpp
Labels: size/XL, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8670 refine log for `CodecUtils`
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.h
Labels: release-note-none, size/M, approved, lgtm

#8671 Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed.
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  tests/fullstack-test/issues/issue_1796.test
  tests/fullstack-test/issues/issue_3333.test
  tests/fullstack-test/issues/issue_3373.test
  tests/fullstack-test/issues/issue_3447.test
  tests/fullstack-test/issues/issue_7695.test
  tests/fullstack-test/issues/issue_8113.test
  tests/fullstack-test/issues/issue_8482.test
  tests/fullstack-test/issues/issue_8601.test
Labels: release-note, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8555 Support `json_extract(column, column, ...)`
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_json_extract.cpp
  tests/fullstack-test/expr/json_extract.test
Labels: size/XL, release-note-none, approved, lgtm

#8642 refine handleOtherConditions in join
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Interpreters/ProbeProcessInfo.h
Labels: release-note-none, size/L, approved, lgtm

#8677 Storages: Don't merge SegmentReadTasks when data sharing is disabled
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: release-note-none, size/M, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8664 Encryption: support upload local encrypted files in DMFile to S3
  dbms/src/IO/BufferBase.h
  dbms/src/IO/ReadBuffer.cpp
  dbms/src/IO/ReadBuffer.h
  dbms/src/IO/ReadBufferFromRandomAccessFile.h
  dbms/src/IO/StdStreamBufFromReadBuffer.cpp
  dbms/src/IO/StdStreamBufFromReadBuffer.h
  dbms/src/IO/StdStreamFromReadBuffer.h
  dbms/src/IO/tests/gtest_std_stream_from_read_buffer.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.cpp
  dbms/src/Storages/DeltaMerge/Remote/DataStore/DataStoreS3.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_checkpoint.cpp
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/S3Filename.h
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/S3/tests/gtest_s3gcmanager.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8690 Storage: remove useless Tuple
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/Tuple.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_tree.cpp
Labels: release-note-none, size/L, approved, lgtm

#8699 DDL: Add the reason why storage instance is created or dropped
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-7.5

#8701 Storage: Refactor for fixing recreate Storage instance
  dbms/src/Debug/dbgFuncMisc.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDataProvider.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDataProvider.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/GlobalStoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/GlobalStoragePool.h
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.h
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePoolConfig.h
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool_fwd.h
  dbms/src/Storages/DeltaMerge/WriteBatchesImpl.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage_storage_pool.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage_mix_mode.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: size/XXL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8702 Storages: Update the length of Block queue and the number of read threads
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8713 `cast as json` remove duplicate keys
  dbms/src/Functions/tests/gtest_cast_as_json.cpp
  dbms/src/Functions/tests/gtest_json_keys.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
Labels: release-note-none, size/M, approved, lgtm

#8720 *: remove useless UncompressedCache
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/IO/CachedCompressedReadBuffer.cpp
  dbms/src/IO/CachedCompressedReadBuffer.h
  dbms/src/IO/CompressedReadBufferBase.h
  dbms/src/IO/UncompressedCache.h
  dbms/src/IO/tests/CMakeLists.txt
  dbms/src/IO/tests/cached_compressed_read_buffer.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_server_config.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8721 ddl: Fix the storage instance may be physically dropped when the region is not removed
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.h
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  tests/fullstack-test2/ddl/alter_drop_table.test
  tests/fullstack-test2/ddl/flashback/flashback_database.test
  tests/fullstack-test2/ddl/flashback/recover_table.test
  tests/fullstack-test2/ddl/partitions/alter_exchange_partition.test
  tests/fullstack-test2/ddl/partitions/reorganize_partition.test
Labels: size/XXL, release-note, approved, lgtm

#8723 ddl: Fix NULL value in non-nullable column (release-6.5)
  dbms/src/Storages/Transaction/RowCodec.cpp
  dbms/src/Storages/Transaction/tests/gtest_region_block_reader.cpp
  tests/fullstack-test2/ddl/alter_column_nullable.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8722 ddl: Fix NULL value in non-nullable column
  dbms/src/Storages/KVStore/Decode/RegionBlockReader.cpp
  dbms/src/Storages/KVStore/tests/gtest_region_block_reader.cpp
  dbms/src/TiDB/Decode/RowCodec.cpp
  tests/fullstack-test2/ddl/alter_column_nullable.test
Labels: size/L, release-note, approved, lgtm

#8698 Storage: Fix max-id being mis-reused cause data corruption after changing tiflash replica number
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/GlobalPageIdAllocator.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/GlobalPageIdAllocator.h
  dbms/src/Storages/DeltaMerge/StoragePool/GlobalStoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.h
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool_fwd.h
  dbms/src/Storages/DeltaMerge/WriteBatchesImpl.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_global_page_id_allocator.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/PageDirectoryFactory.h
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: size/XXL, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8732 Revert "Storages: Update the length of Block queue and the number of read threads (#8702)"
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#8735 ddl: Add the reason why an IStorage instance is recovered
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
Labels: release-note-none, size/M, approved, lgtm

#8734 DTTool: ouput columns order by column id
  dbms/src/Storages/DeltaMerge/File/DMFile.h
Labels: size/XS, release-note-none, approved, lgtm

#8737 Storages: add unit-tests of duplicated handle and version.
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: release-note-none, size/L, approved, lgtm

#8694 Storages: Only print errno instead of its string when CPU affinity of SegmentReader bind fail
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReader.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  tests/docker/run.sh
  tests/docker/util.sh
Labels: release-note-none, size/M, approved, lgtm

#8739 KVStore: share some utils with Debug and refine definitions in KVStore
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/MockKVStore/MockUtils.h
  dbms/src/Debug/dbgNaturalDag.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Debug/dbgTools.h
  dbms/src/Storages/KVStore/Decode/RegionDataRead.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/OrphanKeyInfo.cpp
  dbms/src/Storages/KVStore/MultiRaft/Persistence.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
  dbms/src/Storages/KVStore/tests/region_helper.h
Labels: size/XXL, release-note-none, approved, lgtm

#8571 client-c: Add retry for getting TSO from PD
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/TiKVHelpers/KeyspaceSnapshot.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/PDTiKVClient.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaGetter.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.h
Labels: size/L, release-note, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5
