Repository pingcap/tiflash, pull requests merged in 2024-12, with the labels that each got.

#9675 Refine na semi join
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
  dbms/src/Interpreters/SemiJoinHelper.cpp
  dbms/src/Interpreters/SemiJoinHelper.h
Labels: size/XXL, release-note-none, approved, lgtm

#9670 Column: optimze filter
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnsCommon.cpp
  dbms/src/Columns/ColumnsCommon.h
  dbms/src/Columns/tests/CMakeLists.txt
  dbms/src/Columns/tests/bench_column_filter.cpp
  dbms/src/Columns/tests/column_vector_perftest.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9703 misc: Update devcontainer
  .devcontainer/Dockerfile
  .devcontainer/Makefile
  .devcontainer/misc/codespaces.zsh-theme
  .devcontainer/misc/docker-entrypoint.sh
Labels: release-note-none, size/L, approved, lgtm

#9696 Fix incompatible behavior with TiDB when casting float into string
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  dbms/src/IO/WriteHelpers.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9689 limit the max exec time for nasemi/semi join probe
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskHelper.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskTimer.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskTimer.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9710 *: separate ColumnsCommon
  dbms/CMakeLists.txt
  dbms/src/AggregateFunctions/AggregateFunctionCount.h
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
  dbms/src/Columns/ColumnAggregateFunction.cpp
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnConst.cpp
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFunction.cpp
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnUtil.cpp
  dbms/src/Columns/ColumnUtil.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/VirtualColumnUtils.cpp
  dbms/src/Columns/countBytesInFilter.cpp
  dbms/src/Columns/countBytesInFilter.h
  dbms/src/Columns/filterColumn.cpp
  dbms/src/Columns/filterColumn.h
  dbms/src/Columns/tests/bench_column_filter.cpp
  dbms/src/DataStreams/ExpandTransformAction.cpp
  dbms/src/DataStreams/FilterBlockInputStream.cpp
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/Functions/FunctionsConversion.h
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/ProbeProcessInfo.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMDecoratorStreams.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/RowKeyFilter.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9713 Storages: Shutdown the LocalIndexScheduler before shutting down PageStorage/DeltaMergeStore (release-8.5)
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9711 Avoid useless `transform` operations when block's row count is 0
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
Labels: release-note-none, size/S, approved, lgtm

#9720 PageCtl: Support getting blob data from PageStorage instance (release-8.1)
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  release-centos7-llvm/env/.gitignore
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#9718 *: Add const in some function parameters and member functions
  dbms/src/IO/FileProvider/CompressedReadBufferFromFileBuilder.cpp
  dbms/src/IO/FileProvider/CompressedReadBufferFromFileBuilder.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
Labels: release-note-none, size/M, approved, lgtm

#9717 PageCtl: Support getting blob data from PageStorage instance (release-7.5)
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  release-centos7-llvm/env/.gitignore
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#9608 Storages: New serialization/deserialization for DataTypeString
  dbms/src/Core/tests/gtest_block.cpp
  dbms/src/Core/tests/gtest_spiller.cpp
  dbms/src/DataTypes/DataTypeString.cpp
  dbms/src/DataTypes/DataTypeString.h
  dbms/src/DataTypes/IDataType.cpp
  dbms/src/DataTypes/IDataType.h
  dbms/src/DataTypes/tests/bench_data_type_string.cpp
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/DataTypes/tests/gtest_data_type_string.cpp
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_interpreter.out
  dbms/src/Flash/tests/gtest_planner_interpreter.out
  dbms/src/Functions/tests/gtest_ifnull.cpp
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileMeta.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileMetaV2.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/dtpb/dmfile.proto
  dbms/src/Storages/DeltaMerge/tests/gtest_column_filter.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
  dbms/src/Storages/DeltaMerge/workload/TableGenerator.cpp
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/KVStore/Decode/DecodingStorageSchemaSnapshot.cpp
  dbms/src/Storages/MutableSupport.cpp
  dbms/src/TestUtils/InterpreterTestUtils.cpp
  dbms/src/TestUtils/tests/gtest_column_generator.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
  dbms/src/TiDB/tests/gtest_type_mapping.cpp
Labels: size/XXL, release-note, approved, lgtm

#9723 PageCtl: Support getting blob data from PageStorage instance
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#9712 Storages: Shutdown the LocalIndexScheduler before shutting down PageStorage/DeltaMergeStore
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/executeQuery.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-8.5

#9735 *: Remove RegionPtrWithBlock
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncMockRaftCommand.h
  dbms/src/Debug/dbgKVStore/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncRegion.cpp
  dbms/src/Debug/dbgNaturalDag.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.h
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_spill.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
  tests/delta-merge-test/raft/snapshot.test
Labels: size/XL, release-note-none, approved, lgtm

#9709 vector: refine vector search
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterView.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9738 Storages: load RSResult only once
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/RSResult.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9744 *: Refine the error message when schema mismatch in ExchangeReceiver
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Storages/DeltaMerge/RestoreDMFile.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/FormatVersion.cpp
Labels: release-note-none, size/L, approved, lgtm

#9741 Storages: move ann_query_info to PushDownExecutor
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/WithANNQueryInfo.h
  dbms/src/Storages/DeltaMerge/Remote/RNSegmentInputStream.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9707 KVStore: Reduce the memory before and after a large txn is committed
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/MultiRaft/Persistence.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataTrait.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.h
  dbms/src/Storages/KVStore/tests/bench_parse_lock.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_tikv_keyvalue.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: size/XXL, release-note-none, approved, lgtm

#9751 Enhance FAP metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: release-note-none, size/L, approved, lgtm

#9742 *: enable new serdes format of DataTypeString
  dbms/src/Storages/FormatVersion.h
Labels: size/XS, release-note, approved, lgtm
