Repository pingcap/tiflash, pull requests merged in 2024-02, with the labels that each got.

#8738 Encryption: fix read encryption key from page storage & add unit tests
  dbms/src/Common/LRUCache.h
  dbms/src/Debug/MockProxyEncryptionFFI.h
  dbms/src/Encryption/FileProvider.cpp
  dbms/src/Encryption/FileProvider.h
  dbms/src/Encryption/KeyspacesKeyManager.cpp
  dbms/src/Encryption/KeyspacesKeyManager.h
  dbms/src/Encryption/tests/gtest_keyspaces_key_manager.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/FFI/FileEncryption.h
  dbms/src/TestUtils/CMakeLists.txt
Labels: size/XL, release-note-none, approved, lgtm

#8753 Storages: Refine comparator of row key to operator<=>
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_randomized.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8718 support `json_length(json, path)`
  dbms/src/Functions/FunctionsJson.h
  dbms/src/Functions/tests/gtest_json_length.cpp
  dbms/src/TiDB/Decode/JsonBinary.cpp
  dbms/src/TiDB/Decode/JsonBinary.h
  dbms/src/TiDB/Decode/JsonPathExprRef.cpp
  dbms/src/TiDB/Decode/JsonPathExprRef.h
  tests/fullstack-test/expr/json_length.test
Labels: size/XXL, release-note-none, approved, lgtm

#8760 Encryption: fix circular reference in KeyspacesKeyManager
  dbms/src/Encryption/KeyspacesKeyManager.cpp
  dbms/src/Encryption/KeyspacesKeyManager.h
Labels: release-note-none, size/M, approved, lgtm

#8757 Storages: Refine unit test on DMFile
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.h
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8764 IO: Refine the `CompressedReadBuffer`/`CompressedWriteBuffer`
  dbms/src/IO/Checksum/tests/gtest_dm_checksum_buffer.cpp
  dbms/src/IO/Compression/CompressedReadBuffer.cpp
  dbms/src/IO/Compression/CompressedReadBuffer.h
  dbms/src/IO/Compression/CompressedReadBufferBase.cpp
  dbms/src/IO/Compression/CompressedReadBufferBase.h
  dbms/src/IO/Compression/CompressedReadBufferFromFile.cpp
  dbms/src/IO/Compression/CompressedReadBufferFromFile.h
  dbms/src/IO/Compression/CompressedWriteBuffer.cpp
  dbms/src/IO/Compression/CompressedWriteBuffer.h
  dbms/src/IO/Encryption/CompressedReadBufferFromFileProvider.cpp
  dbms/src/IO/Encryption/CompressedReadBufferFromFileProvider.h
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  tests/run-gtest.sh
Labels: release-note-none, size/L, approved, lgtm

#8748 Support cast decimal to double function
  dbms/src/Core/Field.h
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  tests/fullstack-test/expr/cast_decimal_as_real.test
Labels: release-note-none, size/L, approved, lgtm

#8767 Fix tem object out of scope issue
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
  dbms/src/Flash/Coprocessor/TiDBEnum.h
  tests/fullstack-test/issues/issue_8767.test
Labels: release-note-none, size/M, approved, lgtm

#8766 Fix unstable test in AsyncTasks
  dbms/src/Storages/KVStore/tests/gtest_async_tasks.cpp
Labels: release-note-none, size/M, approved, lgtm

#8780 Fix decimal to real asan stack-use-after-scope error
  dbms/src/Functions/FunctionsTiDBConversion.h
Labels: size/XS, release-note-none, approved, lgtm

#8756 Storages: Make DMFile ready for new column indexes/types
  dbms/src/DataTypes/IDataType.cpp
  dbms/src/DataTypes/IDataType.h
  dbms/src/Storages/DeltaMerge/File/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.h
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/dtpb/dmfile.proto
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/TestUtils/FunctionTestUtils.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
Labels: size/XXL, release-note-none, approved, lgtm

#8782 test: add ft for tidb/issues/51204
  tests/fullstack-test/mpp/apply_with_late_materialization.test
Labels: release-note-none, size/S, approved, lgtm

#8786 ddl: Fix database drop by accident when meet `regenerate_schema_map` flag (release-7.5)
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8785 ddl: Fix database drop by accident when meet `regenerate_schema_map` flag
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8792 fix anti semi join
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/M, cherry-pick-approved, needs-cherry-pick-release-7.1, approved, lgtm

#8795 Add address of WN to message if RPC request failed
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/S, approved, lgtm

#8798 fix mac build error
  dbms/src/Storages/DeltaMerge/ReadThread/CPU.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8797 fix potential memcpy overlap issue in join
  dbms/src/Common/PODArray.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/ProbeProcessInfo.cpp
Labels: release-note-none, size/L, approved, lgtm

#8804 fix agg bug in some corner cases
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  tests/fullstack-test/issues/issue_8799.test
Labels: release-note-none, size/M, approved, lgtm
