Repository pingcap/tiflash, pull requests merged in 2024-08, with the labels that each got.

#9274 ddl: Fix rename come after database has been dropped
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9275 ddl: Fix rename come after database has been dropped (release-7.5)
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  tests/fullstack-test2/ddl/rename_table_across_databases.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9279 coprocessor: Refactor encoding `TiDBColumn`
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
  dbms/src/Flash/Coprocessor/TiDBChunk.cpp
  dbms/src/Flash/Coprocessor/TiDBColumn.cpp
  dbms/src/Flash/Coprocessor/TiDBColumn.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/TiDB/Schema/TiDB.h
Labels: release-note-none, size/M, approved, lgtm

#9283 PageStorage: Fix empty page cause TiFlash failed to start
  dbms/src/Common/UniThreadPool.h
  dbms/src/Storages/Page/V3/Blob/BlobStat.cpp
  dbms/src/Storages/Page/V3/BlobStore.cpp
  dbms/src/Storages/Page/V3/BlobStore.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.cpp
  dbms/src/Storages/Page/V3/spacemap/SpaceMap.h
  dbms/src/Storages/Page/V3/spacemap/SpaceMapSTDMap.h
  dbms/src/Storages/Page/V3/tests/gtest_blob_stat.cpp
  dbms/src/Storages/Page/V3/tests/gtest_blob_store.cpp
  dbms/src/Storages/Page/V3/tests/gtest_free_map.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
Labels: size/XL, release-note, approved, lgtm

#9293 Compression: add microbenchmark
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/IO/Compression/tests/CodecTestSequence.h
  dbms/src/IO/Compression/tests/bench_codec.cpp
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9255 Fix the wrong result bug when casting string as datetime with time zone or illegal chars
  dbms/src/Common/MyTime.cpp
  dbms/src/Common/tests/gtest_mytime.cpp
Labels: release-note, size/M, approved, lgtm

#9300 fix cast to decimal wrong sign
  dbms/src/Functions/FunctionsTiDBConversion.h
  tests/fullstack-test/expr/cast_as_decimal.test
Labels: release-note-none, size/M, approved, lgtm

#9267 Storages: Fix obtaining incorrect column information when there are virtual columns in the query (release-7.1)
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  tests/fullstack-test/expr/generated_columns.test
  tests/fullstack-test/expr/generated_columns2.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9305 fix mac build
  dbms/src/Interpreters/Aggregator.h
Labels: size/XS, release-note-none, approved, lgtm

#9310 tests: Fix unstable unit-tests
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9299 Compression: optimize the CompressionCodecFactory
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/IO/Compression/CompressedReadBufferBase.cpp
  dbms/src/IO/Compression/CompressedWriteBuffer.cpp
  dbms/src/IO/Compression/CompressionCodecDeflateQpl.cpp
  dbms/src/IO/Compression/CompressionCodecDeflateQpl.h
  dbms/src/IO/Compression/CompressionCodecDeltaFOR.cpp
  dbms/src/IO/Compression/CompressionCodecDeltaFOR.h
  dbms/src/IO/Compression/CompressionCodecFOR.cpp
  dbms/src/IO/Compression/CompressionCodecFOR.h
  dbms/src/IO/Compression/CompressionCodecFactory.cpp
  dbms/src/IO/Compression/CompressionCodecFactory.h
  dbms/src/IO/Compression/CompressionCodecLZ4.h
  dbms/src/IO/Compression/CompressionCodecLightweight.cpp
  dbms/src/IO/Compression/CompressionCodecLightweight.h
  dbms/src/IO/Compression/CompressionCodecMultiple.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.h
  dbms/src/IO/Compression/CompressionCodecNone.h
  dbms/src/IO/Compression/CompressionCodecRunLength.cpp
  dbms/src/IO/Compression/CompressionCodecRunLength.h
  dbms/src/IO/Compression/CompressionCodecZSTD.h
  dbms/src/IO/Compression/CompressionFactory.h
  dbms/src/IO/Compression/CompressionInfo.h
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/IO/Compression/ICompressionCodec.h
  dbms/src/IO/Compression/tests/CodecTestSequence.h
  dbms/src/IO/Compression/tests/bench_codec.cpp
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9311 UniPS: Provide more information when meets exception in updateLocalCacheForRemotePage
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9297 Disagg: Fix the issue that lifetime of read-snapshots in WN may be longer than expected
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
Labels: size/L, release-note, approved, lgtm

#9288 Storages: Add whether has null in the result of MinMaxIndex
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/Filter/Like.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/Index/RSResult.cpp
  dbms/src/Storages/DeltaMerge/Index/RSResult.h
  dbms/src/Storages/DeltaMerge/Index/RoughCheck.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_rs_result.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9304 *: add workflow in CMakePresets
  CMakePresets.json
  README.md
Labels: release-note-none, size/L, approved, lgtm

#9323 Compression: fix zstd compression level be negative number
  dbms/src/IO/Compression/CompressionCodecFactory.cpp
  dbms/src/IO/Compression/tests/gtest_codec_factory.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-8.3

#9319 PageStorage: Fix TiFlash may fail to restart after FAP is enabled
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectoryFactory.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/tests/gtest_page_directory.cpp
Labels: release-note-none, size/L, approved, lgtm

#9326 *: Update the description of MacOS build
  README.md
  release-darwin/README.md
Labels: release-note-none, size/S, approved, lgtm

#9333 build: make `cmake --install` work well
  CMakeLists.txt
Labels: size/XS, release-note-none, approved, lgtm

#9341 *: Vector Data types and Functions
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/IColumn.h
  dbms/src/DataTypes/DataTypeArray.h
  dbms/src/Debug/MockExecutor/AstToPB.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Flash/Coprocessor/ArrowColCodec.cpp
  dbms/src/Flash/Coprocessor/DAGCodec.cpp
  dbms/src/Flash/Coprocessor/DAGCodec.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/Coprocessor/TiDBChunk.cpp
  dbms/src/Flash/Coprocessor/TiDBColumn.cpp
  dbms/src/Flash/Coprocessor/TiDBColumn.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Functions/FunctionHelpers.h
  dbms/src/Functions/FunctionsVector.cpp
  dbms/src/Functions/FunctionsVector.h
  dbms/src/Functions/registerFunctions.cpp
  dbms/src/Functions/tests/gtest_vector.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/TiDB/Decode/DatumCodec.cpp
  dbms/src/TiDB/Decode/DatumCodec.h
  dbms/src/TiDB/Decode/RowCodec.cpp
  dbms/src/TiDB/Decode/TypeMapping.cpp
  dbms/src/TiDB/Decode/Vector.cpp
  dbms/src/TiDB/Decode/Vector.h
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDBTypes.h
Labels: size/XXL, release-note, approved, lgtm

#9339 ddl: Remove field "comment" from TiDB::TableInfo
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncMockTiDBTable.cpp
  dbms/src/Debug/dbgFuncMockTiDBTable.h
  dbms/src/Debug/dbgKVStore/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Interpreters/tests/gtest_interpreter_create_query.cpp
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/RaftConfigParser.cpp
  dbms/src/Server/RaftConfigParser.h
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
  tests/delta-merge-test/raft/bugs/FLASH-484.test
  tests/delta-merge-test/raft/ingest_sst.test
  tests/delta-merge-test/raft/read_with_specify_tso.test
  tests/delta-merge-test/raft/region_merge.test
  tests/delta-merge-test/raft/region_merge_common_handle.test
  tests/delta-merge-test/raft/remove_region.test
  tests/delta-merge-test/raft/remove_region_common_handle.test
  tests/delta-merge-test/raft/schema/alter_for_nullable.test
  tests/delta-merge-test/raft/schema/alter_on_read.test
  tests/delta-merge-test/raft/schema/alter_on_write.test
  tests/delta-merge-test/raft/schema/concurrent_ddl_conflict.test
  tests/delta-merge-test/raft/schema/default_value.test
  tests/delta-merge-test/raft/schema/drop_on_read.test
  tests/delta-merge-test/raft/schema/drop_on_restart.test
  tests/delta-merge-test/raft/schema/mydate.test
  tests/delta-merge-test/raft/schema/rename_column.test
  tests/delta-merge-test/raft/schema/truncate_on_read.test
  tests/delta-merge-test/raft/snapshot.test
  tests/delta-merge-test/raft/snapshot_common_handle.test
  tests/delta-merge-test/raft/snapshot_dtfile.test
  tests/delta-merge-test/raft/sync_table_from_raft.test
  tests/delta-merge-test/raft/sync_table_from_raft_common_handle.test
Labels: size/XL, release-note-none, approved, lgtm

#9328 Storage: let segment meta using protobuf format
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/DMChecksumConfig.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileMeta.h
  dbms/src/Storages/DeltaMerge/RestoreDMFile.cpp
  dbms/src/Storages/DeltaMerge/RestoreDMFile.h
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/dtpb/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/dtpb/dmfile.proto
  dbms/src/Storages/DeltaMerge/dtpb/segment.proto
  dbms/src/Storages/DeltaMerge/tests/gtest_segment.cpp
  dbms/src/Storages/FormatVersion.h
Labels: size/XXL, release-note-none, approved, lgtm

#9342 Compression: fix lz4/lz4hc/zstd map concurrent insert
  dbms/src/IO/Compression/CompressionCodecFactory.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9335 Disagg: Reduce the number of threads created for handling disaggregated requests
  dbms/src/Common/UniThreadPool.cpp
  dbms/src/Common/UniThreadPool.h
  dbms/src/IO/IOThreadPools.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/workload/MainEntry.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: size/L, release-note, approved, lgtm

#9318 Storages: Skip filter if all data match in Min-Max index
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Core/tests/gtest_block.cpp
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9193 KVStore: Refine parallel prehandle snapshot (part-2)
  dbms/src/DataStreams/RuntimeFilter.cpp
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Decode/SSTScanSoftLimit.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/KVStore/FFI/SSTReader.cpp
  dbms/src/Storages/KVStore/FFI/SSTReader.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: size/XL, release-note-none, approved, lgtm

#9349 storage: Add vector search metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
Labels: release-note-none, size/M, approved, lgtm

#9361 Storages: Skip filtering for filter column
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: release-note-none, size/L, approved, lgtm

#9364 avoid potential TiFlash crash in `NonJoinedBlockInputStream`
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Planner/plans/PhysicalJoin.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#9343 Storage: support restore segments from checkpoint with format version V7
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile_V3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9362 Set thread name for seg task scheduler
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#9371 storage: Add keyspace_id to DT system tables
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
Labels: release-note-none, size/S, approved, lgtm

#9370 storage: Fix TiFlash system tables cannot query in Keyspace Mode
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
Labels: release-note-none, size/S, approved, lgtm

#9373 Storages: Fix comparing null in MinMaxIndex
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/RoughCheck.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  tests/fullstack-test-dt/expr/compare_null.test
Labels: size/XL, release-note-none, approved, lgtm

#9366 build: Fix duplicate symbol error of string.h
  libs/libarm-optimized-routines/aor.cpp
Labels: release-note-none, size/M, approved, lgtm

#9379 storage: Add system.dt_local_indexes
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Index/IndexInfo.h
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.h
  dbms/src/Storages/System/attachSystemTables.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9381 tests: update the number of read threads in unittest
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9382 Disagg: Wait tasks in thread pool finished before return
  dbms/src/IO/IOThreadPools.h
  dbms/src/IO/tests/gtest_io_thread.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/L, approved, lgtm

#9082 Pipeline: use notify instead of polling for `AggregateRestoreSourceOp`
  dbms/src/Operators/AggregateRestoreSourceOp.cpp
  dbms/src/Operators/AggregateRestoreSourceOp.h
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/SharedAggregateRestorer.h
Labels: release-note-none, size/M, approved, lgtm

#9380 storage: refine DeltaMergeStore
  dbms/CMakeLists.txt
  dbms/src/Common/NotNull.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9386 unittest: Fix ASAN reports of SkippableBlockInputStreamTest
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9390 tests: Refine the README of running integration tests
  README.md
  tests/README.md
Labels: release-note-none, size/L, approved, lgtm
