Repository pingcap/tiflash, pull requests merged in 2024-11, with the labels that each got.

#9577 build: fix darwin build
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9583 Minor refine `Join`
  dbms/src/DataStreams/HashJoinProbeBlockInputStream.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.cpp
  dbms/src/DataStreams/ScanHashMapAfterProbeBlockInputStream.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
Labels: release-note-none, size/M, approved, lgtm

#9560 Add two value logical op
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Planner/Plans/PhysicalFilter.cpp
  dbms/src/Functions/FunctionsLogical.cpp
  dbms/src/Functions/FunctionsLogical.h
  dbms/src/Functions/tests/bench_function_logical_op.cpp
  dbms/src/Functions/tests/gtest_two_value_logical.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9592 KVStore: Fix spurious region overlap when two region are both applying snapshots
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
Labels: release-note-none, size/L, cherry-pick-approved, approved, lgtm

#9572 build: use llvm@17 in darwin
  README.md
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  release-darwin/build/build-release.sh
  release-darwin/prepare-environments/prepare-llvm.sh
Labels: release-note-none, size/M, approved, lgtm

#9587 *: upgarde all docker images to use rocky linux 8
  .github/licenserc.yml
  .gitignore
  README.md
  release-centos7-llvm/Makefile
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/install_cmake.sh
  release-centos7-llvm/dockerfiles/misc/prepare_basic.sh
  release-centos7-llvm/dockerfiles/tiflash-llvm-base-aarch64
  release-linux-llvm/Makefile
  release-linux-llvm/README.md
  release-linux-llvm/dockerfiles/Dockerfile-tiflash-ci
  release-linux-llvm/dockerfiles/Dockerfile-tiflash-ci-base
  release-linux-llvm/dockerfiles/Dockerfile-tiflash-llvm-base
  release-linux-llvm/dockerfiles/Dockerfile-tiflash-rocky8
  release-linux-llvm/dockerfiles/misc/bake_llvm_base.sh
  release-linux-llvm/dockerfiles/misc/bootstrap_llvm.sh
  release-linux-llvm/dockerfiles/misc/cargo-config
  release-linux-llvm/dockerfiles/misc/install_ccache.sh
  release-linux-llvm/dockerfiles/misc/install_cmake.sh
  release-linux-llvm/dockerfiles/misc/install_openssl.sh
  release-linux-llvm/dockerfiles/misc/install_rust.sh
  release-linux-llvm/dockerfiles/misc/prepare_basic.sh
  release-linux-llvm/env/.gitignore
  release-linux-llvm/env/Makefile
  release-linux-llvm/env/README.md
  release-linux-llvm/env/loader
  release-linux-llvm/env/loader-env-dump
  release-linux-llvm/env/prepare-sysroot.sh
  release-linux-llvm/env/tiflash-linker
  release-linux-llvm/gen_coverage.sh
  release-linux-llvm/scripts/build-asan.sh
  release-linux-llvm/scripts/build-debug.sh
  release-linux-llvm/scripts/build-release.sh
  release-linux-llvm/scripts/build-tiflash-release.sh
  release-linux-llvm/scripts/build-tsan.sh
  release-linux-llvm/scripts/fix_compile_commands.py
  release-linux-llvm/scripts/perf-autofdo-llvm.py
  release-linux-llvm/scripts/run-clang-tidy.py
Labels: size/XL, release-note-none, approved, lgtm

#9594 refine resource group task_count metric
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: release-note-none, size/M, approved, lgtm

#9606 Fix the bug that `cloneFullColumn` does not clone the subcolumns at the second and higher levels
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/tests/gtest_column_misc.cpp
Labels: release-note-none, size/M, approved, lgtm

#9597 Storages: Optimize vector search in scenarios with updates
  dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
  dbms/src/DataStreams/SquashingBlockInputStream.cpp
  dbms/src/DataStreams/SquashingBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/WithANNQueryInfo.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/VectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9603 fix substring wrong result bug
  dbms/src/Functions/FunctionsString.cpp
  tests/fullstack-test/expr/substring_utf8.test
Labels: release-note-none, size/S, approved, lgtm

#9611 Storage: Refine the snapshot creation on DeltaValueSpace
  dbms/src/DataStreams/RuntimeFilter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator_fwd.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/TestUtils/ColumnGenerator.h
Labels: size/XL, release-note-none, approved, lgtm

#9602 Fix the fail start of tiflash because of the zero division when getting cpu number
  dbms/src/Common/getNumberOfCPUCores.cpp
  dbms/src/Common/tests/gtest_miscellaneous.cpp
Labels: release-note, size/M, approved, lgtm

#9610 fix lpad/rpad trailing zero miss
  dbms/src/Functions/FunctionsString.cpp
  tests/fullstack-test/expr/pad.test
Labels: release-note, size/M, approved, lgtm

#9628 ddl: Fix unstable test "fullstack-test/mpp/rollup_tpcds.test"
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
Labels: release-note-none, size/L, approved, lgtm

#9615 fix error when first argument of replace function is const
  dbms/src/Functions/FunctionsStringReplace.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Functions/GatherUtils/Algorithms.h
  dbms/src/Functions/tests/gtest_strings_replace.cpp
  tests/fullstack-test/expr/replace.test
Labels: size/XL, release-note, approved, lgtm

#9649 Storages: some minor refine
  dbms/src/Functions/tests/gtest_strings_replace.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Decode/BoundedSSTFilesToBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_version_filter.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9629 *: Simplify the code of executing "CREATE TABLE"
  dbms/src/Databases/DatabasesCommon.cpp
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/Interpreters/tests/gtest_interpreter_create_query.cpp
  dbms/src/Parsers/ASTCreateQuery.h
  dbms/src/Parsers/ASTQueryWithOutput.cpp
  dbms/src/Parsers/ParserCreateQuery.cpp
  dbms/src/Parsers/ParserCreateQuery.h
  dbms/src/Storages/KVStore/tests/gtest_sync_schema.cpp
  dbms/src/Storages/StorageFactory.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9614 Improve s3 random file by introducing cache
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/IO/BaseFile/MemoryRandomAccessFile.h
  dbms/src/IO/BaseFile/PosixRandomAccessFile.h
  dbms/src/IO/BaseFile/RandomAccessFile.h
  dbms/src/IO/Buffer/ReadBuffer.h
  dbms/src/IO/Buffer/ReadBufferFromRandomAccessFile.cpp
  dbms/src/IO/Buffer/ReadBufferFromRandomAccessFile.h
  dbms/src/IO/Encryption/EncryptedRandomAccessFile.h
  dbms/src/IO/FileProvider/ReadBufferFromRandomAccessFileBuilder.cpp
  dbms/src/IO/FileProvider/ReadBufferFromRandomAccessFileBuilder.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPWriteDataSource.h
  dbms/src/Storages/Page/V3/Universal/S3PageReader.cpp
  dbms/src/Storages/Page/V3/Universal/S3PageReader.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/tests/gtest_remote_read.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.h
  dbms/src/TestUtils/TiFlashTestBasic.cpp
  dbms/src/TestUtils/TiFlashTestBasic.h
Labels: size/XL, release-note-none, approved, lgtm

#9655 Abort uploading checkpoint if s3 lock client is not initialized
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-8.5

#9656 *: Fix build and readme in llvm17
  README.md
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
Labels: release-note-none, size/M, approved, lgtm

#9553 Add countSerializeByteSize/serializeToPos/deserializeAndInsertFromPos interface to IColumn
  dbms/CMakeLists.txt
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.cpp
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_misc.cpp
  dbms/src/Columns/tests/gtest_column_serialize_deserialize.cpp
  dbms/src/Common/ColumnsAlignBuffer.h
  dbms/src/Common/PODArray.h
  dbms/src/Common/tests/gtest_pod_array.cpp
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/DataStreams/PrettyBlockOutputStream.cpp
  dbms/src/DataTypes/DataTypeArray.cpp
  dbms/src/DataTypes/DataTypeFixedString.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Functions/FunctionsConversion.h
  dbms/src/Functions/FunctionsGrouping.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Interpreters/AggregationCommon.h
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Storages/DeltaMerge/convertColumnTypeHelpers.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9601 Support collation in `position` function
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/Functions/tests/gtest_strings_position.cpp
  dbms/src/TiDB/Collation/Collator.cpp
  dbms/src/TiDB/Collation/Collator.h
Labels: size/XXL, release-note, approved, lgtm

#9668 `WindowTransformAction::tryCalculate()` calculate at most 1 block result at a time
  dbms/src/DataStreams/WindowBlockInputStream.cpp
  dbms/src/DataStreams/WindowBlockInputStream.h
  dbms/src/Operators/WindowTransformOp.cpp
  dbms/src/TestUtils/WindowTestUtils.h
  dbms/src/WindowFunctions/tests/gtest_lead_lag.cpp
Labels: release-note-none, size/L, approved, lgtm

#9677 Storages: remove ColumnFileTiny cache
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.h
  dbms/src/Storages/DeltaMerge/PKSquashingBlockInputStream.h
Labels: size/XL, release-note-none, approved, lgtm

#9682 Refine & Optimize `deserializeAndInsertFromPos` and NTAlignBuffer
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_serialize_deserialize.cpp
  dbms/src/Common/ColumnNTAlignBuffer.h
  dbms/src/Common/ColumnsAlignBuffer.h
  dbms/src/Common/memcpySmall.h
Labels: size/XXL, release-note-none, approved, lgtm
