Repository pingcap/tiflash, pull requests merged in 2024-04, with the labels that each got.

#8878 remove implicit up bound of active query soft limit
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#8888 fix the issue that building tiflash in mac fail introduced by #8872
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPoolMetrics.cpp
Labels: release-note-none, size/M, approved, lgtm

#8892 Static dispatch Arm-optimized-routines instead of dynamic dispatch
  contrib/arm-optimized-routines-cmake/CMakeLists.txt
  contrib/arm-optimized-routines-cmake/src/aor.c
  libs/CMakeLists.txt
  libs/libarm-optimized-routines/CMakeLists.txt
  libs/libarm-optimized-routines/aor.cpp
  libs/libarm-optimized-routines/aor.h
  libs/libcommon/CMakeLists.txt
Labels: size/XL, release-note-none, approved, lgtm

#8894 logging: Fix `local_region_num` in MPPTaskStatistics logging
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
Labels: size/XS, release-note, cherry-pick-approved, approved, lgtm

#8883 KVStore: Record bypass lock in resolve lock
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/Region.cpp
Labels: release-note-none, size/S, approved, lgtm

#8896 logging: Fix `local_region_num` in MPPTaskStatistics logging
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
Labels: size/XS, release-note, cherry-pick-approved, approved, lgtm

#8907 Fix the unexpected exception "The equal condition from in column should be nullable, otherwise it should be used as join key"
  dbms/src/Interpreters/SemiJoinHelper.cpp
  tests/fullstack-test/issues/issue_8811.test
Labels: release-note, size/M, approved, lgtm

#8906 do not mark spill if there is no data to spill in auto spill mode
  dbms/src/Interpreters/AggSpillContext.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/HashJoinSpillContext.cpp
  dbms/src/Interpreters/SortSpillContext.cpp
  dbms/src/Interpreters/tests/gtest_operator_spill_context.cpp
  dbms/src/Operators/AggregateContext.cpp
Labels: release-note-none, size/M, approved, lgtm

#8909 Revert "Storage: Refactor DMFileReader"
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnCache.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnCache.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: size/XXL, release-note-none, skip-issue-check, approved, lgtm

#8910 ddl: Do not succee the last_gc_safepoint when physically dropping table is skipped
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
Labels: size/XS, release-note-none, approved, lgtm

#8921 Disagg: fix used size metrics of FileCache
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: release-note-none, size/S, approved, lgtm

#8922 tests: Add code coverage scripts
  .gitignore
  CMakePresets.json
  README.md
  release-centos7-llvm/gen_coverage.sh
Labels: release-note-none, size/L, approved, lgtm

#8925 Add insertMany interface for IColumn
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/tests/gtest_column_insertFrom.cpp
  tests/tidb-ci/fullstack-test-dt/timestamp_with_timezone.test
Labels: release-note-none, size/L, approved, lgtm

#8930 *: Keep clang13
  .toolchain.yml
  README.md
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/bootstrap_llvm.sh
Labels: release-note-none, size/M, approved, lgtm

#8931 *: Keep clang13 (release-8.1)
  .toolchain.yml
  README.md
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/bootstrap_llvm.sh
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#8942 catch exception of LocalAdmissionController::stop()
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/M, approved, lgtm

#8944 *: Fix compile error
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.h
Labels: size/XS, release-note-none, approved, lgtm

#8951 fix GeneratedColumnPlaceHolderTransformAction header
  dbms/src/DataStreams/GeneratedColumnPlaceHolderTransformAction.cpp
  tests/fullstack-test/mpp/generated_column.test
Labels: release-note-none, size/M, approved, lgtm

#8950 tests: add tests for timestamp with timezone
  contrib/libunwind-cmake/CMakeLists.txt
  tests/tidb-ci/fullstack-test-dt/timestamp_with_timezone.test
Labels: release-note-none, size/M, approved, lgtm

#8953 Fix AsyncTasks cancel deadlock
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/SharedContexts/Disagg.cpp
  dbms/src/Interpreters/SharedContexts/Disagg.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerContext.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerContext.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: release-note-none, size/M, component/storage, approved, lgtm

#8820 Support Delta/RLE encoding and multiple compression
  .gitmodules
  dbms/CMakeLists.txt
  dbms/src/CMakeLists.txt
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/IO/Compression/CompressedReadBufferBase.cpp
  dbms/src/IO/Compression/CompressionCodecDelta.cpp
  dbms/src/IO/Compression/CompressionCodecDelta.h
  dbms/src/IO/Compression/CompressionCodecMultiple.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.h
  dbms/src/IO/Compression/CompressionCodecRLE.cpp
  dbms/src/IO/Compression/CompressionCodecRLE.h
  dbms/src/IO/Compression/CompressionFactory.h
  dbms/src/IO/Compression/CompressionInfo.h
  dbms/src/IO/Compression/CompressionMethod.h
  dbms/src/IO/Compression/CompressionSettings.cpp
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/IO/Compression/ICompressionCodec.h
  dbms/src/IO/Compression/tests/bench_codec_delta.cpp
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8955 ddl: Fix logging cause by non-dropped table
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-7.5

#8959 *: fix release build when enable PCH
  contrib/protobuf-cmake/CMakeLists.txt
  dbms/CMakeLists.txt
  dbms/src/IO/Compression/CompressionCodecDelta.cpp
Labels: release-note-none, size/S, approved, lgtm

#8963 Storages: Refine log
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.cpp
  dbms/src/Operators/DMSegmentThreadSourceOp.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkers.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_reader.cpp
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/RegionQueryInfo.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8964 Storages: Change CompressionCodecPtr from shared_ptr to unique_ptr
  dbms/src/IO/Compression/CompressionCodecLZ4.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.cpp
  dbms/src/IO/Compression/CompressionCodecMultiple.h
  dbms/src/IO/Compression/CompressionCodecZSTD.cpp
  dbms/src/IO/Compression/CompressionFactory.h
  dbms/src/IO/Compression/ICompressionCodec.h
Labels: release-note-none, size/M, approved, lgtm

#8965 *: some streams do not need to inherit IProfilingBlockInputStream
  dbms/CMakeLists.txt
  dbms/src/DataStreams/AddExtraTableIDColumnInputStream.cpp
  dbms/src/DataStreams/AddExtraTableIDColumnInputStream.h
  dbms/src/DataStreams/AddingConstColumnBlockInputStream.h
  dbms/src/DataStreams/IProfilingBlockInputStream.h
  dbms/src/Dictionaries/CacheDictionary.cpp
  dbms/src/Dictionaries/CacheDictionary.h
  dbms/src/Dictionaries/ComplexKeyCacheDictionary.cpp
  dbms/src/Dictionaries/ComplexKeyCacheDictionary.h
  dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp
  dbms/src/Dictionaries/ComplexKeyHashedDictionary.h
  dbms/src/Dictionaries/DictionaryBlockInputStream.h
  dbms/src/Dictionaries/DictionaryBlockInputStreamBase.cpp
  dbms/src/Dictionaries/DictionaryBlockInputStreamBase.h
  dbms/src/Dictionaries/DictionaryFactory.h
  dbms/src/Dictionaries/FlatDictionary.cpp
  dbms/src/Dictionaries/FlatDictionary.h
  dbms/src/Dictionaries/HashedDictionary.cpp
  dbms/src/Dictionaries/HashedDictionary.h
  dbms/src/Dictionaries/IDictionary.h
  dbms/src/Dictionaries/RangeDictionaryBlockInputStream.h
  dbms/src/Dictionaries/RangeHashedDictionary.cpp
  dbms/src/Dictionaries/RangeHashedDictionary.h
  dbms/src/Dictionaries/TrieDictionary.cpp
  dbms/src/Dictionaries/TrieDictionary.h
  dbms/src/Interpreters/DictionaryFactory.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.h
Labels: size/XXL, release-note-none, approved, lgtm

#8970 *: Refine the code in settings
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
Labels: release-note-none, size/L, skip-issue-check, approved, lgtm

#8971 Storages: Remove some `DBMS_PUBLIC_GTEST` hacks
  dbms/src/Storages/DeltaMerge/ReadThread/MergedTask.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
Labels: release-note-none, size/L, approved, lgtm

#8972 tests: Fix unstable schema test
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/TiDBSchemaManager.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: release-note-none, size/L, approved, lgtm

#8973 Storage: Refine logging about reading snap, place index, index to wait
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
Labels: release-note-none, size/L, approved, lgtm

#8979 KVStore: Add some log for Learner Read
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexDataNode.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorkerManager.cpp
Labels: release-note-none, size/M, approved, lgtm

#8969 Common: support bitpacking
  contrib/CMakeLists.txt
  contrib/fastpforlib/CMakeLists.txt
  contrib/fastpforlib/LICENSE
  contrib/fastpforlib/bitpacking.cpp
  contrib/fastpforlib/bitpacking.h
  contrib/fastpforlib/bitpackinghelpers.h
  dbms/CMakeLists.txt
  dbms/src/Common/BitpackingPrimitives.h
  dbms/src/Common/tests/gtest_bitpacking_primitives.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8989 KVStore: Fix exception in FAP worker
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerContext.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-8.1

#8991 KVStore: Log when meets any commit_ts < observed max_read_tso
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
Labels: release-note-none, size/M, approved, lgtm

#8917 tests: Fix unstable test alter_pk
  tests/fullstack-test2/ddl/alter_pk.test
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#8994 tests: Remove `DBMS_PUBLIC_GTEST` hack in SegmentReadTask
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8997 Storages: Use template to replace macro in RSOperator
  dbms/src/Storages/DeltaMerge/Filter/Equal.h
  dbms/src/Storages/DeltaMerge/Filter/Greater.h
  dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/Less.h
  dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
  dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
Labels: release-note-none, size/M, approved, lgtm

#8927 Storage: Refactor DMFileReader
  dbms/src/Storages/DeltaMerge/File/ColumnCache.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnCache.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  release-centos7-llvm/gen_coverage.sh
Labels: size/XXL, release-note-none, approved, lgtm

#8943 *: Add http docs for TiFlash
  README.md
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  docs/tiflash_http_api.md
  release-centos7-llvm/gen_coverage.sh
Labels: release-note-none, size/L, approved, lgtm

#9000 Storages: Fix cloning delta index when there are duplicated tuples
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/DeltaPlace.h
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9014 Storages: Fix cloning delta index when there are duplicated tuples (release-8.1) (#9000)
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/DeltaPlace.h
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/ReadThread/UnorderedInputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm
