Repository pingcap/tiflash, pull requests merged in 2024-03, with the labels that each got.

#8807 disagg: Set client RPC timeout for FetchDisaggPages
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
Labels: size/XS, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#8816 ddl: Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed (release-6.5)
  .clang-format
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/_env.sh
  tests/fullstack-test/issues/issue_8601.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8805 KVStore: Track memory usage in Lock CF
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_spill.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8821 disagg: Set client RPC timeout for FetchDisaggPages
  dbms/src/Core/Defines.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerFetchPages.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/S, cherry-pick-approved, approved, lgtm

#8825 Fix jemalloc build on Mac
  contrib/jemalloc-cmake/include/jemalloc/internal/jemalloc_preamble.h
  libs/libcommon/cmake/find_jemalloc.cmake
Labels: release-note-none, size/S, approved, lgtm

#8827 Add CMakePresets.json and some common pre-defined cmake presets
  CMakePresets.json
Labels: release-note-none, size/L, approved, lgtm

#8676 Storage: Add the time cost about stream in local/remote
  dbms/src/Flash/Statistics/TableScanImpl.cpp
  dbms/src/Flash/Statistics/TableScanImpl.h
  dbms/src/Operators/IOProfileInfo.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
Labels: release-note-none, size/M, approved, lgtm

#8833 KVStore: Enhance o11y of large txn
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToDTFilesOutputStream.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataTrait.h
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.h
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
Labels: release-note-none, size/L, approved, lgtm

#8847 Fix jemalloc crash on mac
  contrib/jemalloc-cmake/CMakeLists.txt
  contrib/jemalloc-cmake/include/jemalloc/jemalloc.h
  contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h
  contrib/jemalloc-cmake/include/jemalloc/jemalloc_rename.h.in
  contrib/jemalloc-cmake/include_darwin_aarch64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_darwin_x86_64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_freebsd_aarch64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_freebsd_x86_64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_linux_aarch64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_linux_ppc64le/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_linux_riscv64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_linux_x86_64/jemalloc/internal/jemalloc_internal_defs.h.in
  contrib/jemalloc-cmake/include_linux_x86_64_musl/jemalloc/internal/jemalloc_internal_defs.h.in
  dbms/src/Interpreters/AsynchronousMetrics.cpp
Labels: release-note-none, size/L, approved, lgtm

#8846 Add integration test for div_precision_increment support
  tests/fullstack-test2/variables/set_variable_div_precision_increment.test
Labels: release-note-none, size/M, approved, lgtm

#8848 disagg: Fix a potential crash when shutting down
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
Labels: size/S, release-note, approved, lgtm

#8855 KVStore: Fix FFI in disagg mode
  dbms/src/Storages/KVStore/FFI/ProxyFFI.h
Labels: size/XS, release-note-none, approved, lgtm

#8850 Schema: replace invalid default value to zero value under not strict sql mode
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
  dbms/src/IO/ReadHelpers.h
  dbms/src/TiDB/Schema/TiDB.cpp
  tests/fullstack-test2/variables/set_sql_mode_ansi.test
Labels: size/XXL, release-note, approved, lgtm

#8858 Disable 3rd party allocators for sanitizer builds
  CMakeLists.txt
  libs/libcommon/cmake/find_jemalloc.cmake
  libs/libcommon/cmake/find_mimalloc.cmake
Labels: release-note-none, size/S, approved, lgtm

#8812 ddl: Fix an issue where a query may throw an error during a remote read and the precision of a duration data type is changed (release-7.1)
  .clang-format
  dbms/src/DataStreams/NativeBlockInputStream.cpp
  dbms/src/Encryption/tests/gtest_rate_limiter.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.h
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/_env.sh
  tests/fullstack-test/issues/issue_8601.test
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#8865 Monitor learner read failures
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#8866 *: more forward decl
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.cpp
  dbms/src/Flash/Disaggregated/WNFetchPagesStreamWriter.h
  dbms/src/Operators/DMSegmentThreadSourceOp.cpp
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/DMContext.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/DMVersionFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.h
  dbms/src/Storages/DeltaMerge/Remote/RNLocalPageCache.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNWorkerPrepareStreams.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/MultiSegmentTestUtil.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.cpp
  dbms/src/Storages/S3/tests/gtest_s3file.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#8857 Storages: Refine memory tracker of data sharing
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
  dbms/src/Storages/DeltaMerge/tests/gtest_column_sharing_cache.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#8853 Debug: Add find key debug invoker
  contrib/tiflash-proxy-cmake/CMakeLists.txt
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Debug/DBGInvoker.cpp
  dbms/src/Debug/MockKVStore/MockTiKV.h
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncInvestigator.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncInvestigator.h
  dbms/src/Debug/dbgKVStore/dbgFuncMockRaftCommand.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncMockRaftSnapshot.cpp
  dbms/src/Debug/dbgKVStore/dbgFuncRegion.cpp
  dbms/src/Debug/dbgNaturalDag.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/tests/gtest_async_tasks.cpp
Labels: size/XL, release-note-none, approved, lgtm

#8873 KVStore: Improve codes for read index worker
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Storages/KVStore/Read/AsyncNotifier.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.h
  dbms/src/Storages/KVStore/Read/Proxy.cpp
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexDataNode.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorker.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorkerImpl.h
  dbms/src/Storages/KVStore/Read/ReadIndexWorkerManager.cpp
  dbms/src/Storages/KVStore/Read/RegionException.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_read_index_worker.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note-none, approved, lgtm

#8874 Storages: log version of records if enabled
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task_pool.cpp
Labels: release-note-none, size/M, approved, lgtm

#8872 Pipeline: use `notify` instead of `polling` for `UnorderedSourceOp`
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipelineTaskBase.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
  dbms/src/Flash/Pipeline/Schedule/ThreadPool/TaskThreadPool.cpp
  dbms/src/Operators/Operator.h
  dbms/src/Operators/OperatorHelper.cpp
  dbms/src/Operators/UnorderedSourceOp.cpp
  dbms/src/Operators/UnorderedSourceOp.h
  dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: size/XL, release-note-none, approved, lgtm

#8877 adjust the up bound of task_scheduler_active_set_soft_limit
  dbms/src/Flash/Mpp/MinTSOScheduler.cpp
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm
