Repository pingcap/tiflash, pull requests merged in 2024-10, with the labels that each got.

#9498 remove useless function in `TaskProfileInfo`
  dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h
Labels: size/XS, release-note-none, approved, lgtm

#9492 ddl: Remove useless serialized result of `ColumnInfo`
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
  dbms/src/VectorSearch/USearch.h
Labels: release-note-none, size/M, approved, lgtm

#9503 storage: Fix vector index not used
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9504 Storage: Abort adding vector index if encryption enabled
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileV3IncrementWriter.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
Labels: release-note-none, do-not-merge/hold, size/M, approved, lgtm

#9507 Support other integer types for SubstringUTF8 & RightUTF8 functions
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_string_left.cpp
  dbms/src/Functions/tests/gtest_strings_right.cpp
  dbms/src/Functions/tests/gtest_substring.cpp
  dbms/src/TestUtils/FunctionTestUtils.h
  tests/fullstack-test/expr/substring_utf8.test
Labels: size/XXL, release-note-none, approved, lgtm

#9518 *: fix bench_dbms build
  dbms/src/Storages/DeltaMerge/tests/bench_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/bench_vector_index_utils.h
Labels: size/XS, release-note-none, approved, lgtm

#9520 tests: Fix asan check failures
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: release-note-none, size/M, approved, lgtm

#9509 tests: Refine integration tests
  release-centos7-llvm/env/.gitignore
  tests/docker/config/tics_dt.toml
  tests/docker/config/tiflash_dt.toml
  tests/docker/config/tiflash_dt_disable_local_tunnel.toml
  tests/docker/config/tiflash_dt_force_enable_lm.toml
  tests/docker/config/tiflash_dt_lightweight_compression.toml
  tests/docker/config/tiflash_dt_sync_grpc.toml
  tests/docker/run.sh
  tests/docker/tiflash-dt-disable-local-tunnel.yaml
  tests/docker/tiflash-dt-force-enable-lm.yaml
  tests/docker/tiflash-dt-lightweight-compression.yaml
  tests/docker/tiflash-dt-sync-grpc.yaml
  tests/docker/tiflash-dt.yaml
  tests/docker/tiflash-tagged-image.yaml
  tests/docker/util.sh
Labels: release-note-none, size/L, approved, lgtm

#9415 Support cancel when writing fap snapshots
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/ProfileEvents.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/CheckpointIngestInfo.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeerCache.h
  dbms/src/Storages/KVStore/Utils/AsyncTasks.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.cpp
  dbms/src/Storages/Page/V3/Universal/RaftDataReader.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
Labels: size/XXL, release-note-none, approved, lgtm

#9521 Storages: simplify read path
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ReadUtil.cpp
  dbms/src/Storages/DeltaMerge/ReadUtil.h
  dbms/src/Storages/DeltaMerge/RowKeyOrderedBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9525 metrics: Add Thread CPU panel for building vector index
  dbms/src/DataStreams/AsynchronousBlockInputStream.h
  dbms/src/DataStreams/ParallelInputsProcessor.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexWorkerImpl.h
  dbms/src/Storages/KVStore/Read/ReadIndexWorkerManager.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/L, release-note, approved, lgtm

#9519 *: Remove useless column serialize format
  cmake/find_poco.cmake
  dbms/CMakeLists.txt
  dbms/src/Core/BlockGen.h
  dbms/src/DataStreams/CSVRowInputStream.cpp
  dbms/src/DataStreams/CSVRowInputStream.h
  dbms/src/DataStreams/CSVRowOutputStream.cpp
  dbms/src/DataStreams/CSVRowOutputStream.h
  dbms/src/DataStreams/FormatFactory.cpp
  dbms/src/DataStreams/PrettySpaceBlockOutputStream.cpp
  dbms/src/DataStreams/PrettySpaceBlockOutputStream.h
  dbms/src/DataStreams/TSKVRowInputStream.cpp
  dbms/src/DataStreams/TSKVRowInputStream.h
  dbms/src/DataStreams/TSKVRowOutputStream.cpp
  dbms/src/DataStreams/TSKVRowOutputStream.h
  dbms/src/DataStreams/TabSeparatedRawRowOutputStream.h
  dbms/src/DataStreams/TabSeparatedRowInputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowInputStream.h
  dbms/src/DataStreams/TabSeparatedRowOutputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowOutputStream.h
  dbms/src/DataStreams/VerticalRowOutputStream.cpp
  dbms/src/DataStreams/VerticalRowOutputStream.h
  dbms/src/DataStreams/XMLRowOutputStream.cpp
  dbms/src/DataStreams/XMLRowOutputStream.h
  dbms/src/DataTypes/DataTypeAggregateFunction.cpp
  dbms/src/DataTypes/DataTypeAggregateFunction.h
  dbms/src/DataTypes/DataTypeArray.cpp
  dbms/src/DataTypes/DataTypeArray.h
  dbms/src/DataTypes/DataTypeDate.cpp
  dbms/src/DataTypes/DataTypeDate.h
  dbms/src/DataTypes/DataTypeDateTime.cpp
  dbms/src/DataTypes/DataTypeDateTime.h
  dbms/src/DataTypes/DataTypeDecimal.cpp
  dbms/src/DataTypes/DataTypeDecimal.h
  dbms/src/DataTypes/DataTypeEnum.cpp
  dbms/src/DataTypes/DataTypeEnum.h
  dbms/src/DataTypes/DataTypeFixedString.cpp
  dbms/src/DataTypes/DataTypeFixedString.h
  dbms/src/DataTypes/DataTypeMyDate.cpp
  dbms/src/DataTypes/DataTypeMyDate.h
  dbms/src/DataTypes/DataTypeMyDateTime.cpp
  dbms/src/DataTypes/DataTypeMyDateTime.h
  dbms/src/DataTypes/DataTypeNullable.cpp
  dbms/src/DataTypes/DataTypeNullable.h
  dbms/src/DataTypes/DataTypeNumberBase.cpp
  dbms/src/DataTypes/DataTypeNumberBase.h
  dbms/src/DataTypes/DataTypeString.cpp
  dbms/src/DataTypes/DataTypeString.h
  dbms/src/DataTypes/DataTypeTuple.cpp
  dbms/src/DataTypes/DataTypeTuple.h
  dbms/src/DataTypes/DataTypeUUID.cpp
  dbms/src/DataTypes/DataTypeUUID.h
  dbms/src/DataTypes/IDataType.h
  dbms/src/DataTypes/IDataTypeDummy.h
  dbms/src/Dictionaries/IDictionary.h
  dbms/src/IO/ReadHelpers.cpp
  dbms/src/IO/ReadHelpers.h
  dbms/src/IO/WriteHelpers.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  libs/libdaemon/src/BaseDaemon.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9530 Storage: Fix `getSquashDeleteRange` does not return correctly squashed key-range when using common-handle
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetSnapshot.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/Filter/FilterHelper.h
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
Labels: size/L, release-note, approved, lgtm

#9526 Storages: add unit test check read correctness when there is ColumnFileBig whose range is larger than segment range
  dbms/src/DataStreams/OneBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
Labels: release-note-none, size/L, approved, lgtm

#9528 Storages: fix outdated unit tests
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9531 tests: add unit-tests of BitmapFilter
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.h
Labels: release-note-none, size/L, approved, lgtm

#9532 build: Fix cmake preset command
  CMakePresets.json
Labels: size/XS, release-note-none, approved, lgtm

#9538 tests: fix unstable unittests
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: size/XS, release-note-none, approved, lgtm

#9527 Storages: Separate ColumnFileTinyReader & ColumnFileSetInputStream
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyReader.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9535 *: add TabSeparatedWithNames format back
  dbms/src/DataStreams/FormatFactory.cpp
  dbms/src/DataStreams/TabSeparatedRowInputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowInputStream.h
  dbms/src/DataStreams/TabSeparatedRowOutputStream.cpp
  dbms/src/DataStreams/TabSeparatedRowOutputStream.h
Labels: size/XXL, release-note-none, approved, lgtm

#9540 *: add TabSeparated format back
  dbms/src/DataStreams/FormatFactory.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9523 Refine logical op in TiFlash
  dbms/src/Functions/FunctionsLegacyLogical.h
  dbms/src/Functions/FunctionsLogical.cpp
  dbms/src/Functions/FunctionsLogical.h
  dbms/src/Functions/tests/bench_function_cast.cpp
  dbms/src/Functions/tests/bench_function_logical_op.cpp
  dbms/src/Functions/tests/gtest_logical.cpp
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
Labels: size/XXL, release-note-none, approved, lgtm

#9543 fix issue introduced by #9523
  dbms/src/Functions/FunctionsLogical.h
Labels: size/XS, release-note-none, approved, lgtm

#9534 Storages: support building vector index for ColumnFileTiny (Part 1)
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileMeta.h
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/dtpb/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/dtpb/column_file.proto
  dbms/src/Storages/DeltaMerge/dtpb/dmfile.proto
  dbms/src/Storages/DeltaMerge/dtpb/vector_index.proto
  dbms/src/Storages/DeltaMerge/tests/gtest_column_file_clone.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9548 Fix potential hang issues when fine grained shuffle is enabled
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9545 build: fix drawin build
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
Labels: size/XS, release-note-none, approved, lgtm

#9546 Storages: support building vector index for ColumnFileTiny (Part 2)
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9558 *: fix darwin build
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexWriter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9549 Storages: refactor DMFile vector search
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexWriter.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/VectorColumnFromIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/VectorColumnFromIndexReader.h
  dbms/src/Storages/DeltaMerge/File/VectorColumnFromIndexReader_fwd.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9564 test: fix unstable unit test
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9563 overwrite `addBatchSinglePlace` and `addBatchSinglePlaceNotNull` in `AggregateFunctionCountNotNullUnary`
  dbms/src/AggregateFunctions/AggregateFunctionCount.h
Labels: release-note-none, size/M, approved, lgtm

#9568 build: fix drawin build
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9556 ci: upgrade tiflash-ci-base image to use rocky linux8
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci
  release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci-base
  tests/docker/mock-test-dt.yaml
  tests/docker/tiflash-dt-disable-encrypt.yaml
  tests/docker/tiflash-dt-disable-local-tunnel.yaml
  tests/docker/tiflash-dt-force-enable-lm.yaml
  tests/docker/tiflash-dt-lightweight-compression.yaml
  tests/docker/tiflash-dt-sync-grpc.yaml
  tests/docker/tiflash-dt.yaml
Labels: release-note-none, size/S, approved, lgtm

#9547 Storages: support building vector index for ColumnFileTiny (Part 3)
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterView.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexCache.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9570 Disagg: refresh expiration time of snapshot when calling getSnapshot
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/FlashService.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.cpp
  dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.cpp
  dbms/src/Storages/DeltaMerge/Remote/WNDisaggSnapshotManager.h
Labels: release-note-none, size/M, approved, lgtm
