Repository pingcap/tiflash, pull requests merged in 2024-09, with the labels that each got.

#9391 storage: Force evict when downloading vector index files
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
  dbms/src/Storages/S3/tests/gtest_filecache.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9072 Pipeline: use notify instead of polling for `ExchangeSender`
  dbms/src/Common/GRPCQueue.h
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/WaitResult.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpptunnel.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.h
Labels: release-note-none, size/L, approved, lgtm

#9393 Disagg: Set the waiting time for thread pool.
  dbms/src/Common/UniThreadPool.cpp
  dbms/src/Common/UniThreadPool.h
  dbms/src/IO/tests/gtest_io_thread.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: release-note-none, size/L, approved, lgtm

#9387 Disagg: Add nullptr check on `S3LockLocalManager`
  dbms/src/Flash/Disaggregated/S3LockClient.cpp
  dbms/src/Storages/Page/V3/Universal/S3LockLocalManager.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9345 Improve the performance of `length` and `ascii` functions
  dbms/src/Functions/FunctionsNull.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/GatherUtils/Algorithms.h
  dbms/src/Functions/tests/bench_function_string.cpp
  dbms/src/Functions/tests/gtest_strings_ascii.cpp
  dbms/src/Functions/tests/gtest_strings_length.cpp
  dbms/src/Functions/tests/gtest_strings_position.cpp
  libs/libcommon/include/common/StringRef.h
Labels: size/XL, release-note-none, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9230 ddl: Skip updating the tombstone_ts if the table is already tombstone (release-6.5)
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9231 ddl: Skip updating the tombstone_ts if the table is already tombstone (release-7.1)
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  dbms/src/TiDB/Schema/SchemaBuilder.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/L, release-note, cherry-pick-approved, approved, lgtm

#9407 UniPS: Catch exception when dumping incr snapshot
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPFilesWriter.h
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.cpp
  dbms/src/Storages/Page/V3/CheckpointFile/CPManifestFileWriter.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorage.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageStorageService.cpp
  dbms/src/Storages/S3/S3RandomAccessFile.cpp
Labels: release-note-none, size/L, approved, lgtm

#9412 Storages: add metrics of read thread
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/ReadThread/SegmentReadTaskScheduler.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
Labels: release-note-none, size/S, approved, lgtm

#9312 Compression: Support enabling lightweight compression
  .clangd
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/IO/Compression/CompressionCodecDeltaFOR.cpp
  dbms/src/IO/Compression/CompressionCodecFOR.cpp
  dbms/src/IO/Compression/CompressionCodecFactory.cpp
  dbms/src/IO/Compression/CompressionCodecLZ4.cpp
  dbms/src/IO/Compression/CompressionCodecLZ4.h
  dbms/src/IO/Compression/CompressionCodecLightweight.cpp
  dbms/src/IO/Compression/CompressionCodecLightweight.h
  dbms/src/IO/Compression/CompressionCodecLightweight_Integer.cpp
  dbms/src/IO/Compression/CompressionCodecRunLength.cpp
  dbms/src/IO/Compression/CompressionCodecZSTD.h
  dbms/src/IO/Compression/CompressionSettings.cpp
  dbms/src/IO/Compression/CompressionSettings.h
  dbms/src/IO/Compression/EncodingUtil.cpp
  dbms/src/IO/Compression/EncodingUtil.h
  dbms/src/IO/Compression/tests/bench_codec.cpp
  dbms/src/IO/Compression/tests/gtest_codec_compression.cpp
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Server/tests/gtest_server_config.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  metrics/grafana/tiflash_summary.json
  tests/docker/config/tiflash_dt_lightweight_compression.toml
  tests/docker/tiflash-dt-lightweight-compression.yaml
  tests/tidb-ci/lightweight_compression
  tests/tidb-ci/run.sh
  tests/tidb-ci/tiflash-dt-lightweight-compression.yaml
Labels: size/XXL, release-note, approved, lgtm

#9414 ci: udpate OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: size/XS, release-note-none, approved, lgtm

#9416 Compression: enable lightweight temporarily
  dbms/src/IO/Compression/CompressionCodecLightweight.h
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9425 Add info log when pipeline even is scheduled
  dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9427 add more resource group metrics
  dbms/src/Common/ComputeLabelHolder.cpp
  dbms/src/Common/ComputeLabelHolder.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/L, approved, lgtm

#9081 Pipeline: use notify instead of polling for join probe
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/OneTimeNotifyFuture.h
  dbms/src/Flash/Planner/Plans/PhysicalJoinProbe.cpp
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
  dbms/src/Operators/HashJoinProbeTransformOp.h
  dbms/src/Operators/HashProbeTransformExec.cpp
  dbms/src/Operators/HashProbeTransformExec.h
Labels: release-note-none, size/L, approved, lgtm

#9432 storage: fix write stable meta twice when SegmentMerge and SegmentSplit
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
Labels: release-note-none, size/S, approved, lgtm

#9411 storage: Support adding vector index in background
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.h
  dbms/src/Storages/DeltaMerge/File/DMFileV3IncrementWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileV3IncrementWriter.h
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexCache.h
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_meta_version.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.h
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/FormatVersion.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
Labels: size/XXL, release-note-none, approved, lgtm

#9440 ddl: Do not physical drop table after tiflash replica is set to 0
  dbms/src/TiDB/Schema/SchemaBuilder.cpp
  tests/fullstack-test2/ddl/alter_table_tiflash_replica.test
Labels: release-note-none, size/S, approved, lgtm

#9442 ddl: Fix the physically drop storage instance may block removing regions
  dbms/src/Common/FailPoint.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Debug/dbgFuncSchema.cpp
  dbms/src/Debug/dbgFuncSchema.h
  dbms/src/Storages/Transaction/RegionTable.cpp
  dbms/src/Storages/Transaction/RegionTable.h
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  tests/fullstack-test2/ddl/alter_exchange_partition.test
  tests/fullstack-test2/ddl/flashback_database.test
Labels: size/XL, release-note-none, cherry-pick-approved, approved, lgtm

#9449 storage: support the HTTP API of sync table schema
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
  dbms/src/Storages/KVStore/tests/gtest_sync_schema.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: size/XL, release-note-none, approved, lgtm

#9450 join be aware of cancel signal
  dbms/src/DataStreams/AggregatingBlockInputStream.cpp
  dbms/src/DataStreams/HashJoinProbeExec.h
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/CancellationHook.h
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Interpreters/Join.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
  dbms/src/Interpreters/SemiJoinHelper.cpp
  dbms/src/Interpreters/SemiJoinHelper.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AggregateContext.h
  dbms/src/Operators/AutoPassThroughHashAggContext.h
Labels: size/L, release-note, approved, lgtm

#9447 disable some json functions pushdown
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
Labels: release-note-none, size/S, approved, lgtm

#9445 storage: long term cache for integer-like PK column in memory
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilterView.h
  dbms/src/Storages/DeltaMerge/DMContext.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/ColumnCacheLongTerm.h
  dbms/src/Storages/DeltaMerge/File/ColumnCacheLongTerm_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/VectorColumnFromIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ReadUtil.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.cpp
  dbms/src/Storages/DeltaMerge/Remote/DisaggSnapshot.h
  dbms/src/Storages/DeltaMerge/Remote/Proto/remote.proto
  dbms/src/Storages/DeltaMerge/Remote/Serializer.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTask.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_column_cache_long_term.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_common_handle.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment_s3.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.cpp
  dbms/src/Storages/DeltaMerge/workload/DTWorkload.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
  dbms/src/TiDB/Decode/Vector.cpp
  dbms/src/TiDB/Schema/VectorIndex.h
Labels: size/XXL, release-note-none, approved, lgtm

#9456 fix tiflash assert failure
  dbms/src/Flash/Planner/Plans/PhysicalJoin.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinBuild.cpp
  dbms/src/Flash/Planner/Plans/PhysicalJoinProbe.cpp
  dbms/src/Interpreters/Join.cpp
Labels: release-note-none, size/S, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9451 *: support vector index and adding/dropping vector index when doing syncTableSchema
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Debug/MockTiDB.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.h
  dbms/src/Storages/DeltaMerge/Index/IndexInfo.cpp
  dbms/src/Storages/DeltaMerge/Index/IndexInfo.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/KVStore/Types.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9471 ddl: Adapt with the latest vector index definition
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
Labels: release-note-none, size/M, approved, lgtm

#9466 tests: Disable some tests of inactivated features on 7.5
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_fast_add_peer.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: size/XS, release-note-none, cherry-pick-approved, approved, lgtm

#9468 Compression: still using LZ4 by default
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  tests/tidb-ci/run.sh
Labels: release-note-none, size/S, approved, lgtm

#9475 Storage: Support drop vector index defined on ColumnInfo when column is dropped
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/Index/IndexInfo.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9477 vector: Fix ColumnArray does not work well with CHBlockChunkCodec
  dbms/src/DataTypes/DataTypeArray.cpp
  dbms/src/DataTypes/IDataType.h
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_block_chunk_codec.cpp
  dbms/src/TestUtils/ColumnGenerator.cpp
  dbms/src/TestUtils/ColumnGenerator.h
Labels: size/XL, release-note-none, approved, lgtm

#9474 ci: upgrade tiflash-ci-base image to Python3
  release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci
  release-centos7-llvm/dockerfiles/Dockerfile-tiflash-ci-base
  tests/docker/mock-test-dt.yaml
  tests/docker/tiflash-dt-disable-local-tunnel.yaml
  tests/docker/tiflash-dt-force-enable-lm.yaml
  tests/docker/tiflash-dt-lightweight-compression.yaml
  tests/docker/tiflash-dt-sync-grpc.yaml
  tests/docker/tiflash-dt.yaml
  tests/run-test.py
Labels: release-note-none, size/L, approved, lgtm

#9476 Storage: Add error message when fail to build local index
  dbms/src/Common/FailPoint.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.h
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.h
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.cpp
  dbms/src/Storages/DeltaMerge/LocalIndexerScheduler.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_local_indexer_scheduler.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9073 Pipeline: use notify instead of polling for `ExchangeReceiver`
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.cpp
  dbms/src/Flash/Mpp/ReceivedMessage.cpp
  dbms/src/Flash/Mpp/ReceivedMessage.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.cpp
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/StreamRestoreTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/NotifyFuture.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.cpp
  dbms/src/Operators/ExchangeReceiverSourceOp.h
  dbms/src/Operators/GetResultSinkOp.cpp
  dbms/src/Operators/HashProbeTransformExec.cpp
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/UnorderedSourceOp.cpp
Labels: release-note-none, size/L, approved, lgtm

#9470 ddl: Fix adding vector index on empty table may blocked forever
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
  tests/fullstack-test2/vector/vector-index.test
Labels: release-note-none, size/L, approved, lgtm

#9483 storage: fix block rows not match when filter column is the first non-empty column in the block
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/DataStreams/FilterTransformAction.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
Labels: release-note-none, size/M, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9490 vector: Fix join by array meet error "no supertype for types Array(Float32), Nullable(Array(Float32))"
  dbms/src/DataTypes/getLeastSupertype.cpp
  dbms/src/DataTypes/getMostSubtype.cpp
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Flash/Mpp/MPPTaskScheduleEntry.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/DMFileIndexWriter.cpp
Labels: release-note-none, size/L, approved, lgtm

#9484 storage: fix block rows not match when filter column is the first non-empty column in the block
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Storages/DeltaMerge/LateMaterializationBlockInputStream.cpp
Labels: release-note-none, size/M, cherry-pick-approved, approved, lgtm

#9496 Fix build under release mode
  dbms/src/Storages/DeltaMerge/File/DMFileWriter.cpp
Labels: size/XS, release-note-none, approved, needs-1-more-lgtm

#9487 storage: remove vector_index in column level
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/DeltaMergeDefines.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9500 tests: fix build on m1 macbook && re-enable clang-tidy checks
  dbms/CMakeLists.txt
  dbms/src/VectorSearch/SimSIMD.h
  dbms/src/VectorSearch/USearch.h
  release-centos7-llvm/scripts/run-clang-tidy.py
Labels: release-note-none, size/S, approved, lgtm
