Repository pingcap/tiflash, pull requests merged in 2024-06, with the labels that each got.

#9114 *: Use prefix tiflash_ for thread-wise memory alloc info
  dbms/src/Common/TiFlashMetrics.h
  metrics/grafana/tiflash_summary.json
Labels: size/XS, release-note-none, approved, lgtm

#9105 .*: Remove `DAGQueryBlock`
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlock.h
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp
  dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.h
  dbms/src/Flash/Coprocessor/DAGQuerySource.cpp
  dbms/src/Flash/Coprocessor/DAGQuerySource.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.h
  dbms/src/Flash/Coprocessor/InterpreterDAG.cpp
  dbms/src/Flash/Coprocessor/InterpreterDAG.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/Planner/PlanQuerySource.cpp
  dbms/src/Flash/Planner/PlanQuerySource.h
  dbms/src/Flash/Planner/Planner.cpp
  dbms/src/Flash/Planner/Planner.h
  dbms/src/Flash/executeQuery.cpp
  dbms/src/Flash/tests/WindowTestUtil.h
  dbms/src/Flash/tests/gtest_execution_summary.cpp
  dbms/src/Flash/tests/gtest_executors_with_dm.cpp
  dbms/src/Flash/tests/gtest_expand_executor.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_interpreter.cpp
  dbms/src/Flash/tests/gtest_pipeline_interpreter.cpp
  dbms/src/Flash/tests/gtest_planner_interpreter.cpp
  dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  dbms/src/TestUtils/ExecutorTestUtils.h
  tests/docker/config/tiflash_dt_disable_planner.toml
  tests/docker/tiflash-dt-disable-planner.yaml
  tests/fullstack-test2/run.sh
  tests/fullstack-test2/tiflash-dt-disable-planner.yaml
Labels: size/XXL, release-note-none, approved, lgtm

#9119 Storages: Fix read ranges of FastScan
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
Labels: size/L, release-note, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#9065 Pipeline: use notify instead of polling for `ResultQueue`
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutor.h
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Flash/Executor/ResultQueue.h
  dbms/src/Flash/Executor/ResultQueue_fwd.h
  dbms/src/Flash/Executor/tests/gtest_pipeline_executor_context.cpp
  dbms/src/Flash/Pipeline/Pipeline.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/PipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/PipelineTaskBase.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/RFWaitTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/SimplePipelineTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/StreamRestoreTask.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Impls/StreamRestoreTask.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Planner/Plans/PhysicalGetResultSink.h
  dbms/src/Operators/GetResultSinkOp.cpp
  dbms/src/Operators/GetResultSinkOp.h
  dbms/src/Operators/HashJoinProbeTransformOp.cpp
  dbms/src/Operators/HashProbeTransformExec.cpp
  dbms/src/Operators/HashProbeTransformExec.h
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Operators/UnorderedSourceOp.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9126 Storages: Splitting DMFileReaderPool to reduce lock contention
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/ColumnSharingCache.h
Labels: size/L, release-note, approved, lgtm

#9131 KVStore: More metrics for Prehandling
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/M, approved, lgtm

#9137 expression: fix substring_index crash tiflash in some case
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_substring_index.cpp
Labels: size/S, release-note, approved, lgtm

#9138 *: Simplify nesting if..else code
  dbms/src/Common/TiFlashSecurity.h
  dbms/src/Common/tests/gtest_tiflash_security.cpp
Labels: release-note-none, size/L, approved, lgtm

#9134 Storages: Track memory for PageDirectory
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.cpp
  dbms/src/Storages/KVStore/FFI/JointThreadAllocInfo.h
  dbms/src/Storages/KVStore/FFI/SSTReader.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
  dbms/src/Storages/Page/PageStorageMemorySummary.h
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/PageDirectory/PageIdTrait.h
  dbms/src/Storages/Page/V3/PageEntry.h
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#9104 Storages: Refine build filters in StorageDeltaMerge
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  format-diff.py
Labels: size/XXL, release-note-none, approved, lgtm

#9145 Storages: Change the element type of `use_pack` from `bool` to `RSResult` in `DMFilePackFilter`
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/Index/RSResult.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
Labels: release-note-none, size/L, approved, lgtm

#9149 *: Refine logging for rough set filter
  dbms/src/Common/ArrayCache.h
  dbms/src/Common/HashTable/HashTable.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Flash/Coprocessor/InterpreterUtils.h
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Interpreters/ExpressionActions.h
  dbms/src/Parsers/CMakeLists.txt
  dbms/src/Parsers/tests/CMakeLists.txt
  dbms/src/Parsers/tests/create_parser.cpp
  dbms/src/Parsers/tests/lexer.cpp
  dbms/src/Parsers/tests/select_parser.cpp
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/Page/V2/tests/gtest_page_map_version_set.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9150 Storages: Add comments to MinMaxIndex
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
Labels: release-note-none, size/S, approved, lgtm

#9151 Storages: Refine MinMaxIndex
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.h
  dbms/src/Storages/DeltaMerge/Index/RSIndex.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: release-note-none, size/L, approved, lgtm

#9152 Storages: MinMaxIndex::checkIsNull returns RSResult::All if a pack only contains null marks and delete marks
  dbms/src/Storages/DeltaMerge/Index/MinMaxIndex.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
Labels: release-note-none, size/M, approved, lgtm

#9155 KVStore: Enhance Parallel Prehandle
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Debug/MockKVStore/MockRaftStoreProxy.cpp
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/gtest_raftstore_v2.cpp
Labels: release-note-none, size/L, approved, lgtm

#9153 KVStore: Add comments and refine logging about WaitCheckRegionReady
  dbms/src/Common/Checksum.h
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
Labels: release-note-none, size/L, approved, lgtm

#9160 KVStore: More log for Parallel Prehandle
  dbms/src/Storages/DeltaMerge/Decode/SSTFilesToBlockInputStream.cpp
  dbms/src/Storages/KVStore/FFI/SSTReader.cpp
  dbms/src/Storages/KVStore/FFI/SSTReader.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/tests/region_kvstore_test.h
Labels: release-note-none, size/M, approved, lgtm

#8899 Upgrade toolchain to LLVM17 & Support C++23
  .toolchain.yml
  CMakeLists.txt
  README.md
  contrib/grpc-cmake/CMakeLists.txt
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_aarch64.sh
  release-centos7-llvm/dockerfiles/misc/bake_llvm_base_amd64.sh
  release-centos7-llvm/dockerfiles/misc/bootstrap_llvm.sh
Labels: release-note, size/M, approved, lgtm

#8929 Format: insert Newline at EOF using clang-format-17
  .clang-format
  dbms/src/Client/Connection.h
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
  dbms/src/Storages/KVStore/Decode/RegionScanner.cpp
  dbms/src/Storages/KVStore/Read/Proxy.cpp
  dbms/src/Storages/KVStore/Read/ReadIndexDataNode.cpp
  dbms/src/Storages/KVStore/tests/gtest_async_tasks.cpp
  format-diff.py
Labels: release-note-none, size/M, approved, lgtm

#9164 *: update minimum cmake version to 3.23
  CMakeLists.txt
  README.md
Labels: size/XS, release-note-none, approved, lgtm

#9163 Storages: Fix memory trace for UniversalPageId
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageId.h
  dbms/src/Storages/Page/V3/Universal/tests/gtest_universal_page_storage.cpp
Labels: release-note-none, size/M, approved, lgtm

#9166 clang-tidy: ignore unknown pragmas warnings
  .clang-tidy
Labels: size/XS, release-note-none, approved, lgtm

#9171 Add debug log info to locate random fmt exception
  dbms/src/Flash/Planner/PhysicalPlan.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9170 KVStore: Add metrics for AddLock failure
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Disaggregated/S3LockClient.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
Labels: release-note-none, size/M, approved, lgtm
