Repository pingcap/tiflash, pull requests merged in 2025-04, with the labels that each got.

#10048 Storages: support inverted index
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockTiDB.cpp
  dbms/src/Flash/Coprocessor/DAGQueryInfo.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.cpp
  dbms/src/Flash/Coprocessor/TiDBTableScan.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/DMSegmentThreadInputStream.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.h
  dbms/src/Storages/DeltaMerge/Filter/And.h
  dbms/src/Storages/DeltaMerge/Filter/Equal.h
  dbms/src/Storages/DeltaMerge/Filter/Greater.h
  dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IntegerSet.cpp
  dbms/src/Storages/DeltaMerge/Filter/IntegerSet.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/Less.h
  dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Like.h
  dbms/src/Storages/DeltaMerge/Filter/Not.h
  dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Or.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/tests/gtest_dm_inverted_index.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/tests/gtest_inverted_index.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.cpp
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregated.h
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/InvertedIndex.h
  dbms/src/TiDB/Schema/SchemaGetter.h
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
Labels: size/XXL, release-note-none, approved, lgtm

#10073 Fix wrong `has_null_map` usage in hash join v2
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_collation.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_executors_with_dm.cpp
  dbms/src/Flash/tests/gtest_filter_executor.cpp
  dbms/src/Flash/tests/gtest_join.h
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Flash/tests/gtest_query_executor.cpp
  dbms/src/Flash/tests/gtest_runtime_filter_executor.cpp
  dbms/src/Flash/tests/gtest_spill_join.cpp
  dbms/src/Flash/tests/gtest_window_executor.cpp
  dbms/src/Interpreters/JoinV2/HashJoinKey.h
  dbms/src/Interpreters/JoinV2/HashJoinProbe.cpp
  dbms/src/TestUtils/mockExecutor.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#10059 cherry pick #9736 to release-8.5
  dbms/src/Common/GRPCQueue.h
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_trigger_pipeline_writer.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/Operator.cpp
Labels: size/XXL, release-note-none, cherry-pick-approved, approved, lgtm

#10060 Apply decrease for agg when window boundary is current row and unbounded following
  dbms/src/Interpreters/WindowDescription.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/WindowFunctions/tests/gtest_agg.cpp
Labels: release-note-none, size/L, approved, lgtm

#9916 Refine window when preceding and following boundary type are unbounded
  dbms/src/AggregateFunctions/AggregateFunctionAvg.h
  dbms/src/AggregateFunctions/AggregateFunctionCount.h
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxAny.h
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.h
  dbms/src/AggregateFunctions/AggregateFunctionNothing.h
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
  dbms/src/AggregateFunctions/AggregateFunctionSum.h
  dbms/src/AggregateFunctions/IAggregateFunction.h
  dbms/src/Columns/ColumnString.h
  dbms/src/DataStreams/WindowTransformAction.cpp
  dbms/src/DataStreams/WindowTransformAction.h
  dbms/src/WindowFunctions/tests/gtest_agg.cpp
Labels: size/XL, release-note, approved, lgtm

#10070 Add more metrics about pipeline
  dbms/src/Common/GRPCQueue.h
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Executor/ResultQueue.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/OneTimeNotifyFuture.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Interpreters/Join.cpp
  dbms/src/Operators/SharedAggregateRestorer.cpp
  dbms/src/Operators/SharedQueue.h
  dbms/src/Storages/DeltaMerge/ReadThread/WorkQueue.h
  dbms/src/Storages/DeltaMerge/SegmentReadTaskPool.h
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm

#10084 Fixing race condition in ThreadPoolImpl​
  dbms/src/Common/UniThreadPool.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10090 Unit-tests: Fix ThreadSanitizer error of MinMaxIndexTest.InOrNotInNULL
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_dm_minmax_index.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10088 Storages: Fix AddressSanitizer error of RateLimiter
  dbms/src/IO/BaseFile/RateLimiter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10091 Metrics: Fix the Grafana metrics panel of DataSharing
  metrics/grafana/tiflash_summary.json
Labels: size/XS, release-note-none, approved, lgtm

#10075 Storages: Add buildMVCCBitmapFilter for VersionChain
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Debug/TiFlashTestEnv.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/DMContext.cpp
  dbms/src/Storages/DeltaMerge/DMContext.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/VersionChain/ColumnView.h
  dbms/src/Storages/DeltaMerge/VersionChain/DeleteMarkFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/DeleteMarkFilter.h
  dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.h
  dbms/src/Storages/DeltaMerge/VersionChain/RowKeyFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/RowKeyFilter.h
  dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.h
  dbms/src/Storages/DeltaMerge/VersionChain/VersionFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/VersionFilter.h
  dbms/src/Storages/DeltaMerge/VersionChain/tests/bench_version_chain.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/tests/gtest_mvcc_bitmap.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/tests/gtest_version_chain.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_for_fast_scan.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#10097 Storages: Add metrics for VersionChain
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#10101 Do not allocate memory for unit test in `HashJoinPointerTable::init`
  dbms/src/Interpreters/JoinV2/HashJoin.cpp
  dbms/src/Interpreters/JoinV2/HashJoinPointerTable.cpp
  dbms/src/Interpreters/JoinV2/HashJoinPointerTable.h
  dbms/src/Interpreters/tests/JoinV2/gtest_hash_join_pointer_table.cpp
Labels: release-note-none, size/S, approved, lgtm

#10102 fix data race in `EstablishCallData`
  dbms/src/Flash/EstablishCall.cpp
Labels: release-note-none, size/S, approved, lgtm

#10111 *: Fix license checker
  .github/licenserc.yml
Labels: size/XS, release-note-none, approved, lgtm

#10076 tests: add fullstack test for inverted index
  tests/fullstack-test-index/inverted/create-on-alter-table.test
  tests/fullstack-test-index/inverted/create-on-create-table.test
  tests/fullstack-test-index/inverted/datetime-type.test
  tests/fullstack-test-index/inverted/modify-data-type.test
  tests/fullstack-test-index/inverted/unsupported-type.test
  tests/fullstack-test-index/vector/distance.test
  tests/fullstack-test-index/vector/func.test
  tests/fullstack-test-index/vector/vector-index-on-create.test
  tests/fullstack-test-index/vector/vector-index-on-partition.test
  tests/fullstack-test-index/vector/vector-index.test
  tests/fullstack-test2/run.sh
Labels: size/XL, release-note-none, approved, lgtm

#10103 Storages: Reusing distance results when scan vector index
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Functions/FunctionsVector.cpp
  dbms/src/Functions/FunctionsVector.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/CommonUtil.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ColumnFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DistanceProjectionInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DistanceProjectionInputStream.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DistanceProjectionInputStream_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#10035 add storage.temp config to support limit disk usage of spilling files
  dbms/src/Common/DiskSize.h
  dbms/src/Common/SpillLimiter.h
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Core/SpillHandler.cpp
  dbms/src/Core/SpillHandler.h
  dbms/src/Core/Spiller.cpp
  dbms/src/Core/Spiller.h
  dbms/src/Flash/tests/gtest_spill_limiter.cpp
  dbms/src/IO/BaseFile/PosixWritableFile.cpp
  dbms/src/IO/BaseFile/PosixWritableFile.h
  dbms/src/IO/BaseFile/WritableFile.h
  dbms/src/IO/Encryption/EncryptedWritableFile.cpp
  dbms/src/IO/Encryption/EncryptedWritableFile.h
  dbms/src/IO/FileProvider/FileProvider.cpp
  dbms/src/IO/FileProvider/FileProvider.h
  dbms/src/IO/FileProvider/WriteBufferFromWritableFileBuilder.cpp
  dbms/src/IO/FileProvider/WriteBufferFromWritableFileBuilder.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/StorageConfigParser.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Server/tests/gtest_storage_config.cpp
  dbms/src/Storages/PathCapacityMetrics.cpp
  dbms/src/Storages/S3/S3WritableFile.h
  dbms/src/TestUtils/ExecutorTestUtils.h
Labels: size/XXL, release-note, approved, lgtm

#10116 Fix incorrect conversion of column to nullable in Expand operator
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/Flash/Planner/Plans/PhysicalExpand2.cpp
  dbms/src/Functions/FunctionsGrouping.h
  tests/fullstack-test/mpp/rollup.test
Labels: size/L, release-note, approved, lgtm

#10115 *: Fix build issue when ThinLTO is enabled
  libs/libclara-cmake/CMakeLists.txt
  libs/libclara/Cargo.toml
Labels: size/XS, release-note-none, approved, lgtm

#9953 Improve the performance of min and max in window function
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.h
  tests/fullstack-test/mpp/window_agg.test
Labels: size/XL, release-note, approved, lgtm

#10114 Use correct end boundary in window when frame type is range
  dbms/src/DataStreams/WindowTransformAction.cpp
  tests/fullstack-test/mpp/window_agg.test
Labels: size/L, release-note, approved, lgtm

#10122 clara: Fix ASAN
  libs/libclara-cmake/CMakeLists.txt
Labels: size/XS, release-note-none, approved, lgtm

#10126 tidb: Rename HNSW -> Vector
  dbms/src/TiDB/Schema/TiDB.cpp
Labels: release-note-none, size/S, approved, lgtm

#10124 Avoid data race in grpc alarm
  dbms/src/Flash/EstablishCall.cpp
  dbms/src/Flash/EstablishCall.h
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
Labels: release-note-none, size/S, approved, lgtm

#10123 Storages: fix TSAN error
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: release-note-none, size/M, approved, lgtm

#10130 Storages: separate ReadBlockInfo
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/ReadBlockInfo.cpp
  dbms/src/Storages/DeltaMerge/File/ReadBlockInfo.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/DMFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream.cpp
Labels: size/XL, release-note-none, approved, lgtm

#10136 Storages: fix UT ParsePushDownExecutorTest.TimestampColumn when local timezone is UTC
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10142 Fix TimestampColumn fail in ASan/TSan
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: release-note-none, size/M, approved, lgtm
