Repository pingcap/tiflash, pull requests merged in 2025-02, with the labels that each got.

#9839 fix compilation error on arm64
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
Labels: release-note-none, size/L, approved, lgtm

#9765 *: Make tiflash compatible with the cse branch
  dbms/src/Flash/BatchCoprocessorHandler.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.h
  dbms/src/Flash/CoprocessorHandler.cpp
  dbms/src/Flash/Disaggregated/WNEstablishDisaggTaskHandler.cpp
  dbms/src/Flash/Mpp/MPPHandler.cpp
  dbms/src/Functions/FunctionsVector.h
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/MetricsPrometheus.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
  dbms/src/Storages/KVStore/FFI/SSTReader.h
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/PrehandleSnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
  dbms/src/Storages/KVStore/Read/LockException.h
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_tikv_keyvalue.cpp
  dbms/src/Storages/Page/Page.h
  dbms/src/TiDB/Schema/TiDBSchemaSyncer.cpp
  format-diff.py
Labels: size/XXL, release-note-none, approved, lgtm

#9848 vector: fix ANN query info not wrapped in disaggregated mode
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
Labels: size/XS, release-note, cherry-pick-approved, approved, lgtm

#9851 Storages: refine FilterParser
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.cpp
  dbms/src/Storages/DeltaMerge/FilterParser/FilterParser.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
Labels: release-note-none, size/L, approved, lgtm

#9852 vector: Reduce logging under debug level
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.h
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo_fwd.h
  dbms/src/Storages/DeltaMerge/tests/gtest_local_index_info.cpp
  dbms/src/Storages/KVStore/FFI/ProxyFFIStatusService.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/System/StorageSystemDTLocalIndexes.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#9862 remove OVERFLOW_AS_WARNING flag
  dbms/src/Debug/dbgQueryCompiler.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/tests/gtest_dag_context.cpp
  dbms/src/Functions/FunctionsTiDBConversion.h
  dbms/src/Functions/tests/bench_function_cast.cpp
  dbms/src/Functions/tests/gtest_tidb_conversion.cpp
  dbms/src/TestUtils/mockExecutor.cpp
Labels: release-note-none, size/L, approved, lgtm

#9842 support tidb truncate function
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Functions/FunctionsRound.cpp
  dbms/src/Functions/FunctionsRound.h
  dbms/src/Functions/FunctionsString.cpp
  dbms/src/Functions/tests/gtest_functions_round_with_frac.cpp
  dbms/src/Functions/tests/gtest_functions_truncate_with_frac.cpp
  tests/fullstack-test/expr/tidb_truncate.test
Labels: size/XXL, release-note-none, approved, lgtm

#9863 Server: Cherry-pick 2 recent simplification of Server.cpp into release-8.5
  dbms/src/Common/Logger_fwd.h
  dbms/src/Flash/Management/ManualCompact.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/InterruptListener.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/Server.h
  dbms/src/Server/Setup.cpp
  dbms/src/Server/Setup.h
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Server/TCPHandler.h
  dbms/src/Server/TCPHandlerFactory.h
  dbms/src/Server/TCPServersHolder.cpp
  dbms/src/Server/TCPServersHolder.h
  dbms/src/Storages/DeltaMerge/Decode/BoundedSSTFilesToBlockInputStream.cpp
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/ProxyStateMachine.h
Labels: size/XXL, release-note-none, cherry-pick-approved, approved, lgtm

#9867 tests: fix unit-test SegmentReadTaskTest.InitInputStream
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
Labels: release-note-none, size/S, approved, lgtm

#9870 tests: refine some test utils
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_replace_stable_data.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.h
Labels: release-note-none, size/L, approved, lgtm

#9865 *: Refine codes on Raft
  dbms/src/Debug/dbgKVStore/dbgFuncRegion.cpp
  dbms/src/Debug/dbgTools.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Server/Setup.cpp
  dbms/src/Server/Setup.h
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionMeta.h
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.h
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_spill.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9869 KVStore: Move the configs of Raft Read to KVStoreConfig
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/KVStoreConfig.cpp
  dbms/src/Storages/KVStore/KVStoreConfig.h
  dbms/src/Storages/KVStore/MultiRaft/Persistence.cpp
  dbms/src/Storages/KVStore/ProxyStateMachine.h
  dbms/src/Storages/KVStore/Read/LearnerRead.cpp
  dbms/src/Storages/KVStore/Read/ReadIndex.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_proactive_flush.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9758 Support aggregation function in window
  dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h
  dbms/src/AggregateFunctions/AggregateFunctionTopK.h
  dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp
  dbms/src/Common/AlignedBuffer.cpp
  dbms/src/Common/AlignedBuffer.h
  dbms/src/DataStreams/WindowTransformAction.cpp
  dbms/src/DataStreams/WindowTransformAction.h
  dbms/src/Debug/MockExecutor/FuncSigMap.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.cpp
  dbms/src/Debug/MockExecutor/WindowBinder.h
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Interpreters/WindowDescription.cpp
  dbms/src/Interpreters/WindowDescription.h
  dbms/src/TestUtils/mockExecutor.h
  dbms/src/WindowFunctions/IWindowFunction.h
  dbms/src/WindowFunctions/tests/gtest_agg.cpp
  tests/fullstack-test/mpp/window_agg.test
Labels: size/XXL, release-note, approved, lgtm

#9874 Add tiflash network transmission metrics
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Statistics/ExecutionSummaryHelper.cpp
  dbms/src/Flash/Statistics/ExecutionSummaryHelper.h
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.cpp
  metrics/grafana/tiflash_summary.json
Labels: release-note-none, size/L, approved, lgtm

#9807 Support remove region by ps-ctl
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
Labels: release-note-none, size/M, approved, lgtm

#9864 Fix the failure of finding correct current row when frame type is range in window function
  dbms/src/DataStreams/WindowTransformAction.cpp
  dbms/src/DataStreams/WindowTransformAction.h
  dbms/src/WindowFunctions/tests/gtest_agg.cpp
  dbms/src/WindowFunctions/tests/gtest_last_value.cpp
  tests/fullstack-test/mpp/window_agg.test
Labels: size/XXL, release-note, approved, lgtm

#9881 Fix the incorrect value of the max thread size
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/getNumberOfCPUCores.cpp
  dbms/src/Common/getNumberOfCPUCores.h
  dbms/src/Interpreters/SettingsCommon.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/ProxyStateMachine.h
  dbms/src/Storages/KVStore/tests/gtest_proxy_state_machine.cpp
Labels: release-note-none, size/L, approved, lgtm

#9886 *: Set ApplicationType and disagg param when GlobalContext created
  dbms/src/Core/TiFlashDisaggregatedMode.cpp
  dbms/src/Core/TiFlashDisaggregatedMode.h
  dbms/src/DataTypes/DataTypeAggregateFunction.cpp
  dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/CLIService.h
  dbms/src/Server/Client.cpp
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  dbms/src/TestUtils/TiFlashTestEnv.cpp
Labels: release-note-none, size/L, approved, lgtm, needs-cherry-pick-release-8.5

#9888 disagg: Adapt with the GetLifecycleConfig response on AWS S3
  dbms/src/Common/FailPoint.cpp
  dbms/src/Server/StorageConfigParser.h
  dbms/src/Storages/S3/S3Common.cpp
  dbms/src/Storages/S3/S3Common.h
  dbms/src/Storages/S3/tests/gtest_s3client.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
Labels: release-note-none, size/L, approved, lgtm

#9872 Aggregator support new hash function
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/HashTable/Hash.h
  dbms/src/DataStreams/AggregatingBlockInputStream.h
  dbms/src/DataStreams/MergingAggregatedMemoryEfficientBlockInputStream.cpp
  dbms/src/DataStreams/ParallelAggregatingBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/AggregationInterpreterHelper.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/Settings.h
  dbms/src/Operators/AggregateContext.cpp
  dbms/src/Operators/AutoPassThroughHashAggContext.h
Labels: size/XL, release-note, approved, lgtm

#9825 batch serialize/deserialize interface support handling nullmap
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.cpp
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.cpp
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_serialize_deserialize.cpp
  dbms/src/TiDB/Collation/Collator.cpp
  dbms/src/TiDB/Collation/Collator.h
Labels: size/XXL, release-note-none, approved, lgtm

#9903 *: Add stacktrace logging when exceptions are thrown in `Server::main`
  dbms/src/AggregateFunctions/ReservoirSampler.h
  dbms/src/AggregateFunctions/ReservoirSamplerDeterministic.h
  dbms/src/AggregateFunctions/UniquesHashSet.h
  dbms/src/Common/CombinedCardinalityEstimator.h
  dbms/src/Common/CounterInFile.h
  dbms/src/Common/HyperLogLogCounter.h
  dbms/src/Common/OptimizedRegularExpression.inl.h
  dbms/src/Databases/DatabaseTiFlash.cpp
  dbms/src/IO/ReadHelpers.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/Setup.cpp
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionPersister.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
  dbms/src/Storages/KVStore/Utils/SerializationHelper.h
  dbms/src/Storages/Page/Page.h
  dbms/src/Storages/Page/PageStorage.cpp
  dbms/src/Storages/Page/PageStorage.h
  dbms/src/Storages/Page/V2/PageStorage.cpp
  dbms/src/Storages/Page/V2/PageStorage.h
  dbms/src/Storages/Page/V2/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.cpp
  dbms/src/Storages/Page/V3/PageStorageImpl.h
  dbms/src/Storages/Page/V3/tests/gtest_page_storage.cpp
  dbms/src/Storages/Page/workload/PSWorkload.cpp
  libs/libcommon/include/common/ErrorHandlers.h
Labels: release-note-none, size/L, approved, lgtm

#9905 Storage: Fix init_thread_count_scale == 0, tiflash can not start normally
  dbms/src/Interpreters/loadMetadata.cpp
  dbms/src/Server/BgStorageInit.cpp
  dbms/src/Server/BgStorageInit.h
  dbms/src/Server/Server.cpp
Labels: release-note-none, size/L, approved, lgtm

#9918 *: enable `null_as_false` when build push down filter in late materialization
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.h
  dbms/src/Flash/Coprocessor/InterpreterUtils.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
Labels: release-note-none, size/S, approved, lgtm

#9920 fix virtual column not found when remote read happens
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/Coprocessor/RemoteRequest.cpp
  dbms/src/Flash/Coprocessor/TablesRegionsInfo.cpp
  tests/fullstack-test/mpp/remote_read_virtual_column.test
Labels: release-note, size/M, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#9929 *: Fix client default format
  CMakeLists.txt
  cmake/find_readline_edit.cmake
  dbms/src/Server/Client.cpp
  libs/libcommon/include/common/config_common.h.in
  libs/libcommon/include/common/readline_use.h
Labels: release-note-none, size/L, approved, lgtm

#9876 Reduce redundant pack reads during building bitmap filter for delta merge case
  dbms/src/IO/Compression/CompressedReadBufferBase.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
Labels: size/XXL, release-note, approved, lgtm
