Repository pingcap/tiflash, pull requests merged in 2025-03, with the labels that each got.

#9932 Storage: Refine VectorIndexHNSW -> VectorIndex
  .gitignore
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyLocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileLocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Index/ICacheableLocalIndexReader.h
  dbms/src/Storages/DeltaMerge/Index/LocalIndexCache.h
  dbms/src/Storages/DeltaMerge/Index/LocalIndexCache_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/CommonUtil.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Perf.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Perf.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/Index.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndexHNSW/usearch_index_dense.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/VectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/bench_vector_index_utils.h
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9921 KVStore: Defer deleting locks until after the committed data has been written to storage
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_memory.cpp
Labels: release-note-none, size/M, approved, lgtm

#9931 Storages: split LocalIndexCache
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
Labels: release-note-none, size/M, approved, lgtm

#9936 build: Fix ENV setting in tiflash-llvm-base image
  release-linux-llvm/Makefile
  release-linux-llvm/dockerfiles/Dockerfile-tiflash-llvm-base
Labels: release-note-none, size/S, skip-issue-check, approved, lgtm

#9933 Fix memory leak in aggregation function in window
  dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp
  dbms/src/DataStreams/WindowTransformAction.h
Labels: size/XS, release-note, approved, lgtm

#9938 Fix operator new[] and delete mismatch for join probe prefetch states
  dbms/src/Interpreters/JoinV2/HashJoinProbe.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9941 Fix the out of bound array access issue for gtest
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9945 vector: Fix the bug that the local index in CFTiny is not removed during MinorCompaction
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileDeleteRange.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/MinorCompaction.cpp
  dbms/src/Storages/DeltaMerge/Delta/tests/gtest_dm_delta_value_space.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer.cpp
  dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
Labels: size/XL, release-note, approved, lgtm

#9944 *: fix vector index ASAN error
  README.md
  asan_ignores.txt
  cmake/sanitize.cmake
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
Labels: release-note-none, size/S, approved, lgtm

#9948 bench: fix compile error of bench_dbms
  dbms/src/Flash/tests/bench_aggregation_hash_map.cpp
  dbms/src/Storages/DeltaMerge/tests/bench_vector_index.cpp
  dbms/src/Storages/KVStore/tests/bench_parse_lock.cpp
Labels: release-note-none, size/S, approved, lgtm

#9939 Storage: Fix DataTypePtr is not shared as expected
  dbms/src/DataTypes/DataTypeFactory.cpp
  dbms/src/DataTypes/DataTypeFactory.h
  dbms/src/DataTypes/tests/gtest_data_type_get_common_type.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.cpp
  dbms/src/Parsers/StringRange.h
  dbms/src/Storages/StorageDeltaMerge.cpp
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-8.5

#9899 ci: Add gtest_10x test runner
  .gitignore
  README.md
  tests/gtest_10x.py
  tests/gtest_10x_suppress.txt
Labels: size/XXL, release-note-none, approved, lgtm

#9957 disagg: Suppress enum overflow warning on S3 SDK
  contrib/aws-cmake/0003-Suppress-enum-overflow.patch
  contrib/aws-cmake/CMakeLists.txt
Labels: release-note, size/M, approved, lgtm

#9896 KVStore: avoid writting committed data into storage in `doLearnerRead`
  dbms/src/Storages/KVStore/Decode/PartitionStreams.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/Read/LearnerReadWorker.cpp
Labels: release-note-none, size/L, approved, lgtm

#9959 *: Remove useless `ViewDependencies`
  dbms/src/DataStreams/AddingDefaultBlockOutputStream.cpp
  dbms/src/DataStreams/AddingDefaultBlockOutputStream.h
  dbms/src/DataStreams/PushingToViewsBlockOutputStream.cpp
  dbms/src/DataStreams/PushingToViewsBlockOutputStream.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_task_manager.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/InterpreterInsertQuery.cpp
  dbms/src/Parsers/ASTInsertQuery.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/IStorage.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/Universal/UniversalPageIdFormatImpl.h
  libs/libcommon/CMakeLists.txt
  libs/libcommon/include/common/MultiVersion.h
  libs/libcommon/include/common/iostream_debug_helpers.h
  libs/libcommon/src/tests/CMakeLists.txt
  libs/libcommon/src/tests/date_lut2.cpp
  libs/libcommon/src/tests/date_lut3.cpp
  libs/libcommon/src/tests/date_lut4.cpp
  libs/libcommon/src/tests/date_lut_default_timezone.cpp
  libs/libcommon/src/tests/date_lut_init.cpp
  libs/libcommon/src/tests/multi_version.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9954 tests: SegmentBitmapFilterTest supports common handle
  dbms/src/Storages/DeltaMerge/VersionChain/ColumnView.h
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_util.h
  dbms/src/Storages/DeltaMerge/tests/gtest_skippable_block_input_stream.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9967 fix deserialization bug because of uninitialized Decimal256
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/tests/gtest_column_serialize_deserialize.cpp
Labels: release-note-none, size/S, approved, lgtm

#9968 Fix nullptr arena in aggregation window function
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxAny.h
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.h
  dbms/src/DataStreams/WindowTransformAction.cpp
  dbms/src/DataStreams/WindowTransformAction.h
  tests/fullstack-test/mpp/window_agg.test
Labels: size/L, release-note, approved, lgtm

#9777 Aggregator support batch serialize
  dbms/src/Common/Arena.h
  dbms/src/Common/ColumnsHashing.h
  dbms/src/Common/ColumnsHashingImpl.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
Labels: size/XXL, release-note-none, approved, lgtm

#9898 minor refine for column serialize interface
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
Labels: release-note-none, size/S, approved, lgtm

#9975 Storages: fix adding delta vector index does not work with existing indexes
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyLocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileLocalIndexWriter.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9962 Storages: fix a series of data race issues
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalSegment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/S3/FileCache.h
  tests/sanitize/tsan.suppression
Labels: size/XL, release-note, approved, lgtm, needs-cherry-pick-release-8.5

#9990 Storages: use default string type in DeltaMergeStore
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
Labels: release-note, size/M, approved, lgtm

#9987 Columns: optimize ColumnString filter when selectivity is high
  dbms/src/Columns/filterColumn.cpp
  dbms/src/Columns/tests/bench_column_filter.cpp
  dbms/src/Columns/tests/bench_column_string_filter.cpp
Labels: size/XL, release-note, approved, lgtm

#9977 Storages: Refine vector search streams
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInputStream_fwd.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetWithVectorIndexInputStream.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFileLocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileVectorIndexReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Perf.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Perf_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Reader.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ColumnFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ColumnFileInputStream.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ColumnFileInputStream_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/Ctx_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/DMFileInputStream_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/IProvideVectorIndex.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/InputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/InputStream.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/InputStream_fwd.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Writer.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/VectorIndexBlockInputStream.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
Labels: size/XXL, release-note-none, approved, lgtm

#9995 disagg: Fix build under ASAN; Check each aws patch separately
  contrib/aws-cmake/CMakeLists.txt
Labels: release-note-none, size/M, approved, lgtm, needs-cherry-pick-release-8.5

#9994 Storages: enhance data sharing column cache
  dbms/src/Storages/DeltaMerge/File/ColumnCache.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnCache.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_column_cache.cpp
Labels: release-note-none, size/L, approved, lgtm

#10004 Fix spill crash
  dbms/src/DataStreams/FilterTransformAction.cpp
  dbms/src/DataStreams/MergeSortingBlockInputStream.cpp
  dbms/src/Flash/tests/gtest_spill_sort.cpp
  dbms/src/Operators/MergeSortTransformOp.cpp
Labels: release-note, size/M, approved, lgtm

#10003 tests: Fix use-after-free
  cmake/sanitize.cmake
  dbms/src/Common/FailPoint.cpp
  dbms/src/Interpreters/tests/gtest_interpreter_create_query.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_inverted_index.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  tests/sanitize/asan.suppression
  tests/sanitize/asan_ignores.txt
Labels: release-note-none, size/L, approved, lgtm

#10000 fix access invalid memory for Aggregation
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/IColumn.h
Labels: release-note-none, size/S, approved, lgtm

#10009 [cherrypick 9.0-beta.1] fix access invalid memory for Aggregation
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/IColumn.h
Labels: release-note-none, size/S, approved, lgtm

#10017 Storage: Polish ANNQueryInfo in tests
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index_utils.h
Labels: size/XL, release-note-none, approved, lgtm

#10021 fix integration tests failed due to lack of alias of the derived table
  tests/fullstack-test/expr/duration_pushdown.test
Labels: size/XS, release-note-none, approved, lgtm

#10023 *: Remove useless PreparedSets, Prewhere, ExternalTables
  dbms/src/Client/Connection.cpp
  dbms/src/Client/Connection.h
  dbms/src/Client/MultiplexedConnections.cpp
  dbms/src/Client/MultiplexedConnections.h
  dbms/src/Columns/FilterDescription.h
  dbms/src/Columns/VirtualColumnUtils.cpp
  dbms/src/Columns/VirtualColumnUtils.h
  dbms/src/Common/ExternalTable.h
  dbms/src/Flash/Planner/tests/gtest_physical_plan.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Interpreters/ExpressionAnalyzer.cpp
  dbms/src/Interpreters/ExpressionAnalyzer.h
  dbms/src/Interpreters/InterpreterDropQuery.cpp
  dbms/src/Interpreters/InterpreterExistsQuery.cpp
  dbms/src/Interpreters/InterpreterInsertQuery.cpp
  dbms/src/Interpreters/InterpreterSelectQuery.cpp
  dbms/src/Interpreters/LogicalExpressionsOptimizer.cpp
  dbms/src/Interpreters/LogicalExpressionsOptimizer.h
  dbms/src/Parsers/ASTSelectQuery.cpp
  dbms/src/Parsers/ASTSelectQuery.h
  dbms/src/Parsers/ExpressionElementParsers.cpp
  dbms/src/Parsers/ParserSelectQuery.cpp
  dbms/src/Server/Client.cpp
  dbms/src/Server/DTTool/DTTool.cpp
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/DTTool/DTToolMigrate.cpp
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Storages/DeltaMerge/workload/Options.cpp
  dbms/src/Storages/IStorage.h
  dbms/src/Storages/Page/tools/PageCtl/PageStorageCtlV3.cpp
  dbms/src/Storages/Page/workload/PSStressEnv.cpp
  dbms/src/Storages/SelectQueryInfo.h
  dbms/src/Storages/System/StorageSystemTables.cpp
  tests/README.md
Labels: size/XXL, release-note-none, approved, lgtm

#9998 Storages: support build inverted index query info from RSOperator
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/Filter/And.h
  dbms/src/Storages/DeltaMerge/Filter/ColumnRange.cpp
  dbms/src/Storages/DeltaMerge/Filter/ColumnRange.h
  dbms/src/Storages/DeltaMerge/Filter/Equal.h
  dbms/src/Storages/DeltaMerge/Filter/Greater.h
  dbms/src/Storages/DeltaMerge/Filter/GreaterEqual.h
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IntegerSet.cpp
  dbms/src/Storages/DeltaMerge/Filter/IntegerSet.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/Less.h
  dbms/src/Storages/DeltaMerge/Filter/LessEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Like.h
  dbms/src/Storages/DeltaMerge/Filter/Not.h
  dbms/src/Storages/DeltaMerge/Filter/NotEqual.h
  dbms/src/Storages/DeltaMerge/Filter/Or.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/tests/gtest_inverted_index.cpp
  dbms/src/Storages/tests/gtest_filter_parser.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#10030 Storage: Split tests about DeltaMergeStore
  dbms/src/Interpreters/Context.cpp
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/tests/gtest_dm_column_file.cpp
  dbms/src/Storages/DeltaMerge/Decode/tests/gtest_sst_files_stream.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFileFlushTask.h
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/tests/gtest_column_file_clone.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaIndex.h
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaIndexManager.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaIndexManager.h
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaPlace.h
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaTree.h
  dbms/src/Storages/DeltaMerge/DeltaIndex/DeltaTree.ipp
  dbms/src/Storages/DeltaMerge/DeltaIndex/tests/gtest_dm_delta_index_manager.cpp
  dbms/src/Storages/DeltaMerge/DeltaIndex/tests/gtest_dm_delta_tree.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/File/tests/gtest_column_cache.cpp
  dbms/src/Storages/DeltaMerge/File/tests/gtest_column_cache_long_term.cpp
  dbms/src/Storages/DeltaMerge/File/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/File/tests/gtest_dm_meta_version.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/tests/gtest_inverted_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/bench_dataset/.gitignore
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/bench_dataset/README.md
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/bench_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/bench_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_dm_minmax_index.cpp
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_local_index_info.cpp
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_local_indexer_scheduler.cpp
  dbms/src/Storages/DeltaMerge/Index/tests/gtest_rs_result.cpp
  dbms/src/Storages/DeltaMerge/ReadThread/tests/gtest_segment_read_task_pool.cpp
  dbms/src/Storages/DeltaMerge/Remote/RNDeltaIndexCache.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StoragePool/tests/gtest_global_page_id_allocator.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/ColumnView.h
  dbms/src/Storages/DeltaMerge/tests/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_storage_delta_merge.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_utils.cpp
  dbms/src/TiDB/Schema/tests/gtest_schema_sync.cpp
Labels: release-note-none, size/L, approved, lgtm

#10025 grafana: Add Grafana panels about Raft-Engine
  metrics/grafana/tiflash_proxy_details.json
Labels: size/XXL, release-note, approved, lgtm

#10040 *: Fix invalid json in ExchangeReceiveDetail
  dbms/src/Flash/Statistics/ExchangeReceiverImpl.cpp
  dbms/src/Flash/Statistics/ExchangeSenderImpl.cpp
  dbms/src/Flash/Statistics/TableScanImpl.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10043 *: Fix param typo in ProxyStateMachine
  dbms/src/Storages/KVStore/ProxyStateMachine.h
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5

#10006 Storages: add DMFile & ColumnFileTiny & Segment inverted index reader
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.cpp
  dbms/src/Storages/DeltaMerge/BitmapFilter/BitmapFilter.h
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTinyLocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/File/ColumnStat.h
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/Filter/ColumnRange.cpp
  dbms/src/Storages/DeltaMerge/Filter/ColumnRange.h
  dbms/src/Storages/DeltaMerge/Filter/ColumnRange_fwd.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromSegment.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromSegment.h
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Writer.cpp
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/tests/gtest_dm_inverted_index.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#10054 Support enabling hash join v2 by TiDB
  dbms/src/Flash/FlashService.cpp
  dbms/src/Interpreters/JoinV2/HashJoin.cpp
Labels: release-note-none, size/S, approved, lgtm

#10063 Add some failpoints in hash join v2 to fix integration tests failure
  dbms/src/Interpreters/JoinV2/HashJoin.cpp
Labels: release-note-none, size/S, approved, lgtm

#10053 Storages: refine download index file
  dbms/src/Storages/DeltaMerge/Index/InvertedIndex/Reader/ReaderFromDMFile.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/Stream/ReaderFromDMFile.cpp
  dbms/src/Storages/S3/FileCache.cpp
  dbms/src/Storages/S3/FileCache.h
Labels: release-note-none, size/L, approved, lgtm

#10055 KVStore: Fix fail to restore tikv value larger than 16MiB
  dbms/src/IO/ReadHelpers.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFilePersisted.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVKeyValue.h
  dbms/src/Storages/KVStore/Utils/SerializationHelper.h
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
Labels: release-note, size/M, approved, lgtm

#10065 CI: fix regex in interpreters OWNERS file
  dbms/src/Interpreters/OWNERS
Labels: size/XS, release-note-none, skip-issue-check, approved, lgtm

#10061 tests: Avoid disk IO in `RegionSeriTest`
  dbms/src/Debug/dbgNaturalDag.h
  dbms/src/IO/Buffer/WriteBufferFromString.h
  dbms/src/IO/Buffer/WriteBufferFromVector.h
  dbms/src/Storages/KVStore/Decode/DecodedTiKVKeyValue.h
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/KVStore/tests/gtest_region_persister.cpp
  dbms/src/TiDB/Decode/DatumCodec.h
  dbms/src/TiDB/Decode/RowCodec.h
Labels: release-note-none, size/L, approved, lgtm
