Repository pingcap/tiflash, pull requests merged in 2025-07, with the labels that each got.

#10273 docs: Add http api docs
  docs/tiflash_http_api.md
Labels: release-note-none, size/M, approved, lgtm

#10292 ddl: Fix invalid memory access in InterpreterCreateQuery
  dbms/src/Interpreters/InterpreterCreateQuery.h
Labels: size/XS, release-note-none, approved, lgtm

#10286 metrics: Enhance the o11y of TiFlash storage layer (release-7.5)
  CMakeLists.txt
  dbms/src/Common/CurrentMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Encryption/RateLimiter.cpp
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/InterpreterCreateQuery.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFile.h
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileInMemory.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.cpp
  dbms/src/Storages/DeltaMerge/Delta/MemTableSet.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Statistics.cpp
  dbms/src/Storages/DeltaMerge/Filter/In.h
  dbms/src/Storages/DeltaMerge/Filter/IsNull.h
  dbms/src/Storages/DeltaMerge/Filter/NotIn.h
  dbms/src/Storages/DeltaMerge/Filter/PushDownFilter.h
  dbms/src/Storages/DeltaMerge/Filter/RSOperator.h
  dbms/src/Storages/DeltaMerge/Filter/Unsupported.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StoragePool/StoragePool.cpp
  dbms/src/Storages/IStorage.cpp
  dbms/src/Storages/IStorage.h
  dbms/src/Storages/ITableDeclaration.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/Storages/System/StorageSystemDTSegments.cpp
  dbms/src/Storages/System/StorageSystemDTTables.cpp
  dbms/src/TestUtils/gtests_dbms_main.cpp
  dbms/src/TiDB/Schema/SchemaSyncService.cpp
  libs/libcommon/include/common/logger_util.h
  libs/libdaemon/src/BaseDaemon.cpp
  metrics/grafana/tiflash_proxy_details.json
  metrics/grafana/tiflash_summary.json
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#10302 Raft: Increase max retry times to avoid too large remote requests
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
Labels: release-note, size/M, cherry-pick-approved, approved, lgtm

#10301 Raft: Increase max retry times to avoid too large remote requests
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Storages/DeltaMerge/Delta/ColumnFilePersistedSet.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
Labels: release-note, size/M, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#10298 Revert "Support graceful shutdown in TiFlash"
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/Server.cpp
  dbms/src/Storages/KVStore/ProxyStateMachine.h
Labels: release-note-none, size/L, approved, lgtm

#10133 Support (left outer) (anti) semi join in hash join v2
  dbms/CMakeLists.txt
  dbms/src/Flash/Planner/Plans/PhysicalJoinV2.cpp
  dbms/src/Interpreters/JoinV2/HashJoin.cpp
  dbms/src/Interpreters/JoinV2/HashJoin.h
  dbms/src/Interpreters/JoinV2/HashJoinKey.cpp
  dbms/src/Interpreters/JoinV2/HashJoinProbe.cpp
  dbms/src/Interpreters/JoinV2/HashJoinProbe.h
  dbms/src/Interpreters/JoinV2/SemiJoinProbe.cpp
  dbms/src/Interpreters/JoinV2/SemiJoinProbe.h
  dbms/src/Interpreters/JoinV2/SemiJoinProbeList.cpp
  dbms/src/Interpreters/JoinV2/SemiJoinProbeList.h
  dbms/src/Interpreters/tests/JoinV2/gtest_semi_join_probe_list.cpp
Labels: size/XXL, release-note-none, approved, lgtm
