Repository pingcap/tiflash, pull requests merged in 2025-01, with the labels that each got.

#9736 ExchangeSenderOp check writer status only if there is data to flush to MPPTunnel
  dbms/src/Common/GRPCQueue.h
  dbms/src/Common/LooseBoundedMPMCQueue.h
  dbms/src/DataStreams/ExchangeSenderBlockInputStream.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/StreamWriter.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/UnaryDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/LocalRequestHandler.h
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/MPPTunnelSet.cpp
  dbms/src/Flash/Mpp/MPPTunnelSet.h
  dbms/src/Flash/Mpp/MPPTunnelSetWriter.h
  dbms/src/Flash/Mpp/ReceivedMessageQueue.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Mpp/tests/gtest_trigger_pipeline_writer.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.cpp
  dbms/src/Operators/ExchangeSenderSinkOp.h
  dbms/src/Operators/Operator.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9755 Storages: fix the range of load DMFilePackFilterResult
  dbms/src/DataStreams/BlocksListBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Range.h
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_ingest.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/TestUtils/InputStreamTestUtils.cpp
Labels: size/XL, release-note-none, approved, lgtm

#9763 KVStore: Fix unreleased Region instance
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/KVStore.h
  dbms/src/Storages/KVStore/MultiRaft/RaftCommandsKVS.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionRangeKeys.h
  dbms/src/Storages/KVStore/MultiRaft/RegionSerde.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionState.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionState.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.h
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
Labels: release-note-none, size/L, approved, lgtm

#9766 storage: Remove tryBuildWithVectorIndex
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_vector_index.cpp
Labels: release-note-none, size/L, approved, lgtm

#9779 Fix the incompatible behavior when handling `IN(Timestamp | MysqlTime * )` expressions with timezone
  dbms/src/Flash/Coprocessor/DAGExpressionAnalyzer.cpp
  dbms/src/Interpreters/Set.cpp
  dbms/src/Interpreters/Set.h
  tests/fullstack-test/expr/in_expression.test
Labels: release-note, size/M, approved, lgtm

#9759 *: only enable new string serdes format in exchange when MppVersion >= MppVersionV3
  dbms/src/DataTypes/DataTypeString.h
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodec.h
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.h
  dbms/src/Flash/Coprocessor/ChunkDecodeAndSquash.cpp
  dbms/src/Flash/Coprocessor/ChunkDecodeAndSquash.h
  dbms/src/Flash/Coprocessor/CodecUtils.cpp
  dbms/src/Flash/Coprocessor/CodecUtils.h
  dbms/src/Flash/Coprocessor/tests/gtest_block_chunk_codec.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_chunk_decode_and_squash.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTunnelSetHelper.cpp
  dbms/src/Flash/Mpp/MppVersion.h
  dbms/src/Flash/Mpp/Utils.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
  tests/fullstack-test2/mpp/mpp-version.test
Labels: size/XL, release-note-none, approved, lgtm

#9782 Small refinement of DataTypeString
  dbms/src/DataTypes/DataTypeString.cpp
Labels: release-note-none, size/S, approved, lgtm

#9783 Fix several network stats issues
  dbms/src/Flash/Coprocessor/DecodeDetail.h
  dbms/src/Flash/Coprocessor/ExecutionSummary.cpp
  dbms/src/Flash/Mpp/ExchangeReceiver.cpp
  dbms/src/Flash/Mpp/MPPTunnel.h
  dbms/src/Flash/Mpp/ReceivedMessage.h
  dbms/src/Flash/Statistics/BaseRuntimeStatistics.cpp
Labels: release-note-none, size/M, approved, lgtm

#9789 ddl: fix query partition table failed after rename column
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  tests/fullstack-test2/ddl/partitions/rename_column.test
Labels: size/L, release-note, approved, lgtm

#9737 Add decrease interface for aggregation
  dbms/src/AggregateFunctions/AggregateFunctionArray.h
  dbms/src/AggregateFunctions/AggregateFunctionAvg.h
  dbms/src/AggregateFunctions/AggregateFunctionCount.h
  dbms/src/AggregateFunctions/AggregateFunctionFactory.cpp
  dbms/src/AggregateFunctions/AggregateFunctionFactory.h
  dbms/src/AggregateFunctions/AggregateFunctionForEach.h
  dbms/src/AggregateFunctions/AggregateFunctionGroupConcat.h
  dbms/src/AggregateFunctions/AggregateFunctionMaxIntersections.h
  dbms/src/AggregateFunctions/AggregateFunctionMerge.h
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxAny.h
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.cpp
  dbms/src/AggregateFunctions/AggregateFunctionMinMaxWindow.h
  dbms/src/AggregateFunctions/AggregateFunctionNothing.h
  dbms/src/AggregateFunctions/AggregateFunctionNull.cpp
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
  dbms/src/AggregateFunctions/AggregateFunctionSequenceMatch.h
  dbms/src/AggregateFunctions/AggregateFunctionSum.h
  dbms/src/AggregateFunctions/HelpersMinMaxAny.h
  dbms/src/AggregateFunctions/IAggregateFunction.h
  dbms/src/AggregateFunctions/registerAggregateFunctions.cpp
  dbms/src/AggregateFunctions/tests/gtest_window_agg.cpp
  dbms/src/Common/AlignedBuffer.cpp
  dbms/src/Common/AlignedBuffer.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9793 Fix compilation errors with unused variables
  dbms/src/AggregateFunctions/AggregateFunctionNull.h
Labels: size/XS, release-note-none, approved, lgtm

#9679 Aggregator support prefetch
  dbms/src/AggregateFunctions/AggregateFunctionGroupUniqArray.h
  dbms/src/AggregateFunctions/KeyHolderHelpers.h
  dbms/src/Common/ColumnsHashing.h
  dbms/src/Common/ColumnsHashingImpl.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Common/HashTable/FixedHashTable.h
  dbms/src/Common/HashTable/Hash.h
  dbms/src/Common/HashTable/HashTable.h
  dbms/src/Common/HashTable/HashTableKeyHolder.h
  dbms/src/Common/HashTable/SmallTable.h
  dbms/src/Common/HashTable/StringHashMap.h
  dbms/src/Common/HashTable/StringHashTable.h
  dbms/src/Common/HashTable/TwoLevelHashTable.h
  dbms/src/Common/HashTable/TwoLevelStringHashTable.h
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
  dbms/src/Flash/tests/gtest_compute_server.cpp
  dbms/src/Flash/tests/gtest_spill_aggregation.cpp
  dbms/src/Interpreters/Aggregator.cpp
  dbms/src/Interpreters/Aggregator.h
  dbms/src/Interpreters/JoinPartition.cpp
  dbms/src/Interpreters/SetVariants.h
  libs/libcommon/include/common/StringRef.h
Labels: size/XXL, release-note-none, approved, lgtm

#9792 *: some minor refine
  dbms/src/Debug/MockStorage.cpp
  dbms/src/Debug/MockStorage.h
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Planner/Plans/PhysicalMockTableScan.cpp
  dbms/src/Storages/IManageableStorage.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDeltaMerge.h
  dbms/src/TiDB/Decode/TypeMapping.cpp
  dbms/src/TiDB/Decode/TypeMapping.h
Labels: release-note-none, size/L, approved, lgtm

#9804 *: Simplify Server.cpp
  dbms/src/Common/Logger_fwd.h
  dbms/src/Flash/Management/ManualCompact.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/InterruptListener.h
  dbms/src/Server/MockComputeClient.h
  dbms/src/Server/Server.cpp
  dbms/src/Server/Server.h
  dbms/src/Server/Setup.cpp
  dbms/src/Server/Setup.h
  dbms/src/Server/TCPHandler.cpp
  dbms/src/Server/TCPHandler.h
  dbms/src/Server/TCPHandlerFactory.h
  dbms/src/Server/TCPServersHolder.cpp
  dbms/src/Server/TCPServersHolder.h
  dbms/src/Storages/DeltaMerge/Decode/BoundedSSTFilesToBlockInputStream.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9813 Re-enable jemalloc's background thread by default
  dbms/src/Server/Setup.cpp
Labels: size/XS, release-note, approved, lgtm

#9756 support comparison semantics for batch serialize/deserialize of Column
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.cpp
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.cpp
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/tests/gtest_column_serialize_deserialize.cpp
  dbms/src/TiDB/Collation/Collator.cpp
  dbms/src/TiDB/Collation/Collator.h
Labels: size/XXL, release-note-none, approved, lgtm

#9805 *: Remove useless `Macros`/`Graphite`
  dbms/src/Common/Macros.cpp
  dbms/src/Common/Macros.h
  dbms/src/Interpreters/AsynchronousMetrics.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Server/CMakeLists.txt
  dbms/src/Server/MetricsTransmitter.cpp
  dbms/src/Server/MetricsTransmitter.h
  dbms/src/Server/Server.cpp
  dbms/src/Storages/System/StorageSystemGraphite.cpp
  dbms/src/Storages/System/StorageSystemGraphite.h
  dbms/src/Storages/System/StorageSystemMacros.cpp
  dbms/src/Storages/System/StorageSystemMacros.h
  dbms/src/Storages/System/attachSystemTables.cpp
  dbms/src/TestUtils/TiFlashTestException.h
  libs/libdaemon/CMakeLists.txt
  libs/libdaemon/include/daemon/BaseDaemon.h
  libs/libdaemon/include/daemon/GraphiteWriter.h
  libs/libdaemon/src/BaseDaemon.cpp
  libs/libdaemon/src/GraphiteWriter.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9818 Remove redundant pack reads during building bitmap filter for stable only
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
Labels: release-note-none, size/L, approved, lgtm

#9830 fix false assert in tiflash debug binary after enable new string serde
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
Labels: size/XS, release-note-none, approved, lgtm

#9780 KVStore: Record decoded memory of each Region
  dbms/src/Debug/MockKVStore/MockUtils.h
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.h
  dbms/src/Storages/KVStore/MultiRaft/RaftCommands.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataTrait.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  dbms/src/Storages/KVStore/Region.cpp
  dbms/src/Storages/KVStore/Region.h
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/DecodedLockCFValue.h
  dbms/src/Storages/KVStore/tests/bench_parse_lock.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_new_kvstore.cpp
  dbms/src/Storages/KVStore/tests/gtest_tikv_keyvalue.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9834 Fix compile issue of RegionDataMemDiff in macOS
  dbms/src/Storages/KVStore/MultiRaft/Disagg/RaftLogManager.h
  dbms/src/Storages/KVStore/MultiRaft/RegionCFDataBase.h
  dbms/src/Storages/KVStore/MultiRaft/RegionData.cpp
  dbms/src/Storages/KVStore/MultiRaft/RegionData.h
  libs/libcommon/include/common/demangle.h
Labels: release-note-none, size/S, approved, lgtm
