Repository pingcap/tiflash, pull requests merged in 2025-06, with the labels that each got.

#10229 make tici-search-lib compile compatible with mac
  contrib/tici-search-lib/CMakeLists.txt
Labels: size/XS, approved, lgtm

#10230 fix wrong check for agg when block.rows() is zero
  dbms/src/Common/ColumnsHashing.h
  dbms/src/Flash/tests/gtest_aggregation_executor.cpp
Labels: release-note-none, size/M, approved, lgtm

#10235 build: fix unbound variable error for darwin build script
  release-darwin/build/build-release.sh
Labels: size/XS, release-note-none, approved, lgtm

#10242 tests: Enable more integration tests for next gen
  dbms/src/TiDB/Decode/RowCodec.cpp
  tests/fullstack-test-next-gen/run.sh
  tests/fullstack-test/expr/duration_filter_late_materialization.test
  tests/fullstack-test/expr/duration_filter_late_materialization2.test
  tests/fullstack-test/expr/expr_tree_too_deep.test
  tests/fullstack-test/expr/from_days.test
  tests/fullstack-test/expr/substring_utf8.test
  tests/fullstack-test/mpp/extra_physical_table_column.test
  tests/fullstack-test/mpp/generated_column.test
  tests/fullstack-test/mpp/remote_cop_fail.test
  tests/fullstack-test2/clustered_index/ddl.test
  tests/fullstack-test2/variables/set_variable_fastscan.test
  tests/run-test.py
Labels: release-note-none, size/M, approved, lgtm

#10238 Fix the issue that window function returns incorrect result when range type frame end is preceding
  dbms/src/DataStreams/WindowTransformAction.cpp
  dbms/src/WindowFunctions/tests/gtest_agg.cpp
Labels: release-note, size/M, approved, lgtm

#10255 *: Fix the performance degradation caused by using DataTypeFactory::get
  dbms/src/Flash/Coprocessor/CHBlockChunkCodecV1.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10265 Fix ExpressionAction Project miss block start offset
  dbms/src/Core/Block.cpp
  dbms/src/Core/Block.h
  dbms/src/DataStreams/ExpandTransformAction.cpp
  dbms/src/Interpreters/ExpressionActions.cpp
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  tests/fullstack-test/expr/duration_filter_late_materialization.test
Labels: release-note-none, size/M, approved, lgtm
