Repository pingcap/tiflash, pull requests merged in 2025-08, with the labels that each got.

#10322 Storages: Fix VersionChain::getBytes
  dbms/src/Storages/DeltaMerge/Remote/RNMVCCIndexCache.h
  dbms/src/Storages/DeltaMerge/SegmentReadTask.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.h
Labels: release-note-none, size/M, approved, lgtm

#10325 Storages: Deprecated libclara for normal build
  CMakeLists.txt
  dbms/CMakeLists.txt
  dbms/src/Common/TiFlashBuildInfo.cpp
  dbms/src/Common/config.h.in
  dbms/src/Flash/Coprocessor/DAGStorageInterpreter.cpp
  dbms/src/Server/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/CMakeLists.txt
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/ReadBlockInfo.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.cpp
  dbms/src/Storages/DeltaMerge/Filter/PushDownExecutor.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Perf.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Reader.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Reader.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/BruteScoreInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/BruteScoreInputStream.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ColumnFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ColumnFileInputStream.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/Ctx.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/Ctx.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/DMFileInputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/DMFileInputStream.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/IProvideFullTextIndex.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/InputStream.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/InputStream.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ReaderFromColumnFileTiny.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ReaderFromColumnFileTiny.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ReaderFromDMFile.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Stream/ReaderFromDMFile.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Writer.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/Writer.h
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/tests/gtest_dm_fulltext_index.cpp
  dbms/src/Storages/DeltaMerge/Index/FullTextIndex/tests/gtest_dm_fulltext_index_utils.h
  dbms/src/Storages/DeltaMerge/Index/LocalIndexInfo.cpp
  dbms/src/Storages/DeltaMerge/Index/LocalIndexWriter.cpp
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/StorageDeltaMerge.cpp
  dbms/src/Storages/StorageDisaggregatedRemote.cpp
  dbms/src/Storages/tests/gtests_parse_push_down_filter.cpp
  dbms/src/TiDB/Schema/TiDB.cpp
  dbms/src/TiDB/Schema/TiDB.h
  libs/CMakeLists.txt
Labels: size/XL, release-note-none, approved, lgtm

#10349 *: fix MacOS build
  dbms/src/Server/CMakeLists.txt
Labels: size/XS, release-note-none, approved, lgtm

#10359 dttool: Add dttool bench for sparse column
  dbms/src/Server/DTTool/DTTool.h
  dbms/src/Server/DTTool/DTToolBench.cpp
  dbms/src/Server/DTTool/DTToolInspect.cpp
  dbms/src/Server/tests/gtest_dttool.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/VersionChain/MVCCBitmapFilter.cpp
Labels: size/XL, release-note-none, approved, lgtm

#10086 Support non-recursive CTE in TiFlash
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Common/WeakHash.h
  dbms/src/Flash/Coprocessor/DAGContext.h
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.cpp
  dbms/src/Flash/Coprocessor/GenSchemaAndColumn.h
  dbms/src/Flash/Executor/PipelineExecutor.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.cpp
  dbms/src/Flash/Executor/PipelineExecutorContext.h
  dbms/src/Flash/Mpp/CTEManager.cpp
  dbms/src/Flash/Mpp/CTEManager.h
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
  dbms/src/Flash/Mpp/MPPTaskId.h
  dbms/src/Flash/Mpp/MPPTaskStatistics.cpp
  dbms/src/Flash/Mpp/MPPTaskStatistics.h
  dbms/src/Flash/Mpp/tests/gtest_cte_manager.cpp
  dbms/src/Flash/Pipeline/Exec/PipelineExec.cpp
  dbms/src/Flash/Pipeline/Schedule/Reactor/WaitReactor.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/PipeConditionVariable.h
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.cpp
  dbms/src/Flash/Pipeline/Schedule/Tasks/Task.h
  dbms/src/Flash/Planner/PhysicalPlan.cpp
  dbms/src/Flash/Planner/PhysicalPlan.h
  dbms/src/Flash/Planner/PhysicalPlanNode.h
  dbms/src/Flash/Planner/PlanType.h
  dbms/src/Flash/Planner/Plans/PhysicalCTESink.cpp
  dbms/src/Flash/Planner/Plans/PhysicalCTESink.h
  dbms/src/Flash/Planner/Plans/PhysicalCTESource.cpp
  dbms/src/Flash/Planner/Plans/PhysicalCTESource.h
  dbms/src/Flash/Planner/Plans/PhysicalProjection.cpp
  dbms/src/Flash/Planner/Plans/PhysicalProjection.h
  dbms/src/Flash/Statistics/CommonExecutorImpl.h
  dbms/src/Flash/Statistics/ExecutorStatisticsCollector.cpp
  dbms/src/Flash/Statistics/traverseExecutors.cpp
  dbms/src/Interpreters/Context.cpp
  dbms/src/Interpreters/Context.h
  dbms/src/Operators/CTE.cpp
  dbms/src/Operators/CTE.h
  dbms/src/Operators/CTEPartition.h
  dbms/src/Operators/CTEReader.cpp
  dbms/src/Operators/CTEReader.h
  dbms/src/Operators/CTESinkOp.cpp
  dbms/src/Operators/CTESinkOp.h
  dbms/src/Operators/CTESourceOp.cpp
  dbms/src/Operators/CTESourceOp.h
  dbms/src/Operators/IOProfileInfo.h
  dbms/src/Operators/SharedQueue.cpp
  dbms/src/Operators/tests/gtest_cte.cpp
  dbms/src/Storages/KVStore/TMTContext.cpp
  dbms/src/Storages/KVStore/TMTContext.h
Labels: size/XXL, release-note, approved, lgtm

#10377 Fix cte concurrent unit test
  dbms/src/Operators/tests/gtest_cte.cpp
Labels: size/XS, release-note, approved, lgtm
