Repository pingcap/tiflash, pull requests merged in 2025-09, with the labels that each got.

#10383 Support graceful shutdown in TiFlash (release-8.5)
  dbms/src/Flash/FlashService.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.cpp
  dbms/src/Flash/Mpp/MPPTaskManager.h
  dbms/src/Server/FlashGrpcServerHolder.cpp
  dbms/src/Server/Server.cpp
Labels: release-note, size/M, cherry-pick-approved, approved, lgtm

#10388 tests: Download next-gen binaries
  tests/docker/config/tiflash_dt.toml
  tests/docker/config/tiflash_dt_disable_local_tunnel.toml
  tests/docker/config/tiflash_dt_force_enable_lm.toml
  tests/docker/config/tiflash_dt_lightweight_compression.toml
  tests/docker/config/tiflash_dt_sync_grpc.toml
  tests/docker/next-gen-config/tiflash_cn.toml
  tests/docker/next-gen-config/tiflash_wn.toml
  tests/docker/next-gen-utils/.gitignore
  tests/docker/next-gen-utils/Makefile
  tests/docker/next-gen-utils/README.md
  tests/docker/next-gen-yaml/disagg_tiflash.yaml
Labels: release-note-none, size/L, approved, lgtm

#10396 Storages: Fix the statistics of user_read_bytes and add metrics
  dbms/src/Common/TiFlashMetrics.cpp
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Coprocessor/DAGContext.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/Delta/Snapshot.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_vector_index_utils.h
  dbms/src/Storages/DeltaMerge/ReadMode.h
  dbms/src/Storages/DeltaMerge/ScanContext.cpp
  dbms/src/Storages/DeltaMerge/ScanContext.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/Common.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/Common.h
  dbms/src/Storages/DeltaMerge/VersionChain/DMFileHandleIndex.h
  dbms/src/Storages/DeltaMerge/VersionChain/DeleteMarkFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/RowKeyFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/VersionChain.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/VersionFilter.cpp
  dbms/src/Storages/DeltaMerge/VersionChain/tests/mvcc_test_utils.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  metrics/grafana/tiflash_summary.json
Labels: size/XL, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5

#10406 PageStorage: Fix an exception in gc when meet an empty WriteBatch
  dbms/src/Storages/Page/V3/LogFile/LogFilename.h
  dbms/src/Storages/Page/V3/PageDirectory.cpp
  dbms/src/Storages/Page/V3/PageDirectory.h
  dbms/src/Storages/Page/V3/WAL/WALReader.cpp
  dbms/src/Storages/Page/V3/WAL/WALReader.h
  dbms/src/Storages/Page/V3/WALStore.cpp
  dbms/src/Storages/Page/V3/WALStore.h
  dbms/src/Storages/Page/V3/tests/gtest_wal_store.cpp
Labels: size/L, release-note, approved, lgtm

#10387 Limit memory usage of exchange sender
  dbms/src/Flash/Coprocessor/DAGDriver.cpp
  dbms/src/Flash/Coprocessor/DAGResponseWriter.h
  dbms/src/Flash/Coprocessor/DAGUtils.cpp
  dbms/src/Flash/Coprocessor/DAGUtils.h
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.cpp
  dbms/src/Flash/Coprocessor/StreamingDAGResponseWriter.h
  dbms/src/Flash/Coprocessor/tests/gtest_streaming_writer.cpp
  dbms/src/Flash/Coprocessor/tests/gtest_ti_remote_block_inputstream.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.cpp
  dbms/src/Flash/Mpp/BroadcastOrPassThroughWriter.h
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.cpp
  dbms/src/Flash/Mpp/FineGrainedShuffleWriter.h
  dbms/src/Flash/Mpp/HashPartitionWriter.cpp
  dbms/src/Flash/Mpp/HashPartitionWriter.h
  dbms/src/Flash/Mpp/newMPPExchangeWriter.cpp
  dbms/src/Flash/Mpp/newMPPExchangeWriter.h
  dbms/src/Flash/Mpp/tests/gtest_mpp_exchange_writer.cpp
  dbms/src/Flash/Planner/Plans/PhysicalExchangeSender.cpp
  dbms/src/Storages/KVStore/tests/gtest_kvstore_fast_add_peer.cpp
Labels: size/XL, release-note-none, approved, lgtm

#10400 Improve like perf for utf8 ci collations
  dbms/src/Functions/CollationStringSearchOptimized.h
  dbms/src/Functions/FunctionsStringSearch.cpp
  dbms/src/TiDB/Collation/Collator.cpp
  dbms/src/TiDB/Collation/Collator.h
  dbms/src/TiDB/tests/gtest_tidb_collator.cpp
Labels: size/XL, release-note-none, approved, lgtm

#10459 Storage: Fix data race in `DeltaMergeStore::checkSegmentUpdate`
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
Labels: release-note-none, size/S, approved, lgtm

#10293 Reduce redundant pack reads during building bitmap filter for delta merge case (release-8.5)
  dbms/src/IO/Compression/CompressedReadBufferBase.cpp
  dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileBig.cpp
  dbms/src/Storages/DeltaMerge/DeltaMerge.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp
  dbms/src/Storages/DeltaMerge/DeltaTree.h
  dbms/src/Storages/DeltaMerge/File/ColumnStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFile.h
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileBlockInputStream.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilterResult.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter_fwd.h
  dbms/src/Storages/DeltaMerge/File/DMFileReader.cpp
  dbms/src/Storages/DeltaMerge/File/DMFileReader.h
  dbms/src/Storages/DeltaMerge/File/DMFileWithVectorIndexBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/StableValueSpace.cpp
  dbms/src/Storages/DeltaMerge/StableValueSpace.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store_test_basic.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_file.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_read_task.cpp
  dbms/src/TestUtils/InputStreamTestUtils.cpp
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm
