Repository pingcap/tiflash, pull requests merged in 2025-05, with the labels that each got.

#10127 Storages: implement fast scan using bitmap
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.cpp
  dbms/src/Storages/DeltaMerge/ConcatSkippableBlockInputStream.h
  dbms/src/Storages/DeltaMerge/DMDecoratorStreams.h
  dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.h
  dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.h
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.cpp
  dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h
  dbms/src/Storages/DeltaMerge/Segment.cpp
  dbms/src/Storages/DeltaMerge/Segment.h
  dbms/src/Storages/DeltaMerge/SegmentRowID.h
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_bitmap.cpp
Labels: size/XXL, release-note-none, approved, lgtm

#9956 Support left-outer join and join-level late materialization for other conditions in hash join v2
  dbms/src/Columns/ColumnAggregateFunction.h
  dbms/src/Columns/ColumnArray.cpp
  dbms/src/Columns/ColumnArray.h
  dbms/src/Columns/ColumnConst.h
  dbms/src/Columns/ColumnDecimal.h
  dbms/src/Columns/ColumnFixedString.h
  dbms/src/Columns/ColumnFunction.h
  dbms/src/Columns/ColumnNullable.cpp
  dbms/src/Columns/ColumnNullable.h
  dbms/src/Columns/ColumnString.h
  dbms/src/Columns/ColumnTuple.h
  dbms/src/Columns/ColumnVector.h
  dbms/src/Columns/IColumn.h
  dbms/src/Columns/IColumnDummy.h
  dbms/src/Columns/filterColumn.cpp
  dbms/src/Columns/tests/gtest_column_misc.cpp
  dbms/src/Common/ColumnNTAlignBuffer.h
  dbms/src/Common/FailPoint.cpp
  dbms/src/Core/Block.cpp
  dbms/src/Core/Types.h
  dbms/src/Flash/Mpp/HashBaseWriterHelper.cpp
  dbms/src/Flash/Mpp/HashBaseWriterHelper.h
  dbms/src/Flash/Planner/Plans/PhysicalJoinV2.cpp
  dbms/src/Flash/tests/gtest_join_executor.cpp
  dbms/src/Interpreters/JoinUtils.cpp
  dbms/src/Interpreters/JoinV2/HashJoin.cpp
  dbms/src/Interpreters/JoinV2/HashJoin.h
  dbms/src/Interpreters/JoinV2/HashJoinBuild.cpp
  dbms/src/Interpreters/JoinV2/HashJoinBuild.h
  dbms/src/Interpreters/JoinV2/HashJoinKey.cpp
  dbms/src/Interpreters/JoinV2/HashJoinPointerTable.cpp
  dbms/src/Interpreters/JoinV2/HashJoinProbe.cpp
  dbms/src/Interpreters/JoinV2/HashJoinProbe.h
  dbms/src/Interpreters/JoinV2/HashJoinRowLayout.h
  dbms/src/Interpreters/JoinV2/HashJoinSettings.h
  dbms/src/Interpreters/NullAwareSemiJoinHelper.cpp
  dbms/src/Interpreters/NullAwareSemiJoinHelper.h
  dbms/src/Interpreters/SemiJoinHelper.cpp
  dbms/src/Operators/HashJoinV2ProbeTransformOp.cpp
  dbms/src/TestUtils/ExecutorTestUtils.cpp
  tests/fullstack-test/mpp/rollup.test
Labels: size/XXL, release-note-none, approved, lgtm

#10143 use logical cpu cores as the default pool size of grpc async client pool
  dbms/src/Common/getNumberOfCPUCores.cpp
  dbms/src/Server/Server.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10151 Storage: Adapt to ingesting snapshot with irregular region range
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/Index/VectorIndex/tests/gtest_dm_delta_merge_store_vector_index.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/RowKeyRangeFromRegion.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/StorageDeltaMergeHelpers.h
Labels: size/XXL, release-note, approved, lgtm

#10154 Storage: Adapt to ingesting snapshot with irregular region range (release-8.1)
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/RowKeyRangeFromRegion.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/Disagg/FastAddPeer.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/StorageDeltaMergeHelpers.h
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#10153 Storage: Adapt to ingesting snapshot with irregular region range (release-7.5)
  dbms/src/Common/RandomData.cpp
  dbms/src/Common/RandomData.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/RowKeyRangeFromRegion.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/StorageDeltaMergeHelpers.h
Labels: size/XXL, release-note, cherry-pick-approved, approved, lgtm

#10162 ddl: Fix compatibility with null expression index
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/TiDB/Decode/TypeMapping.cpp
  dbms/src/TiDB/Schema/tests/gtest_table_info.cpp
  dbms/src/TiDB/tests/gtest_type_mapping.cpp
  tests/fullstack-test2/ddl/expression_index.test
Labels: size/L, release-note, approved, lgtm

#10178 ddl: Update integration test of expr index
  tests/fullstack-test2/ddl/expression_index.test
Labels: release-note-none, size/S, approved, lgtm

#10175 Fix address alignment error
  dbms/src/Common/tests/gtest_arena.cpp
  dbms/src/Interpreters/JoinPartition.cpp
Labels: release-note-none, size/M, approved, lgtm

#10160 Storages: Enable VersionChain
  dbms/src/Interpreters/Settings.h
Labels: size/XS, release-note, approved, lgtm

#10185 fix mock LAC unit test data race
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
Labels: release-note-none, size/M, approved, lgtm

#10186 Storage: Adapt to ingesting snapshot with irregular region range
  dbms/src/Common/RandomData.cpp
  dbms/src/Common/RandomData.h
  dbms/src/Storages/DeltaMerge/DeltaMergeStore_Ingest.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.cpp
  dbms/src/Storages/DeltaMerge/RowKeyRange.h
  dbms/src/Storages/DeltaMerge/RowKeyRangeFromRegion.cpp
  dbms/src/Storages/DeltaMerge/tests/DMTestEnv.h
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_delta_merge_store.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_dm_simple_pk_test_basic.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_key_range.cpp
  dbms/src/Storages/DeltaMerge/tests/gtest_segment_test_basic.cpp
  dbms/src/Storages/KVStore/Decode/RegionTable.cpp
  dbms/src/Storages/KVStore/KVStore.cpp
  dbms/src/Storages/KVStore/MultiRaft/ApplySnapshot.cpp
  dbms/src/Storages/KVStore/MultiRaft/IngestSST.cpp
  dbms/src/Storages/KVStore/TiKVHelpers/TiKVRecordFormat.h
  dbms/src/Storages/StorageDeltaMergeHelpers.h
Labels: size/XXL, release-note, approved, needs-1-more-lgtm

#10140 fix tiflash resource control low token signal miss
  dbms/src/Common/TiFlashMetrics.h
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/ResourceControlQueue.cpp
  dbms/src/Flash/Pipeline/Schedule/TaskQueues/tests/gtest_resource_control_queue.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/LocalAdmissionController.h
  dbms/src/Flash/ResourceControl/MockLocalAdmissionController.cpp
  dbms/src/Flash/ResourceControl/TokenBucket.cpp
  dbms/src/Flash/ResourceControl/TokenBucket.h
Labels: size/XXL, release-note, approved, lgtm

#10196 Downgrade reportStatus log level from error to info
  dbms/src/Flash/Mpp/MPPTask.cpp
Labels: size/XS, release-note-none, approved, lgtm

#10210 add mpp task execution time in info log
  dbms/src/Flash/Mpp/MPPTask.cpp
  dbms/src/Flash/Mpp/MPPTask.h
Labels: size/XS, release-note-none, approved, lgtm
